### ISSUE TITLE
FODC doesn't log creator of group

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1006]
Searched by name/e-mail of creator, got their badge creation and later deletion.  Searched by group, got creation info w/out leader/creator.  Subsequent transfer of Leader position logged both from and to, so was able to get needed info

**Comment by binary1230** [comment]
super-dumb question: what's FODC?

**Comment by thaeli** [comment]
Feed Of Database Changes

**Comment by binary1230** [comment]
ah man I should have totally known that : )
