### ISSUE TITLE
Will Murnane can't be made an admin

### ISSUE THREAD

**Issue by willmurnane** [magfest/ubersystem#1012]
The "manage accounts" page has a list of attendees who can be promoted to admin. Will Murnane doesn't show up in this page, and Jennifer Murnane does, although they have very similar profiles in Uber otherwise: not trusted, signed up for reg shifts, etc. Other Wills show up as Will or William, but WM is neither. He's in the list of attendees elsewhere, and has a badge.

https://prime.uber.magfest.org/m13/registration/form?id=<id omitted>
https://prime.uber.magfest.org/m13/accounts/

-- Will and Blue Hat Dave

**Comment by EliAndrewC** [comment]
Bug confirmed, I'll look into it and push out a fix tonight.
