### ISSUE TITLE
break out email daemon code into its own plugin, run as a separate process

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1041]
I'd like to think about moving email processing onto it's own process (and potentially, a different server) as it consumes a decent chunk of resources on startup, and we don't necessarily need a lot of it for at-the-con mode.

Some puppet changes I'm planning this year will make this process a lot less painful.

**Comment by EliAndrewC** [comment]
Seems legit.  This would be pretty easy to do, code-wise, but would be a lot of infrastructure work since we'd need to give remote postgres access and a new set of puppet manifests/templates for the other server.

Definitely doable though.

**Comment by binary1230** [comment]
Yea, and the stuff that would be needed in order to setup the other installs and maintain them in lockstep with each other is stuff that will be a side effect of some work I was planning on doing anyway.

**Comment by EliAndrewC** [comment]
We've since fixed the email code to no longer consume very many system resources so I'm closing this as redundant.
