### ISSUE TITLE
"Dealers" link should probably be removed from pre-reg page

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1048]
Probably? We don't have dealers right?

**Comment by kitsuta** [comment]
Yeah, seems legit.

**Comment by EliAndrewC** [comment]
Yeah, good call, I have dealers enabled in the config just because I was making sure they worked in my local dev machine with all the changes I've been making, but I should change the config to turn them off.

**Comment by EliAndrewC** [comment]
This has been merged.
