### ISSUE TITLE
"Allergies" field is displayed even if someone isn't purchasing food

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1049]
Is this required?

**Comment by EliAndrewC** [comment]
Good catch, I agree this should be shown/hidden based on the result of the dropdown.  In fact I swear I did implement that, but apparently not, or maybe I did and there's a bug.

**Comment by EliAndrewC** [comment]
(Turns out there was a bug, now fixed, I'll make a PR in a few minutes when I finish the last of the fixes for tonight.)

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/ubersystem/pull/1059
