### ISSUE TITLE
Pre-reg confirmation email not received.

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1050]
Made a test attendee and paid, but did not receive a confirmation e-mail. Used a mailinator address, and verified in the attendee history tab that an e-mail was sent.

Unsure if this is just a server mail configuration issue.

**Comment by kitsuta** [comment]
I think Eli's tester server has emails turned off.

**Comment by EliAndrewC** [comment]
It does have them turned off, I was waiting until I had the correct email verbiage before turning them on.

**Comment by binary1230** [comment]
hey, a quick note, the rockage branch in the ubersystem repo has a bunch of modifications to the base emails which allow a plugin to easily override parts of the email text.  when we get to the email customization stuff, it might be worth pulling some of the changes from the rockage branch in to make customizing email text easier for all plugins in the future

**Comment by binary1230** [comment]
I'm a little fuzzy on the exact details since it's been a while

**Comment by EliAndrewC** [comment]
Cool, I'll take a look at that when I get to that point.

**Comment by kitsuta** [comment]
Do we have text for these emails?

**Comment by EliAndrewC** [comment]
I've asked a few times in emails but still haven't gotten anything.  Normally I'd just write something sensible myself, but there was mention in the original Google doc about including campground rules or something along those lines, so I want to get that right.

**Comment by EliAndrewC** [comment]
I just turned emails on.  I figure we can just configure a separate email for things like campground rules and FAQs and such.

Here's an example of the registration confirmation email: 
http://magstock.mailinator.com
