### ISSUE TITLE
"i don't wish to provide a number" has no visible effect

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1054]
Checking this box doesn't visually affect the phone number field in any way. Should probably do something like disable it if checked.

**Comment by EliAndrewC** [comment]
Actually, one thing that we used to do was make required field labels bold and optional field labels normal.  The styling that we ganked from Anthrocon doesn't seem to do that, which it probably should (or something morally equivalent).

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/ubersystem/pull/1059
