### ISSUE TITLE
Is badge name a needed field?

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1056]
When supporter level is selected, a badge name field appears. Does magstock have badges with custom names?

**Comment by EliAndrewC** [comment]
I assumed they did, but this is an excellent question, since they very well might not.

**Comment by EliAndrewC** [comment]
Fixed by https://github.com/magfest/magstock/commit/a8dc349e60add73ede5d27f16a864121e8632d4d
