### ISSUE TITLE
Configuration changes for Magstock

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1057]
* pre-reg close date
* supporter level close date
* t-shirt pre-order close date
* no white t-shirt option
* interests options: chilling, grilling,  music, slip & slide, lake, video games, moonbounce, & activities
* noise level options: party, normal, quiet
* camping type options: small tent (6 or less), large tent (8 or more), sleeping in car, larger vehicle (box truck, RV, etc), not staying on-site?
* job interest options: registration, music, food, slip & slide, cat herding, standby/misc

**Comment by EliAndrewC** [comment]
This is all just config options.  Obviously, it needs to be updated, I'm just noting that it won't require any code changes.

**Comment by kitsuta** [comment]
Threw some other notes in here from the wishlist doc.

**Comment by EliAndrewC** [comment]
I just noticed the white tshirt option.  I must have missed that.  I just sent an email to the MAGStock folks:

> Quick question - I just noticed a note about a "white tshirt option".  I didn't realize that people could pick between multiple tshirt colors.  How many different tshirt options should there be?  I can do whatever, and it's a super-easy addition, I just need to know what all the options are.  I could make it "Regularly Colored Tshirt" and "White Tshirt" or something if desired.  Or I can leave this out entirely if it's not a thing anymore.

**Comment by EliAndrewC** [comment]
All of these are done, except for white tshirt one which is pending me figuring out what the deal with it is.

Here's the result of a ``sep print_config``:
https://gist.github.com/EliAndrewC/8ceb37a355bc8a496a3c

And here's the actual ``development.ini`` file:
https://gist.github.com/EliAndrewC/b307a1116b088a77eb75

@binary1230 said he could puppetize this and then set up the https://magstock.uber.magfest.org/ server for us.
