### ISSUE TITLE
Separate food option from kick-in levels

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1064]
Food needs to be available for Magstock as an extra paid option, but it should preferably _not_ be a kick-in level because it shouldn't include a Supporter package or vice-versa.

**Comment by EliAndrewC** [comment]
This is basically done but I'm gonna go grab some dinner.  I'll come back and push my changes then finish the last of the config changes and get Dom the info he needs for puppetization.

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/magstock/commit/fd0fe7929a70e6b5f8379c91f067b4a09253078a
