### ISSUE TITLE
Auto-assign "roughing it" ribbon to attendees with a certain site type

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1065]
Anyone who opts for the "primitive" campsite type should also get a "Roughing It" Ribbon automatically.

**Comment by EliAndrewC** [comment]
Have you done this yet?  There's a new API for handling this kind of thing, so if you haven't already done it, then I should probably tackle it.

**Comment by EliAndrewC** [comment]
I'll assign this to myself regardless so that I can use the new API for it.

**Comment by EliAndrewC** [comment]
Here's the fix (in the MAGStock repo):
https://github.com/magfest/magstock/commit/86ab2e8f56ac13722341af281fdb4f63f98c0a98

As you can see, there's now a ``@presave_adjustment`` decorator which you can use to add presave adjustments in the event-specific plugin, which is one of the ways we'll do this kind of per-event logic going forward.

**Comment by kitsuta** [comment]
Oh, neat! Sorry for self assigning this and not getting around to it -
thanks for taking care of it.
