### ISSUE TITLE
Badge numberless check-in for Magstock

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1066]
There needs to be a way to skip having badge numbers on a per-event basis. Currently, the system requires a badge number before it will check anyone in.

**Comment by thaeli** [comment]
This is an interesting request. I've certainly heard it before. Breaks a lot of stuff, though, to truly have no badge numbers. Would "system shall automatically assign an unused valid badge number" be a reasonable implementation?

**Comment by kitsuta** [comment]
Possibly? Certainly there are other events who simply don't care about badge numbers. And "the system can't do that, here's a pen" only goes so far. :P

**Comment by EliAndrewC** [comment]
This doesn't seem all that hard.  It seems like for a logistical basis that events ought to want to have badge numbers, but that assums they have badges in the first place as opposed to just stamps on their hands or tickets or wristbands or whatever.  I mean, I don't know how many of those types of events would use Uber, but assuming that the answer is "more than zero" then we might as well support it.

**Comment by thaeli** [comment]
We do a LOT of stuff that depends on the person having a badge number though. So just auto-assign the badge number and you don't really have to write it down anywhere..

**Comment by binary1230** [comment]
yea btw when i did magstock and rockage last time, the path of least resistance was to have a config option and functionality to support 'auto assign next available badge number'.

whatever it is just needs to be tested carefully for both the self-checkin and the reg staff

**Comment by kitsuta** [comment]
Fixed by https://github.com/magfest/ubersystem/pull/1136
