### ISSUE TITLE
hardcoded app path in utils.py

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1070]
utils.py always assumes that the app path is "/uber", when trying it with a different path (like "/magfest" or "/magstock") it fails on loading plugins.

in uber/utils.py", line 253, in static_overrides()

```
appconf = cherrypy.tree.apps['/uber'].config
```

solution: either:
1) read the path from a config setting from development.ini
or
2) require /uber for all ubersystem install paths from now on

**Comment by binary1230** [comment]
I'll try and see if something like c.PATH is all that's needed here

**Comment by EliAndrewC** [comment]
Fixed in the linked PR.
