### ISSUE TITLE
Badge level tweaks

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1075]
Level Text:

"Attendee: $50
 Includes three day admission and campground fees"

"Plus T-Shirt: $70
 Attendee level plus a MAGStock themed t-shirt"

"Supporter: $100
 T-shirt level plus additional swag (Available until X. Limited quantities.)"

Also, remove the "kick in extra" drop down. No sense having it if it has the exact same options as the badge levels.

**Comment by binary1230** [comment]
Plus T-Shirt is $50 not $70?

**Comment by nickthenewbie1** [comment]
Sorry, I meant 70.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

On Mon, Apr 27, 2015 at 2:21 PM, Dominic Cerquetti <notifications@github.com

**Comment by binary1230** [comment]
this one is about changing the text?

**Comment by EliAndrewC** [comment]
I assume so.  Those text changes should be simple to implement, as should hiding the extra dropdown.

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/magstock/commit/645f4ac77e6fe18067efacc765b41cd1ecfe8afa
