### ISSUE TITLE
Remove minor consent link

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1076]
Remove "Attendees under 18 MUST bring a signed and notarized parental permission slip."

**Comment by EliAndrewC** [comment]
Oh, is that not true for MAGStock?  That's cool - Dom mentioned that he unset the ``MINOR_CONSENT_FORM`` setting, which is what causes that to be displayed.  So it's just a config change.

**Comment by binary1230** [comment]
hey is this still present in the production server? I removed the config option so I think it should now be gone.  if so, ready to close this bug.

**Comment by EliAndrewC** [comment]
What's the URL of the production server?  I assumed it would be https://magstock.uber.magfest.org/

**Comment by binary1230** [comment]
https://magstock.uber.magfest.org:4443/uber/

**Comment by kitsuta** [comment]
This looks like it's fixed in production.
