### ISSUE TITLE
incorrect supporter deadline

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1079]
on production server, the main page if you select swag it says 

"Supporter level and higher are only available until 11:59pm EST on Saturday, Dec 26."

![image](https://cloud.githubusercontent.com/assets/5413064/7354372/1f9488c0-ece9-11e4-9091-a2f8494edf8c.png)

**Comment by EliAndrewC** [comment]
Whoops, forgot to fix that in my local config before sending the gist to Dom.  The actual date which was agreed upon in email is May 31st.

**Comment by binary1230** [comment]
so this bug is technically fixed because we hid the entire thing in the toolbar, and also i fixed the date in puppet.

The question now is, do we want to display just that text of "only available until May 31" because at the moment, it's not showing up on the page at all

**Comment by binary1230** [comment]
so to clarify: with all recent changes we aren't displaying the May 31st deadline anywhere on the page right now like we were before.  do we want to do that? if so, need a code change.

**Comment by kitsuta** [comment]
Looks like this is in production as description text for the Supporter badge option. Closing as fixed.
