### ISSUE TITLE
text: tent leader typo

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1080]
![image](https://cloud.githubusercontent.com/assets/5413064/7354617/8be946d6-ecea-11e4-809f-51897ee50cdf.png)

should read "Who is your tent leader" currently reads "Who your tent leader"

**Comment by EliAndrewC** [comment]
Much leader. Many tent.  Some typo.  Wow.

**Comment by EliAndrewC** [comment]
Side note: even after having the typo pointed out, I had to re-read Dom's bug report like 4 times before my eyes actually caught it.  I kept thinking, "He's just repeating the same thing twice!  There's no difference!"

**Comment by binary1230** [comment]
WHO YOUR TENT LEADER

**Comment by binary1230** [comment]
: )

**Comment by EliAndrewC** [comment]
Just got home, gonna tackle a few of these quick fixes before dinner, starting with this one.

> WHO YOUR TENT LEADER

THEN WHO WAS PHONE?!

**Comment by thaeli** [comment]
BEAR IS TENT LEADER
HOW CAN THIS BE

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/magstock/commit/02602a10ea7921bd402790a70b9b58e532e35095
