### ISSUE TITLE
text: supporter popup

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1081]
it has a bunch of stuff about season supporters

`Kicking in Extra Money

Want to give us a little extra cash to help make the festival better? If you do, we'll throw in a few special keepsakes! Each donation level gets you an extra bit of swag, in addition to all of the swag from all of the lower donation levels. None of these things (except the tshirt) will be for sale, so this is the only way to get them! 

If you've registered as a Supporter in the past, that's still available as a donation level. It's pretty much the same as always, except that now you can donate even more if you'd like, and we'll even kick in a few extra mementos as thanks. We also have an even higher Season Supporter Pass level for those interested in other MAGStock events. 

We also let you identify an affiliate; basically, this tells us which groups are throwing the most financial support into MAGStock so that we can reciprocate by doing cool things for those groups.`

**Comment by EliAndrewC** [comment]
Good catch.  We should generically have it check whether season supporters are enabled before displaying that text.

**Comment by EliAndrewC** [comment]
This is no longer relevant since we no longer display the kick-in dropdown which is what had the link to these pages.  But I have updated them with more accurate verbiage for MAGFest itself and other events:
https://github.com/magfest/ubersystem/commit/7329af857fd1eed567cf73a53ab42bf5e87338de
