### ISSUE TITLE
password information sent via GET instead of POST

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1084]
if I type in a username and password, it shows up in the querystring.  we need to switch it from GET to POST

![image](https://cloud.githubusercontent.com/assets/5413064/7356359/8ab572a2-ecf5-11e4-8367-592c60eba650.png)

**Comment by EliAndrewC** [comment]
YIKES!  It was definitely a ``POST`` originally, that must have gotten changed as part of the bootstrapping and style overhaul.  Should be an easy fix.  Good catch though, that's a REALLY bad bug!

**Comment by kitsuta** [comment]
Hm, this WAS introduced in the AnthroCon branch (I just checked M13, it doesn't do it). We need a live fix for that ASAP.

**Comment by EliAndrewC** [comment]
Looks like @thaeli fixed this in https://github.com/magfest/ubersystem/commit/4f0fc555eba7c72771d677cfb521bb0f219a95a1

**Comment by EliAndrewC** [comment]
Unfortunately, @thaeli's fix broke the login form :(

I'll fix the fix in a sec.

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/ubersystem/commit/7322dae07f7c5637c35177f06d437c049677326e

**Comment by EliAndrewC** [comment]
Side note: every time I think to myself, "This change is so simple that I literally don't even need to test it" then I end up discovering that there was a bug.  At least one.  Sometimes more. :)
