### ISSUE TITLE
Exceptions causing BADGE_LOCK to not be released

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1085]
We just had a problem where an exception while saving caused Uber to effectively freeze.  This is almost certainly the BADGE_LOCK problem we had last year.  I suspect that when we upgraded SQLAlchemy, their event semantics changed slightly, or something.  I'll need to check the docs and be REALLY sure that this can't happen in production.

**Comment by binary1230** [comment]
fixed via https://github.com/magfest/ubersystem/issues/1887
