### ISSUE TITLE
Staffers don't need badge name

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1086]
remove field on registration form when a staffer is filling out a self-service registration link

**Comment by EliAndrewC** [comment]
Seems legit.  I'll tackle this tomorrow after work.

**Comment by nickthenewbie1** [comment]
For magstock. Not necessary for reg launch

**Comment by EliAndrewC** [comment]
Agreed.

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/magstock/commit/5296902e9d0c1fc8b95a2e8677fd51f84a310015
