### ISSUE TITLE
"Who is in your group?" for tent leaders should not be required

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1088]
I don't care if the DB is modified to allow an empty value, or if "none" is inserted in lieu of empty, or just the attendee is put in there. Just make it so that no error stops the user from proceeding if that field is empty.

**Comment by EliAndrewC** [comment]
Definitely an easy fix I can make tomorrow after work.

**Comment by nickthenewbie1** [comment]
If possible, I'd like to get this in so we can put up reg this afternoon. Is anyone available now to make the change?

**Comment by EliAndrewC** [comment]
If anyone is, the relevant block is https://github.com/magfest/magstock/blob/master/magstock/__init__.py#L63

There are two sub-branches in the if-chain, one for tent leaders and one for everyone else.  We could simply NOT return an error message for tent leaders and everything would work.

**Comment by nickthenewbie1** [comment]
Vic mentioned a db change was required to not have anything in that field? Is that not the case?

**Comment by kitsuta** [comment]
That was under the assumption that we'd like to still warn tent leaders if they don't have anything in their "who's in your group" field, and instead add a checkbox for "I'm coming alone." But there are other ways to solve this.

**Comment by EliAndrewC** [comment]
Right - just allowing the field to be left blank doesn't require any kind of db change, but adding a new checkbox does require one.

I would recommend NOT making an extra checkbox and instead adding a third option to the dropdown that says "I'm coming alone" since that makes more sense than "I am the Tent Leader" for someone who is coming alone.

**Comment by kitsuta** [comment]
Yes, this was the conclusion I came to as well. :) Gonna have a PR for that shortly.

**Comment by kitsuta** [comment]
OK, this is addressed in https://github.com/magfest/magstock/pull/2 - the only thing left after merging that is to add a new config option for `COMING_AS` that says "I'm coming alone".

We can also, if we want, add a fourth option called "I don't know yet."

**Comment by kitsuta** [comment]
That PR has been merged, so this should be fixed.
