### ISSUE TITLE
Attempting to add food to an already paid reg using the self-service link results in weird dollar amounts

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1089]
See screenshot
![fooddonation](https://cloud.githubusercontent.com/assets/7833809/7384388/ec09946a-edff-11e4-9238-8f108300382f.PNG)

**Comment by nickthenewbie1** [comment]
WEIRD SHIT.

1. Attendee registers and pays at standard level without food
2. Attendee follows edit link in confirmation email
3. Attendee checks the food checkbox, and clicks update
4. Attendee does not pay
5. Admin goes to attendee's record and unchecks food checkbox
6. Admin clicks update to save record

Problem: Checkbox remains checked.

**Comment by kitsuta** [comment]
Just to note here, Nick told me that clicking "Nevermind" also does not unset the food checkbox. So it's just plain not getting updated.

**Comment by EliAndrewC** [comment]
Hmm, interesting.  These are some edge cases I hadn't considered when implementing the new "plugins can add stuff like extra costs" feature.  This should be easy enough to fix though, we'll just need a small addition to the ``Attendee`` class.  I can handle that after work tonight (I should definitely be the one to do this one, so I'm assigning it to myself now, unlike the others where theoretically someone else could do them if they have time before I do).

**Comment by kitsuta** [comment]
@EliAndrewC Can we launch pre-reg before you fix this or no?

**Comment by nickthenewbie1** [comment]
Launch is ok without this. I removed the tag.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by EliAndrewC** [comment]
I'll still try to get this fixed tonight, but I agree that we don't need to hold up launch for it.

**Comment by EliAndrewC** [comment]
Didn't manage to find time for this, but I fixed a few other things.  I'll get to this over the weekend.

**Comment by EliAndrewC** [comment]
I have a fix for this which I'll push out in a little while, but I've filed #1094 to track a limitation in our current approach.

**Comment by EliAndrewC** [comment]
Fixed in
https://github.com/magfest/ubersystem/commit/6b589b79322648c0ba175e0af1966e480089dc69
and
https://github.com/magfest/magstock/commit/b7b13580732e2b63df3ad6955bc49d049d2eadef
