### ISSUE TITLE
Change "badge" to "wristband" on the legal name explanation page

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1090]
Text is currently:

To help ensure the safety of everyone at MAGStock, registrations are tied to attendees using their photo ID. Attendees present their photo ID upon check-in to claim their badge. 

If you are unsure what name to use, or if your legal name is in flux, simply enter the name that will appear on your photo ID when you check in. 

Your legal name will not appear on your badge.

replace badge with wristband

**Comment by EliAndrewC** [comment]
Seems legit.  I'll handle this after work.

**Comment by binary1230** [comment]
I think i have the updated text in the magstock plugin if the template overrides work the way I think they work.  Eli double check me but if you merge that pull request in the magstock plugin, should do the trick.

**Comment by kitsuta** [comment]
Weird, that PR merge should have auto-closed this. Oh well, it's fixed now.

**Comment by EliAndrewC** [comment]
PR merges only auto-close things when they are merged into master.  We're still on mag-unstable.

Side-note: sometime in the near future we probably want to make mag-unstable the new master andhave a separate "magstock" branch that we merge master into when we're ready to deploy changes.
