### ISSUE TITLE
Favicon in IE and FF is anthrocon logo

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1091]
![magstock_firefox](https://cloud.githubusercontent.com/assets/7833809/7384665/ba1e0156-ee05-11e4-832c-126a7966521e.jpg)

**Comment by EliAndrewC** [comment]
Weird, I'll look into this after work.  I know @binary1230 dropped the correct favicon into place, but I'm guessing the anthrocon folks specified a different favicon in one of their templates or something.

**Comment by binary1230** [comment]
so technically, the Right Way to do it is to specify it in the header of the page somewhere, so that probably exists and is overriding the generally accepted, but not standards compiant, way of having a file named favicon.ico in the root dir.

my guess is somewhere something's doing that.

**Comment by kitsuta** [comment]
The relevant line is here:
https://github.com/magfest/ubersystem/blob/mag-unstable/uber/templates/base.html#L234

This was also hard-coded in master. The problem here is that whenever you try to use a relative link, the favicon does not show up properly. Until we figure that out, we're stuck hardcoding the URL.

**Comment by EliAndrewC** [comment]
Oh hey, look at that.  We can construct and absolute path using ``c.URL_BASE`` and ``c.PATH`` and such, so I'll plan on doing that when I get home if no one beats me to it first.

**Comment by binary1230** [comment]
Don't care that much BUT if we can do it with relative paths, that's better since someday I hope to destroy c.URL_BASE

but if it takes more than 5 minutes..... SHIP IT!

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/ubersystem/commit/769176cc9583e84d080e80f5ad3510786ce61272
