### ISSUE TITLE
Change magstock logo

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1093]
fuck mingstock
![magstockfinal](https://cloud.githubusercontent.com/assets/7833809/7401160/e122f42a-ee8f-11e4-83af-efcaf374e544.png)

**Comment by kitsuta** [comment]
Fixed in commits https://github.com/magfest/magstock/commit/168a636b44e0eabcf0e7ec24f6331e08b49377c3 and https://github.com/magfest/magstock/commit/a3539d0c408a182aa717b6e9a9e53b933d6901d0

**Comment by EliAndrewC** [comment]
Looks great!  (Then again, my opinion is pretty useless on how things look, since I also thought the wood paneling background looked good, haha.)
