### ISSUE TITLE
Add badge choice header to other forms

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1098]
We currently only show the ``BADGE_CHOICES`` header row on the main prereg form.  Anthrocon apparently also shows it on the confirmation page. There's probably also no reason not to show it on the form for assigning an unclaimed group badge as well.

**Comment by kitsuta** [comment]
Oh! Yes! That's pretty important as well.

**Comment by kitsuta** [comment]
It took a while, but we finally got this into master via https://github.com/magfest/ubersystem/pull/1224
