### ISSUE TITLE
fix base vagrant deploy

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1100]
the current vagrant deploy with master and the new config changes is probably broken, there's a few config options that have changed which need to be migrated.

**Comment by EliAndrewC** [comment]
If possible, I'd really love to see https://github.com/magfest/ubersystem-puppet/issues/28 tackled if/when you get a chance.  I'll see if I can find time for it myself, but with all the stuff on my plate I'm not sure when I'll get to it, and it would really make life easier for this kind of maintenance.

**Comment by binary1230** [comment]
fixed. (excluding the proposed config management changes, which we'll address when we do docker)
