### ISSUE TITLE
Re-add overlooked fixes from AC-Merge

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1101]
When doing the big refactor, I noticed that there was a ``dealerRules.html`` file which wasn't being linked to from anywhere.  I assumed it was a vestigial file which had been forgotten about.  Apparently it's something we put there so that we'd have a convenient page to link to when sending manual emails.  So it would be nice to add it back in.

**Comment by kitsuta** [comment]
I was talking about the dealer _registration_ template, not the dealerRules file (which I'm not sure IS linked anywhere). :P

I'm gonna repurpose this into a catch-all for logging things I find were reverted when they shouldn't have been.

**Comment by kitsuta** [comment]
While going through models.py (probably the most useful feature of PyCharm is a well-done compare feature you can easily fire up for any file) I found this block had been changed:

```
if self.badge_type in [PSEUDO_GROUP_BADGE, PSEUDO_DEALER_BADGE]:
            self.badge_type = ATTENDEE_BADGE
            if self.is_dealer:
                self.ribbon = DEALER_RIBBON
```

This was just a readability fix, so it should be re-added.

**Comment by kitsuta** [comment]
Actually @EliAndrewC it also looks like you left a bunch of `CUSTOM_BADGES_REALLY_ORDERED` stuff in? Wasn't that supposed to be officially changed for MAGFest?

**Comment by kitsuta** [comment]
Line 613 was reverted from `and self.badge_type in TRANSFERABLE_BADGE_TYPES` to go back to hard-coding transferable badge types, so that's definitely bad.
