### ISSUE TITLE
send banned emails to another email list (i.e. security)

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1107]
Dom says: "As a security staffer, I'd like to know when someone banned attempts to register for Magfest by getting an email sent to the security specific list."

looks like a simple change:

https://github.com/magfest/ubersystem/blob/457bf794df0dc32c26982a928051913e2b0f40fd/uber/site_sections/preregistration.py#L29

Just need to add in there a new _EMAIL config option like SECURITY_EMAIL.  It could default to REGDESK_EMAIL or be overridden by config to be a different address PLUS the original regdesk address.

-Dom

**Comment by thaeli** [comment]
I would prefer to send this email to an actual mailing list, and then whoever wants those notifications can subscribe to that list. Same code change to do that though.

**Comment by binary1230** [comment]
Oh yea and in fact that's what we do, we normally set say a new "SECURITY_EMAIL" config setting to be a security dept mailing list.  I could be wrong but I seem to remember you can set these vars to multiple emails already, so we could just put in the regdesk mailing list AND the security mailing list

**Comment by EliAndrewC** [comment]
Correct - config options are allowed to be lists of strings rather than just strings, and email destinations are also allowed to be lists of strings, so this is an easy change.

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/ubersystem/pull/1766
