### ISSUE TITLE
possible copy+paste bug: PORK

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1126]
this might not actually be broken, but bugging it here anyway. PyCharm flagged this:

in models.py in FoodRestrictions class:

```
elif restriction == PORK and {c.VEGETARIAN, c.VEGAN}.intersection(self.standard_ints):
```

should it instead be?

```
elif restriction == c.PORK and {c.VEGETARIAN, c.VEGAN}.intersection(self.standard_ints):
```

it's complaining about that PORK var

**Comment by kitsuta** [comment]
Yes, this is almost definitely just a missed c. addition.

**Comment by EliAndrewC** [comment]
Agreed.
