### ISSUE TITLE
at-the-con-mode keeps prereg form live

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1141]
Magstock folks want prereg form to stay disabled.

Going into 'at the con mode' will never allow prereg_base.html to show.  

probably add a config option like 'disable prereg' or just in 'at the con mode' or something.  will look at thsi later today, sorry for brevity, currently coding in a car dealership

**Comment by EliAndrewC** [comment]
Ah, interesting.  We'll need to make this configurable then, since MAGFest explicitly wants the prereg form to stay live during the event and MAGStock explicitly wants it not to be.

**Comment by binary1230** [comment]
yea it's goofy : )

**Comment by binary1230** [comment]
i can take a stab at this tonight, i anticpiate I'll just be mostly workign on / testing uber for magstock starting as soon as I get solid.  I'll be on-site tomorrow afternoon

**Comment by EliAndrewC** [comment]
That's fine, though I can tackle it instead if you'd like, since I already owe MAGStock a way to take campsite numbers and license plates at check-in.

**Comment by binary1230** [comment]
sure, if you have the bandwidth, go for it yea that'd be great.  hit me up if you need to punt it

**Comment by kitsuta** [comment]
Any chance we can do this in the plugin?

Maybe something like:
```
{% if AT_THE_CON %}
{% from preregistration %}
>javascript disables literally every field
>display message directing attendee to line
{% endif %}
```

**Comment by EliAndrewC** [comment]
Hmm, I'm not sure if that's how we'll want to do it long term, but that does sound like a good temporary solution.  Though I'll probably just redirect outright to the correct page instead of providing a link someone would need to click on.

**Comment by kitsuta** [comment]
Well no, it would tell them to get in line - this is something an attendee might see if they were trying to register on the phone, for example.

**Comment by EliAndrewC** [comment]
Ah, good point.  A link probably does make more sense than a redirect then.

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/magstock/pull/10
