### ISSUE TITLE
Create Duplicate Badge Form Emails in Uber

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#115]
Dupe badges are a huge pain in the arse and all require basically the same emails sent out with small variations. I'll need to write these actual emails out and probably meet with Eli to figure out how the feature would work, but the most common scenarios are:

Problem: Someone who has their own (non-special) badge and is in a group.
Solution: Tell them they can transfer their lone badge.

Problem: Someone is a group leader and has a special badge (Staff/Supporter/Guest)
Solution: Change the group leader badge to the other badge's type, then credit them with an extra badge in their group. Email them telling them you did this. (in uber, marking someone as something other than 'paid by group' moves the group # of badges down without changing the payment info - you can move the # of badges back up to give them an extra unassigned badge)

Problem: Someone has two special badges (this is surprisingly rare)
Solution: Offer to either refund them the basic badge price (i.e., if they have a supporter badge and paid $100, you'd refund them $40) or give them a badge to transfer to someone else.

Problem: Two people have the same name and email, but different age groups.
Solution: Add "Sr" to the elder individual, then email them and explain that you changed the names for easier check-in.

Problem: Someone has one regular badge and a comped badge of some sort.
Solution: Contact the staff member who made the comped badge, make sure a refund is appropriate. (this probably can't be automated, but might as well be included here)

Problem: All other cases PLUS everyone who hasn't responded to inquiries after several weeks.
Solution: Email them reminding them very strongly that they absolutely cannot pick up two badges under the same name, and recommend they transfer or re-sell one of their badges.

---------------------------------------
- Bitbucket: https://bitbucket.org/EliAndrewC/magfest/issue/116
- Originally Reported By: [Victoria Earl](http://bitbucket.org/kitsuta)
- Originally Created At: 2013-12-27T01:03:24.737

**Comment by kitsuta** [comment]
This is a customer service issue, not a code issue. Whoops.
