### ISSUE TITLE
Admins cannot sort the Staffers table

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1159]
The page registration/staffers used to have linked columns that allowed you to re-order the Staffers table by data. However, this functionality was accidentally removed after the merge and refactor for 2015. It should be added back.

**Comment by kitsuta** [comment]
Now that I'm looking into this, I notice that _all_ tables have had their client-side sorting removed. @EliAndrewC, did you do this during the refactor?

**Comment by EliAndrewC** [comment]
Hmm, if it was working before and is broken now then it must have been me, but I definitely didn't break it deliberately.

**Comment by kitsuta** [comment]
Closing this as a dupe of #1273.
