### ISSUE TITLE
API for Staff Suite Information collection

### ISSUE THREAD

**Issue by JennyTruss** [magfest/ubersystem#1163]
I would like to be able to grab information from the database to used in an external app for the Staff Suite. The app will handle food restriction/allergy collection, check in at the suite, and food ordering for delivery.

Information that I will need and would like to request using JSON:
Badge Number
Name
Attendee Type (staff, volunteer, guest)
Hours worked (to determine if they are food eligible)
Schedule (to determine where they are working to make filling in delivery form easier and faster and if they are actually on shift during service)
If they are a DH (if a DH missed cut off time for food delivery, they will have the option to designate a personal food runner to ensure they are fed)
Zip code ( or something to use as a check that it is that person signing in to order food)

Thinking this could either be on demand by entering in badge number and/or zip code and send to RAMS and get info back. or have either a timed or button triggered gathering of latest info of all that is saved in staff suite app.

**Comment by EliAndrewC** [comment]
This is really easy to put into an API; our system already supports exposing modules/classes/functions in this way, so it'll be really easy to whip something up and iterate from there.

The main thing we need to determine is how to manage our certs.  Our existing deployment assumes that we'll be running our own CA and issuing client certs which will be used for authentication.  That's easy to do, we just need to settle on how it's happening.

Joe Cooter from Tech Ops chimed in awhile back when I mentioned this to say, "Techops is planning on running a FreeIPA instance for authentication for things like wifi.  One of the things it includes is a CA infrastructure with an established way to manage and enroll systems and services.  We're actually looking for the uber API to streamline user account creation, so it's a bit circular, but it should be able to provide the CA stuff you're looking for (in addition to kerberized logins if you want to do that as well)."

So maybe we'll go with that.  Or for the time being we could just run a couple of ``openssl``commands by hand to make a CA and generate some client certs.

Regardless, this seems like something we can easily have ready around the same time we launch prereg for MagClassic (i.e. around the beginning of July).  And then at the very least you could point your own code at one of our staging servers for testing.

**Comment by JennyTruss** [comment]
Sounds good to me. Hit me up here or on Slack to let me know if there is
anything you need from me or anything else.

**Comment by gergc** [comment]
Adding to this, LAN/BS would like the same information (as you already know, we connect directly to the DB) with the addition of the phone number (if available). But yes, please let me know how it goes! :)
