### ISSUE TITLE
Set up puppet deploy configs

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1167]

**Comment by binary1230** [comment]
just about done this

**Comment by EliAndrewC** [comment]
Is there any chance we could get something like 
https://github.com/magfest/ubersystem-puppet/issues/28
if we're going to go with Puppet?  I can't count the number of times I've gone to make a simple change and then realized that I need to update the puppet repo as well to support a new config option oreven just an existing config option which wasn't already puppetized, etc.

Not strictly required, but if we're using puppet then I'd rather have this than almost anything :)

**Comment by binary1230** [comment]
I think I want to tackle the config stuff in docker, the puppet stuff is going away and I don't -think- we're going to need it for installing docker-related stuff.

I was looking around at some approaches included maestro-ng (a more powerful looking docker-compose like tool) which uses templating to insert different blocks of config.  that might be exactly what we need.

really, what I'm after is saying something like:

env = m14 production
m14 production = uber base settings + magfest base settings + couple of m14 tweaks
vagrant m14 = m14 production + couple of tweaks

**Comment by binary1230** [comment]
btw, actual vague plan for this (still investigating) is to use an orchestration tool like maestro-ng which supports templated config files.

maestro-ng uses jinja2 templates, so you can create a base config block,and inherit/override that per-environment per-server.

that would allow us to create a hierarchy of config templates without having to duplicate options and explicitly define them as we do now.

**Comment by binary1230** [comment]
I'm going to close this issue now as this task is done as far as magclassic is concerned.  The larger config stuff we'll have to address later.
