### ISSUE TITLE
Decide kick-in levels

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1168]
TBD

**Comment by kitsuta** [comment]
Ribbon, t-shirt, supporter package? Did we have Season Supporter last year?

**Comment by EliAndrewC** [comment]
We didn't have Season Supporter for 8.5 last year, so it was indeed just the levels you mentioned, IIRC.

**Comment by EliAndrewC** [comment]
I'm inclined to do $5 / $20 / $50 as the button / shirt / supporter levels.  That's what I implemented in puppet.  We can change it, but I'm gonna go ahead and close this issue for now.  We can re-open if people feel differently.

This was implemented in puppet.
