### ISSUE TITLE
Enable marketplace applications

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1169]
Prices TBD

**Comment by kitsuta** [comment]
This _should_ be just a config change. @nickthenewbie1 We'll need prices before we launch, can you get those?

**Comment by nickthenewbie1** [comment]
Trying to get those, but marketplace has been slow to respond.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by kitsuta** [comment]
@nickthenewbie1 Shall we call this done?

**Comment by nickthenewbie1** [comment]
Yup.
