### ISSUE TITLE
MAGClassic 2015: Shift Hours Error

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1179]
https://stage.uber.magfest.org/uber/jobs/index?location=40827098#2015-09-11%2008:00:00-04:00

Created a shift to be 8am on Friday in the Cat herding Department (We need to change the Department names back to traditional MAG names)

The page https://stage.uber.magfest.org/uber/jobs/index?location=40827098
Shows the job starting at Noon on Friday (4 hours later... is this Time Zone issue?)

I created a test staffer, and assigned him to Cat Herding,
https://stage.uber.magfest.org/uber/jobs/staffers_by_job?id=8b96b14d-8f78-4d93-93fc-ec8ea0ed62c0

When I go to assign them to that shift... no staffer is in the drop down box....

**Comment by kitsuta** [comment]
Moving out of the launch milestone because we don't actually need it until after launch.

**Comment by kitsuta** [comment]
I can't reproduce this on my local copy or on staging - it may have already been fixed. @bds002 can you confirm?

**Comment by bds002** [comment]
This still does not line up correctly on the Jobs page, production server, reviewed on 2 different browsers.

**Comment by kitsuta** [comment]
I'm not sure we're talking about the same bug.

**Comment by bds002** [comment]
I outlined the issue at the beginning.. Created a 8AM shift, it shows up on the Department schedule as a Noon Shift. -  3 hour time difference.

There is  secondary issue in that Staffers that are assigned to departments are not showing up in the correct departments.  Ben Seburn is assigned to Staff Suite, but is showing up in Staff Ops....

@EliAndrewC I don't think the Staffing section of Rams has been review since the big refractoring....
MAGStock had it, but didn't really use it. and it wasn't online for Anthrocon.

Brent

**Comment by earl7399** [comment]
These links all cause 500 errors at this point.  @bds002 can you recreate the issue, or provide links that work in Staging?

**Comment by kitsuta** [comment]
Just remove the location parameter from the URL and it should work.

**Comment by earl7399** [comment]
That leaves me looking at a consoles schedule with 1 8AM shift.  When I switch to one of the other views, I cannot switch back to the calendar view without first changing the location drop-down.  However, I don't see the 8 vs 12 problem.

**Comment by bds002** [comment]
Staff Ops created for 8AM start - 

![ops_8am](https://cloud.githubusercontent.com/assets/8822346/8891573/c3adfbd0-32fd-11e5-8079-969ef793df11.PNG)


Ops Calendar displaying incorrect info:
![ops_calendar](https://cloud.githubusercontent.com/assets/8822346/8891575/cf8871c4-32fd-11e5-9074-3fb94e4db90d.PNG)

**Comment by kitsuta** [comment]
OH, I know! The text is displaying in the middle of the four hour block,
but there's no border, so it looks like it's in the wrong place. So this is
a minor display bug.

**Comment by kitsuta** [comment]
I see also that you re-filed the secondary issue as bug https://github.com/magfest/ubersystem/issues/1264 - thanks. :)
