### ISSUE TITLE
Change convention to festival on prereg page

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1189]
"Allows access to the convention for its duration."

should be

"Allows access to the festival for its duration."

**Comment by EliAndrewC** [comment]
Maybe instead of changing Festival to Convention for anyone in the ``jerks`` config setting, it could do something even worse.  Does anyone have any ideas?

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/magclassic/commit/020aa3d4011be1f7bdc41441cc7b67a8b26080b2

I could have changed it in the core repo, but most places are fine with the word "convention" so I left it unchanged in the core repo :P

**Comment by kitsuta** [comment]
Y'know Eli, that `jerks` setting really shouldn't stay in the main repo. :P

**Comment by EliAndrewC** [comment]
Not only should it stay in the main repo, we should make it extra-configurable, like instead of just flat-out replacing festival/convention you can define arbitrary substitutions!

I mean, it's not like other events don't have jerks :P
