### ISSUE TITLE
Replace pre-reg masthead image

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1190]
![masthead](https://cloud.githubusercontent.com/assets/7833809/8512804/1c5d2328-2322-11e5-8b9b-be84a4de5cb8.png)

**Comment by EliAndrewC** [comment]
This appears to have been done, since I see the Magstock logo on the staging server.

**Comment by EliAndrewC** [comment]
Wait, never mind - it's not showing up on my local dev server.... I suspect that someone just told Nginx to serve a different file or something, which isn't the "correct" way to do it... but I guess so long as it works on both the staging and production server I'm not gonna worry about it for now.

**Comment by nickthenewbie1** [comment]
I see a different colored and truncated version on mine. http://imgur.com/oJHtKlv

**Comment by EliAndrewC** [comment]
Oh, you want the B&W version?  I can make that change pretty easily if so.

**Comment by binary1230** [comment]
history:  I made the crappy color version of the logo that is checked into the plugin now.

Nick wants that color version replaced with this nicer black and white version.

I don't believe we're doing any shenanigans with nginx, if you see anything that looks like that, file that as a bug, nginx should be completely vanilla and sane.

**Comment by binary1230** [comment]
for the record I would personally vote for a colorized version of Nick's logo here, but keep Nick's framing.  but IANAA (I am not an artist)

**Comment by binary1230** [comment]
short version is we replace dis https://github.com/magfest/magclassic/blob/master/magclassic/static/theme/banner.png

**Comment by EliAndrewC** [comment]
It was actually just a caching issue on my machine; my browser was serving the old cached banner.  Sorry for the confusion; Dom did check in the new banner the correct way.

I'll need to do some tweaking since the current styling assumes the banner is a certain height, but that should just be a one-line CSS change in our ``regextras.html`` override.

**Comment by EliAndrewC** [comment]
Honestly I think the colorized version looks better.  Here's what the B&W version looks like on my machine:
http://imgur.com/l4krYqU

I could tweak the width to make it line up, but I think it would be better to get a non-truncated version of the colorized logo and use that.

**Comment by kitsuta** [comment]
@nickthenewbie1 Any chance we could get an updated color logo that matches the framing of the B&W one? I also think colorized looks better, it's easy to read since the graphic itself is a bit busy.

**Comment by nickthenewbie1** [comment]
Would you be able to put it together with this?
https://www.dropbox.com/s/t5jrjyrj10hmdr1/Magclassic_07_Linecleanup.psd?dl=0

If not, I can whip one up with a little screepcap mspaint magic.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by kitsuta** [comment]
I can't actually open that PSD properly in GIMP, but I'll go ahead and screencap it for myself. :) Thanks!

**Comment by kitsuta** [comment]
Closed by https://github.com/magfest/magclassic/pull/3
