### ISSUE TITLE
MAGClassic 2015: Menu Bar Format Issues / LOGIN ID

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1212]
On the Top Menu bar - the following changes needs to be made.

1 = Please add a mouse over message to the icons on the far right hand side so users know what the Icons mean: (Github/Issue Tracker, Site Map, Login/Logout Icon respectively)

2 = We need verbage on that page that indicates who is logged in (Logged in as: xyz...)

**Comment by kitsuta** [comment]
Doesn't need to be in place to launch MAGClassic, so I'm moving it to a different milestone.
