### ISSUE TITLE
MAGClassic 2015: feature request: Marketplace M Points badge tracking

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1213]
Just a thought- talking to Ruby at Anthrocon about magfest marketplace -- 
Marketplace in the past has recorded Mpoints to cash exchanges from the vendors on paper.  Would we want to consider an Input method for Marketplace to record Mpoint exchanges linked to Vender badge numbers.... (Badge # turned in $250 in Mpoints, $250 in cash returned to them)
Eli seems to be the recipient of this paper trail per Ruby

Brent

**Comment by EliAndrewC** [comment]
There is a form for this in Uber, and the reason why they've tracked it on paper traditionally is that we haven't had reliable wifi in the past.  Now that we kind of probably do, we can probably switch to paper being the backup they use when the system is down and they can use a laptop at the Marketplace desk to enter the data as people do the cashouts.

**Comment by kitsuta** [comment]
So then, does this feature work and therefore the issue can be closed out?

**Comment by EliAndrewC** [comment]
I'd say so.  We should still take the action to make sure that Marketplace has a working laptop/tablet/phone with Uber access, but that doesn't need to be tracked here.
