### ISSUE TITLE
volunteer interest enums outdated

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1214]
For Magclassic, the volunteer interests are placehodler and still reflect Magstock settings, fix or copy these from last year's uber

**Comment by EliAndrewC** [comment]
Whoops, I thought I had fixed all of that in the puppet hiera data on mcp.magfest.net but apparently not!

**Comment by binary1230** [comment]
repeating here: IN THEORY, the new procedure for this should be to modify the repo, and 'magbot deploy' now runs a script that pulls down the latest ubersystem-puppet, ubersystem-deploy, and magfest-hiera-nodes before doing the actual deploy.

So, IN THEORY, you shouldn't ever need to SSH into mcp anymore.  However, I didn't test this amazingly thoroughly so not super-sure.

Also, if you made changes on mcp, you may need to commit them and 'git pull' to bring it up to head in order to make sure magbot doesnt choke on detached heads or something.  Eli, lemme know if you need me to look at that (I probably will in a sec anyway)

**Comment by EliAndrewC** [comment]
Gotcha.  Yeah, I made a bunch of changes on ``mcp.magfest.net`` to the hiera data.  I can commit those to the puppet data repo when I get home, though you're welcome to do that yourself if you get to it before I get home tonight.

I kind of forgot we had a puppet data repo - whoops!

**Comment by EliAndrewC** [comment]
Where is the puppet data repo?  I can't find it under either https://github.com/magfest/ or https://github.com/binary1230?tab=repositories

/cc @binary1230

**Comment by kitsuta** [comment]
It's a private repo, so won't show up in the page you linked. I'll send you a link in Slack.

**Comment by EliAndrewC** [comment]
Awesome, thanks.  I'll try to figure out what options we had there last year and use those then, unless someone else knows specifically what departments should exist for those checkboxes.

**Comment by bds002** [comment]
So the Attendee Interest "What interests you?" got updated, but we still have Slip 'n Slide, & Cat Herding of MAGClassic Volunteer Options... Can we have a Slip n Slide at the Mark Center? It should still be warm in September.  Cat Herding should be security etc...

**Comment by binary1230** [comment]
i dont think there's any harm in me posting the private repo link, which is 
https://github.com/binary1230/magfest-hiera-nodes

it should come up as a 404 for anyone I didn't share the link with.  @EliAndrewC , you should have access already

I just today also requested a Bronze github plan, which 501c3's can get for free, which comes with 10 private repos, so we can move that repo to the magfest github organization when we get the clearance.
