### ISSUE TITLE
typo in "what you get for volunteering"

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1215]
static html, says:

In the What You Get For Volunteering dialog box there's a minor typo:
Working at least 18 hours gets you a complementary Staff badge for next year's MAGClassic, which will make you eligible for space in one of our staff hotel ```rools.```

**Comment by kitsuta** [comment]
@earl7399 Go ahead and fix this in the master repo, please.

**Comment by EliAndrewC** [comment]
Since I'm about to make a PR with a bunch of other changes anyway, I went ahead and fixed this typo.  It'll get merged in with that PR.
