### ISSUE TITLE
prereg form allows you to enter same phone# for your phone and emergency contact

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1216]
It should not do this? probably not.

**Comment by EliAndrewC** [comment]
Hmm, when I was in high school and no one in my family had a cellphone yet, my home phone and EC phone would have been the same number.  Is that realistic these days?  With 20,000 people someone is probably in that same boat.  On the other hand, most people who enter the same number are just not paying attention or not bothering to do the right thing, so maybe another checkbox shows up if they're the same value that says "No really, this is the landline to my house, and it's what you should call if something happens to me"?

**Comment by kitsuta** [comment]
People who don't want to bother giving us an emergency contact # will always find ways to be lazy. I don't think we should worry too much about it beyond some basic checks (which are already in place).

One case where the numbers would be the same is a parent registering a minor without a cellphone. I don't think it's worth it to inconvenience/confuse attendees doing that for the sake of possibly preventing a few attendees who don't want to give us a second number.

**Comment by EliAndrewC** [comment]
I agree with @kitsuta so I'm gonna marked this as closed.
