### ISSUE TITLE
Add separator on group pre-reg form 

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1218]
When pre-registering a group you're asked to give the group name, number of badges in the group, and then the info for the group leader's badge.

Underneath the dropdown for number of badges in a group, there should be a text header that says "Please enter the information for the group leader (additional group member information will be entered after purchase is complete)"

**Comment by EliAndrewC** [comment]
I've confirmed this as working on my machine so I'm closing this as resolved.
