### ISSUE TITLE
Add t-shirt sizing guide

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1219]
Next to t-shirt size put: "Size guides: Unisex (http://www.mygildan.com/Categories/T-Shirts/Short-Sleeve//p/2000L), Female (http://www.mygildan.com/Categories/T-Shirts/Short-Sleeve//p/2000L)"

**Comment by kitsuta** [comment]
These both link to the same thing.

**Comment by nickthenewbie1** [comment]
Sorry here's the unisex one: http://www.mygildan.com/Categories/T-Shirts/Short-Sleeve//p/2000

**Comment by EliAndrewC** [comment]
Since this has been fixed and I've confirmed the fix on my machine, I'm marking this as closed.
