### ISSUE TITLE
Implement badge statuses from Anthrocon

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1222]
Anthrocon asked us to implement badge statuses for their registration last year. This ended up being a really useful feature and I want it for MAG events, including Classic if possible.

The statuses include:
* New (registrations that are simply not complete, usually because they're unpaid)
* Complete (attendees that can check in without further action)
* Invalid (duplicates, mistakes, and badges we want to 'delete')
* Deferred (attendees who cannot check in for various reasons, usually having to do with the watch list)
* Refunded (not the same as 'paid and refunded,' these are fully refunded badges that cannot check in)

We may want this as a plugin, but it's useful enough and hooks into a lot of other different features that I'm thinking of putting it in core. @EliAndrewC thoughts on that?

**Comment by thaeli** [comment]
+1 for core. This is exactly the sort of global feature that should be in core.

**Comment by EliAndrewC** [comment]
Agreed; this seems like something which absolutely belongs in core.  Obviously plugins can override and add behaviors if they want different sets of statuses, and ideally it will be easy enough to do that, but regardless this seems like a good core feature.

**Comment by EliAndrewC** [comment]
With that being said, I'm not sure that this is something we need at launch.  Not that it would be bad to have, I just don't think it's necessarily a blocker.

**Comment by kitsuta** [comment]
Yeah, I was planning to get this stuff done this weekend, but wasn't able to get around to it. The statuses themselves will be a little messed up if we implement it after launching, but we'll just have to deal with that.
