### ISSUE TITLE
Move badge level below "please enter information...."

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1225]
To make it more clear that the badge level selection is just for the group leader, move the badge level buttons below the "Please enter the information for the group leader" notice.

**Comment by EliAndrewC** [comment]
Good idea.  All that's needed to make that happen is to move the ``div`` at line 48
https://github.com/magfest/ubersystem/blob/master/uber/templates/preregistration/form.html#L48
to right before the ``regform.html`` include:
https://github.com/magfest/ubersystem/blob/master/uber/templates/preregistration/form.html#L162

I can do that after work tonight, or someone else can make that change if we want to launch preregistration during the day today.
