### ISSUE TITLE
Remove Supporter badges

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1227]
As discussed in https://github.com/magfest/ubersystem/pull/1223, the idea of assigning Supporters a badge has caused us multiple problems in the past because they can't be combined with Staff badges.

For MAGClassic, it would be nice if we stopped assigning Supporter badges and instead added a "Supporter swag" line to the merch field if someone has a kick-in level above Supporter.

So it would display it in three places:
* The modal pop-up we use to check people in
* The message shown when someone checks in
* The Merch page

The new style of Supporter badge would be numberless, and for swag purposes only.

**Comment by EliAndrewC** [comment]
Would staffers rebel if we did the same thing with Staff badges too?  It would be nice if those could be numberless and just go along with their "real" Attendee badge as well.  That way we could eliminate preassigned badges from the core repo.

**Comment by kitsuta** [comment]
I'd lean towards keeping Staff badges custom because those grant you special privileges. If we got rid of them, we'd have to come up with something else to denote that someone is staff, and anything besides a custom badge is relatively easy to transfer between attendees and difficult to trace.

**Comment by EliAndrewC** [comment]
Hmm, that's a good point, Staff badges being numbered does have some utility which doesn't matter for Supporter badges.  Alas!
