### ISSUE TITLE
MAGClassic 2015: Affiliate's field on Pre-reg doesn't have a text box or none of the above option

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1228]
So Issue # 903 & #174 sort of address this, but the current issue isn't solved for Classic.
On the Prereg form: 
https://classic.uber.magfest.org/uber/preregistration/form

We ask attendees to identify their affiliation, there are 9 affiliations listed.
The link on the right hand of that line "What's an affiliate?" goes to:
https://classic.uber.magfest.org/uber/static_views/affiliates.html

In which is stated: "You can choose one of the default affiliate groups, enter a new one, or ignore this completely. "

--- We don't have a spot for people to create new Affiliation groups (no text box, or none of the above option).

**Comment by kitsuta** [comment]
While it's not the most obvious bit of UI, you can actually just type in a new affiliate name and hit "enter" to create a new affiliate.

**Comment by bds002** [comment]
Yeah - my Browser (Firefox) won't let me do this.

**Comment by kitsuta** [comment]
Yeah, so it's broken - likely related to Bootstrap, since that was a really big UI change. It shouldn't block MAGClassic launch, but I'll put it on the next milestone after that.
