### ISSUE TITLE
MAGClassic 2015: Date of Birth Error message

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1229]
On the Registration page when someone enters the incorrect month, there is a message that says - "Month must be 1-12", for date it says "Day must be 1-31"...  Both of these message are Red and immediate so the end user know to correct them.

For Year - there is no error message. It's not until you click register and if you have a birthday in the future you get "You cannot be born in the future." as an notification message across the top of the browser.. I also got it as Text that blends into the Classic Logo so that the actual text is unreadable.  I entered 2020 as the test for Birthday year and got the error message, When I entered 1800 as the birth year I didn't get an error message ... 

Can we insert come logic check command here to make sure Birthdate is Current year or earlier?
(to match the error messages received for Day and Month enteries.
Maybe add something for 1800 as well - Current year - 125 years as part of the logic check.

**Comment by EliAndrewC** [comment]
I'm not sure if the javascript library we're using supports that, but it certainly seems like it should!  There's probably some config option for that - I'll look into that tonight.

**Comment by kitsuta** [comment]
This is a @thaeli question if she's available before we get around to it.
