### ISSUE TITLE
MAGClassic 2015: Department Checklist

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1231]
Can we please remove the following from the MAGClassic Department Head Checklist:
"https://classic.uber.magfest.org/uber/dept_checklist/item?slug=hotel_assignments"
Assign Hotel Roomates You KNOW Want To Room Together

Also the format looks awkward on Firefox:
https://classic.uber.magfest.org/uber/dept_checklist/overview

**Comment by bds002** [comment]
Speaking of the Checklist....
https://classic.uber.magfest.org/uber/dept_checklist/index

All the dates are Nov. & Dec....

**Comment by EliAndrewC** [comment]
Thankfully all of that can be handled in configuration, so this shouldn't be a big deal once we're past getting prereg launched.
