### ISSUE TITLE
MAGClassic 2015: Pending Emails needing Approval

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1232]
We have two emails in the system currently:
https://classic.uber.magfest.org/uber/emails/pending
-------------------------------------------
Claim your MAGFest 8.5 tickets with your MAGClassic Season Pass 	MAGFest Registration <regdesk@magfest.org> 	See Examples 	
Claim your Monster Party tickets with your MAGClassic Season Pass 	MAGFest Registration <regdesk@magfest.org> 	See Examples 	
-------------------------------------------
Should they be updated to MAGClassic?

**Comment by kitsuta** [comment]
This isn't a bug or a problem. Just ignore them.
