### ISSUE TITLE
MAGClassic 2015: Group Registration

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1235]
Issues related to #1166 #1193 

When you select Group registration on:
https://classic.uber.magfest.org/uber/preregistration/ 
The box doesn't highlight like is does for Attendee or Supporter.

The discount says that badges or $40/per for a minimum of 8 badges purchased.
I went through and added 8 people to 1 registration page (Name 1 Last Name 1  - Name 8 last name 8)  The checkout page shows me a cost of $50 each for a total of $400.

There was some discussion about groups getting swag or extras instead of ticket discounts for future event, but keeping Groups price discount for MAGClassic 2015.

It appears to me that the Group Registration is not working as planned.

**Comment by kitsuta** [comment]
NAB - please test staging, production hasn't been deployed in a while.
