### ISSUE TITLE
MAGClassic 2015: Badge Level vs "Want to Kick in extra"

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1236]
as referenced in #1075 for MagStock,

Should we remove the Kick in Extra drop down box if we are using the Badge Level options earlier on the registration page.  The only extra in the Kick in drop down box is $5 for a button. 

It seems like extra confusion on the registration page, not worth the $5 button option.

**Comment by kitsuta** [comment]
It's a bit redundant, but since the dropdown box changes when you select the different buttons, it should be fine. I don't think we should consider this an issue until/unless someone complains.

**Comment by nickthenewbie1** [comment]
I vote to axe the "button" level, and then the dropdown as well. Does anyone feel strongly against that?

**Comment by EliAndrewC** [comment]
If an event literally has zero donation tiers which aren't already listed in the Badge Type row, then it seems reasonable to not display it in those cases, as removing redundant form fields seems like a good idea.

As for removing it in general, let's look at the numbers.  Here's a list of the kick-ins which MAGFest had last year:
- 1306: Ribbon ($5)
- 1144: Button ($10)
- 1053: Tshirt ($20)
- 596: Supporter Package ($60)
- 82: MAGFest USB Drive ($100)
- 43: Season Supporter Pass for 2015 ($160)
- 13: MPoint Holder ($200)
- 6: Lightsuit ($500)

Let's assume that MAGFest itself would only list Attendee, Tshirt, Supporter, and Season levels and simply not have any of the other levels.  Let's further assume that anyone who donated at any other level would have instead donated at the level below that (e.g. the MPoint Holder folks would have just been Season Pass folks instead).

That means that last year we'd have lost out on exactly $3900 in revenue, which if memory serves is less than one half of one percent of last year's revenue.  Sooo... yeah I'm probably okay with axing it all the time on the basis that it's just not worth the hassle.

**Comment by nickthenewbie1** [comment]
DO you have those numbers for 8.5?

**Comment by EliAndrewC** [comment]
With that being said, this might be slightly non-trivial to remove.  I mean, it's not more than a few hours work at most, but all of the logic behind showing/hiding rows based on the donation level is currently tied into that dropdown.  We'd just have to tie it to the Badge Type row instead, which I doubt would be all that hard.  However, I'm not sure that I'll have time for that tonight, though I should definitely have time for it tomorrow night.  If we're comfortable waiting that long to launch then that's fine by me.  Or we could launch with it as-is and then deploy this change after launch.  Either way.

**Comment by nickthenewbie1** [comment]
If it's non-trivial, then we'll just leave it in for classic. It's not that intrusive. We can revisit for super mag.

**Comment by EliAndrewC** [comment]
> DO you have those numbers for 8.5?

https://half.uber.magfest.org/ is apparently no longer online.  If it was then you could find those numbers at the bottom of the https://half.uber.magfest.org/magfest_85/summary/affiliates page.  Since it's not I'd need to check the database, which I can't do from work.

**Comment by binary1230** [comment]
https://archive-half.uber.magfest.org/magfest_85/

**Comment by nickthenewbie1** [comment]
Closing this since we will not be removing the dropdown for classic.

**Comment by EliAndrewC** [comment]
That's fine, but I'd still like to remove the $5 button level in the MagClassic if we plan on removing the dropdown for MagPrime.  Otherwise it'll be harder to remove the dropdown later and run the two of them out of the same core repo, since a lot of that logic is in core Ubersystem.

**Comment by nickthenewbie1** [comment]
Fair enough. You're the boss.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by binary1230** [comment]
removed $5 button
