### ISSUE TITLE
Add price increase warning

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1237]
Below badge level buttons, add red italic text that says "Prices increase by $10 on August 1st"

**Comment by bds002** [comment]
Since Classic had a low attendance last year and with registration is going up so late (so close to event), would there be any consideration to changing the Price Increase date from Aug. 1st to 8th? That gives people just over 2 weeks, instead of 10 days after we launch before prices go up.

**Comment by kitsuta** [comment]
Would there be any consideration to _not increasing the price_? :P

Seriously though, I'll ping you about this in private.
