### ISSUE TITLE
Add deadline to t-shirt and supporter pack

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1239]
Add "Available Until August 20th" on t-shirt and supporter buttons.

**Comment by EliAndrewC** [comment]
The way this works now (and has worked for the past several years) is that only the next deadline is shown at any given time.  So as of now, the message will currently be "Price goes up to ___ on ___." and then after the final price bump it'll say "___ closes on ____" or whatever.

That will happen automatically for the Supporter registration, but currently the tshirts are not configured with a cutoff date.  We can add a cutoff date for them, but do we really want to?  Typically we keep shirts up for sale all the way until Uber goes offline right before the event.  Closing tshirt sales several weeks beforehand seems like a waste.

**Comment by kitsuta** [comment]
I actually quite like the way it works now, I'd forgotten about it.

**Comment by nickthenewbie1** [comment]
Ok, i like how the message switches from price bump to deadline.

Also ryan says he does not need to cut off shirt orders early, and will instead use his predication method. No deadline on shirts is needed aside from the normal badge deadline.

**Comment by kitsuta** [comment]
OK, since the current behavior is acceptable, I'll go ahead and close the issue.
