### ISSUE TITLE
dealer reg still open

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1242]
![image](https://cloud.githubusercontent.com/assets/5413064/8811806/5bd28f74-2fc6-11e5-8007-b84ce4dd581c.png)

and looks uglaaaay

**Comment by binary1230** [comment]
bug is that I need to close dealer reg

**Comment by binary1230** [comment]
config is getting set correctly.... weird.

seems to be an issue with our c.AFTER_xyz  functionality, checking it out in the debugger.

**Comment by binary1230** [comment]
WAIT lying didn't see this other config option:
BEFORE_DEALER_REG_PUBLIC

we'll need to set that in puppet.... adding...

**Comment by binary1230** [comment]
fixed

**Comment by kitsuta** [comment]
https://github.com/magfest/ubersystem/pull/1245

**Comment by binary1230** [comment]
ah yea thanks i had something else in my pastebuffer
