### ISSUE TITLE
android phone getting stuck on slow loading page

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1246]
AFTER paying successfully and finishing preregistering, Tony got stuck on this page.  Android OS

Guess we better test some mobile stuff

```
We rely on modern technology in order to provide you with a safe and secure registration and checkout experience. Because of this, our registration interface may not work for everyone. Here are the common reasons behind problems you may be experiencing:

Outdated Browsers: We support IE8+, Google Chrome, and Mozilla Firefox. Please make sure your browser is up-to-date.JavaScript Disabled: We use Javascript to dynamically display our registration and payment form. Please make sure any script-blockers are turned off or disabled for this website.Firewall Blocking: Some users may not be able to access our site from their place of work, as the form can be partially disabled by strict firewall rules. Please try accessing the form from home instead.

If you are having trouble accessing the site and you need help, please contact us at anthrocon AT anthrocon DOT org.
```

**Comment by kitsuta** [comment]
Can you define "stuck" a little better?

That message displays when you click on the "Loading..." page. Is it possible that Tony hit it by accident?

**Comment by binary1230** [comment]
not super-sure.  apparently after finishing with Stripe, instead of getting to the confirm page, it stayed on this page indefinitely.

**Comment by kitsuta** [comment]
This works for me on staging. Until we can get more information, we can't really do anything about this.

**Comment by thaeli** [comment]
Sounds like they double clicked at just the wrong time. The existing slow load handling code was written in part to handle AC specific requirements around ancient browser support. I can make this much more reliable overall if we do not require defined behavior on pre-JavaScript browsers.

**Comment by earl7399** [comment]
Don't miss the fact that it refers the user to AC, not MAGFest

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by kitsuta** [comment]
We can't do anything with this until/unless we get more information on what is actually happening, so I'm closing this out.
