### ISSUE TITLE
incorrect text for dealer apps

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1248]
dealer_confirmation.html has a bunch of refs to anthrocon, replace with EVENT_NAME and such.

```

    Your Dealership Payment includes your table cost, your Dealer Membership, and any selected Dealer Assistant
    Memberships.  After payment, you'll be sent a link by email to follow if you wish to later upgrade your membership.
    Your Dealer Assistants will be able to upgrade their own memberships and pay for those upgrades on their own.
```

replace 'membership' with 'registration' or similar.  may even want to have a config option for this like {{ c.TXT_REGISTRATION }} and set it to 'registration' by default

**Comment by kitsuta** [comment]
Let's try to limit the number of superfluous text-change-only config options, please. :)
