### ISSUE TITLE
Magclassic 2015 Masthead framing on mobile

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1249]
Shit's fucked.
![screenshot_2015-07-21-21-15-07](https://cloud.githubusercontent.com/assets/7833809/8815921/e5ec9a3e-2fed-11e5-8b82-6dfa5ba5388a.png)

**Comment by earl7399** [comment]
Looks good on my phone?  Your phone must suck.  ;)
[image: Inline image 1]

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by nickthenewbie1** [comment]
I just realized the wood paneling is there, so I might have a cached version

**Comment by nickthenewbie1** [comment]
Refreshing corrected the issue. Sorry.
