### ISSUE TITLE
MAGClassic 2015 Departments for staffing

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1251]
We need to add a number of departments to the MAGClassic 2015 information.
Looking at this page: https://classic.uber.magfest.org/uber/registration/form?id=None

The following departments are listed under "Where do you want to help?"
 Consoles   Arcade   LAN   Music   Panels   Tabletop 

The following departments are listed under Assigned Departments:
Consoles   Arcade   LAN   Panels   Tabletop   Marketplace   Stops   Fest Ops

For 8.5 we had the following departments:
Requested Depts.
 Anything   Arcade   Consoles   Food Prep   Jam Space   LAN   Panels   Regdesk   Security   Tabletop   Tech Ops   Video Room

Assigned Departments:
 Arcade   Artemis   Challenges   Charity   Chipspace   Concert   Consoles   Contractors   Dispatch   Dorsai   Events   Fest Ops   Food Prep   Indie Games   Jam Space   LAN   Load-In   MEDIATRON!   Marketplace   Merchandise   Reg Managers   Regdesk   Rescuers   Security   Shedspace   Staff Support   Staffing Ops   Tabletop   Tabletop (CCG)   Tea Room   Tech Ops   Treasury

-----
We need to add the departments so DH's can start assigning their staff.

**Comment by kitsuta** [comment]
Looks like the job interests were updated, but not the actual job locations (the former controls what attendees can ask for, the latter controls what they can be assigned to).

**Comment by bds002** [comment]
We are still missing Security, Dorsai, and Reg Ops if @kitsuta is going to have that department.

**Comment by bds002** [comment]
@nickthenewbie1 Are we going to have MEDIATron as a department at Classic - 
We also need Tea Room listed... as well as Treasury
@binary1230 Are both Artemis and StarShip Horizons going to be at Classic?

The following is the list we used for MAGClassic Can the same list be added/updated?
Arcade Artemis Challenges Charity Chipspace Concert Consoles Contractors Dispatch Dorsai Events Fest Ops Food Prep Indie Games Jam Space LAN Load-In MEDIATRON! Marketplace Merchandise Reg Managers Regdesk Rescuers Security Shedspace Staff Support Staffing Ops Tabletop Tabletop (CCG) Tea Room Tech Ops Treasury

**Comment by EliAndrewC** [comment]
This was fixed in the production config earlier this evening.

**Comment by nickthenewbie1** [comment]
We will have MEDIATRON!, however that group is presently invite only, and
should not be shown to the public for signups.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org
