### ISSUE TITLE
MAGClassic 2015 Attendee Badge Sales Cap Error

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1255]
So current Magbot answer in slack:
magclassic badges sold/left: 106 / 19894

Cap for MagClassic should be 2,000 not 20,000

**Comment by binary1230** [comment]
great catch

**Comment by binary1230** [comment]
huh. I commented this out during a refactor and never commented it back in, I'll check in the easy fix in a few.

**Comment by binary1230** [comment]
fixed by https://github.com/magfest/ubersystem-puppet/pull/32
