### ISSUE TITLE
Group payment should check all group members

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1257]
The ``/preregistation/group_members`` page has a payment link which appears if the group is unpaid.  The two most common things which would cause this are
- the group has unpaid badges
- the group has one or more members who kicked in extra but then didn't pay

There's code in ``/preregistration/process_group_payment`` which checks the second condition - but only for the group leader.  It should check it for all group members instead of only the group leader.

**Comment by kitsuta** [comment]
Actually, I'm not so sure that this is desired behavior. If we did this, then the group leader would be prompted to pay for group members' kick-in levels - that's not really something people would normally want to do. I think we only checked the group leader because we only ever wanted the group leader's kick-in level to be included in the group's payment prompt.

**Comment by EliAndrewC** [comment]
Well, consider the two scenarios:
- after the group is paid for, the group leader ups their kick-in level and doesn't pay
- after the group is paid for, a non-leader group member ups their kick-in level and doesn't pay

It seems like we should display a payment warning/link for either both of those situations or neither.  I don't have a strong opinion on which, but the inconsistency seems bad.

**Comment by kitsuta** [comment]
Hm, I agree, but I don't want either:
* The group leader to have to pay for the group's cost, then in a separate transaction pay for a kick-in level they selected for themselves earlier
* A group member kicking in and not paying, and the group leader getting a payment warning and thinking that we increased the price of the group or something

**Comment by EliAndrewC** [comment]
> The group leader to have to pay for the group's cost, then in a separate transaction pay for a kick-in level they selected for themselves earlier

Since the group leader has to pay for his own kick-in when the group is initially paid for, I'm not sure that's even possible at the moment.  How would we end up with an unpaid group leader kick-in for a group which hasn't even been paid for yet?

> A group member kicking in and not paying, and the group leader getting a payment warning and thinking that we increased the price of the group or something

Fair enough, I can see wanting to alert the attendee rather than the group leader in this case,

**Comment by kitsuta** [comment]
>Since the group leader has to pay for his own kick-in when the group is initially paid for, I'm not sure that's even possible at the moment. How would we end up with an unpaid group leader kick-in for a group which hasn't even been paid for yet?

I, er, don't quite know what this situation would be. So then do we want to remove the group leader from the charge form?

**Comment by EliAndrewC** [comment]
I think so, for the sake of consistency.  Either all kick-ins should show up as an unpaid group balance or none of them should.  Otherwise it'll be confusing, both to the people in the group and to us when a year from now we've both forgotten we ever had this conversation.

**Comment by nickthenewbie1** [comment]
Should we be allowing unpaid group member kickins to exist? I understand that the group leader for a vendor may have an unpaid bill, including their group leader registration, but why would we allow group member upgrades to exist in an unpaid state?

**Comment by EliAndrewC** [comment]
There's a backlog ticket for getting rid of that and making those changes pending.  Right now the (simple) workflow is:
- group member adds a kick-in, and edits various other fields such as tshirt size
- their registration is saved,
- they are prompted to pay based on what they entered

What we want the workflow to be is
- group member adds a kick-in, and edits various other fields
- the parts of their registration are saved EXCEPT the parts that relate to the kick-in, which are stored in the session
- they are prompted to pay based on the extra stuff
- after they pay, the remainder is saved

Alternatively, we could just have their entire registration not saved until they pay.

The first option was much less work, which is why we did it that way.  We can just send reminder emails and reset their registrations to no longer having the kick-in if they don't pay, which is what we currently do.  Obviously the other approaches would be better, so whenever we can find time for that we'll get to it.  I don't recall the issue number, but it's definitely a ticket.

**Comment by kitsuta** [comment]
Huh... actually, upon testing, this was already fixed.
