### ISSUE TITLE
Several job pages need to be faster

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#127]
I'm hacking around this for our convenience during the con, but for next year I'll need something better for Job.everything().

---------------------------------------
- Bitbucket: https://bitbucket.org/EliAndrewC/magfest/issue/129
- Originally Reported By: [ ](http://bitbucket.org/EliAndrewC)
- Originally Created At: 2013-12-30T21:52:18.131

**Comment by kitsuta** [comment]
You fixed this with #976 right?

**Comment by EliAndrewC** [comment]
I did, thanks  I'll close this now.
