### ISSUE TITLE
add dates and event name to confirmation emails

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1275]
Amazingly, some people still get confused about which event they actually registered for.  We should make sure the attendee confirmation email text includes the event's name, date, and whatever else.

Use c.EVENT_NAME and similar config variables for this.

**Comment by earl7399** [comment]
If it isn't already happening, they should see these dates a least *2
billion* times before they pay money.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

On Mon, Jul 27, 2015 at 3:45 PM, Dominic Cerquetti <notifications@github.com
