### ISSUE TITLE
[MAGClassic] Vendor special requests and address not being addedto db

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1282]
After submitting the dealer application form, the special request and address fields are not shown on the corresponding group page.

**Comment by kitsuta** [comment]
In the case of the 'address' field, this is now tied to the group leader - it's just a matter of displaying the group leader's address on the group form page.

Not sure what's up with special requests not being shown - that'll require looking into.

**Comment by kitsuta** [comment]
I couldn't reproduce the problem with special requests, so it seems that they're saved properly.
