### ISSUE TITLE
[Classic] Fix dealer table and badge prices

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1284]
In the config, please set dealer tables to be $80 per table, and $20 per badge. 

(Separate issue, because the other issue referred to form text)

**Comment by nickthenewbie1** [comment]
Did this take? I'm looking at https://stage.uber.magfest.org/uber/groups/form?id=7801b9fe-c190-4b7a-ab7b-563dfa3c567b and the numbers aren't adding up. The total price should be 80 + 80 + 20 = 180, not 390.

**Comment by kitsuta** [comment]
Hm, looks like there's probably some table price in the config that's messing it up. I'll look into it.

**Comment by nickthenewbie1** [comment]
This looks ok for this group after testing at 1:20pm on 31 july.

https://stage.uber.magfest.org/uber/groups/form?id=302d69aa-831e-4e0e-ad6b-aeaca1150a12

Close?

**Comment by kitsuta** [comment]
Yup, this was fixed in config. Thanks for checking!
