### ISSUE TITLE
[Classic] Deadlines on group member kickins

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1287]
Attempting to edit this group badge:
https://stage.uber.magfest.org/uber/preregistration/register_group_member?group_id=b32b4e3d-33bc-43ee-bbc8-35cd6a00e139

Registration deadlines should be shown on the badge level buttons.

**Comment by kitsuta** [comment]
What registration deadlines?

**Comment by nickthenewbie1** [comment]
Supporter cutoff.

**Comment by kitsuta** [comment]
Oh I see, the warning text that's shown on the form page isn't shown when you're registering a group member. Got it.

**Comment by nickthenewbie1** [comment]
Unfortunately, while this fix will show the absolute final deadline, it also shows price increase deadlines. While the base badge may change, the add-ons are always a fixed price increase, so there is, at present, a confusing message indicating a price increase to a price that does not match what the button says.

Since the price for badge upgrades is constant (at least for now), the buttons to upgrade a previously purchased badge should not show the next price increase deadline, they should only show the absolute latest deadline to order them.

**Comment by EliAndrewC** [comment]
What @nickthenewbie1 is talking about is already tracked by #1290 so I think this could be re-closed and tackled as part of that ticket.

**Comment by nickthenewbie1** [comment]
Agreed. Closing, as #1290 is sufficient.
