### ISSUE TITLE
Change dealer badge form to max out at 8

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1288]
When applying as a dealer, attendees should only be able to select a maximum of 8 badges.

**Comment by nickthenewbie1** [comment]
https://stage.uber.magfest.org/uber/preregistration/dealer_registration Still allows me to select 20 badges.

**Comment by kitsuta** [comment]
Whoops, sorry - I had hardcoded this, then undid that change later when I realized there's actually a config option. Now we just need to change the config option.
