### ISSUE TITLE
Suppress notices when not applicable

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1290]
We currently display notices about price bumps on the main prereg form.  For example, the "Add a tshirt" option says "Price goes up to ___ on ___."

When someone clicks the "Group Leader" option, we switch from saying the absolute price to the relative price.  For example, instead of "$70" for the tshirt it says "+$20".  However, we still display a notice like "Price goes up to $75 on ___."  This doesn't really fit, so we should probably suppress the notice when Group Leader is clicked.

HOWEVER, after the final price bump but before the deadline, the notice changes from "Price goes up on ___" to "This option no longer available after ____."  So we DO want to display that even for group badges.

**Comment by kitsuta** [comment]
Hm... any chance we can pass the price notice custom tag the Attendee object? Then it could inspect properties like `is_new` and `badge_type == c.PSEUDO_GROUP_BADGE`.

**Comment by EliAndrewC** [comment]
I don't see why not.  If that makes implementation easier, we totally should.

**Comment by kitsuta** [comment]
Sure - though, now that I think about it, this won't help us much when the form changes dynamically.
