### ISSUE TITLE
Rams/Uber Stops Automated Email Signature Line

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1292]
The Emails generated by Rams have the following for all STOPS Emails as a Signature block:
Jack Boyd
Staffing Coordinator
MAGFest
http://magfest.org

I would like to change that to the same thing that we use in our Email signature block:
------------------------------
Thank You,
Staff Operations: MAGClassic 
MAGFest Inc.
http://www.magfest.org

**Comment by kitsuta** [comment]
I _think_ this has been fixed by the above-referenced PR, but I can't test it on my local copy because I can't get my system to send any emails from STOPS.

**Comment by bds002** [comment]
When #1301 and #1302 get fixed and we can start sending badge confirmation emails to staffers again, we will know if it's fixed.

**Comment by kitsuta** [comment]
Just checked it in Classic, looks good.

**Comment by binary1230** [comment]
I think I just removed the 'MAGClassic' part today by accident in the puppet refactor  It's trivial to add it back in, I'll re-open this though so we don't forget.

The rest of the sig is fine.

**Comment by kitsuta** [comment]
If there any way we can concatenate config inside of config? So can we say that stops_sig emails "string" + c.EVENT_NAME_AND_YEAR?

**Comment by EliAndrewC** [comment]
> If there any way we can concatenate config inside of config? So can we say that stops_sig emails "string" + c.EVENT_NAME_AND_YEAR?

Not sure how you mean.  When rendering data into a template we can already say e.g. ``{{ c.FOO }} {{ c.BAR }}`` or whatever.  Do you mean that we want a new config option which is specifically a concatenation of those two options which is shorter so it's less of a hassle given how often we're using it?

**Comment by kitsuta** [comment]
Yeah, or just instead of:
```
uber::config::stops_sig: "Thank You,\nStaff Operations: MAGFest Inc.\nhttp://www.magfest.org"
```

It's something like:
```
uber::config::stops_sig: "Thank You,\nStaff Operations: MAGFest Inc.\nhttp://www.magfest.org " + config::event_name_and_year
```

**Comment by EliAndrewC** [comment]
Oh interesting, so actually composing settings in puppet itself.  That makes sense, but I unfortunately have no idea.

**Comment by binary1230** [comment]
actually, it's I THINK possible to do this in hiera like  so:

```
uber::config::stop_sig: 'Thanks, STOPS %{uber::config::event_name} %{uber::config::year}'
```

I think. no promises.

**Comment by kitsuta** [comment]
Sadly it looks like this doesn't quite work. The output is:

```
stops_email_signature = '''Thank You,
Staff Operations: prime 
MAGFest Inc.
http://www.magfest.org'''
```
