### ISSUE TITLE
error sending email related to groups

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1294]
probably an easy fix, it doesn't like ```c.DECLINED```

:19:53,123 [ERROR] sideboard.lib._threads.DaemonTask: unexpected error#012Traceback (most recent call last):#012  File "/usr/local/uber/sideboard/lib/_threads.py", line 28, in run#012    self.func()#012  File "/usr/local/uber/plugins/uber/uber/automated_emails.py", line 58, in send_all#012    attendees, groups = session.everyone()#012  File "/usr/local/uber/plugins/uber/uber/models.py", line 619, in everyone#012    groups = self.query(Group).filter(Group.status != c.DECLINED).options(joinedload(Group.attendees)).all()#012  File "/usr/local/uber/plugins/uber/uber/config.py", line 184, in __getattr__#012    raise AttributeError('no such attribute {}'.format(name))#012AttributeError: no such attribute DECLINED

**Comment by kitsuta** [comment]
@binary1230 you got this fixed, right?

**Comment by binary1230** [comment]
woops, yea fixed by https://github.com/magfest/ubersystem/pull/1303
