### ISSUE TITLE
Email to complete registration wasn't sent

### ISSUE THREAD

**Issue by JennyTruss** [magfest/ubersystem#1302]
A few people that I have entered in manually to staff appear to not have had an email sent to them according the History tab.

https://classic.uber.magfest.org/uber/registration/history?id=d22d7b1c-c2ee-4ffb-b732-8767d0d81dd7 for example.

When I got to look at another person I entered prior, their history shows the email going out and it was also verified.

**Comment by kitsuta** [comment]
I'm pretty sure we got this fixed when we fixed the other email error, particularly since the link you provided now shows that an email has been sent. Please reopen if it happens again.
