### ISSUE TITLE
Create Homepage/Quick links for Reg Logins

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#131]
I would super love some "quick links" for reg - is it possible to have a reg homepage for reg logins and the admins of reg (like my own login)? The links we need brought to the front are:

http://50.56.242.7:4321/magfest/registration/discount (put a note next to that link saying "For Directors and Assistant Directors only!")
http://50.56.242.7:4321/magfest/registration/new_reg_station
http://50.56.242.7:4321/magfest/registration/register
http://50.56.242.7:4321/magfest/registration/new (this link should have a note saying "For At-Door check-in stations only!")
http://50.56.242.7:4321/magfest/registration/recent ("For any check-in station")
http://50.56.242.7:4321/magfest/registration/register ("Attendee Registration Form")
https://docs.google.com/document/d/1q0KSU8ymwjg-NvcCYyLvxKVbKTfatl-rwqzI9-1cCjU/edit?usp=sharing ("Reference Docs")

---------------------------------------
- Bitbucket: https://bitbucket.org/EliAndrewC/magfest/issue/133
- Originally Reported By: [Victoria Earl](http://bitbucket.org/kitsuta)
- Originally Created At: 2013-12-31T00:26:15.078

**Comment by kitsuta** [comment]
Addressed by 9ef439406564e65fe5f437365bafe7053df0c4f6
