### ISSUE TITLE
Admin form now showing payment fields

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1316]
We added a line of JS code to hide the kick-in dropdown, but this caused it to become hidden on the admin form.  We should add an if check so that it does the correct thing in both cases.

**Comment by kitsuta** [comment]
This had been fixed, but then Eli broke it again in https://github.com/magfest/magclassic/commit/189efe0630575fb1096db0c395d164951543eaa9, the jerk. :)

**Comment by EliAndrewC** [comment]
Uh oh, every time someone refers to me as a "jerk", I worry that I'll get added to the ``c.JERKS`` config option that I created to troll Nick.  I ONLY MADE THAT WEAPON TO USE AGAINST OTHERS, I NEVER EXPECTED IT TO BE TURNED AGAINST ME!!!!!
