### ISSUE TITLE
[MAGFest 2016] Add shirt sizes

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1327]
There are currently no shirt sizes in the config. Please add all the sizes from classic.

**Comment by kitsuta** [comment]
You're looking at the staging2 server, right?

**Comment by nickthenewbie1** [comment]
No this is on prod. I was trying to add my own record/account.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org
