### ISSUE TITLE
[MAGFest 2016] Wrong year and month message

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1328]
On prod https://prime.uber.magfest.org/uber/preregistration/dealer_registration

"Dealers room applications for MAGCon (September 2015) "

(ignore the MAGCon [fuck you eli])

**Comment by EliAndrewC** [comment]
> "Dealers room applications for MAGCon (September 2015) "

Fixed in config, as seen at
https://prime.uber.magfest.org/uber/preregistration/dealer_registration

> (ignore the MAGCon [fuck you eli])

You brought this on yourself, Nick!
