### ISSUE TITLE
Automate Email's Subject line...

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1334]
Hey what do we think about the automated emails for MagFest that have started going to... 
To change the Subject line to say MAGFest 2016 .... (what ever the rest of the subject is) in the subject line to further differentiate from MagClassic or older Fest.?

**Comment by binary1230** [comment]
from a naming perspective: we can say whatever we want.  I think it's a decent idea to change the subject line, yea.

one non-obvious technical detail:  The email system tracks which emails have and haven't been sent by their subject line.  so if you change the subject line, it will, at the moment, incorrectly re-send any of those emails.

**Comment by bds002** [comment]
I think we can clos

**Comment by binary1230** [comment]
keeping this one closed, but, I do want to look into this after the end of this year's Magfest because I think it's still valid.  see further discussion in https://github.com/magfest/ubersystem/issues/1494
