### ISSUE TITLE
fix config inheritance

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1335]
I was hoping to wait for Docker, but, here's how we fix puppet to not require us to keep 3 identical versions of the staging/production/vagrant config in-sync manually, which is a pain in the ass and asking for trouble.

Loose brainstorming:
- (the not-hard-but-involved part) In uber's puppet module, instead of having uber::instance be a ```define```, make it a ```class```.  This means that we can't have more than one uber instance per physical server, but, no one has ever done this, we don't plan on doing it, and I'm fine saying it can't be done.  doing this will enable us to:
- remove the create_instances() stuff in https://github.com/magfest/ubersystem-deploy/blob/master/puppet/manifests/uber_server.pp
- remove this stuff from the hiera files
```
uber_instances:
        ubersystem_vagrant:
```
- use normal automatic data binding paramaters, as outlined:
https://docs.puppetlabs.com/hiera/1/puppet.html#automatic-parameter-lookup
restructure the hiera files to take advantage of this.
- figure out how to get puppet to distinguish production vs staging vs vagrant.  I believe 'the right way' is to use environments as outlined vaguely here: https://docs.puppetlabs.com/puppet/latest/reference/environments_creating.html.  we'd have a staging, production, and vagrant environment, and they'd inherit from a common base.  
I am not sure, but this requirement may involve retooling our deploys to use a puppet master, which could end up making this a much bigger task.
As an alternative to that we may be able to generate custom facter facts which are installed on each server before puppet is run that tell it whether it's supposed to be a production, staging, or vagrant environment.  This is a big question mark, though if it can be resolved easily (which it might be) that would make things easier.

# MORE DETAILED INFO:

Because we were using a ```define``` instead of a ```class``` in puppet, we currently use a hash_merge to suck in all the config data from the various files and merge it together.  hiera is normally setup to do the more intuitive data-binding methods which manage inheritance much more like you'd expect (i.e. base config with most options, derived config with production-specific or staging-specific options). data-binding doesn't play nice with hash merging, so that's why our current setup doesn't do inheritance like you'd expect.

The reason we wanted to use a define in the first place is that classes can only have one instance of them, whereas a define you can have multiple instances.  When I first set this up I was thinking conventions might not want to have a separate physical server for staging and production servers, so I set it up this way unaware of the data-binding implications.  I think it's worth throwing out the multi-instance support (which... is completely untested anyway) and re-tool to use the data binding.

This work may go away with docker, however, it might not, because hiera (which is a separate tool from puppet) might still be a great fit for managing config data from a centralized location, especially if we get this part working.  There's a ton of homework we need to do on the 'right way' to roll out config and how this interacts with the proposed redis config DB etc etc, which is a much bigger discussion beyond the scope of this issue.

Not bad for a guy that just walked in the door from vacation, eh? :)

**Comment by binary1230** [comment]
and needless to say, after we do this everyone will need a new from-scratch redeploy.  I know how much you guys love that stuff.

**Comment by kitsuta** [comment]
Dom, did you fix this to your satisfaction?

**Comment by binary1230** [comment]
Yea, this is fine.  We should keep Eli's request about not having to add vars explicitly to the puppet class in order to get them to show up in the config, but that's a different ticket than this one so I'll close this one out.
