### ISSUE TITLE
fix puppet trying to rebuild python deps each time

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1336]
There's something I think pretty easy where we can cause the puppet deploys to not try and rebuild dependencies if requirements.txt in various locations hasn't been modified.  Pretty sure we're just not marking out the dependency correctly in the uber puppet manifest.

IN THEORY pip already should skip this, it just takes the majority of the vagrant deploy, which is SLOW on windows.  

Fixing this one thing would speed up puppet re-deploy times on windows dramatically.  It would speed up production and staging re-deploys marginally.

I wasn't going to bother to fix this originally since Docker would make this entire process obsolete, but since we're on puppet-based deploys at least through magclassic and probably through magprime, might as well have a stab at this.

**Comment by binary1230** [comment]
oh yea and the 'vcsrepo' module also takes forever to sync up on windows shared vagrant folders.  might look into why that is and if we can speed it up. 

pip and git take the vast majority of time on windows re-deploys.

**Comment by binary1230** [comment]
will be fixed by the new big puppet refactor

**Comment by kitsuta** [comment]
@binary1230 the puppet refactor seems to have worked, so is this fixed?

**Comment by binary1230** [comment]
Oh yea, cool too close out
