### ISSUE TITLE
Have travis run our unit tests

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1339]
Now that unit tests are working again in https://github.com/magfest/ubersystem/pull/1338 it would be nice if Travis ran them.  Currently Travis only runs our PEP8 checks, which is good but running unit tests as well would be better, so that we'd know before merging a PR whether someone had broken something.

**Comment by binary1230** [comment]
So hey I found that some of the sideboard tests, at least under Docker, were failing to run.  Not sure if this is normally a problem elsewhere.

I marked the test that failed to run as "nonfunctional" like this:

```
@pytest.mark.nonfunctional
 class SideboardServerTest(TestCase):
```

and then ran the unit tests like this:
```
../env/bin/py.test -m 'not nonfunctional' sideboard
```

Maybe that helps you get them up and running from travis

**Comment by EliAndrewC** [comment]
Hmm, I haven't tried running the tests lately under Vagrant, but they pass in general, and Travis actually does run the Sideboard tests on both Python 2 and 3, so I'd expect them to pass anywhere.

I'll note that the ``SideboardServerTest`` cases are all tests which actually spin up the CherryPy server and then do real tests of stuff like our JSON-RPC and WebSocket functionality.  So if we're having problems with these on Docker, it's likely because of something unexpected about how networking is set up there, or something.

**Comment by RobRuana** [comment]
Done and done.
