### ISSUE TITLE
[Classic/2016] Update vendor cutoffs

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1344]
From danielle:

"Given the number of applications we have received for Prime, and 24 have gone to autowaitlist. I would go ahead and cut it tonight [Tuesday, August 4] at 11:59/midnight. For Classic--we received a lot less, but we have less space, and I don't want it to get too crazy, but we are barely getting 1 a day, so leave that open until Friday  [August 7] at 11:59/midnight. Thanks!"

**Comment by EliAndrewC** [comment]
This is easy enough to do with settings changes in the ``production-config`` repo.  I'm turning in early tonight (for once) so I can take care of this tomorrow after work if no one gets to it before then.

This will also give us a chance to turn off preregistration in general for MAGFest.  Last time I checked, no one has figured out that you can preregister by changing the URL, which is good :)

**Comment by nickthenewbie1** [comment]
No they already have :)

We've had a couple people do so.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org
