### ISSUE TITLE
invalid? situation where attendee.paid == PAID_BY_GROUP and attendee.group is None

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1350]
this was throwing an exception on m13's old uber:
```python
'paid_noshows':  
count(paid=HAS_PAID, checked_in=None) + 
len([a for a in attendees 
if a.paid == PAID_BY_GROUP and a.group and a.group.amount_paid 
and not a.checked_in]),

# result:
AttributeError: 'NoneType' object has no attribute 'amount_paid'
```

I've fixed that particular situation with https://github.com/magfest/ubersystem/pull/1349

However, the question for this issue is:   Is this a valid situation?

Is it OK that there is a situation where ```attendee.paid == PAID_BY_GROUP``` but ```attendee.group is None```?

**Comment by kitsuta** [comment]
So, technically the answer is no, but I'm not sure this is a thing we can fully prevent - data that can be edited by dozens of people has a way of going out of bounds. Certainly it's best to make sure it doesn't cough up 500 errors when it DOES happen. I think the summary page is actually the only thing that did that in this case.

**Comment by EliAndrewC** [comment]
Well, we could add a validation check so that the attendee wouldn't get saved in that case.  That way if someone removed the attendee from a group without changing their "paid" dropdown, they'd be prompted to do so.

**Comment by kitsuta** [comment]
I'd like to just auto-set their payment to "not paid" in this case. If that sounds good, I'll tag this as a newcomer issue and we can take care of it that way.

**Comment by EliAndrewC** [comment]
> I'd like to just auto-set their payment to "not paid" in this case. If that sounds good, I'll tag this as a newcomer issue and we can take care of it that way.

I'd still be inclined to just have a validation which prevents saving an Attendee with ``PAID_BY_GROUP`` without a group.  I can't think of a valid case for that, so forcing an admin to manually select the proper payment status when they make that change seems like a better solution.

**Comment by kitsuta** [comment]
Okay, no problem - we'll do that. It's probably still a newcomer issue. ...probably.

**Comment by EliAndrewC** [comment]
Yeah, totally.  This would be a really good one for a newcomer, since "add a simple validation" is a good introduction how how we do validations.

**Comment by EliAndrewC** [comment]
On further review, this needs to be closed as WONTFIX because it actually IS valid to create attendees with paid-by-group badges who don't have a group - we deliberate do this so that people can be associated with existing groups when they preregister.

**Comment by EliAndrewC** [comment]
FWIW, the issues causing an exception for these badges have been fixed.
