### ISSUE TITLE
magclassic ribbons are incorrect - doesn't have a rockstar ribbon, and other stuff

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1352]
need to add that option in.

also, ribbon selection is............. weird. huh.   I bet that "r" is supposed to be "Rockstar", I'll check it out.

```python
r
a
no ribbon
Volunteer
Department Head
Shopkeep
Panelist
```

**Comment by binary1230** [comment]
in case it doesn't show up in other pages, this stuff is showing up in /registration/form

![image](https://cloud.githubusercontent.com/assets/5413064/9123942/fc3b760a-3c60-11e5-8059-322ca22a024d.png)

**Comment by binary1230** [comment]
ok figured this out, slightly hilarious but mostly facepalm-worthy.  we didn't specify ribbons in hiera which is now using broken default values:

```puppet
$ribbon_types = [ 
    "press_ribbon = 'Camera'",
    "band_ribbon = 'Rock Star'",
  ],
```

the template is using:

```ruby
[[ribbon]]
<% @ribbon_types.each do |ribbon_type| -%>
<%= ribbon_type[0] %> = "<%= ribbon_type[1] %>"
<% end -%>
```

so "press_ribbon = 'Camera'"[1] = 'r'
and     "band_ribbon = 'Rock Star'"[1] = 'a'

I've been sticking with removing the default values from the instance.pp puppet module, and forcing them to go into hiera, which makes a lot more sense with the new refactor which has a good hierarchy of default values in hiera and doesn't require a bunch of duplication.

We will need to make sure there are entries for these in hiera:

```
volunteer_ribbon = string(default="Volunteer")
dept_head_ribbon = string(default="Department Head")
dealer_ribbon    = string(default="Shopkeep")
panelist_ribbon  = string(default="Panelist")
```

I'll handle it.

**Comment by earl7399** [comment]
Nice catch.  What's up with just pulling the first character?  When could
that have worked?

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

On Fri, Aug 7, 2015 at 10:35 AM, Dominic Cerquetti <notifications@github.com

**Comment by binary1230** [comment]
so what happened is the original (bad) way this worked was to have the data in puppet/hiera like this:

```
ribbon_types:
- "press_ribbon = 'Camera'"
- "band_ribbon = 'Rock Star'"
```
And then just paste those lines into the .ini file

That is pretty hacky and bad though, so I changed it to be actual data in hiera like this:

```
ribbon_types:
- band: "rockstar"
- dealer: "shopkeep"
...
```

So the template with this code:
```
[[ribbon]]
<% @ribbon_types.each do |ribbon_type| -%>
<%= ribbon_type[0] %> = "<%= ribbon_type[1] %>"
<% end -%>
```
should grab [0] as "band" and [1] as "rockstar" with that array data, and produce a line in the INI like:
```
band = "rockstar"
```

The mistake is that we didn't update the default value in the puppet module to not be the original hacky string, and we didn't notice til now because we had always overridden it in puppet (we just didn't happen to override it this time for the latest deploys).  So instead of [0] being the first element in the array, it was the first *character* in the string.  Same with [1].  so it produced a line like:
```
b = "a"     # BAnd
p = "r"    #   PRess
```

It's hilarious that this by random chance happened to not throw an exception.

**Comment by earl7399** [comment]
That is hilarious, and amazing.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

On Fri, Aug 7, 2015 at 10:55 AM, Dominic Cerquetti <notifications@github.com
