### ISSUE TITLE
search functionality broken for groups

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1353]
/uber/groups/
![image](https://cloud.githubusercontent.com/assets/5413064/9124045/b8787bb0-3c61-11e5-8906-9b51ff648274.png)

I bet it's the same as https://github.com/magfest/ubersystem/issues/1293

**Comment by binary1230** [comment]
oh hey actually, it's not the same as #1293 because we never actually implemented search functionality in the first place :)

so, looks like it might be a bigger task after all.

either we should implement searching, or kill the box for now so people don't get confused why it doesn't work.

**Comment by earl7399** [comment]
Not laughing.  Truly not.  Really.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

On Fri, Aug 7, 2015 at 11:33 AM, Dominic Cerquetti <notifications@github.com

**Comment by binary1230** [comment]
hey, gotta dream

**Comment by kitsuta** [comment]
This was fixed in that PR, not sure why it wasn't auto-closed.
