### ISSUE TITLE
feature request: add ability to add ribbon to new group badges

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1354]
"As a user who is putting in a bunch of bands who need the "rockstar ribbon", it'd be great if there was a way to tell a group to add that ribbon to all the badges by default." -what chaney is likely thinking

I think a simple solution to this is just to add the "ribbon" field to the group edit page?

And probably to name that ribbon field "Ribbon to use for new badges" similar to what is needed to fix https://github.com/magfest/ubersystem/issues/1345

What do you guys think?

**Comment by kitsuta** [comment]
I thought I already did this. Oops.
