### ISSUE TITLE
DH Checklist dates...

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1366]
I know this is probably more of a Config setting that a true coding/programing hard issue.... but this is the easiest place to put it this info as it changes.

Eli - I have preliminary dates to be added to the DH Checklist.... I have a number of queries out to other departments to get their feed back on particular dates, but I think this is a good start based on how little time we have left between now and Classic

Creating Shifts - Aug 22

Volunteers Assigned to Your Department-  Aug 22

Staffers Requesting Hotel Space - Aug 26

Approve/Decline Requests to Help With Setup/Teardown - Aug. 26

Checking Placeholder Registrations - Aug 31 (Email out to office & Reg. I would like to set this date to be 1 week before staff badges go to the printers)

Tech Requirements -  Sept 2nd (Date choosen by Tech Ops via Slack)

Printed Signs - Aug. 31 (Approved from Office via Email)

Office Supplies - Sept 6

Cash / MPoint Needs - Sept 6

(After the Event) Marking and Rating Shifts - Sept. 18 (while still fresh in their minds, so we can do a Staff compare import from this and M13 for M2016)

**Comment by bds002** [comment]
Please edit: Staffers Requesting Hotel Space - Aug 29 (That give volunteers two weeks from the time the Vol. checklist goes out.

**Comment by EliAndrewC** [comment]
Fixed in the ``production-config`` repo.
