### ISSUE TITLE
Dietary Restrictions Form Change

### ISSUE THREAD

**Issue by JennyTruss** [magfest/ubersystem#1371]
We feed our volunteers three meals per day during MAGClassic, and our chefs have an easier time planning meals when they know what kind of food restrictions we all have. 

[] Vegetarian^   [] Vegan**   [] No gluten  []  No Dairy   [] No Pork [] No Eggs [] No Nuts [] No Red Meat

Please select sandwich options you like. This is to determine how much to buy:
[] Turkey [] Ham [] Cheese [] Peanut Butter [] Jelly [] Prefer Salad instead of sandwich

Let us know if you have any other allergies or restrictions, please use commas to separate each allergy and food restriction: 
We do not serve seafood or use ingredients with seafood in it.
[TEXTBOX]
 

^ Does not eat meat. We understand that there are different types of vegetarians, but due to the amounts and restrictions we have to cook, we cannot accommodate all types. If you only eat chicken, please indicate that in the text box.

** Does not eat animal by-products

**Comment by JennyTruss** [comment]
If it's still possible can you add the following to the first sentence?

Staff Suite information, meal schedule, menu, and food delivery information can be found at http://magsuite.jennytru.com.

**Comment by EliAndrewC** [comment]
I did everything except the extra text.  Theoretically it would have been easy to add it to the top of the form, but we're trying to keep links like this out of the main repo.  There's a feature I'm implementing soon (like tomorrow if all goes as planned) that makes it easy to do this in a plugin, so I'll add that link when I make that change.

FWIW, we'll also be sending out staff suite info in a separate email, and we'll be sure to include this link when we do.
