### ISSUE TITLE
Add techops link to DH checklist

### ISSUE THREAD

**Issue by jcooter** [magfest/ubersystem#1374]
Can we get a link added to the DH checklist for departments to fill out tech requirements?

Link: https://docs.google.com/forms/d/1u_VysbvSepXZ_W6IHUSGtYpo4lWxpN7XIwFaEXU97Dw/viewform?usp=send_form

**Comment by earl7399** [comment]
Pretty sure I can handle this one, if someone smarter than me okays it.

**Comment by kitsuta** [comment]
Yeah, seems like a good idea. I think there may already be some sort of tech requirements form, so look for that in the config.

**Comment by EliAndrewC** [comment]
There are two minor issues with putting this on the Dept Checklist:

1) We don't currently have a way to link to external forms.  The code that links to items on the checklist is
https://github.com/magfest/ubersystem/blob/master/uber/templates/dept_checklist/index.html#L15
It wouldn't be that hard to modify this to check whether it's a relative or absolute path and then link appropriately.

2) There's currently no way to mark off whether or not the item has actually been completed.  This is the tougher part; until we write some kind of integration with Google Docs (which is probably not that hard to do) it would just show up as incomplete for everyone.  That kind of defeats the purpose of having it on the checklist.

So what I propose instead is to just configure a separate email asking people to fill out this form which will get sent out to our department heads.  How does that sound?

**Comment by jcooter** [comment]
Our reasoning for having this on the checklist is so that departments don't forget it.  I don't think it matters that we can't integrate with google docs to "know" if a department head fills out the checklist or not.  A simple checkbox that says something to the effect of "We've filled out the techops form.  Promise".

Sure, someone could technically check the box and not fill out the google doc form, but that would not really be in their best interests, and it would also be the same thing as someone "forgetting" to click on the link in the email, except they would have a harder time trying to blame us for not being diligent.

**Comment by EliAndrewC** [comment]
Ok, so it sounds like the workflow you want is:
- there's a "Tech Needs" item on the Dept Checklist, as before
- clicking it takes you to a page within Uber with a link to the Google Doc
- there's a button on that page which says something like "Click here to indicate you've filled out that form" which causes the item on the checklist to become checked

That's pretty easy to implement, so I can whip that together tonight.  What due date would you like?

**Comment by bds002** [comment]
Their deadline:
Tech Requirements - Sept 2nd (Date choosen by Tech Ops via Slack)
Via Issue 1366 - DH checklist.

**Comment by jcooter** [comment]
Yep, that's exactly what we're looking for. If an API for the checklist ever becomes available, we can look into doing some more meaningful integration, but for now that's all we need.

**Comment by binary1230** [comment]
hey, random:  there is actually a 'google script' API, I was just playing with it. you can have it set so that on form submit on the google doc, it reaches out to uber which could check the box somehow.

that's all probably more complex than it's worth, but, it's definitely doable.

for now, I'd say do it like you were going to.

**Comment by binary1230** [comment]
i.e. on form submit, it calls a function which runs on google's server (javascript) that then talks to uber and can submit data from the google form.
