### ISSUE TITLE
Staffer Summary Information & Layout

### ISSUE THREAD

**Issue by JennyTruss** [magfest/ubersystem#1375]
As a Department Head I would like to be able to view the Staffer Summary for my department as an easy to read table that includes the following information so that I do not have to click on every staffer for quick information, not particularly in this order:

* Name
* Confirmed Badge
* Trusted status
* Multiple departments
* Total number of hours signed up for
* Number of hours signed up for in my department
* Volunteer checklist status
* Load in/out status

If my schedule permits, I'd be happy to mock up an HTML page if that will help.

**Comment by earl7399** [comment]
If I understand correctly, the page in its current form is missing
"Confirmed Badge" (and what exactly do you mean by this?) and Volunteer
checklist status - is that right?

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by JennyTruss** [comment]
Confirmed Badge is that they have logged in and filled out the information to claim their placeholder badge. But yes, those two are what I could think of as missing from a quick glance sort of view. It could also be handy to know if they requested hotel space. Just with a checkmark icon if they did.

I also think it would be better in a table layout with columns and checkmarks instead of the letter designation, which tends to get cluttered.

**Comment by earl7399** [comment]
I agree, especially with the extra info you're requesting, the layout needs to standardize so you can find the info you want at glance, and a table is the simple way to do that.  Assuming that @kitsuta doesn't see some compelling reason not to do this, I may try to tackle it tonight.

**Comment by thaeli** [comment]
+1 for table-ization

**Comment by earl7399** [comment]
Okay - I'm going to try to glom off what is happening on the Attendees page
when it has a list to show.  Wish me luck!

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086
