### ISSUE TITLE
can't uncheck attendee assigned depts

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1381]
repros on staging

create new attendee:
badge type: staff
paid: doesnt need to
*assigned depts: music*
fill in other junk required like cell phone/etc

save

edit that attendee, uncheck 'music', save

expected:
music remains unchecked

actual:
music is checked.

![image](https://cloud.githubusercontent.com/assets/5413064/9318724/74d775f8-4514-11e5-8a5b-3ab9a553be47.png)

**Comment by bds002** [comment]
Yeah that's odd, it was on staging server? not live server... I am curious as to know the name if someone can send it to me.

**Comment by binary1230** [comment]
It's both, it works for both

**Comment by bds002** [comment]
I am not able to reproduce this error on the Live server, I am able to unassign Staff from departments and click upload .. the check is gone, and then readd them to other departments without issue.

Chaney gave me the users she was having trouble with, I will look at this more tonight.
Just to clarify is it Attendee's or Staff that this issue is with?

**Comment by binary1230** [comment]
it's only when the badge is "staff" and marked as "doesnt need to pay", exactly. i was only able to repro with that combo. and was able to repro with the user chaney was looking at.

**Comment by binary1230** [comment]
basically, follow the repro steps exactly and that'll do it.

**Comment by bds002** [comment]
I am also having this issue with Attendee Volunteers - The line is: 
Attendee 	updated 	00:27 on August 24 2015 	Brent Smart 	assigned_depts=''Tech Ops / AV' -> 'LAN''
Under Assigned Departments, It would appear that we are able to Change departments, but not able to set the "assigned_dept" to an unchecked or unselected state once we have added the person to a department.

I think we need a Assigned_depts=(Unchecked) or something to that affect?

Brent

**Comment by binary1230** [comment]
Messing around with this.

Here's some more info that I think is a more specific case we can work with:

Everything works as expected, unless you un-assign someone from ALL departments on the list, then it doesn't stick.

The reason, I suspect (and am trying to verify) is that if no assigned departments are selected, then 'params' being passed to registration.py does not contain an 'assigned_depts' entry in it.

I suspect that something is interpreting the absence of 'assigned_depts' as meaning 'don't change anything' instead of what we want it to mean which is 'remove all depts'

I'm attempting to write a unit test which replicates what I think is going wrong, I'll check back in if I make some progress.

**Comment by binary1230** [comment]
uh hey wait I may have just found it.

in models.py, under Attendee::apply():

```
    def apply(self, params, *, bools=(), checkgroups=(), restricted=True, ignore_csrf=True):
        bools = self.regform_bools if restricted else bools
        checkgroups = self.regform_checkgroups if restricted else bools
```


is this supposed to be:
```
        checkgroups = self.regform_checkgroups if restricted else checkgroups
```
instead of 
```
        checkgroups = self.regform_checkgroups if restricted else bools
```

trying that and checking it.

**Comment by binary1230** [comment]
yep, that's it.

**Comment by binary1230** [comment]
this would work if restricted=True, but for some reason it's ... not here. which might be a separate issue, the admin edit form should probably be restricted=True?  I'll investigate that too.

**Comment by EliAndrewC** [comment]
``restricted=True`` means to assume that the input should be restricted to fields which we allow attendees to set on their own registrations.  So it should definitely NOT be set for admins, since they need to be able to set all fields.  Perhaps we should have a less confusing name for it.

**Comment by binary1230** [comment]
ohhh ok, I got it backwards then which explains why I can't fix my test. thanks for the insight.
