### ISSUE TITLE
Changing passwords doesn't require password confirmation

### ISSUE THREAD

**Issue by Blue-24** [magfest/ubersystem#1387]
Changing passwords in uber does not require typing your new password twice. When changing a password there should be three text boxes, one for the old password and two for the new password. When creating a password there should be two boxes for your password and password confirmation. This affects both the accounts administration page and the change-your-own-password page.
![passwordadminpage](https://cloud.githubusercontent.com/assets/8770069/9368318/8e0de6ba-4690-11e5-8f6f-802bfb287b0d.png)
![passwordpage](https://cloud.githubusercontent.com/assets/8681241/9367770/5a0b92fc-4674-11e5-98eb-533d06b27b0e.PNG)

**Comment by earl7399** [comment]
I blurred the attendee name, eh
