### ISSUE TITLE
Individual Volunteer Checklist - viewable by Stops staff or DH's

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1391]
Can we create a link to see a volunteer's checklist - so we can tell if they have completed part of it etc... I was helping someone at the MAGCOn and I couldn't tell where they where on their checklist until they logged in as themselves and showed me

From Eli: Oh right, there used to be a link on the admin form that would log you in as that volunteer, but that accidentally got deleted during the refactor.  If you wouldn't mind, make a ticket in Github for that.  The code is still there on the backend, we just need to re-add the link on the admin form (Github issue made)

**Comment by EliAndrewC** [comment]
The backend page handler is ``goto_volunteer_checklist`` in ``uber/site_sections/registration.py``.
