### ISSUE TITLE
Staffer Summary 

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1392]
This is related to #1375 / #1385 
I love the new layout to be able to see all pertinent data for staffers.
Currently is it broken down by department:
https://classic.uber.magfest.org/uber/jobs/staffers

Can we create a page, (or am I missing it somewhere) that would show all this data for all staffers.
Once Sorting is figured out, that will allow us to quickly sort and Identify any staffers that haven't completed the info.

**Comment by earl7399** [comment]
Sorting is about figured, thank to Victoria.  Once that's happy, I'll look
at this if someone smarter hasn't already - and if my home computer is back
up.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086
