### ISSUE TITLE
[Classic] Change volunteer hotel requirement hours

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1394]
Classic uber currently lists 30 hours as the requirement for getting hotel space. Please change any informational pages, as well as internal logic, to instead be 24 hours.

**Comment by kitsuta** [comment]
@nickthenewbie1 Is this just for Classic?

**Comment by nickthenewbie1** [comment]
Yup!

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org
