### ISSUE TITLE
Modify personalized badges report

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1397]
Right now it spits out a csv report with all staff and supporter names and badge numbers. Have it instead spit out a .zip file containing

-csv with attendee badge numbers and barcodes
-csv with guest badge numbers and barcodes
-csv with one-day badge numbers and barcodes
-csv with staff badge numbers, names,  and barcodes
-csv with supporter names

**Comment by binary1230** [comment]
going to work on this stuff, working with nick end result may end up a little different.
