### ISSUE TITLE
[Classic]Incongruous shirt counts

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1399]
Can someone figure out what the "shirt sales by week" in https://classic.uber.magfest.org/uber/summary/ corresponds to? If it's truly "sales", it's not congruent with the current number of t-shirt and supporter level registrations listed at https://classic.uber.magfest.org/uber/summary/affiliates

**Comment by kitsuta** [comment]
It is not truly sales - it is merely a count of how many people have `a.shirt != c.NO_SHIRT`. So this includes staffers, etc.

The Affiliates page counts only those who have `amount_extra > 0` so it is a much more accurate count of sales.

**Comment by binary1230** [comment]
I had a thought a while ago that we might want to eventually make some kind of 'manufacturing report' that is just info ready to be consumed for manufacturing tasks like 'how many tshirts should order', and also contain links for 'download personalized badges CSV' etc.

A lot of this info is already available, but scattered around.  I might take a quick shot at this.

**Comment by EliAndrewC** [comment]
We already improved the shirt count pages to where I *think* this is resolved.
