### ISSUE TITLE
Hotel reminder email should link to account setup page

### ISSUE THREAD

**Issue by thaeli** [magfest/ubersystem#1400]
The "remember to sign up for hotel space" email doesn't have the "If you have trouble logging in, you can verify/update your personal information at" paragraph in it. This is confusing if you're an irresponsible staffer like me who doesn't create her account from the previous emails and only pays attention at the hotel reminder email. (Also, perhaps we should add some additional text on the staffer login page about getting your account setup/creation link resent?)

**Comment by EliAndrewC** [comment]
+1 on this suggestion.  We should probably have a snippet with this verbiage which we ``{% include %}`` in all of the relevant emails.

**Comment by earl7399** [comment]
+1 / +1

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by bds002** [comment]
I was going to add a paragraph with @thaeli thought about Login in and personal info....
I think Eli's {%include%} might be good to add as well, however I don't know the coding to write up for that.
