### ISSUE TITLE
Food Restrictions Email for Guests

### ISSUE THREAD

**Issue by JennyTruss** [magfest/ubersystem#1402]
I'm not sure who or what generates the email, but there has been an email in the past that goes out to guests to have them fill out food restrictions. As far as I know, this has not gone out yet for MAGClassic and it needs to go out so we can get that data.

**Comment by kitsuta** [comment]
Hm, looks like this was removed when we transitioned off the magprime_emails repo. We'll have to add it back in.

**Comment by EliAndrewC** [comment]
D'oh, sorry about that, I thought I had moved that over, but I guess not.  Yeah we can definitely re-add that soon.
