### ISSUE TITLE
Update to: Reminder to sign up for MAGClassic hotel room space

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1406]
Can we please setup a new return Email address for this email to:
MAGFest Staff Rooms <staffrooms@magfest.org>

Thanks, Brent

**Comment by EliAndrewC** [comment]
@binary1230: Can you log into our AWS account and make sure that staffrooms@magfest.org has permission to send emails?  I don't think we've sent from this address before, so that will need to be added.

**Comment by EliAndrewC** [comment]
I made this fix in the code at https://github.com/magfest/hotel/commit/5cdda1c42fd8c377cd1839751d2084792003d54a

**Comment by binary1230** [comment]
TLDR: yes, once I deploy.

long story:
switching the AWS key from the older eli key to the newer dom key, which allows *.magfest.org and explicitly staffrooms@magfest.org.   Also the Dom key does some stuff like Domainkeys and DKIM which will increase chances that emails don't get eaten up by spam filters.

this PR https://github.com/magfest/ubersystem/pull/1407 contains a new test email page which I was using locally to verify the new key works OK.  going to switch the key and run that on prod and verify things are fine.

**Comment by binary1230** [comment]
ok this is all deployed, and verified that emails work from any magfest.org address.  if you want to do the same visit /uber/emails/test_email

**Comment by binary1230** [comment]
associated discussion https://github.com/magfest/ubersystem/pull/1407

**Comment by kitsuta** [comment]
This is fixed, isn't it? Emails are currently going out from staffrooms@?

**Comment by bds002** [comment]
I need an Update to the verbage in that Email...
 are ok if you don’t reply to this email by 11:59pm LMT on Saturday, Sep 5.
Should be EST ....

**Comment by EliAndrewC** [comment]
Oh right, I promised Brent I would look into that.  I'll be sure to do that this weekend so we can start sending these out.

**Comment by EliAndrewC** [comment]
I just deployed and verified a fix for this.
