### ISSUE TITLE
[2016] Supporter tiers

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1409]
+5 Ribbon
+10 Button 
+20 T-Shirt
+40 MAGFest 2016 guitar keychain (art preview (link: http://magfest.org/sites/default/files/keychainsample.png))
+80 Supporter Package
+100 Custom Battery pack
+160 Season Pass
+250 Canvas MAGFest 2016  artwork print (art preview (link:http://magfest.org/sites/default/files/canvassample.png))
+500 MAGFest 2016 decorative air guitar

**Comment by kitsuta** [comment]
We can't put links in the kick-in levels, so we'll have to figure out something else for the art previews.

**Comment by thaeli** [comment]
I think I can add this. Not necessarily by Monday.

**Comment by kitsuta** [comment]
I can probably hack in a fix through the plugin ABI, so don't worry about it.
