### ISSUE TITLE
[2016] Additional donation field

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1411]
Add a field for people to be able to contribute additional donations.

descriptive text "MAGFest inc is a 501(c)(3) charitable organization, and additional donations are 100% tax deductible. Your employer may also have a charitable donation matching program. E-mail contact@magfest.org for details."

**Comment by kitsuta** [comment]
This is actually a significant change, as it requires us to separate
kick-in tiers and amount extra. Currently if anyone has an amount extra
that doesn't match a kick in level, we get 500 errors.

**Comment by nickthenewbie1** [comment]
How was it handled for magstock's food purchasing option?

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by EliAndrewC** [comment]
This would only be a significant change if we made the extra donation part of the ``amount_extra``, i.e. if we modified ``amount_extra`` to handle arbitrary values.  If we instead had a separate database column which was referenced in a ``@cost_property`` (as we did with MAGStock food purchasing) it would be easier.  Of course, that's probably a worse UI experience.

A still-a-lot-of-work-but-not-too-bad option would be to let them enter an arbitrary amount like and then we'd set the ``amount_extra`` to the highest option below that amount and then leave the rest as ``non_kickin_donation``.  Like if someone entered $123 so we mark them as getting the ``100`` option and having ``23`` in the second field.

Not a trivial amount of work, so I'm honestly not sure it's worth the effort for the small amount of extra money we might get from it.

**Comment by nickthenewbie1** [comment]
I think we'd like to have the swag money and the "additional" donation
money be completely separate, as to make it abundantly clear that one of
those fields is 100% tax deductible, and one isn't.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by thaeli** [comment]
Nitpick: "may be deductible" not "is deductible". Important for us to not
make anything that could be construed as giving tax advice :)

I agree with adding "contribution" as a separate column if we do this.
What's "swag money"? Is that kickin amount or is it a third category?

**Comment by nickthenewbie1** [comment]
Sorry, swag money is the same as kickin amount.

**Comment by kitsuta** [comment]
Alright cool, that's easier to do for sure.

I think the plan UI-wise is to always have the extra box not count towards kick-in levels, so adding it as a `@cost_property` isn't a bad thing in that case.

**Comment by EliAndrewC** [comment]
If it's not tied to the ``amount_extra`` kick-in dropdown, then I agree this is much easier and pretty doable.

Stepping back a minute though, do we really want to have two different ways to kick-in, one of which gives you cool swag and one of which doesn't?  I'll generally defer to Nick on these things, since his promotion instincts are usually 10x better than mine, but this seems like a questionable goal to me.

**Comment by nickthenewbie1** [comment]
95% of people will not use the additional donation field. The primary
purpose this to catch the attention of our most philanthropic attendees, as
well as those who work for companies that match charitable contributions.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org
