### ISSUE TITLE
[2016]Update t-shirt sizes

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1412]
Available options:

S Unisex
M Unisex
L Unisex
XL Unisex
2XL Unisex
3XL Unisex
4XL Unisex
5XL Unisex
S Unisex slim fit
M Unisex slim fit
L Unisex slim fit
XL Unisex slim fit
2XL Unisex slim fit
S Women's 
M Women's 
L Women's 
XL Women's 
2XL Women's 
S Women's slim fit
M Women's slim fit
L Women's slim fit
XL Women's slim fit
2XL Women's slim fit

**Comment by binary1230** [comment]
taking a shot at this.

**Comment by nickthenewbie1** [comment]
Please also add an italics notice next to the t-shirt size selection "Slim fit sizes only available during online pre-order."
