### ISSUE TITLE
reset_uber_db doesn't work anymore

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1416]
recent foreign key constraints seem to have broken our 'sep reset_uber_db' command, when running it I get:

```
sqlalchemy.exc.InternalError: (psycopg2.InternalError) cannot drop table attendee because other objects depend on it
DETAIL:  constraint room_assignment_attendee_id_fkey on table room_assignment depends on table attendee
constraint hotel_requests_attendee_id_fkey on table hotel_requests depends on table attendee
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
 [SQL: '\nDROP TABLE attendee']
```

apparently the fix is something like this:
http://www.mbeckler.org/blog/?p=218

I'll give that a shot real quick.

I will admin this is latest code WITHOUT the new hotel plugin, could be a side effect of that.  But it should probably still work with any combo of plugins, so I'll try the other solution

**Comment by EliAndrewC** [comment]
Copied from my comment on the PR:

> The existing code is handles dependencies, but it DOESN'T handle foreign key dependencies we don't know about because they're not in our codebase. For example, if you pulled the latest ubersystem which no longer has the hotel tables and tried to do a sep reset_uber_db it would fail because it's only trying to drop the tables it knows about but there are other tables which foreign key into the ones you're dropping.

> Dropping tables which we don't have any knowledge of in the codebase, that seems bad and not something we want any code to ever automatically do. My opinion is that in the rare cases where we do get into this kind of situation, it's better to require a manual intervention (especially when dropping tables is concerned).

**Comment by binary1230** [comment]
ok, i'm fine with that answer, closing this
