### ISSUE TITLE
[2016] Change badge tier buttons to a slider control

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1422]
Since we have many many many tiers, and have removed the badge tier dropdown, replace the buttons with a slider control. Alternatively, just orient all the buttons vertically.

PEOPLE LOVE SLIDERS, THOUGH!

**Comment by EliAndrewC** [comment]
That's a pretty tall order, and I'm definitely not a good enough UI designer to make this happen.  I believe @thaeli may have offered to take a shot at this at some point, but barring that I don't see this happening in time for MAGFest 2016 prereg launch.

**Comment by thaeli** [comment]
Do you mean in the admin interface? I chose the multi buttons in the customer interface for reasons..

**Comment by thaeli** [comment]
Or is this just the ticket for the previously discussed kickin level slider? We are starting to seriously need a standardized glossary for this stuff..



inb4 next ticket is "change stuff on the thing"

**Comment by nickthenewbie1** [comment]
Sorry, yes, this is what we were previously talking about.

Also don't forget to fix that thing with the issue on that page.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by EliAndrewC** [comment]
Closing as resolved.
