### ISSUE TITLE
[2016]Separate base badge price from kickin levels/badge tiers

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1425]
For the sake of common nomenclature, if I ever say kickin level, badge tier, or supporter tier, those area all referring to the same thing :)

After talking with @kitsuta, we think it would be a good idea to have an option to have the badge tiers be either displayed in-line together, as is the current implementation, or to have the base badge price separated out for the rest of the tiers, and the tiers listed in their own control (big buttons, radios, slider, etc)

For events like classic, magstock, or any other event that has a small number (<=3) of badge tiers, the big buttons make sense. For events that have finer granularity of kickin levels (e.g. supermag) breaking the badge price out from the kickin levels has a few benefits:

- Since the base price for the badge is variable over time, but the tier prices are static in their additional cost, separating the badge price avoids having the price increase notice appear on every single tier
- Separating the badge price makes the tier costs look like the nice round numbers they're meant to be, rather than whatever odd sum comes out of the base badge price plus their tier upgrade amount
- It makes the badge tiers seem not so expensive when you separate out by themselves instead of including the base badge price in it as well.

**Comment by kitsuta** [comment]
Just to note, we already have this general type of functionality - we use it for the confirm page and other pages where an attendee already has a badge paid for. It's just a matter of switching it on for the pre-reg form as well.

If we do want to keep the badge level buttons (to promote certain kick-in levels), we'd want to think carefully about how they communicate the price. Right now you can have a situation where the big obvious button tells you that your badge is $70 but your kick-in level actually makes it $90. Not ideal.

**Comment by nickthenewbie1** [comment]
We could make the supporter and season supporter levels more prominent on
whatever control we decide using.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by kitsuta** [comment]
Yeah, that'd be a good idea!
