### ISSUE TITLE
[2016]add option to view all groups

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1427]
Request from Danielle. Right now you can only view up to 100 groups per page. Please add an option to view all groups on one page.

**Comment by bds002** [comment]
This looks like is has been complete for MAGFest2016.
https://prime.uber.magfest.org/uber/groups/ 
has an ALL selection, I don't have the ability to close this issue.

**Comment by binary1230** [comment]
verified, fixed.
