### ISSUE TITLE
[classic] supporters can't edit their printed badge name / supporter display issues

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1430]
This is only a big deal because the deadline is tomorrow, and we're about to send an email out for people to edit their customized badges.

2 issues on this page:

http://i.imgur.com/c7lXVEd.png

1) Printed Badge Name is not showing up, this is because it's parent div CSS is set to `display:none`. This is the important thing

2) The `badge level` is not showing up.  Other pages have this for staff/etc, but supporters this is blank:

http://imgur.com/gG7UdX0

not as important, but probably related.

---

If I had I to guess, it's probably related to removing supporters as a distinct type.

**Comment by binary1230** [comment]
is this going to be a further issue for magprime or any events going forward now that supporter is no longer a distinct badge type? i.e. should we close out the ticket?

**Comment by kitsuta** [comment]
We should make sure it actually works for the new type of Supporter first.

**Comment by RobRuana** [comment]
Verified this is no longer an issue:

<img width="869" alt="screen shot 2017-09-21 at 11 10 26 pm" src="https://user-images.githubusercontent.com/2592431/30727892-1b04c750-9f22-11e7-92e0-c394f00bacfb.png">
