### ISSUE TITLE
[2016]Review registration emails to include mention of extra donation

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1435]
We don't need the full proper donation form letter yet, but we should at least make passing mention about their additional donation.

**Comment by nickthenewbie1** [comment]
lol the supporter swag available for pickup at the merch booth includes the additional donation.

**Comment by kitsuta** [comment]
Hm, that means the email is just pulling all cost properties, which would often not be merch stuff. Let me look into that.
