### ISSUE TITLE
Extra cruft on Attendee view page

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1447]
![image](https://cloud.githubusercontent.com/assets/8770069/9616587/fdea6b02-50cc-11e5-9612-d2c057b5b34c.png)

**Comment by kitsuta** [comment]
So what you're really saying is, the kickin button group isn't displayed?

**Comment by earl7399** [comment]
Correct.  I didn't realize it was supposed to be!

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by kitsuta** [comment]
Oh no, I misunderstood - I didn't recognize this as the admin page (which I really should have, haha). This is just extra cruft that should be removed.
