### ISSUE TITLE
Unable to cancel A+ box in Safari

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#145]
Clicking on A+ brings up a box to fill in notes. 

In Safari, clicking cancel blanks out the page but leaves the popup. Hitting cancel does nothing. The only way to get out is to quit the browser.

---
- Bitbucket: https://bitbucket.org/EliAndrewC/magfest/issue/149
- Originally Reported By: [ ](http://bitbucket.org/carlavoorhees)
- Originally Created At: 2014-01-04T02:08:49.979

**Comment by bds002** [comment]
I remember this issue, I thought it was resolved, maybe just not closed out? @EliAndrewC

**Comment by kitsuta** [comment]
We'll need someone with Safari to test it.

**Comment by EliAndrewC** [comment]
@DataFighter since you use a Mac then can you see if you can reproduce this?

**Comment by DataFighter** [comment]
A+ worked on safari for me?

**Comment by kitsuta** [comment]
Good enough for me!
