### ISSUE TITLE
Mag 2016 Needs 30 hours for Staff Hotel

### ISSUE THREAD

**Issue by StephPrader** [magfest/ubersystem#1450]
Yo!
https://prime.uber.magfest.org/uber/static_views/stafferCo Says 24 hours but it should go back to 30 now for the big Mag, right?
Steph

**Comment by StephPrader** [comment]
Link isn't working, it's the "What do I get for volunteering?"

**Comment by bds002** [comment]
The link is:
https://prime.uber.magfest.org/uber/static_views/stafferComps.html

From: https://prime.uber.magfest.org/uber/preregistration/form

But yes the last line needs to update to show 30 hours, not 24.

**Comment by StephPrader** [comment]
I love that it just got corrected for Classic but now we need to change it
back for Prime. ;p Oops!
Steph

On Tue, Sep 1, 2015 at 9:32 PM, Brent Smart <notifications@github.com>
wrote:

> The link is:
> https://prime.uber.magfest.org/uber/static_views/stafferComps.html
>
> From: https://prime.uber.magfest.org/uber/preregistration/form
>
> But yes the last line needs to update to show 30 hours, not 24.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magfest/ubersystem/issues/1450#issuecomment-136910486>
> .
>



-- 
__
Stephanie Prader
Division Director, Programming
MAGFest
www.magfest.org
703-964-6707
