### ISSUE TITLE
[Classic] Custome Badge #'s and Forms

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1452]
If we have sent off the customer badge names and numbers, we need to lock out the ability for people to add "Staff" badges to MAGCLassic, as well as the ability to change Staff badge numbers.

registration/change_badge?

We  should also lock out the "Name on Badge" for on the Classic Registration page.

@nickthenewbie1 Did that information get sent out already?

**Comment by nickthenewbie1** [comment]
Yes, it's all out. Please lock down badge numbers and names immediately.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by binary1230** [comment]
alright i got dis.
