### ISSUE TITLE
[Classic] Admin accounts not behaving correctly.

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1454]
Hey - So Mike Ridgeway - has an admin account:
https://classic.uber.magfest.org/uber/accounts/

We try to set  Registration and Staffing    Inventory and Scheduling as options for him, and click save and it doesn't take. 

I tried to delete the admin account - which usually works and it wouldn't let me do that either
He's not a placeholder badge - one of the other issues I have seen with admin accounts

If you refresh the screen after you click the save button, the checks are gone.

**Comment by binary1230** [comment]
so I think @EliAndrewC and @Lusarien fixed this, may have fixed this  in https://github.com/magfest/ubersystem/pull/1501

**Comment by EliAndrewC** [comment]
Correct, that PR does indeed fix this issue.
