### ISSUE TITLE
Hotel rooms link 

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1476]
With the new Puppetization of the Staff rooms work flow, we need to add the links back into the Site map:

https://magstock.uber.magfest.org/uber/accounts/sitemap

I thought I had already submitted this as a request... but maybe not.

**Comment by binary1230** [comment]
closing as a duplicate of https://github.com/magfest/ubersystem/issues/1428

@bds002 if that's not a duplicate, please re-open
