### ISSUE TITLE
BEFORE SENDING OUT VOLUNTEER SHIFT EMAILS

### ISSUE THREAD

**Issue by StephPrader** [magfest/ubersystem#1477]
YO, so Uber did the Time Zone thing again where it moved all of the panel times off by 4 hours when I downloaded the schedule to upload to Guidebook. I recall it filtering out to the volunteer shift sheets when they were emailed to the staffers. I suggest y'all check it before those emails go out.
Steph

**Comment by StephPrader** [comment]
Wait, no, it's not from Uber but the schedule in Guidebook is all screwed up. Sorry. False Alarm! I should go to bed...but I wanna figure this out. >:(
Steph

**Comment by bds002** [comment]
Hmm we don't have that Email configured for Classic.... :(

**Comment by StephPrader** [comment]
It was a false alarm. Guidebook fucked it up, not Uber. Either way I'm
irritated.

Oh, I thought we always had those emails out to staffers, so they knew when
their shifts were. Not that I'm used to gettng one but year.
Steph

On Tue, Sep 8, 2015 at 1:24 AM, Brent Smart <notifications@github.com>
wrote:

> Hmm we don't have that Email configured for Classic.... :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magfest/ubersystem/issues/1477#issuecomment-138437396>
> .
>



-- 
__
Stephanie Prader
Division Director, Programming
MAGFest
www.magfest.org
703-964-6707

**Comment by binary1230** [comment]
hm so guidebook is exporting things in UTC likely instead of EDT.  it should be a simple change

**Comment by StephPrader** [comment]
I said NO. Uber is fine, it's Guidebook that fucked it up. I jumped the gun
and immediately blamed Uber and I'M SORRY I feel bad. It's what happened
last time so I figured it was Uber before I opened the spreadsheet file. It
looked fine so it MUST be Guidebook. I closed the ticket even. GEEEEZ
Steph

On Tue, Sep 8, 2015 at 6:48 AM, Dominic Cerquetti <notifications@github.com>
wrote:

> hm so guidebook is exporting things in UTC likely instead of EDT. it
> should be a simple change
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magfest/ubersystem/issues/1477#issuecomment-138514792>
> .
>



-- 
__
Stephanie Prader
Division Director, Programming
MAGFest
www.magfest.org
703-964-6707

**Comment by binary1230** [comment]
so Steph, there's an important note here:  which is, if uber exports something that isn't read correctly by guidebook on the first try, then it's uber's fault and we should fix our code to match what they are expecting.

could you describe the process you are going through to import into guidebook?

As far as I knew this was:
1) export schedule_tsv from uber
2) import that into guidebook without opening or editing it

If you're doing something differently, could you tell us what that is?

**Comment by binary1230** [comment]
like, it's really important that we export in exactly the correct format guidebook wants so that a human doesn't have to ever edit the file.

**Comment by StephPrader** [comment]
Uber gets it to me in a perfectly fine way with the correct formatting. The
formatting isn't what I'm changing. It's already perfect for my uses.
Please concentrate on stuff that actually needs your attention. This is a
non-issue.

The ticket is closed and doesn't need further discussion until we're in the
same place at the same time with my computer sitting in front of us so I
can show you how Guidebook works.
Steph

On Tue, Sep 8, 2015 at 11:23 AM, Dominic Cerquetti <notifications@github.com
> wrote:

> like, it's really important that we export in exactly the correct format
> guidebook wants so that a human doesn't have to ever edit the file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magfest/ubersystem/issues/1477#issuecomment-138599237>
> .
>



-- 
__
Stephanie Prader
Division Director, Programming
MAGFest
www.magfest.org
703-964-6707

**Comment by kitsuta** [comment]
This is an export called tsv, not guidebook_tsv. My vote is that it ought to stay the way it is - it exports the times in the event's timezone, which is what you'd expect/hope from your average schedule export.

**Comment by binary1230** [comment]
i'm going to close out this ticket, but, will revisit checking on the guidebook export because I want to make sure it's putting out the right columns/format the guidebook expects.  I went through a lot of trouble to make sure originally that this export put out the exact info in the exact way that guidebook wanted it, so I want to make sure we are currently doing it "the right way"

**Comment by StephPrader** [comment]
Since it already does export exactly as guidebook expects, this ticket can
be closed PERMANENTLY.
Steph

On Thu, Oct 1, 2015 at 7:18 PM, Dominic Cerquetti <notifications@github.com>
wrote:

> i'm going to close out this ticket, but, will revisit checking on the
> guidebook export because I want to make sure it's putting out the right
> columns/format the guidebook expects. I went through a lot of trouble to
> make sure originally that this export put out the exact info in the exact
> way that guidebook wanted it, so I want to make sure we are currently doing
> it "the right way"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magfest/ubersystem/issues/1477#issuecomment-144875055>
> .
>



-- 
__
Stephanie Prader
Division Director, Programming
MAGFest
www.magfest.org
703-964-6707

**Comment by binary1230** [comment]
I don't believe you Steph : )  but yea it's closed.
