### ISSUE TITLE
[Classic]Send FAQ Email

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1486]
If you are receiving this, you are registered for <a href="http://classic.MAGFest.org">MAGClassic</a>, occurring September 11-13, 2015. This FAQ should answer most your questions about the event. You may reach us at contact@magfest.org for any questions not covered here.

<b> Will passes be sold at the door?</b>
Yes. Full three-day passes will be available for $60, and one day passes will be available for $35 for Friday, $35 for Saturday, and $25 for Sunday. Children 5 & under are free, and children 12 & under receive a discount. We do not anticipate selling out, so you should have no problem purchasing a pass at-event.

<b>Where do I go when I arrive? How do I pick up my pass?</b>
The first step is to go to the registration desk, located in Upper Foyer near the parking garage entrance to pick up your pass. The registration desk is open from 10am - midnight Friday and Saturday, and 10am-1pm Sunday. If you pre-registered, simply show photo id such as a driver's license, military id, or student id to the registration staffers. If you do not have photo id, print out the confirmation e-mail you received when you pre-registered.

<b>Which registration line do I use?</b>
- Attendees who purchased a standard badge should use the "Pre-Registered Badge Pickup" line.
- Attendees who did a group registration, or Marketplace vendors, should use the "Groups & Dealers" line.
- Staff, Supporters, Guests, and Panelists should use the line that lists those categories.
- If you are not already registered for a pass, use the "On-Site Registration" line.

<b>Where can I pick up swag that I pre-ordered, such as a t-shirt or supporter bundle?</b>
After you've picked up your pass, you can pick up your swag at the MAGFest merch booth. The merch booth is located at the base of the escalators.

<b>Where can I view a schedule of events?</b>
There are multiple ways to view our schedule.

<i>Using a desktop web browser</i>: Our <a href="https://classic.uber.magfest.org/uber/schedule/" target="_blank">online schedule</a> is best viewed on desktop computers.

<i>Using the Guidebook app on a mobile device</i>: Go to the  <a href="https://guidebook.com/guide/44016/" target="_blank">Guidebook website</a> to view the guidebook in your web browser. Make sure to check for guidebook updates periodically through the weekend, as we may make schedule changes.

<b>Can I check if I'm pre-registered</b>
Use <a href="https://classic.uber.magfest.org/uber/preregistration/check_if_preregistered">this page</a> to check your registration status.

<b>Do you provide refunds or ticket transfers?</b>
We do not provide refunds, but we do allow you to sell or transfer your ticket to anyone you wish. E-mail regsupport@magfest.org from the original e-mail address you registered with (or provide the original e-mail) along with your full name, and we will send you a link to transfer your ticket as soon as we can.

<b>Only questions about ticket transfers, ticket confirmations, or general registration questions should be e-mailed to the registration desk e-mail address. We are unable to respond to any other inquiries.</b>

**Comment by binary1230** [comment]
can we make "all other emails will be ignored" sound a little less harsh?

**Comment by nickthenewbie1** [comment]
Done
