### ISSUE TITLE
client certs prompt users when they browse to the page

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1488]
Our new client cert thing is prompting the user to select a cert

Seeing this on mobile and got reports on some safari browsers

I'll look into it ASAP

**Comment by EliAndrewC** [comment]
Interesting, I've never had this happen in Firefox or Chrome.  I wonder if there's some HTTP header that would tell Safari to not bother prompting.

**Comment by binary1230** [comment]
android chromium is happening for me now consistently.

it's gotta be some nginx header yea.

https://code.google.com/p/chromium/issues/detail?id=268055
```I can fix the issue if you have access to IIS. Basically you need to go to SSL Settings and make sure Require SSL is unchecked and that "Ignore" is selected for Client Certificates```

there's gotta be an nginx equivlent of that.

**Comment by binary1230** [comment]
looks like this (someone else's screenshot)
![image](https://cloud.githubusercontent.com/assets/5413064/9797087/5bf33b24-57c7-11e5-9177-d1b1481995f2.png)

**Comment by binary1230** [comment]
this command is useful running locally to debug the SSL output
```
openssl s_client -connect stage.uber.magfest.org:443 -debug -state
```

the interesting thing is yielded here:

```
Acceptable client certificate CA names
/C=US/ST=MD/L=Baltimore/O=MAGFestINC/CN=onsite.uber.magfest.org
```

that's the CA, so OpenSSL is getting that information provided to it by nginx

**Comment by binary1230** [comment]
nginx config (names have been changed to protect the innocent)
https://gist.github.com/binary1230/8e5ba715d4100161f708

**Comment by binary1230** [comment]
THING TO CHECK
instead of what we're using do instead
ssl_trusted_certificate

**Comment by binary1230** [comment]
so I can't figure this out, tried every nginx option I could find and also read the source code to nginx and openssl, zilcho.  it works fine as-is on most browsers, just not all of them.

so I'm going to solve this by requiring another hostname based vhost , and maybe we can solve this better later if we can figure out how to do it in a better way. my SOUL

**Comment by binary1230** [comment]
FYI, I still intend on fixing this up before we go into Magprime by making nginx listen on a different port just for /jsonrpc

slightly lame, but I think the best solution.

**Comment by binary1230** [comment]
FYI, fixed this by making nginx listen on two ports: one for normal web traffic, the other port is just for jsonrpc requests and requires the client cert.

Kind of lame that we couldn't get it working on one port (I spent way too much time trying and reading the guts of the C code of openssl and nginx), but currently solution does work pretty nicely now.
