### ISSUE TITLE
[MAGFest 2016] Rename "Security" to "Security-Badge-Checking" in pre-reg form

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1495]
Rene and Carol requested this change due to volunteer expectations of working "Security."

**Comment by bds002** [comment]
I agree we need a better name for this... Does anyone have any other ideas?

It would be a global change - department name change not just on the pre-reg form.
I am not aware of anything else that the "general security" staff do outside of badge Checking.

Dorsai have their own department.
Concert Security has their own department.
Public Safety (our internal First Aid providers) have their own department.

If Rene and team cull someone out of the general security, they tend to go to the Dorsai Department as Dorsai Folk .... (Josh is an example of this from MAGClassic)

**Comment by EliAndrewC** [comment]
Whoops, missed this one for Mag2016.

**Comment by bds002** [comment]
We never really came up with a good name.
