### ISSUE TITLE
disable wristband notification for at-door checkin

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1499]
Uber currently says "give red wristband" or similar on checkin, we should disable that prompt for magclassic so that we're not confusing the checkin staff

**Comment by binary1230** [comment]
now that we're a bit past magclassic, we should probably make this a config option about whether we use wristbands.

or I vaguely recall we already had something like this that could be disable via config.  if so, close this bug and open a JIRA ticket for the next magclassic/stock

**Comment by EliAndrewC** [comment]
This was fixed.
