### ISSUE TITLE
Checking in an attendee to a leaderless group deletes a bade

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1502]
When someone claims an unregistered group badge at the door, here's the procedure:
- the attendee types out their info at a kiosk, creating a `c.NEW_STATUS` badge marked as `c.PAID_BY_GROUP` but not associated with any group yet
- the attendee goes to the preregistered line with their group leader
- an admin regdesk worker clicks "Check In" and selects the group they belong to and submits the form
- the backend code finds an unclaimed badge of the correct type (returning a failure message if no unclaimed badges of the correct type exist for that group) and deletes it and adds the new attendee to that group

This all works fine EXCEPT in the situation where no group leader exists for the group.  In that case the system does all of the above except that it deletes TWO badges from the group instead of one.  From a brief tracing through of the code, it's not obvious why.

There was only one group with unassigned badges without a leader for MagClassic, so we assigned the correct person as the leader of that group.  We therefore don't expect this to be a problem for classic, so we're filing the issue and will fix it later.

In general we shouldn't have groups with only unassigned badges without a leader (since regdesk won't know who is authorized to allow those badges to be claimed) but this will probably happen in practice at MAGFest, so we should definitely fix this before then.

**Comment by kitsuta** [comment]
Cannot reproduce this bug -- this seems to have been fixed.
