### ISSUE TITLE
[MAGFest 2016] Rename "LAN Lounge" to "LAN Events" in pre-reg form

### ISSUE THREAD

**Issue by DeastDX** [magfest/ubersystem#1512]
We've undergone quite a few name changes, this is the current (and future) name for this department.

**Comment by earl7399** [comment]
Funny thing is, you say it like it's true.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by EliAndrewC** [comment]
The Once And Future ~~King~~ Department Name.

**Comment by bds002** [comment]
Is there a way to Merge Issue ticket #'s #1513 is another department name change and I have a third one pending as well.

**Comment by kitsuta** [comment]
Just file one issue per name change. We can close multiple issues at once.

**Comment by earl7399** [comment]
Fixing via https://github.com/magfest/production-config/compare/rename-lan-lounge-to-lan-events?expand=1

**Comment by kitsuta** [comment]
Please link to the PR _after_ you create it. xP

**Comment by bds002** [comment]
This has been completed and can be closed.
