### ISSUE TITLE
[MAGFest 2016] Rename "Food Prep" to "Staff Suite" in pre-reg form and department lists

### ISSUE THREAD

**Issue by JennyTruss** [magfest/ubersystem#1513]
Please rename all instances of "Food Prep" to "Staff Suite"

**Comment by EliAndrewC** [comment]
This is definitely easy to do.

With that being said, I think it might be a good idea to keep it labeled as "Food Prep" on the list of checkboxes where new volunteers say which departments they're interested in.  Although anyone who's familiar with conventions knows that "Staff Suite" means, MAGFest gets a lot of new volunteers who haven't been to a lot of other conventions or volunteered anywhere else.

It would definitely be easy to keep it "Food Prep" in that place and change it to "Staff Suite" everywhere else.  Or we could change it in both places if you think that would be better for whatever reason.  Your department - your decision! :)

**Comment by JennyTruss** [comment]
We started using Staff Suite last year and also at classic, so I don't really think there would be much confusion. It might even be easier for some.

**Comment by bds002** [comment]
So I for this case I think Staff Suite is better, - Jenny does a good job of Emailing her volunteers, new and old about what the responsibilities are.  "Food Prep" I think sets the expectations of the volunteers that they would be helping prepare food, and while that is 1 role in the Suite, there are many other roles... and "Food Prep" itself is something that you have prove yourself for.

**Comment by EliAndrewC** [comment]
Fair enough!  We can just change it everywhere in that case.

**Comment by kitsuta** [comment]
Fixed in https://github.com/magfest/production-config/pull/71.
