### ISSUE TITLE
Price bump warning says EST, but we're totally in EDT

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1521]
BZZZT

**Comment by EliAndrewC** [comment]
Hmm, interesting - we're using an older version of the ``pytz`` library, so upgrading would probably/hopefully fix this, since if memory serves we just have Python render the timezone for us.

**Comment by binary1230** [comment]
I'm pretty sure "EST" is hardcoded into the HTML here, if I remember correctly.

**Comment by binary1230** [comment]
I remember having to hack this for Rockage : )

**Comment by binary1230** [comment]
Yea just checked, hilarious:
```python
return '<div class="prereg-price-notice">Price goes up to ${} at 11:59pm EST on {}</div>'.format(price - discount + int(amount_extra), (day - timedelta(days=1)).strftime('%A, %b %e'))
```

**Comment by EliAndrewC** [comment]
Oh, ha.  Fair enough, I dunno why we aren't just using ``strftime`` for the timezone as well.  I'm guess it's because this code predates our use of timezones so it never got updated.

**Comment by binary1230** [comment]
hey @earl7399 you should totally try and fix this one, the key is adding a new format arg to strftime() that causes it to display the timezone.

**Comment by earl7399** [comment]
I don't have a working environment for MAGPrime, and honestly, I don't have
the expected two days to spend getting one. Otherwise, I'd love to.

Unless there's a super fast and easy way to get my Classic environment *safely
and completely* switched over, I'm out for a while.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

On Mon, Sep 21, 2015 at 8:48 AM, Dominic Cerquetti <notifications@github.com

**Comment by kitsuta** [comment]
I mean, in this case, you could just fix it in your MAGClassic environment
and commit that.

**Comment by earl7399** [comment]
I understand the words you used, and will follow your instructions. Please
don't imagine that means I understand how / why that will work.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by earl7399** [comment]
Vagrant up fails because I have the current version of VirtualBox.  I'm
tired of downgrading it.  Can we get current with Vagrant?

For now, someone else should fix this timezone display.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086
