### ISSUE TITLE
Changing of Department name

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1529]
Please change the name of ShedSpace Department to Jam Clinic

**Comment by bds002** [comment]
There is a pull request pending production for this.

**Comment by kitsuta** [comment]
Instead of commenting on these by hand, you can simply say something like "Fixes X" where X is a link to the issue.

This does two things: it automatically puts a link on that issue to the pull request in question, AND it automatically closes the issue when the pull request is merged in.
