### ISSUE TITLE
Change email text: "MAGFest Staff Suite Volunteering" (food_interest.txt)

### ISSUE THREAD

**Issue by JennyTruss** [magfest/ubersystem#1535]
* Change Reply To email to be MAGFest Staff Suite <chefs@magfest.org>
* Replace the current text with the following text. The current file is food_interest.txt.

-------------

Hello {{ attendee.first_name }}!

Thank you for not only signing up to volunteer at {{ EVENT_NAME }}, but to volunteer with the Staff Suite. If you are confused, then allow me to explain. When you signed up to volunteer, you either checked any or specifically checked “Staff Suite” as a requested department to work in.

If you are not familiar with the Staff Suite, it’s part of the perks of volunteering. We are the ones who cook and provide the 3 meals a day, as well as snacks and drinks. Tasks could include badge checking, serving food, preparing and cooking food, cleaning and washing dishes, maintaining supplies, and other miscellaneous jobs as needed. We are always on the lookout for volunteers who are willing to put in the time and effort and make a significant contribution to this department and MAGFest as a whole. 

If you are still interested in working with us, then GREAT! Please fill out the form here http://goo.gl/forms/SkRL9depRC. Please note that lack of experience will not exclude you from joining us. Your answers are only for informational purposes. 

If you are no longer interested in working with us, please let us know as soon as possible, and we will get that corrected within the system. This will mean that you will not be able to see Staff Suite shifts to sign up for.

Otherwise, we look forward to working with you, if you have any questions please let us know!

Thanks!

MAGFest Staff Suite
chefs@magfest.org

http://magfest.org

**Comment by JennyTruss** [comment]
Is there a projected date that this will get done so it can start going out to potential volunteers?

**Comment by earl7399** [comment]
PR https://github.com/magfest/magprime/pull/28 created.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by bds002** [comment]
I believe this was finished in the last deploy - @earl7399 can you confirm?

**Comment by JennyTruss** [comment]
It doesn't look like it has been deployed yet. It's still the old text.

**Comment by earl7399** [comment]
PR magfest/magprime#28 was never merged, since it was never +1'd.  @EliAndrewC @binary1230 @kitsuta ???

**Comment by JennyTruss** [comment]
Also, the send from and reply to needs to be chefs@magfest.org and not stops

**Comment by earl7399** [comment]
Correct. I said so in the text you included earlier.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by JennyTruss** [comment]
@EliAndrewC @binary1230 @kitsuta Can this be reviewed and deployed please? This is the email to send out to volunteers interested in working in the Staff Suite and we need to get it out to them ASAP so we can get some additional information from them.

**Comment by kitsuta** [comment]
Doing it now.

**Comment by JennyTruss** [comment]
@earl7399 @kitsuta @binary1230 The line with my personal email address needs to be removed, please.

**Comment by kitsuta** [comment]
Done.
