### ISSUE TITLE
"MAGFest Staff Suite Volunteering" Email : Change who it is sent to

### ISSUE THREAD

**Issue by JennyTruss** [magfest/ubersystem#1569]
Currently this email only sends to those who request Staff Suite, but are not assigned to any other department. Please change this to send to anyone who requests to work in the Staff Suite, regardless if they are already assigned, and also to anyone who is already assigned to the Staff Suite.

The form we have created does collect some information that we would like to gather from anyone working in the Staff Suite.

**Comment by JennyTruss** [comment]
Will this be implemented soon or should I just send out a blast email?

**Comment by kitsuta** [comment]
@bds002 Can you go ahead and include this change in https://github.com/magfest/magprime/pull/40? It's similar to the other changes in that PR.

**Comment by bds002** [comment]
I updated that request to included those volunteers/staffers that are interested in staff suite (or) are assigned to staff suite.  Please verify the coding ;)

**Comment by bds002** [comment]
I thought this gwased closed and pull into Staging... can someone check for me please...?

Brent

**Comment by binary1230** [comment]
From what I can see, it looks like this was changed correctly in github, and it looks like a deploy has happened recently (on Nov 16).

Current code will have this sent to anyone who either:
1) is requesting to work in staff suite, or
2) is assigned to work in staff suite
```python
AutomatedEmail(Attendee, 'MAGFest Staff Suite Volunteering', 'food_interest.txt',
           lambda a: a.requested(c.FOOD_PREP) or a.assigned_to(c.FOOD_PREP), sender='MAGFest Staff Suite <chefs@magfest.org>')
```

So, from my eyes it looks good and I think we can close this issue.  Please feel free to re-open if anyone feels this isn't the case
