### ISSUE TITLE
Improve phone number validation

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1578]
Our current validation for phone numbers is just a regexp and is based on several assumptions, like the fact that only attendees outside of the US will have an international number. It also doesn't do any validation for international numbers.

Instead we should endeavor to use a library built for this purpose. I've looked around and it seems that http://jackocnr.com/intl-tel-input.html is our best bet. We can use Google's libphonenumber library (linked on that page) to do the actual validation.

**Comment by EliAndrewC** [comment]
I've done this recently at work, so I know that the code would look something like.

```
import phonenumbers
parsed = phonenumbers.parse(number, 'US')
phonenumbers.is_possible_number(parsed)
```

This uses the https://github.com/daviddrysdale/python-phonenumbers library.  It'd be cool to also use this library for normalizing phone numbers for display as well.

**Comment by EliAndrewC** [comment]
@Utilityman - this is a good next ticket.
