### ISSUE TITLE
fix prereg page refreshing under weird conditions

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1582]
I had a note that we need to cherry-pick this into master
https://github.com/magfest/ubersystem/commit/aeb6a2d1dd21097ae1c41358d0f083559a28d9cd

**Comment by kitsuta** [comment]
Yeah, I fixed it in a different commit, which has its own PR (https://github.com/magfest/ubersystem/issues/1042). That's why the original issue is closed.
