### ISSUE TITLE
Group leader pays for group + kickin, e-mail only mentions group

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1583]
This e-mail should include the money paid for the kick-in in order to be a complete record.

**Comment by kitsuta** [comment]
@earl7399 Attendees SHOULD be sent an extra email about their extra donation, does this not happen?

**Comment by earl7399** [comment]
Ah - I missed the fact that there is a separate e-mail for the kick-in ... that makes total sense, of course.
Closing.
