### ISSUE TITLE
UTC+Daylight Savings time calculation bugs: dealers

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1589]
Everyone loves date+time bugs, especially when they involve timezones. Whee.

This bug is about dealers, but is a specific case of a general class of bugs we might find because we aren't specifying dates/times in an absolute timezone like UTC or EDT vs EST, instead we're specifying times in "eastern time" which can float depending on daylight savings time.

In this case, a dealer registers at 3:04AM, which is after our deadline of 3AM Aug 2nd 2015 EDT (note: EDT = daylight savings = -4 GMT) so they should be auto-waitlisted and receive an email about it.

However, between then and now, Daylight savings time has kicked in so we're now in EST which is GMT -5.

What we want to mean is that the deadline is 3:00am EDT, but we don't specify daylight savings time or not. So it's really "Eastern Time", which can mean -4 GMT or -5 GMT, depending on Daylight savings time. 

That means ubersystem thinks the deadline is 3:00AM, which means different things if you're before or after Daylights savings time locally:
3:00AM "Eastern Time" = 7:00AM UTC when we're in EDT, 8:00AM UTC when we're in EST.

This means the deadline floats depending on the local timezone (daylight savings time).

So the answer to "did this vendor registered before the deadline" changes due to the deadline floating (bad), and us saving vendor registered times in the database as UTC (good).

Before daylight saving's time changes on Nov 1st, the answer is: "yes, they are after the deadline":
Deadline = 3am Eastern Time, converts to EDT(-4) = 7am UTC, vendor reg'd at 7:04AM UTC. 4 minutes after deadline

After daylight saving's time changes on Nov 1st, the answer is: "no, they are before the deadline":
Deadline = 3am Eastern Time, converts to EST(-5) = 8am UTC, vendor reg'd at 7:04AM UTC

Obviously, we don't want this answer to flip flop, it should remain yes or not regardless of local timezone.

---

This behavior will only occur when 
1. a dealer registers within the hour after the deadline has passed 
2. the code to run the emails is sent out after Daylights savings time changes

---

This might not really be worth fixing because it will be a large change to test and upgrade all our config, but:

Probably "The right way" is for us to specify all of our times in the config file with timezones, or expressed in UTC.  If we were able to say, instead of 3:00AM "eastern time", that the deadline is 3:00AM EDT or 7:00AM UTC, that would fix this.

---

Date/time bug suuuuuuuuuuuuuuuuuuuuuuuuuuuuck,

**Comment by binary1230** [comment]
ok wait, curiously, the vendor that I calculated this would be an issue for, it's not an issue now.  I need to investigate further, though I still think this class of bug can exist.

**Comment by binary1230** [comment]
OK I checked this out and it turns out, as usual, python is actually more clever than I am.

Check these two dates out, which are before and after daylight savings:

```python
>>> c.DEALER_REG_DEADLINE
datetime.datetime(2015, 8, 2, 3, 0, tzinfo=<DstTzInfo 'US/Eastern' EDT-1 day, 20:00:00 DST>)

>>> c.EPOCH
datetime.datetime(2016, 2, 18, 8, 0, tzinfo=<DstTzInfo 'US/Eastern' EST-1 day, 19:00:00 STD>)
```

So turns out that it automatically (correctly) guesses which daylight savings time each of those dates "should" be in based on the date, and automatically picked EDT or EST.

So, maybe this is not really as much of an issue as I thought it would be.

**Comment by earl7399** [comment]
We should really specify the correct TZ when giving dates - then at least
it would be easier to see if something is being handled correctly, or if we
got the logic wrong.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by binary1230** [comment]
I guess what I'm saying is that, not specifying explicit time zones is indeed what I was concerned about, but, in fact, pytz is "doing the right thing" assigning explicit timezones (EDT/EST) to dates based on inferring whether they are before or after daylight sayings times.

i.e. when we say "7pm eastern time on XYZ date/time", it looks like it is applying the following logic:
if date between Nov 1st and March 8th, timezone is EST, if not, it's EDT.

I think this actually alleviates my fears, and the only time this would break is on the exact 1-hour boundary of a daylights savings timezone coming into effect.  The bugged behavior that I was worried about with this particular dealer was in fact solved by this.

**Comment by EliAndrewC** [comment]
Yeah, the way we do it is to store everything in the database in UTC so that ``pytz`` can do the appropriate timezone math.  There shouldn't be a bug here based on my reading of the code, though it's definitely possible I missed something.

**Comment by binary1230** [comment]
Yea agreed, on looking it over again and playing around with some test data, it does appear that we're doing the right thing and don't need to explicitly set the timezones.  I have really been going off on some fishing expeditions this weekend :)  Very clever python. very clever...
