### ISSUE TITLE
Changing attendee from "paid by group" to "no" produces error

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1590]
Per @kitsuta this is b/c making this change and clicking update causes the badge price to be set to 0 and then checked to make sure it isn't 0.
Work-around is to leave "Automatically recalculate badge price." checked and put non-zero amount in the base price - the Update process will replace it with the correct base price for when the badge was created.

**Comment by kitsuta** [comment]
The fix here should be pretty simple - the checking script just needs to check that the "recalculate" box is unchecked BEFORE trying to enforce the 'no $0 badge' rule.

**Comment by kitsuta** [comment]
I can't reproduce this error at all, so I'm closing it for now.
