### ISSUE TITLE
uniquely identify emails by something other than subject lines

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1594]
We currently treat email subject line strings as unique IDs for RAMS to know if it has sent a particular email or not.

That's super-convenient when first setting it up, though, it causes issues when you want to change the subject line such as in https://github.com/magfest/ubersystem/issues/1494

I propose that we instead have an explicit unique string that IDs a particular email.  For backwards compatibility, if set to None, we just use the subject line as the unique ID.

Example of how this might look: 

old-style backwards compatible, ID is None and will be the subject line:
```python
StopsEmail(subject='{EVENT_NAME} shifts available', template='shifts/created.txt')
```

new-style explicit which we'd do for all new emails:
```python
StopsEmail(subject='{EVENT_NAME} shifts available', template='shifts/created.txt', id="shifts_available")
```

backwards-compatible-style, when we want to change the subject line but have RAMS know it's really the same email.  This passes in the old subject line as the ID:
```python
StopsEmail(subject='BOBs QUALITY CARPET WAREHOUSE', template='shifts/created.txt', id='{EVENT_NAME} shifts available')
```

Bonus: if we wanted to, we could store the ID as the hash of that string so that it's faster to lookup, if we cared.  might be something to just let the DB handle though.

**Comment by EliAndrewC** [comment]
This seems like a good and sensible way to go about this.
