### ISSUE TITLE
staff can't sign up for setup/teardown shifts despite being approved for pre/post hotel room

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1596]
repro setup: 
* create a staff badge
* marked as assigned to and trusted in Charity dept
* create some restricted setup/teardown shifts for Charity dept
* use /uber/signups/login as staffer in RAMS, fill in volunteer checklist
* request hotel rooms before and after event
* visit /uber/hotel/requests, approve request
* use /uber/signups/login to try and sign up for those teardown/setup shifts

expected behavior: staffer can see teardown/setup shifts
actual behavior: staffer doesn't see teardown/setup shifts

HINTS

```attendee.possible``` lists shifts they can sign up for and filters by ```attendee.can_work_setup``` and ```attendee.can_work_teardown```  these are both ```False``` for the bugged staffer.

I suspect that this ```@presave_adjustment``` function in the hotel plugin is not getting called when the staffer is approved for extra hotel room nights:

```python
    @presave_adjustment
    def staffer_setup_teardown(self):
        if self.setup_hotel_approved:
            self.can_work_setup = True
        if self.teardown_hotel_approved:
            self.can_work_teardown = True
```

Investigating further, wanted to document what I had so far

**Comment by binary1230** [comment]
current theory is that we need to re-save the attendee when approving the request, the current handler wouldn't re-save the attendee.

```
    @ajax
    def approve(self, session, id, approved):
        hr = session.hotel_requests(id)
        if approved == 'approved':
            hr.approved = True
        else:
            hr.decline()
        session.commit()
        return {'nights': hr.nights_display}
```

BONUS: confirmed that if you do save the attendee in some unrelated way (like editing their first name), then the setup/teardown shifts appear.  

So the fix here needs to be to make sure that we re-save the attendee.

**Comment by binary1230** [comment]
when we fix this bug, we will need to re-save all existing attendees with approved extra night hotel requests (or just re-save all attendees) either from the command line or as part of a new ```sep``` command, so they pick up their correct hotel statuses.

to fix this bug we just need to re-save the attendee associated with the hotel request whenever it's updated.  I figure there's some easy sqlalechemy way to do this (relationship/cascade?), I'll pick it back up in the morning if no one knows the answer to that.

**Comment by binary1230** [comment]
should probably also do a unit test for this as well.

**Comment by EliAndrewC** [comment]
The best fix is probably to add something like this to the ``HotelRequests`` class:

```python
    @presave_adjustment
    def cascading_save(self):
        self.attendee.presave_adjustments()
```

that will make sure that anytime we make a change to someone's hotel requests, it applies the appropriate changes to the attendee.

With that being said, there's definitely an argument to be made to the idea that the presave adjustment that sets those database fields should be on the ``HotelRequests`` class and not the ``Attendee`` class in the first place.  If it was on this class then we wouldn't need to worry about any of this cascading silliness.  I dunno, I don't have a strong preference.

**Comment by binary1230** [comment]
pretty sure we fixed this issue and the PR didn't mark it as closed, closing it now.

**Comment by kitsuta** [comment]
Yeah, you have to say "Fixes ####" inside the PR description - commenting won't work.
