### ISSUE TITLE
Descriptive info not closing on Shift descriptors.

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1598]
On: https://prime.uber.magfest.org/uber/signups/shifts#/

There is a ? beside the Shift title to display more info about the shift.
This should be set as an display on / display off feature.

Current behavior is to display the descriptor when users clicks the questions mark. 
Upon a subsequent click, the descriptor repeats a post of the information..... and continues to do so on each click.

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/ubersystem/pull/1744
