### ISSUE TITLE
DataTable no longer allows pre-selecting a page size

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1599]
At one point, we could put the following line of code into a template to cause the default ``DataTable`` page size to show all items in the table:

```javascript
$.fn.dataTable.defaults.pageLength = 'All';
```

I actually did this in the MIVS codebase, and it worked as of a month or two ago:
https://github.com/magfest/mivs/blob/master/mivs/templates/mivs_base.html#L30

I'm not sure at what point this stopped working, but we probably made some DataTable-related change which requires us to do this a different way now.

Relatedly, am I mis-remembering, or did DataTable at one point remember your page size such that if you clicked a link and then returned to the page, it would use the page size you selected previously?  That doesn't seem to work anymore, though maybe that was never a thing and I just dreamed it.

I'll see if I can tackle this myself sometime this week, since the MIVS folks have said it's a hassle for them given their workflow of constantly switching back and forth between pages with DataTables.

**Comment by kitsuta** [comment]
I just checked the production server, and we do have an "All" page option, which I had put in a few weeks ago. So... I don't... know what you're talking about.

**Comment by EliAndrewC** [comment]
> I just checked the production server, and we do have an "All" page option, which I had put in a few weeks ago. So... I don't... know what you're talking about.

What I'm pointing out is that while the "All" option exists, it's not the default, so every time that the MIVS folks visit a page they have to re-select the "All" option because they rarely if ever want to only look at 25 things at a time.

The line of code I linked to used to cause "All" to be the default selected option when the page first loaded, and that stopped working sometime in the past month or two, presumably because of some other DataTable-related change.  I'll try to track down what caused that, but I figured I'd ask whether anyone already had any idea.

**Comment by thaeli** [comment]
Any calls to the DataTable functions intended to run on page load
should be within a $( document ).ready() block. Really, any scripts
run on page load should be within document-ready blocks - JQuery has
weird timing issues like this when you have 'bare' commands inline.

Cheers,
Ian

**Comment by thaeli** [comment]
Actually, thinking about this a bit more, there is an even better
solution in this particular case. Specify the default page size in a
data attribute on the table itself by adding data-page-length="All" to
the <table> tag.

**Comment by EliAndrewC** [comment]
Ah, thanks!  I didn't know about that attribute, but that does seem like a much better way since it's presumably how DataTable intends for us to specify this.  I'll give that a shot tonight.

**Comment by EliAndrewC** [comment]
Now that my new computer has arrived I had a chance to test this out.  It works great, though due to the implementation details of how DataTable handles the "All" option, I have to say ``data-page-length="-1"`` instead of ``data-page-length="All"`` which is mildly annoying but certainly acceptable.  I'm therefore marking this as closed.  Thanks again for the tip.
