### ISSUE TITLE
Seperate Hotel room nights from Load-in/Load out shifts

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1602]
Stated Issue:
We need to Separate the Load in/load out shifts in all departments from the Hotel room night request.

User Story:
Load-in/Load-out shifts on: https://prime.uber.magfest.org/uber/jobs/ page are only view able to staffers that have been approved by DH (Uber Admin accounts) for early/late hotel rooms:
https://prime.uber.magfest.org/uber/hotel/requests

As we have grown, we have a number of staffers that are available to help do setup and or tear-down that don't necessarily need Hotel crash space during their load-in shifts.  The easiest way to account for that is to break apart the links from requiring Pre and Post event shifts to be tied to hotel room request.

--Maybe in the end what we have is when a staffers signs up for shifts, Rams re-checks their room night request and says - you have shifts on a Thurs evening, but only request a room starting Friday (Is this correct)?

-- I still like the idea of DH's having to verify Load-In/Load-out staffers, but it should be unlocked from Hotel room night information

This is somewhat related to:
https://github.com/magfest/ubersystem/issues/1601 as a Hotel work flow issue and should be considered at the same time.

**Comment by EliAndrewC** [comment]
This will be an easy lift, because we just need to add two checkboxes (approved for setup and approved for teardown) to the admin form to let admins set the booleans that are already in the database.

Normally this is where I'd say that I'd take care of this literally tonight after work (since I'm finally done with the bulk of my department-specific plugin work), but my computer crashed last night and came back up with all kinds of problems and I can't even connect to the internet yet, so it might be at least a few days before I can get to it :(

**Comment by bds002** [comment]
The other quick fix I was thinking here, was that if someone DECLINEs room space, they should be able to see all available shifts as well... Declined could be because they live locally, or they have other arrangements.

**Comment by EliAndrewC** [comment]
That would also be covered by the change I proposed.

I totally forgot about this ticket while my new computer was being ordered and then never remembered it afterwards.  Is this still a high priority?  I could get it knocked out this week if so.  I can also just mark specific people in the database as being approved for setup/teardown shifts even without adding these checkboxes if someone emails their names to stops@magfest.org or wherever.

**Comment by bds002** [comment]
This is in Jira as well - BADGE CONSISTENCY Check is Primo priority 1 so we can get the Staff badges ordered.   After that is the 2 email verification that the Interns are working on and having issues with .. then this....  (in the nice to have, but not blocker or on fire at this point)
