### ISSUE TITLE
Sitemap should include CSV exports

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1605]
The currently implementation of the sitemap happens to miss `@csv_file` page handlers.  It should be updated to include those, because we often have people asking about their the URLs.

**Comment by binary1230** [comment]
example for anyone who would work on this:

the URL ```/uber/summary/staff_badges```  should show up in the sitemap, but it doesn't.

it's defined like this in summary.py:
```
   @csv_file
    def staff_badges
```
