### ISSUE TITLE
Logistics shift extensions staring on 13th

### ISSUE THREAD

**Issue by pelololoquin** [magfest/ubersystem#1609]
Need to be able to create shifts starting on the 13th at Noon to accommodate truck crew and loading for hotel room hours.

**Comment by EliAndrewC** [comment]
You should be able to do this.  Click on the "Add a setup shift" link and it should let you create shifts as early as 8am on the 12th (Tuesday).

**Comment by pelololoquin** [comment]
I think you're looking at a January calendar.

**Comment by EliAndrewC** [comment]
Ahhh, so I am.  Good call!

So basically, we want setup shifts to be able to exist at least 5 days before the event?  Fair enough, we just need to change the line of code at
https://github.com/magfest/ubersystem/blob/master/uber/config.py#L378
from 2 days to 5.  Or better yet, add a new config option for how many days in advance we want setup shifts to run, and then use that new config option.

That sounds like a great task for a newcomer, so I'll add that tag to this ticket.  If no one else is able to tackle this in a reasonable time period I can do it myself when I get a chance.
