### ISSUE TITLE
Urgent issue with current/future pricing

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1615]
Reported by potential attendee, confirmed by me.  "Hi I have a question I went to buy my ticket and it says that the price goes up to 70$ on January 17th however when I click to buy it the price is already listed at 70$. How can it be 70$ already when that price isn't supposed to be in effect until the 17th?"

![image](https://cloud.githubusercontent.com/assets/8770069/12074475/359467a8-b124-11e5-91d9-8d0dd46aeab6.png)

**Comment by bds002** [comment]
Event Prime has this coded to be:
 - { '2016-01-20': 75 } so somewhere it's drawing false information

**Comment by bds002** [comment]
It looks like info is being pulled from:
 ubersystem/uber/configspec.ini

prereg_takedown = string(default="2016-01-18")

**Comment by EliAndrewC** [comment]
Fixed in #1617

**Comment by binary1230** [comment]
+1
