### ISSUE TITLE
significant: prereg page supporter options broke after the deadline

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1626]
pretty major bug here, might be an easy fix though.

repro: view the prereg confirmation page for anyone who kicked in $80 or more (supporter level), past the supporter deadline (Jan 10th for mag2016)

expected: page works
actual: multiple elements of the page are broken including the kickin slider, tshirt size selection, and other stuff

![image](https://cloud.githubusercontent.com/assets/5413064/12237784/7854a716-b84e-11e5-92b6-d44a89a9b956.png)

=== cause:

client-side javascript errors cause the page to crash out before it has a chance to set the various elements display states correctly.

javascript tries to determine 'amount_extra' by looking at which element is 'checked' in the kickin dropdown.  it will use 'amount_extra' to show and hide various things on the page like tshirt sizes/etc

for supporters, they should have an $80 option checked.  however due to the following code, no $80 element was ever placed into the HTML:

```
    @property
    def PREREG_DONATION_OPTS(self):
        if self.BEFORE_SUPPORTER_DEADLINE and self.SUPPORTER_AVAILABLE:
            return self.DONATION_TIER_OPTS
        else:
            return [(amt, desc) for amt, desc in self.DONATION_TIER_OPTS if amt < self.SUPPORTER_LEVEL]
```

that means the only options in the HTML is the following:
![image](https://cloud.githubusercontent.com/assets/5413064/12237864/f947b6c4-b84e-11e5-80fd-7d98f13ff1ce.png)
(note: none of these options are $80, and none of them are checked)

the page crashes when common.js tries to access the 'checked' element

![image](https://cloud.githubusercontent.com/assets/5413064/12237933/4d1efdf2-b84f-11e5-8ebc-eac91868df6c.png)

**Comment by binary1230** [comment]
solutions: (I don't really know the implications of changing this stuff so would like others more familiar with this system to weigh in)

1) display all the supporter options in ```PREREG_DONATION_OPTS``` regardless of deadline, and make the template/js deal with disabling the stuff they aren't allowed to pick
2) pass in 'amount_extra' in some way unrelated to the checkboxes, and make the JS deal with not having a checked element for 'amount_extra'

**Comment by binary1230** [comment]
possibly related (though lesser priority), on non-supporter pages, we're getting weird links showing up at the bottom:

![image](https://cloud.githubusercontent.com/assets/5413064/12238445/0bcef1ce-b852-11e5-8733-cd4d0e53b285.png)

**Comment by binary1230** [comment]
currently considering an emergency fix to give us breathing room on this of pushing back the supporter deadline

**Comment by binary1230** [comment]
pushed out the supporter deadline til Wed which alleviates the immediate pressure and makes it so we can take our time fixing this one.

**Comment by EliAndrewC** [comment]
Pushing back the deadline to give us more time seems like a good solution.

**Comment by binary1230** [comment]
@kitsuta @thaeli do you guys have any suggestions on the best way to fix this?
