### ISSUE TITLE
arbitrary_charge_form for M2016

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1633]
SO we have: https://prime.uber.magfest.org/uber/registration/arbitrary_charge_form?

I don't think this link is working:
https://prime.uber.magfest.org/uber/registration/arbitrary_charge_form?amount=450.00&description=Hotel+Room

When I input a number... it returns an error message that value must be between 1 and 999
https://prime.uber.magfest.org/uber/registration/arbitrary_charge_form?

It's not linking to Stripe to create the Charge Link. (wrong)

Update:
It does work.. it takes whole numbers only... no decimals.

**Comment by EliAndrewC** [comment]
This is now confirmed as working.
