### ISSUE TITLE
Search Attendees w/phone # give 500 error

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1641]
URL: https://prime.uber.magfest.org/uber/registration/index?order=last_first&search_text=9026522339
produces this:

> 500 Internal Server Error
> 
> The server encountered an unexpected condition which prevented it from fulfilling the request.
> 
> Traceback (most recent call last):
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
>     context)
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.DataError: value "9026522339" is out of range for type integer
> LINE 4: ...N (163076611, 215389669) AND attendee.badge_num = '902652233...
>                                                              ^
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
>     response.body = self.handler()
>   File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
>     self.body = self.oldhandler(_args, *_kwargs)
>   File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
>     return self.callable(_self.args, *_self.kwargs)
>   File "/usr/local/uber/plugins/uber/uber/decorators.py", line 179, in with_timing
>     return func(_args, *_kwargs)
>   File "/usr/local/uber/plugins/uber/uber/decorators.py", line 170, in with_caching
>     return func(_args, *_kwargs)
>   File "/usr/local/uber/plugins/uber/uber/decorators.py", line 194, in with_session
>     retval = func(_args, session=session, *_kwargs)
>   File "/usr/local/uber/plugins/uber/uber/decorators.py", line 278, in with_restrictions
>     return func(_args, *_kwargs)
>   File "/usr/local/uber/plugins/uber/uber/decorators.py", line 240, in with_rendering
>     result = func(_args, *_kwargs)
>   File "/usr/local/uber/plugins/uber/uber/site_sections/registration.py", line 42, in index
>     count = attendees.count()
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2724, in count
>     return self.from_self(col).scalar()
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2503, in scalar
>     ret = self.one()
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2472, in one
>     ret = list(self)
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2515, in **iter**
>     return self._execute_and_instances(context)
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2530, in _execute_and_instances
>     result = conn.execute(querycontext.statement, self._params)
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
>     return meth(self, multiparams, params)
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
>     compiled_sql, distilled_params
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
>     context)
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
>     exc_info
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
>     raise value.with_traceback(tb)
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
>     context)
>   File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.DataError: (psycopg2.DataError) value "9026522339" is out of range for type integer
> LINE 4: ...N (163076611, 215389669) AND attendee.badge_num = '902652233...
>                                                              ^
>  [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT attendee.id AS attendee_id, attendee.watchlist_id AS attendee_watchlist_id, attendee.group_id AS attendee_group_id, attendee.placeholder AS attendee_placeholder, attendee.first_name AS attendee_first_name, attendee.last_name AS attendee_last_name, attendee.email AS attendee_email, attendee.birthdate AS attendee_birthdate, attendee.age_group AS attendee_age_group, attendee.international AS attendee_international, attendee.zip_code AS attendee_zip_code, attendee.address1 AS attendee_address1, attendee.address2 AS attendee_address2, attendee.city AS attendee_city, attendee.region AS attendee_region, attendee.country AS attendee_country, attendee.no_cellphone AS attendee_no_cellphone, attendee.ec_phone AS attendee_ec_phone, attendee.cellphone AS attendee_cellphone, attendee.interests AS attendee_interests, attendee.found_how AS attendee_found_how, attendee.comments AS attendee_comments, attendee.for_review AS attendee_for_review, attendee.admin_notes AS attendee_admin_notes, attendee.badge_num AS attendee_badge_num, attendee.badge_type AS attendee_badge_type, attendee.badge_status AS attendee_badge_status, attendee.ribbon AS attendee_ribbon, attendee.affiliate AS attendee_affiliate, attendee.shirt AS attendee_shirt, attendee.can_spam AS attendee_can_spam, attendee.regdesk_info AS attendee_regdesk_info, attendee.extra_merch AS attendee_extra_merch, attendee.got_merch AS attendee_got_merch, attendee.reg_station AS attendee_reg_station, attendee.registered AS attendee_registered, attendee.checked_in AS attendee_checked_in, attendee.paid AS attendee_paid, attendee.overridden_price AS attendee_overridden_price, attendee.amount_paid AS attendee_amount_paid, attendee.amount_extra AS attendee_amount_extra, attendee.amount_refunded AS attendee_amount_refunded, attendee.payment_method AS attendee_payment_method, attendee.badge_printed_name AS attendee_badge_printed_name, attendee.staffing AS attendee_staffing, attendee.requested_depts AS attendee_requested_depts, attendee.assigned_depts AS attendee_assigned_depts, attendee.trusted_depts AS attendee_trusted_depts, attendee.nonshift_hours AS attendee_nonshift_hours, attendee.past_years AS attendee_past_years, attendee.can_work_setup AS attendee_can_work_setup, attendee.can_work_teardown AS attendee_can_work_teardown, attendee.extra_donation AS attendee_extra_donation, attendee.hotel_eligible AS attendee_hotel_eligible \nFROM attendee LEFT OUTER JOIN "group" ON "group".id = attendee.group_id \nWHERE attendee.badge_status IN (%(badge_status_1)s, %(badge_status_2)s) AND attendee.badge_num = %(badge_num_1)s) AS anon_1'] [parameters: {'badge_status_1': 163076611, 'badge_num_1': '9026522339', 'badge_status_2': > 215389669}]
> Powered by CherryPy 3.6.0

**Comment by EliAndrewC** [comment]
Interesting.  What's happening is that when we see a search which consists only of a single integer, we interpret that as a badge number.  Unfortunately, since a 10-digit number is larger than our database things an integer should be, it throws that exception.

I think the solution is to have an if-else statement where if the search consists of a single integer, we check how long it is, and if it's 10 or more digits, we interpret it as a phone number search, and otherwise we interpret it as a badge number search.
