### ISSUE TITLE
Add Indicator of Weights to shift hours for Admin screen

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1642]
On the header screen for Staffers:
Attendee Data 	Shifts 	History 	Return to Staffer List 	Return to Attendee List

For Shifts - the drop down box shows all the available shifts, it should also show their corresponding weighted hours.

https://prime.uber.magfest.org/uber/registration/shifts?id=be66c012-cf03-4157-81d3-e67373efe019

**Comment by bds002** [comment]
https://jira.magfest.net/browse/MAGDEV-69

**Comment by EliAndrewC** [comment]
Fixed in #1743
