### ISSUE TITLE
Double word in MAGFest food for guests e-mail

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1643]
Currently says:
"Thanks for coming out to MAGFest as a Guest! Since our Staff Food Suite is also open to to Guests,"

Should say:
"Thanks for coming out to MAGFest as a Guest! Since our Staff Food Suite is also open to Guests,"

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/magprime/pull/78
