### ISSUE TITLE
Create transactional automated email for refunds.

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1645]
So in the past staffers have come to Ops when their hours for a refund where completed.

With the new volunteers due refunds page, we are capable of processing refunds without the volunteer being present.  We should create an email that is sent to them when we marke their badge as being refunded....

**Comment by bds002** [comment]
Oh I tried to do some editing on my phone, didn't realize it made a new ticket.... :(

**Comment by EliAndrewC** [comment]
fixed in #1780
