### ISSUE TITLE
group names displayed badly via email

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1651]
repro steps:

1) create a group with an ampersand in the name, such as "D&D Adventurers League"
2) get uber to send you the email of group_preassign_reminder.html

expected:
`Our records indicate that your group (D&D Adventurers League) currently has some unassigned badges`

actual (gmail):
![image](https://cloud.githubusercontent.com/assets/5413064/12563157/ce9e96a8-c376-11e5-9cdf-4c3d721f33de.png)

to fix: need to use a django template filter like |safe or something similar to it (not sure which one).  

there are probably many other emails where we're displaying this incorrectly as well, check around for them.  check if this is a thing that only happens in .html emails or .txt as well.

NOTE: there's a chance this might just be an artifact of this attendee forwarding us an email in supportbee, and supportbee or this attendee's email client broke the formatting.  worth checking on.

**Comment by EliAndrewC** [comment]
Oh yeah, I think a ``|safe`` filter would take care of this.

**Comment by migetman9** [comment]
This appears to be implemented.
