### ISSUE TITLE
uber not fully offline with no internet - google maps API being hotlinked

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1658]
I am doing Jury duty today with spotty internet : )

I discovered we are loading this in base.html on every single page:
```
<script src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"></script>
```

Because my internet is garbage here, it's hanging on loading that on each page.  in our goal of making uber work offline as much as possible, is it possible to pull this into something like bower and include it statically vs hotlinking to googleapis.com?

@kitsuta something to do with this, though it's loading super-slow for me with my crappy interenet :)  https://github.com/magfest/ubersystem/commit/d7ba12fbe446cedbbbbd16a8ec3f6f13affecd90

**Comment by EliAndrewC** [comment]
If you look at
https://github.com/magfest/ubersystem/blob/master/uber/templates/base.html#L174
you'll see that this is ONLY turned on when we're in ``c.PRE_CON`` mode.  Thus when we're on-site it won't even try to load, regardless of whether internet is available or not.

**Comment by kitsuta** [comment]
That's not true, @EliAndrewC - the if statement ends before the GoogleMaps API call.

I submitted a PR way back when to implement 'offline mode' and I essentially got talked out of it, so this issue was never addressed.

**Comment by EliAndrewC** [comment]
Ah, you're right! Well we should probably move that API call to the bottom of the <body> at least then.  I don't know/recall what that's even there for.

**Comment by binary1230** [comment]
yea actually i thought it was in that c.PRE_CON block too, had to double take a few times :)

it's something to do with address verification when people have to enter their full address, didn't dig much deeper than that

**Comment by kitsuta** [comment]
It's needed for the Google-powered address search in the pre-reg form. Really just a nicety for attendees.

**Comment by EliAndrewC** [comment]
Since we don't make use of that, would it make sense to wrap that in ``{% if c.COLLECT_FULL_ADDRESS %}`` since otherwise it's pointless and will make the page take (slightly) longer to load?  That seems like a reasonable change, which I'll open a PR for tonight, and we can merge it in if everyone agrees.

**Comment by kitsuta** [comment]
Whoops, yes. Good point!
