### ISSUE TITLE
Staffers who decline to staff don't have their badge numbers reset

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1659]
Steps to reproduce:
- create a person with a Staff badge, which is a preassigned badge type
- visit the ``/preregistration/confirm`` page for that staffer
- uncheck the "Want to volunteer?" box and submit the form

Expected results:
- the person has been changed to an Attendee badge and their badge number unset

Actual results:
- the person has been changed to an Attendee badge but still has their original pre-assigned badge number from their Staff badge

**Comment by kitsuta** [comment]
This _should_ be fixed by #1901 - it is according to the unit tests, anyway - but I still need to test this manually.

**Comment by kitsuta** [comment]
OK, fixed this in #1901.
