### ISSUE TITLE
Allow multiple ribbons per registration

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1664]
Ribbons are currently a dropdown field which only allow a single value.  This is becoming a larger headache every year; we'd like to be able to select any number of ribbons for people so that someone can be e.g. both a volunteer and a panelist, etc.

**Comment by bds002** [comment]
I just did an inventory of badges, we have 12 different types and I think we are ordering 2 more types....
 Reg. doesn't hand all of those out, but they do have the bulk of them.

Reg doesn't handle:
Arcade Crew Chief - Arcade department
The Law - Dorsai
Managers - Operations (Given to DH's as needed)
Prop/Weapon Check - Dorsai
Tech Ops - handled by Tech Ops DH's
I love Magfest - handled by Merch (Support/Swag and for sale)

I think MIVS and MAGES should all be handled at the Department level as well.

That leaves for following to be handled/handed out by Reg:
Volunteer
Rock Star
Shopkeep
Department Head
Panelist

**Comment by kitsuta** [comment]
Whoops, I somehow completely forgot to link this to https://github.com/magfest/ubersystem/pull/2711! This is done! \o\
