### ISSUE TITLE
UX request: 'unassign' and 'rating' buttons to be moved further apart from each other

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1666]
feedback from staff suite last year: 

As a user of RAMS job system on mobile, I want the 'unassign' and 'rating' buttons to be moved further apart from each other because it's too easy to accidentally press the wrong button

**Comment by EliAndrewC** [comment]
Seems easy enough.  I'll make sure this gets done before the event.

**Comment by binary1230** [comment]
Amazing work guys
