### ISSUE TITLE
Welcome message with new accounts

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1667]
We create a LOT of admin accounts these days, and people who get a cryptic email about their login creds often have no idea what it's all about.  It would be nice if when we created an account, we could include a welcome message explaining what to expect, e.g. "We created this account for you because you're an indie judge" or "this account exists so you can log in to work regdesk on-site", etc.

**Comment by bds002** [comment]
Why are we on the same page so much... I was just asking @iollan (Sean Person) about this for their At-Con registration accounts....

**Comment by EliAndrewC** [comment]
Haha, that was also what made me think of this feature.

**Comment by kitsuta** [comment]
Hahah oops, if only we had had a chance to fix this BEFORE those 200+
accounts got made...
