### ISSUE TITLE
Workflow for: Staffers/Volunteers Cancelling pre-event.

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1668]
Eli, Vicki etc.....

This is an issue that has come to the fore front as we are in crunch time for people to verify schedules at work etc....

When a Staffer or Volunteer uses the link in their email to tell us they are not coming:
It marks the badge as invalid, However:

They volunteers Shifts are still in Uber as active/signed up for shifts.
Their Hotel room is also still allocated with their name on it.

Stops needs to receive an Email when attendees/staffs remove themselves and their shifts/rooms need to be unassigned.

Brent

https://jira.magfest.net/browse/MAGDEV-58

**Comment by EliAndrewC** [comment]
I'd hoped to get to this over the weekend but didn't quite find the time.  It's still something I expect I can tackle sometime this week, probably Wednesday.

**Comment by EliAndrewC** [comment]
This is done.  The report can be found at https://prime.uber.magfest.org/uber/magprime_reports/ and Stops will get an email when volunteers are marked as invalid in the future.
