### ISSUE TITLE
User-marked Invalid group badge doesn't become unassigned

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1669]
All group badges show as assigned (pre-reg and logged in views):
![image](https://cloud.githubusercontent.com/assets/8770069/12844326/a30b002c-cbcc-11e5-9c3d-5e82ae4282e9.png)
![image](https://cloud.githubusercontent.com/assets/8770069/12844434/2cc3ef04-cbcd-11e5-9f58-cea8b2923acf.png)

Search for the member who shouldn't be - their badge already has been marked Invalid by Non-Admin.

Clicking the Unassign button properly removes the Invalid badge from the group and leave an     [Unassigned Attendee] badge.

**Comment by EliAndrewC** [comment]
IMO the correct fix here is to either

1) Simply not show the "I'm not coming" button for group badges on the ``confirm`` page.

2) Show that button, but do NOT mark the badge invalid when it's clicked and instead just unassign the badge like we would on the group members page.

I like the second option better.

**Comment by earl7399** [comment]
+1 for option #2

**Comment by floraline** [comment]
Regarding option 2 above, does this apply both when a badge is part of a group and when it is not? Do we always want to *delete* the badge and never *invalidate* it, even when the badge is NOT part of a group?

**Comment by kitsuta** [comment]
Nah, we'd want to invalidate it when it's not in a group. It's just that when changing what the button does, someone (probably me) forgot that it would result in a really weird user experience to simply mark a group badge as 'invalid'
