### ISSUE TITLE
Preregistration Page Changes

### ISSUE THREAD

**Issue by iollan** [magfest/ubersystem#1670]
Add a disclaimer that states: "MAGFest has a one badge per person policy. If you purchase multiple badges (for your family, as a gift), please ensure that each badge is purchased in the name of the individual who will be picking it up. You may use the same email address so the surprise isn't ruined." Or something like that, make it sleeker and shorter. 

Also change "Attendees under 18 MUST bring a signed and notarized parental permission slip." to Attendees under 18 MUST bring a signed parental consent form, which MUST be notarized if the parent is not attending the fest."

**Comment by EliAndrewC** [comment]
As part of this work, we should add these disclaimers to the bottom of the at-the-door prereg page.

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/ubersystem/pull/1740
