### ISSUE TITLE
Make "show all badges" the default during at-con mode

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1683]
While checking people in, it will save a lot of time if we do not have to constantly switch each station to the 'show all badges' view while searching for people. Ideally we'd solve this in a more elegant way, but for now a good quick solution is to default the Attendee admin page to show all badges as long as we're in at-con mode.

**Comment by EliAndrewC** [comment]
I'm not sure I understand.  Are you saying that when someone does a search and more than 100 results are returned, it should show all results no matter how many there are?  I don't think that sounds like a good idea.

**Comment by kitsuta** [comment]
Oh my, no.

By default, all badges that aren't "New" or "Complete" are hidden from
search. This means that if you search for an attendee and the only match is
an invalid badge, the search will tell you that it didn't find anything.

Keeping invalid badges is partly to bypass the "I can't find your badge in
the system" dance and go straight to "you had a badge but it was deleted,
let's see what happened." But if invalid badges don't show up in search,
that partially undermines their purpose. So we'd want invalid badges to
show up, but only during at con checkin.

**Comment by EliAndrewC** [comment]
Ahhhh, that makes sense and does sound like a great idea which I fully endorse.
