### ISSUE TITLE
Add admin option to 'turn off' certain badge types for kiosks

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1684]
In order to deal with selling out of badges during the event, it will be tremendously helpful if admins can manually 'turn off' options in the at-door kiosk page, without requiring a configuration restart. This allows us to control exactly when the option goes away to make everyone happier.

Ideally, this would also let us choose to turn off options _only_ for users that aren't logged in - that way we can prevent online registrations from sniping people who have patiently waited in line. (Kiosks would have an admin login, which is the easiest way to differentiate them from people on their phones).

**Comment by EliAndrewC** [comment]
For what it's worth, a variant on this is already implemented as of last night.  You can configure a number of badges in the ``[[stocks]]`` config section, and the options will disappear from the kiosk page without a restart as soon as the stocks are exhausted.  Which probably gets us what we need.

Worst case scenario, if we decide to suddenly close down selling badges of a particular type, we can update the stock setting and restart the process.  I know we'd prefer to not restart all things being equal, but considering that we restarted like probably dozens of times last year without any real incident it's probably not that big a deal.

**Comment by kitsuta** [comment]
Yeah, this was specifically going to be a button we controlled because we wanted to be able to say, "OK, there are about 100 badges of [TYPE] left, let's turn off this badge for online users."
"OK, there are about 50 badges left now. Now, we'll put a line wrangler at the end of the at-door line to tell people they can no longer buy that type of badge."
"OK, the line wrangler has reached the front of the line, so we should turn that badge off now."

This gives us a lot more control over line management than just a stock option, which I already knew about.

**Comment by kitsuta** [comment]
I'm going to close this issue for now, since this is an old user story and is no longer necessarily needed. We can re-open it if we decide later we need it before the more general practice of setting config via a web interface solves this problem.
