### ISSUE TITLE
Need accurate description in Stripe for charges

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1699]
With Stripe history potentially lasting for years, it becomes easy to miss the fact that a charge you found is for a previous fest.

To make this less likely, we need good description text for charges including Festname/Festdate, like "MAGFest 2016 badge for so-and-so"

**Comment by EliAndrewC** [comment]
+1 on this idea.

**Comment by EliAndrewC** [comment]
This already works :)

Except that we never set the option in our puppet config :(

We created a Jira issue to make sure we get this done before prereg opens next year :/

https://jira.magfest.net/browse/MAGDEV-78
