### ISSUE TITLE
Shift signup page makes frequent requests after we switch to at-the-con mode

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1721]
Our shift signups page has a Javascript handler which periodically refreshes the list of shifts available via an Ajax request.  When that request fails, it waits 1 second and then tries again:
https://github.com/magfest/ubersystem/blob/cc479eaf7dd378ecf8b1081cfe36b0e77d20a417/uber/static/angular-apps/signups/app.js#L29

I never got around to implementing that `TODO`, and once we go to `c.AT_THE_CON` mode, that server page stops working.  This means that if a bunch of people have their shift schedule open, nd leave it open in a tab, then when we switch to at-the-con mode, their browser will go crazy and request the same page once per second.

There are two coding solutions, neither of which will help at present since people who already have the tab open won't get the latest code, but which would prevent this from being a problem next year:

1) Implement the exponential backoff which was mentioned in the TODO.  MAke a request after 1 second, then 2 seconds, then 4, then 8, up to some round number like 1024.

2) Once we enter at-the-con mode, respond to that page with a JSON response which tells the frontend to redirect the user to their printable schedule, so we'll stop making requests period.

We should probably implement both of the above.

In the meantime, we have the immediately problem of dealing with the requests we're getting hammered with from the people with their browsers open.  Fortunately, the page being requested has NO validity when we're in at-the-con mode, so the simple solution is to tell nginx to drop it.  If we configure the Nginx server running `onsite.uber.magfest.org` to just respond with a 404 for all requests to `/uber/signups/jobs` then those requests will never hit our CherryPy backend and we'll never create session files for them, never run out of inodes because of these requests, etc.  I'll coordinate with @binary1230 about making this change.

**Comment by binary1230** [comment]
FYI, we worked around this on-site with https://github.com/magfest/ubersystem-puppet/pull/72, and then reverted that quick fix with https://github.com/magfest/ubersystem-puppet/pull/79

The underlying issue still remains and should be a very high priority to fix before Magstock goes live.

**Comment by kitsuta** [comment]
Actually it looks like timrxd fixed this with https://github.com/magfest/ubersystem/commit/24bc7d00b36b0eeaa5e63ba0d175c682779e0063. I assume he was working with @EliAndrewC - Eli, is this fixed?

**Comment by EliAndrewC** [comment]
We implemented the first of the two suggestions but not the second.  So the page no longer makes a zillion requests, but it doesn't pre-emptively redirect you to the printable schedule page.

**Comment by binary1230** [comment]
@RobRuana btw, this thing always bites us and we always forget to fix it or fixed it wrong in the past.  definitely worth checking because it basically amounts to a DDOS that we inflict on ourselves : )

**Comment by RobRuana** [comment]
All of our pain is self inflicted.
