### ISSUE TITLE
Hitting enter twice double submits the registration form

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1730]
We used to protect against this, but I'm guessing that broke in the bootstrap refactor or something.

I just tried submitting a form by hitting Enter twice on one of the form fields.  It created two unpaid registrations instead of one.  We should fix the Javascript which prevents double form submission.

**Comment by RobRuana** [comment]
Could not reproduce. Tried a variety of methods, including hitting enter twice on a bunch of different fields, also while the "Submit" button was focused.  Also tried clicking the button twice really fast. Tested in the latest Safari, Chrome, and Firefox.
