### ISSUE TITLE
Cannot change badge type without a badge number

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1734]
According to @kitsuta:
Uh... I can't actually change anyone's badge type
Didn't I fix this for MAGClassic?
Basically if I don't include a badge number, the page goes through but the badge type doesn't change.

I'll look into this in the morning when I have my laptop back.

**Comment by EliAndrewC** [comment]
Confirmed in staging.  I can set a badge type if I provide a number but if I leave the number blank or enter 0, the badge type is not changed.

**Comment by EliAndrewC** [comment]
Shouldn't be too hard to push out a fix in the morning.

**Comment by kitsuta** [comment]
@EliAndrewC If you're not tackling this, I can have a go.

**Comment by EliAndrewC** [comment]
I'm working on it now.
