### ISSUE TITLE
On Group Info page, checked-in times appear to be UTC, GL doesn't show checked-in time

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1742]
e.g.:

Badges:  
GL NAME	(paid => doesn't need to,    badge => One Day #XXXX)	Leader	(cannot unassign group leader)
GL Member1	(paid => paid by group,    badge => One Day #XXXX)	Make Leader Checked-in 4:21pm Fri

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/ubersystem/pull/1755
