### ISSUE TITLE
Add check-in button/checkbox/something to badge number change form

### ISSUE THREAD

**Issue by zebranky** [magfest/ubersystem#1750]
I've probably failed to check in several dozen people up to this point at M2016 because I assumed setting a badge number did that. I'd also accept showing check-in time on the attendee data page right under badge number, and ideally offer a button if they're not checked in yet.

**Comment by EliAndrewC** [comment]
Huh, setting a badge number SHOULD check them in!  Since that's not happening it's a bug!  I'll push out a fix tonight.

**Comment by EliAndrewC** [comment]
fixed in https://github.com/magfest/ubersystem/pull/1752

**Comment by EliAndrewC** [comment]
46 people were affected by this bug - I marked all of those people as checked in.
