### ISSUE TITLE
Reg Take Report is broken

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1778]
This was never fully converted after we changed from Django to SQLAlchemy a few years ago :(

We need to fix `/registration/reg_take_report` to eliminate the reference to `Attendee.objects`.

**Comment by migetman9** [comment]
Is this still valid? 
` def reg_take_report(self, session, **params):
        if params:
            start = c.EVENT_TIMEZONE.localize(datetime.strptime('{startday} {starthour}:{startminute}'.format(**params), '%Y-%m-%d %H:%M'))
            end = c.EVENT_TIMEZONE.localize(datetime.strptime('{endday} {endhour}:{endminute}'.format(**params), '%Y-%m-%d %H:%M'))
            sales = session.query(Sale).filter(Sale.reg_station == params['reg_station'],
                                               Sale.when > start, Sale.when <= end).all()
            attendees = session.query(Attendee).filter(Attendee.reg_station == params['reg_station'], Attendee.amount_paid > 0,
                                                       Attendee.registered > start, Attendee.registered <= end).all()
            params['sales'] = sales
            params['attendees'] = attendees
            params['total_cash'] = sum(a.amount_paid for a in attendees if a.payment_method == CASH) \
                                 + sum(s.cash for s in sales if s.payment_method == CASH)
            params['total_credit'] = sum(a.amount_paid for a in attendees if a.payment_method in [c.STRIPE, c.SQUARE, c.MANUAL]) \
                                   + sum(s.cash for s in sales if s.payment_method == c.CREDIT)
        else:
            params['endday'] = localized_now().strftime('%Y-%m-%d')
            params['endhour'] = localized_now().strftime('%H')
            params['endminute'] = localized_now().strftime('%M')

        stations = sorted(filter(bool, Attendee.objects.values_list('reg_station', flat=True).distinct()))
        params['reg_stations'] = stations
        params.setdefault('reg_station', stations[0] if stations else 0)
        return params`

**Comment by kitsuta** [comment]
Well, the report is certainly still broken. Here's the full error:

```
Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 224, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 215, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 239, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 355, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 304, in with_rendering
    result = func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/registration.py", line 711, in reg_take_report
    stations = sorted(filter(bool, Attendee.objects.values_list('reg_station', flat=True).distinct()))
AttributeError: type object 'Attendee' has no attribute 'objects'
```

I expect the report (based on its name, at least) is used by Resource Management.* Or they would use it, if they could.



*The Department Formerly Known As Reg Support
