### ISSUE TITLE
Force password change at first login

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1785]
When we're in on-site mode, admins create admin accounts for other people by actually setting a password rather than emailing a randomly generated one to them.

We should probably have a feature that forces password change at first login, probably with a checkbox which toggles that.

**Comment by kitsuta** [comment]
Whoa, no way. I sit the volunteers down at the station while making the
account and they set their own password. Making them change their own
password is super tedious.

**Comment by bds002** [comment]
I have to agree with @kitsuta on this one, I'm not sure who else is creating other Admin on-site accounts, but My practice is to get to the admin page and let the user type in their own password on site.

**Comment by EliAndrewC** [comment]
To be clear, this ticket was for a checkbox which wouldn't be checked by default.  However, if both Stops and Regdesk say that they don't want or need this feature then I'll just close it as WONTFIX.
