### ISSUE TITLE
Don't let notification bar interfere with menu options

### ISSUE THREAD

**Issue by outlaw-josiah** [magfest/ubersystem#1786]
As a Stops staffer, it's rather annoying to have to exit out of the blue notification bar at the top of the screen (appears after changes) any time I need to access the menu at the top for some reason. Can we make that bar appear elsewhere, or make it intangible?

**Comment by EliAndrewC** [comment]
Strong agree on needing to refactor that.  Regdesk has made similar complaints.  This will definitely change and not be a problem next time around, and I'll keep this ticket open to track that - thanks!

**Comment by outlaw-josiah** [comment]
This got solved a long time ago, closing it out now.
