### ISSUE TITLE
A "Checked In" item on the attendee page would be useful

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1794]
e.g. "Never" or timestamp (local to event)

**Comment by kitsuta** [comment]
FYI, this information is actually printed on the page. It's just not particularly obvious.

**Comment by earl7399** [comment]
Apparently only while AT_THE_CON

**Comment by kitsuta** [comment]
Fixed by https://github.com/magfest/ubersystem/pull/2220.
