### ISSUE TITLE
Saving a group fails if the $$ involved is too big?

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1797]
e.g. amount owed is $4050, try to add comment, get error that "amount must be reasonable"

Please remove arbitrary limit, or make it use the # of badges to guess what might be reasonable.

**Comment by EliAndrewC** [comment]
Whoops!  I'll put this on the top of the list of newcomer tickets.  I'm planning on putting together a task list for the interns this weekend, so this will be somewhere around number 1.

**Comment by EliAndrewC** [comment]
Looks like the hard-coded is here:
https://github.com/magfest/ubersystem/blob/c98f868927450158c3e58d719cfce482fd10ed76/uber/model_checks.py#L67

We should probably just remove that check.
