### ISSUE TITLE
Cannot update attendee record created w/out e-mail @ Fest

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1798]
It requires an e-mail address before saving any updates. It's bad form to require it now if it was not required when created.

**Comment by earl7399** [comment]
buh ... zip code too!!!

**Comment by EliAndrewC** [comment]
D'oh.  That should ALSO be optional in post-con mode, I guess we introduced a bug where it's only optional in pre-con mode.  Should be an easy fix.  I'll put this around the top of the newcomer tasks for our interns, which I'm going to send out this week.

**Comment by earl7399** [comment]
IIRC, you told me it was set up to work in at-con mode, but I'm sure it'll
get sorted regardless.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by EliAndrewC** [comment]
Looks like there are some places in
https://github.com/magfest/ubersystem/blob/master/uber/model_checks.py
where it checks ``c.AT_THE_CON`` but really it should be checking ``c.AT_OR_POST_CON``.  Should be an easy fix.
