### ISSUE TITLE
Volunteers Owed refunds.... - Hours are marked, still on sheet

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1800]
For the third section of this report:
https://prime.uber.magfest.org/uber/summary/volunteers_owed_refunds

There is a staffers that was schedule for 31 hours - so he would have been refund eligible.
He is marked as being in the section as possible eligible for refund if hours are marked.

All hours are marked - however most of them are marked as "Staffer didn't show up"
That should count as a marked shift, just simply ineligible.

Staff in question: Luc Hale.

**Comment by EliAndrewC** [comment]
Closing as a duplicate of #1803 which I thought hadn't already been filed.  MY BAD.
