### ISSUE TITLE
Smaller test data set for Heroku

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#181]
Our current set of test data is too large for Heroku's free database service, which limits us to 10,000 rows per table.  According to their docs, we should keep our tables under 7,000 rows.  So we should keep it to like a few thousand attendees; the Tracking and Email tables will have he most entries, so those are the ones to watch out for.  If we have like 1,000 attendees then that should be fine.

**Comment by thaeli** [comment]
Closing, this is no longer relevant.
