### ISSUE TITLE
failing unit test: TestUnsetVolunteer

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1816]
may require #1815 to be merged first

the following test is failing: TestUnsetVolunteer:test_badge_at_con()

```
(fixture: c.AT_THE_CON = True)

        monkeypatch.setattr(Attendee, 'is_new', False)
        a = Attendee(badge_num=1)
        a._misc_adjustments()
        assert not a.checked_in
```

```
FAILED

self = <uber.tests.models.test_attendee.TestUnsetVolunteer object at 0x7f4d4acd2b38>
monkeypatch = <_pytest.monkeypatch.monkeypatch object at 0x7f4d4aa9ab70>
at_con = None

    def test_badge_at_con(self, monkeypatch, at_con):
        a = Attendee()
        a._misc_adjustments()
        assert not a.checked_in

        a = Attendee(badge_num=1)
        a._misc_adjustments()
        assert a.checked_in

        monkeypatch.setattr(Attendee, 'is_new', False)
        a = Attendee(badge_num=1)
        a._misc_adjustments()
>       assert not a.checked_in
E       assert not datetime.datetime(2016, 4, 29, 13, 17, 29, 364947, tzinfo=<UTC>)
E        +  where datetime.datetime(2016, 4, 29, 13, 17, 29, 364947, tzinfo=<UTC>) = <Attendee full_name=' '>.checked_in

sideboard/plugins/uber/uber/tests/models/test_attendee.py:245: AssertionError
```

**Comment by kitsuta** [comment]
Did this unit test ever work? It makes no sense.

**Comment by binary1230** [comment]
I uh... no idea?  Maybe? I recall at some point all the tests passed.  But beyond that, no clue :)

**Comment by EliAndrewC** [comment]
The purpose of this test is to assert the following behaviors of at-the-con mode:
- a new attendee created with no badge number assigned is NOT automatically checked in
- a new attendee created with a badge number assigned IS automatically checked in
- an existing attendee who already has a badge number who is then saved is NOT automatically checked in

The first two tests are passing, it looks like the third is failing.  I'd need to look into why to have any clue.

**Comment by RobRuana** [comment]
I think I figured this one out... Inside of `_misc_adjustments`, the value of `checked_in` is set like this:
```python
        if c.AT_THE_CON and self.badge_num and not self.checked_in and \
                (self.is_new or self.badge_type not in c.PREASSIGNED_BADGE_TYPES):
            self.checked_in = datetime.now(UTC)
```

However, from the unit test, `self.badge_type` will *NEVER* be in `c.PREASSIGNED_BADGE_TYPES`, so the conditional always resolves to true.

The test passes if you change it to look like this:
```python
        monkeypatch.setattr(Attendee, 'is_new', False)
        a = Attendee(badge_num=1, badge_type=c.PREASSIGNED_BADGE_TYPES[0])
        a._misc_adjustments()
        assert not a.checked_in
```

Which leads me to believe that there is an error in `_misc_adjustments`; namely the `badge_type` clause in the conditional should look like this:
```python
self.badge_type in c.PREASSIGNED_BADGE_TYPES
```

**Comment by RobRuana** [comment]
@EliAndrewC can you take another look at this when you have a chance, I think I see the problem.

**Comment by EliAndrewC** [comment]
> @EliAndrewC can you take another look at this when you have a chance, I think I see the problem.

I see you already made an MR with this change, which I agree is correct.  I believe you've accurately identified the bug.
