### ISSUE TITLE
MAGStock - Shift / Jobs/ Departments, Signups view is erroring out.

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1820]
https://magstock6.uber.magfest.org/uber/jobs/signups?location=105587304

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 179, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 170, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 194, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 278, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 240, in with_rendering
    result = func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/jobs.py", line 71, in signups
    'checklist': location and session.checklist_status('postcon_hours', location)
  File "/usr/local/uber/plugins/uber/uber/models.py", line 453, in checklist_status
    raise ValueError("Can't access dept checklist INI settings for section '{}', check your INI file".format(slug))
ValueError: Can't access dept checklist INI settings for section 'postcon_hours', check your INI file

**Comment by kitsuta** [comment]
Looks like we have a required checklist item. :(

**Comment by bds002** [comment]
Yes? There are Checklist for Stock

**Comment by binary1230** [comment]
belongs in magstock plugin github

**Comment by bds002** [comment]
Just to follow up on Dom's and I discussion about location of tickets/issues. 
Anything that is submitted out of the magstock6.uber.magfest.org instance is going to end up here:
https://github.com/magfest/ubersystem/issues 
The same as this issue. 

So while moving this issue might help for this 1 time, we will still need to check this repository for issues submitted from Stock, unless the "Report a bug" link reference for the instance is changed.

**Comment by kitsuta** [comment]
By 'required checklist item' I mean, we have the code dependent on certain configuration (in this case, it excepts a dept checklist item called 'postcon_hours'). This is generally a Bad Thing.

@EliAndrewC can you comment on the best way to go about fixing this?

**Comment by EliAndrewC** [comment]
> @EliAndrewC can you comment on the best way to go about fixing this?

The short answer is that it requires a fix to the core ``uber`` plugin in terms of the API we use for dealing with the dept checklist.  I agree that this is bad, and it's something I didn't even notice until last year (the year after we started doing the dept checklist), and it's not something that's been high enough priority to fix.  FWIW, I did put it in my "Post-MAG2016 Refactoring" document:

"Our department head checklist currently has some options which are effectively required, in the sense that if you don’t have them, you get an exception when trying to load pages which reference them.  We should update those pages to work if those steps are missing from the config."

:/

**Comment by kitsuta** [comment]
Oh oops. My memory is not great apparently - I should reread that doc.

It sounds then like the most expedient thing to do is to add the 'required'
options to magstock config. Brent, will magstock have a traditional concept
of staffing / hours?

**Comment by bds002** [comment]
Short answer is yes.... We will have shifts and tracking hours etc for Stock. We started it last year in the system, mostly registration and we are trying to do a better job overall of that.

**Comment by kitsuta** [comment]
This was ultimately the same bug as https://github.com/magfest/ubersystem/issues/1860, so it's fixed now.
