### ISSUE TITLE
confirmation emails not sent to placeholder badges that later get confirmed

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1825]
I think this is true, need to test exactly what's up.

It seems that for people who were created as placeholder badges and later fill in their registrations, they don't get a confirmation email.

Some interesting facts about Brent's badge in magstock6 uber:
staffing=true
registered=None
placeholder=False

this seems to slip through the cracks for every kind of badge email.

our question is:
1) should this case be covered by something in automated_emails.py already and it's not, such as:

``` pyton
StopsEmail('{EVENT_NAME} Volunteer Badge Confirmation', 'placeholders/volunteer.txt',
           lambda a: a.placeholder and a.first_name and a.last_name
                                      and a.registered_local > c.PREREG_OPEN)
```

2) if not, should we add a new line for this case?

Also, is registered=None a bug or intentional?

I'm too tired to dig in more tonight

**Comment by binary1230** [comment]
also i should note that for Brent, his badge was created before pregeg opened, so that one check would not catch it.

**Comment by RobRuana** [comment]
Also related to https://github.com/magfest/ubersystem/issues/1709 and https://github.com/magfest/ubersystem/issues/2772
