### ISSUE TITLE
Need to be able to mark a plugin as 'last to load'

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1827]
For the benefit of those who don't want to edit sideboard to get their event running, we need to be able to say within a plugin that it should override other plugin templates, etc.

This was specifically a problem when I installed the badge_printing plugin for anthrocon - its regextra template overrode the one for anthrocon_plugin, causing all sorts of fun problems.

**Comment by binary1230** [comment]
are you familiar with the 'priority_plugins' setting in sideboard?

ours currently is set like this:  
```priority_plugins = uber, panels```

does that solve the issue or do you need something else to happen?

**Comment by binary1230** [comment]
one quick note: this is a sideboard .ini setting, not a uber .ini

**Comment by thaeli** [comment]
I think this request is to provide a method to do this without editing the priority_plugins setting. Problem with doing it within the plugin is that there could still be collisions.. I think the least bad way to handle this is to set the priority_plugins each time.

Would suggest moving this issue to upstream - note that for Anthrocon, which is running on the upstream Dockerized deploy, the development.ini for sideboard is readily available within the quickstart setup.

**Comment by kitsuta** [comment]
Oh! I forgot that very last point - that you could edit sideboard's .ini file in upstream Docker.

Oooops

**Comment by thaeli** [comment]
Closing this for now. Reopen if needed against upstream Sideboard.

**Comment by binary1230** [comment]
oh yea i guess another version of this could be a plugin could say what it's dependencies are, and then sideboard could build a dependency graph and try to resolve the best order in which to load things.

sounds like you guys figured it out though, cool.
