### ISSUE TITLE
As webmaster, I would like a JSON feed of the current ticket price...

### ISSUE THREAD

**Issue by cybersenshi** [magfest/ubersystem#1833]
... so I don't have to change the price on the site frontpage manually at midnight.

Dom adds this link without explaining why: https://github.com/magfest/ubersystem/blob/master/uber/site_sections/registration.py#L952

**Comment by migetman9** [comment]
That file is used by magbot to grab badge prices.

**Comment by cybersenshi** [comment]
That does sound appropriately useful.

**Comment by kitsuta** [comment]
The file doesn't return badge prices, it's only used by the bot to grab badge _sales_ stats (i.e., how many badges sold vs how many are left).

What we need, from a coding perspective, is to slap a new variable into that function that returns the current badge price.

**Comment by thaeli** [comment]
+1, might want to add config for turning those features on/off too.

**Comment by migetman9** [comment]
This issue can be closed as solved by a recent PR. Badge price can be found on registration/stats

**Comment by binary1230** [comment]
real answer:     public-facing websites like ours should use /uber/registration/prices for this
