### ISSUE TITLE
Do we need a special case for common.js anymore?

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1851]
in server.py, we have some special case code for common.js

```python
@all_renderable()
class Root:
    def index(self):
        raise HTTPRedirect('common/')

    def common_js(self):
        cherrypy.response.headers['Content-Type'] = 'text/javascript'
        return render('common.js')

    static_views = StaticViews()
```

Do we actually need that to be a special case anymore, or could that be removed and we just do common.js through ```/static_views/```.  It strikes me that this special case might be around from before we had static_views, which basically does the same thing.

**Comment by binary1230** [comment]
For context: common.js is written using django templates variables, so needs to be parsed as a template.  Nowadays we have StaticViews() which is designed to do exactly that, so it strikes me that we don't need this special-case anymore.

**Comment by kitsuta** [comment]
To be honest... I don't know. What I CAN tell you, however, is that the common_js function definitely existed _before_ any form of the static_views variable. You can see one such commit here: https://github.com/magfest/ubersystem/commit/f9bc9f49979578caf26cc96a9f0c8c275362d0bc

**Comment by kitsuta** [comment]
This is an @EliAndrewC question, I think.
