### ISSUE TITLE
As the person who orders supporter swag, I need a supporter count

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1861]
Used to be on the /summary/ page, however, 'Supporter' isn't a badge type anymore so it doesn't work.

A workaround is you can get a count by going to /uber/summary/printed_badges_supporters to get a CSV and use that, but a report would be nice.

**Comment by bds002** [comment]
@cybersenshi This count is available at the bottom of:
c.event_name.uber.magfest.org/uber/summary/affiliates

https://labs.uber.magfest.org/uber/summary/affiliates
https://super2016.uber.magfest.org/uber/summary/affiliates

**Comment by kitsuta** [comment]
@binary1230 Is the link provided good enough?

**Comment by binary1230** [comment]
I think, as long as @cybersenshi or @nickthenewbie1 think it is

**Comment by nickthenewbie1** [comment]
Yes, that's the page that I use.
