### ISSUE TITLE
Stock Uber, can't see band's W9s

### ISSUE THREAD

**Issue by StephPrader** [magfest/ubersystem#1863]
Hi! I need to get to the W9s in the Band Plugin please. I can see that they uploaded them, but the link isn't there to click on to view them. It was there in M2016's Uber, for reference.
Thank you!
Steph

**Comment by StephPrader** [comment]
Or if ya wanna save time to bother coding it, then just send me what's there in an email. Honestly, there's only 3: Insane Ian, Thrillerkiller, and Gunblade X. Once I get them I'll never look at it again, so maybe don't bother so you can concentrate on more important stuff.
Steph

**Comment by binary1230** [comment]
tech info:
found the bug, it's band.taxes.completed now, we had it as band.taxes.completed_w9 which is always false.  testing a fix since I'm in the neighborhood

**Comment by StephPrader** [comment]
Thanks Dom! I'll wait for the deploy. ^_^
Steph

**Comment by StephPrader** [comment]
Do you think this will deploy by noon tomara/Thurs? I want to print the checks and I need to make sure the name on the check is correct first. Thanks!
Steph

**Comment by kitsuta** [comment]
This is merged and deployed now.
