### ISSUE TITLE
README.md setup instructions create a superuser database user, is that what we want?

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#188]
I think it might be insecure to have our postgres user setup be superuser, we probably should look into that and put the instructions in instead to create a user with the correct permissions.

**Comment by thaeli** [comment]
No longer relevant

**Comment by binary1230** [comment]
This is still a concern as puppet creates users this way

**Comment by binary1230** [comment]
alright with the ability to run multiple copies of uber on the same server removed, and with eventual migration to docker, yea let's kill this one.
