### ISSUE TITLE
is this dead code? preregistrationn/badge_choice()

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1889]
In preregistration.py() there's a function called badge_choice() which seems to not be referenced by anything and doesn't have a template associated with it.  Is this just dead code?

```
@check_if_can_reg
    def badge_choice(self, message=''):
        return {'message': message}
```

**Comment by kitsuta** [comment]
Ah, yea, remember when we had a 'splash' page for Registration that let you select your badge type? This is from that. It is safe to remove.
