### ISSUE TITLE
Add ability to Export / Import Staffing Shifts

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1893]
Year over year each DH creates a Shift schedule for their event.
For MAGFest Laboratories, the shifts should be similar to MAGClassic shifts, I would like the ability to Export the shift schedule from MAGClassic into the MAGLabs Uber instance.

https://labs.uber.magfest.org/uber/jobs/

This should a per department option to export and then import the information.
I feel like this is something that I wrote up before, but I wasn't able to find it.

**Comment by kitsuta** [comment]
This is also covered by https://github.com/magfest/ubersystem/issues/1844
