### ISSUE TITLE
Add fields for preferred name vs legal name

### ISSUE THREAD

**Issue by ShevaDas** [magfest/ubersystem#1894]
As a user whose legal name does not match my preferred name, I would love to be able to put both in Uber—legal name for hotel requests, preferred name for use all other places.

**Comment by thaeli** [comment]
+1 and also +lots - note that this is distinct from Badge Name!

**Comment by kitsuta** [comment]
I'm not super sure what you mean by 'hotel requests.'

For MAGFest's purposes, we use the legal name for checking folks in. We don't _exactly_ have a use-case for recording a preferred name on the admin side (at least, from Registration's POV). That being said, I can totally see it affecting other core features (like searches) and possible plugins/extra features, so I still think it's a good idea.

Probably the best way to implement it UI-wise is to have a link under the Legal Name field that says "Most people know me by a different name" that, when clicked, shows the extra Name field.

**Comment by ShevaDas** [comment]
I should have clarified a bit more, there are three-ish use cases here: one for general attendees (the UI for which you described in your comment), one for MAGFest staffers (presumably the same UI as attendees, legal name is also necessary for hotel room requests), and one for Uber admins (where legal name shows up in various places in the admin interface, like in the top right corner).

**Comment by kitsuta** [comment]
Oh yeah that's a good point, I completely forgot that we added admins'
names to the interface. So that'd definitely be another place in core RAMS
where we'd use a display name.

**Comment by khyperia** [comment]
I took an attempt at implementing this, and ran into some issues - so I'm documenting them here in a request for thoughts/etc.

**Places where preferred name is useful:**

* The volunteer pages repeatedly display a name everywhere, and need it for log-in.
* Most (all?) emails that go out start with a name. This includes group emails for things like room assignments - openly stating someone's legal name to their roommates is a problem. (This is different from sending legal name to the hotel reservation system)
* User search/etc. is broken without preferred name - for example, if someone tried to find me using my actual name (which I use in most places, including IDs that I'll be carrying), they wouldn't be able to find me.

**My first attempt:**

* Add a preferred_name column to the database
* Map the first_name and last_name to legal_first_name and legal_last_name (in Python, not renaming the actual database columns, to reduce migrations)
* Change full_name to first check preferred_name, and if that isn't present, use legal_first_name and legal_last_name
* Add legal_name similar to full_name but skips the preferred_name check and just gives the legal first/last name.

However, this ran into some issues: *many* places in code use first_name and last_name in unrelated ways, for example, checks to see if the record is valid or form parameters are sane. Also, there's a lot of random places that need a lot of thought to update - for example, the reg discount page uses first and last name as a user-inputted key to identify a user, which isn't clear how that should interact (it at least needs *some* modification). This makes the work needed excessive and results in a huge/unacceptable diff.

**My thoughts:**

* Add a legal_name DB column that defaults to `first_name + " " + last_name`, and use it very selectively where needed.
* As first_name and last_name are no longer used for legal purposes, they may be used for whatever (i.e. preferred name)
* Don't touch anything else.

This has the downside that users can't update their preferred name (first_name and last_name) whenever they feel like it (at least I'd guess so - mostly wishy-washy concerns about security and no stable identity). However, as preferred name isn't that common of a use case (although it's a very important one), having manual (admin?) updates doesn't seem too bad. I'm unsure of that, though.

---

Thoughts on the above?

**Comment by ShevaDas** [comment]
One quick thought: users can't update their legal name whenever they feel like it right now, so I don't think restricting updating preferred name is a huge issue.

**Comment by migetman9** [comment]
The discount page might actually be unnecessary once we merge in the new promo code stuff.

**Comment by khyperia** [comment]
@migetman9 that was mostly just an example of a change that made it impractical to update things in that way - some other things that came up while I was trying to implement it include:

* searching, with extremely strange logic with what exactly a comma means and intricacies of how names combine (all specific to English)
* an *incredible* amount of places that check `attendee.first_name == ''` to check if an attendee is assigned. Similarly, if form parameters contain 'first_name', etc.
* Dealer owner names
* Sorting results of various things by last name

and lots more similar things - while each change isn't too in-depth or problematic, it'd take more than a few days to fully update everything. Seeing as MAGFest is coming up quick, it'd be really, really nice if updating didn't take a month for all the code to be worked out.
