### ISSUE TITLE
test_data.sql contains hardcoded m13 database name

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#190]
minor thing

test_data.sql contains 'm13' hardcoded inside it.

```
ALTER TABLE public."Account" OWNER TO m13;
```

**Comment by thaeli** [comment]
At this point, we should probably just remove the test_data.sql file entirely. It doesn't work anymore.

**Comment by EliAndrewC** [comment]
Yeah, this was always just intended as a shortcut for my own use, but then people started using it and it wasn't well documented or well supported, so it's probably better to just get rid of it.

I do need to fix the test data import though.  And set up Travis to run that import and run the unit tests automatically so we can more easily keep an eye on it.

**Comment by kitsuta** [comment]
As far as I can tell, this SQL file is long gone.
