### ISSUE TITLE
As an event that might sell out, I want to raise the badge price after a certain # of badges sold

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1906]
If I don't sell to the badge limit specified, I want the badge price to increase after certain dates like it currently does. So, for example, I want to say that "the badge price should increase to $50 either after 5000 badges have been sold or after September 1st."

The slightly tricky thing here is that we never want a badge price to _lower_ again, but (unlike dates) the 'number of badges sold' is something that can change.

The more 'fool-proof' way to do this is to store the badge price in the database, and only update it if the update is an increase. However, we can alternatively use the "Refunded" status as part of the 'badges sold' calculation, and trust that admins will actually correctly use the system and not just delete badges willy-nilly. I don't really want to store the badge price in the database, but... admins and data integrity don't always mix.

**Comment by earl7399** [comment]
​... yeah ...​

On Sat, Jul 23, 2016 at 10:49 PM, Victoria Earl <notifications@github.com>
wrote:

> trust that admins will actually correctly use the system




--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086
