### ISSUE TITLE
As a Music Head, I need a way to unmark bands in the band pluggin

### ISSUE THREAD

**Issue by pelololoquin** [magfest/ubersystem#1912]
![image](https://cloud.githubusercontent.com/assets/7318559/17254078/469602ee-5581-11e6-89ff-c0ef77a19577.png)

Accidently marked a vendor as a band when I went to set up a new band and now I cannot find a way to unmark them as a band. Vendor name is alicia's anime.  I don't think they'll put on a good show.

**Comment by migetman9** [comment]
Have attempted to solve. Made [PR](https://github.com/magfest/bands/pull/53)

**Comment by kitsuta** [comment]
PR https://github.com/magfest/bands/pull/53 was merged some time ago, so this should be fixed now.
