### ISSUE TITLE
Display textual description of badges remaining in current price tier on pre-reg page

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1943]
If someone is purchasing an attendee badge, the following text should be displayed above the badge type (single/group/child) buttons (not inside the buttons):

"Current availability of badges at this price: [High|Medium|Low|Extremely Low]"

Those descriptions are based on the following criteria
High: 75% - 100% available at current price
Medium: 25% - <75% available at current price
Low: 10% - <25% available at the current price
Extremely Low: <10% available at the current price.

Availability keyword should be color coded:
High - Green
Medium - Yellow
Low - Orange
Extremely Low - Red

This calculation should be done server side, and baked into the rendered page text, so that the end-user is unable to view the current number of badges available at that tier.

**Comment by earl7399** [comment]
After looking at the code, I'm saying that this one's a bit over my head.
Or a mile.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by binary1230** [comment]
nick and I talked about the idea of instead of doing this, just linking the text "no later than" to magfest.org/faq or whatever where it explains the tiered badge threshold stuff

**Comment by nickthenewbie1** [comment]
http://magfest.org/faq#-KOpcFnNhdsUIqvvf6VB

**Comment by kitsuta** [comment]
Hilariously, that's actually:
1. Really tricky.
2. Bad UI, because clicking the button selects it.

I think maybe we're best off adding some help text below the reg-types form group.
