### ISSUE TITLE
integrate puppet with vagrant

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#196]
After you run ```Vagrant Up```, we'll ```apt-get install puppet``` and then ```puppet apply``` to let puppet handle all the rest of the config for postgres, db, uber install, Db init. everything, same as production servers.

We'll have to think carefully since at least some of the puppet stuff currently resides in a private repo.

**Comment by thaeli** [comment]
this is implemented in the ubersystem-deploy repo
