### ISSUE TITLE
optimization: move /uber/static_views/magfest_js out of StaticViews

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1972]
I was looking into the idea of aggressively caching /uber/static_views with nginx, however, we have a javascript file in there called /uber/static_views/magfest_js which dumps config values out for use in angular apps.

If the URL was changed to not be /static_views/, we could cache that dir more heavily

**Comment by binary1230** [comment]
alternatively, we could differentiate Config() so that it contains only purely static data calculated once at startup (from the config file and from data derived from it), and put more dynamic data (like c.BADGES_SOLD) into another class somewhere.  I know @thaeli looked into separating that out as part of the configDB work

**Comment by kitsuta** [comment]
Yeah, having separate objects for dynamic and static config was definitely a long-term goal.

**Comment by binary1230** [comment]
i did go ahead and fix just this one for now by moving magfest.js out of static_views
