### ISSUE TITLE
Price going up causing issues for people who paid lower price already

### ISSUE THREAD

**Issue by Strrgzrrshawano** [magfest/ubersystem#1981]
People who check the status of their registration are seeing notices to pay more. Examples: 
Single attendee:
Screen shots in ticket show issue, but attendee is seeing $5 more payment expected: https://magfest.supportbee.com/tickets/9673266

Group payment: 
Uber history shows expected payment amount increasing, after payment already recieved based on sent e-mails: 
https://super2017.uber.magfest.org/uber/registration/history?id=3f0e6ea5-af0d-4eff-REMOVED
Mentions seeing option to pay $100 more (second issue:) 
https://magfest.supportbee.com/tickets/9673347

**Comment by binary1230** [comment]
Hey, quick note don't post attendee id's in github, tha confidential stuff.  Thanks for the report we'll check it out asap

**Comment by binary1230** [comment]
I removed the id
