### ISSUE TITLE
Viewing a Child badge on the admin side is confusing

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1988]
What I expect:
Clear indication that the badge is either discounted, or free, and that it is paid for (if free, or actually paid for)

What happens:
At the top, it says "Unpaid Minor" - implying they owe money.
In the Badge Price section, it auto-calcs the badge price as the current price as of badge creation, and says they haven't paid even though birth date makes them under 6 (and says so: "(Under 6)")

**Comment by kitsuta** [comment]
Just checked this in staging4, and we have since fixed this bug -- a new child badge is marked as need not pay by the system.
