### ISSUE TITLE
Group badge limits need spelling out on the purchase page

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1989]
What I expect to happen:
When I go to purchase a group of badges, I need to know what the lower and upper limits are for this purchase, as well as for later additions.

What happens:
The Group Leader button is clear that the minimum # is 8, but doesn't specify an upper limit.
The information about later purchase of badges for the same group is not available on this page or any popup linked from it.

**Comment by RobRuana** [comment]
Is this issue really closed, or was the fix actually for #1541?

There is still no mention of any upper limit (other than the fact that the dropdown only goes to 100).

Also, we don't actually disallow someone from purchasing more than 100 badges in a single group on the backend. A sneaky attendee could manually POST a value greater than 100.

**Comment by kitsuta** [comment]
Whoops, you're right!

Is there actually an upper limit on attendee groups? If someone wants to pay us several hundred dollars for an attendee group, is there a reason to disallow that?

**Comment by RobRuana** [comment]
Actually, I don't think we care. I just checked with Nick and he said in the rare case someone tricked the system like that, it would be immediately apparent.

So... I think we could probably close this?
