### ISSUE TITLE
A payment screen will sometimes say $0.00, should offer ability to pay it

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1995]
What I expect to happen:
If I manage to get to a payment page (e.g. https://super2017.uber.magfest.org/uber/preregistration/attendee_donation_form?id=SOME.VALID.ID) but don't owe any money, I should be told that and not presented with a "Pay With Card" button

What actually happens:
I see a message like this:
"Extra Payment for SOME PERSON
Thanks for offering to kick in money to help make MAGFest better. As thanks, your total donation (of which $0.00 is outstanding) entitles you to the following:"

The screen has a "Pay With Card" button that unsurprisingly invokes the payment processor.

**Comment by binary1230** [comment]
same bug as https://github.com/magfest/ubersystem/issues/1987

**Comment by RobRuana** [comment]
Yup, this has been resolved 😄
