### ISSUE TITLE
feature request: setup screen

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#202]
as a new unfamiliar user of a newly installed ubersystem, I'd like to see a setup screen that asks for stuff like:

What is the date of your event?

And then based on that, picks some sane defaults for stuff like #days til prereg closes, #days til the price hike happens/etc.

This could be a dedicated 'install' screen or it could just be an options screen you can get to from inside ubersystem.

**Comment by binary1230** [comment]
this task has certainly changed a lot and looks very different with our new deployments and stuff, doesn't it? :)

**Comment by EliAndrewC** [comment]
Ha, indeed!  I'm gonna marked this as closed since it's been obviated by our new puppet deploys and such.
