### ISSUE TITLE
Session.auto_badge_num() can cause an infinite loop

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2020]
I observed and reproduced our production code going into an infinite loop in Session.auto_badge_num().

I was able to extract the local stack variables from the running uber instances and create a reproduction case where this happens.  That code is available here: https://gist.github.com/binary1230/0aca608b8b16f9d781d07105d1ee1a34

Expected: no matter what input is thrown, the function returns
Actual: function goes into an infinite loop and never returns

This is a high priority bug as it can cause server deadlocks as detailed in https://github.com/magfest/ubersystem/issues/2017

**Comment by binary1230** [comment]
real quick, other suggestion: in addition to fixing the algorithmic problem here, we should also implement some kind of safety check where if the loop has gone through N iterations (where N is some sufficiently large number, like 1,000), then we raise an exception to break out of the loop.  

stuff in _presave_adjustments HAS to finish running _at all costs_ so that we can release ```c.BADGE_LOCK```, or else the entire server will stop responding.

The only problem with throwing an exception here is that it will get eaten by ```@swallow_exceptions``` because we must NEVER propagate exceptions upwards.  So the end user won't see it, won't know that badge numbers didn't actually get shifted, and we'll only have a logfile message (which will be caught by magfest reporting tools so at least we will see it there).

That alternative, crappy as it is, is still way better than not being able to release c.BADGE_LOCK, so I think we should implement it.

**Comment by binary1230** [comment]
sidenote: is it possible to replace our binary search code here with an off the shelf implementation? something like http://stackoverflow.com/questions/212358/binary-search-bisection-in-python

**Comment by kitsuta** [comment]
Unlike most binary searches, we're not searching for a specific value - we're searching for a gap in a list of sequential numbers, if such a gap exists. Since that's the inverse of what `bisect` does, I didn't think we could use it.
