### ISSUE TITLE
Lack of information about groups in Feed of Database Changes, no History page

### ISSUE THREAD

**Issue by Strrgzrrshawano** [magfest/ubersystem#2038]
As simple as the title states, there is no history page for a group itself, only each individual within a group. In addition, the FoDC only seems to show creation and page views, not updates of anything with particular members of the group. Specifically the reason this was sought this time is that there was no way to check via the 'group' information regarding deletion of a badge by an admin, but other reasons are possible. If nothing else information in FoDC would be necessary, but a history page for groups would also be useful.

**Comment by earl7399** [comment]
See also https://github.com/magfest/ubersystem/issues/1654, https://github.com/magfest/ubersystem/issues/770, https://github.com/magfest/ubersystem/issues/1006
