### ISSUE TITLE
MIVS Judges should be created as comped attendee badges, not staff.

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#2060]
Currently the judges are created as staff badges and get confused when it comes to all the staffing emails that go out about the event.  In discussing things with Tronster and the MIVS team, a fair number of the MIVS Judges aren't doing anything at event, and don't need to be Staff (In the sense of food, hotel space, shifts etc etc).  They should be created as Attendee's with comped badges for their work as a judge.  They are created following the link found at: https://super2017.uber.magfest.org/uber/mivs_admin/create_judge

If any of them decide they are coming to MAGFest then Tronster and his team can change their badge to Staff (or reach out to the Staff Ops team and they can change the badge).

.

**Comment by RobRuana** [comment]
This has been fixed!
