### ISSUE TITLE
Department Head Checklist - DH in Multiple departments

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#2061]
Every year we have DH's that get assigned or assign themselves to multiple departments. 
Current coding for the DH Checklist is that it only applies to DH's that are assigned to 1 department.

I would like us to look how best to change that function. 
Maybe on: https://super2017.uber.magfest.org/uber/dept_checklist/index
If a DH is assigned to more then 1 department they get a screen/drop down box that ask which Department they are filling out the checklist for.  This would allow them to pick which department they are working on at the time.

I am sure there is more to the background code than just the one page and @EliAndrewC  would know best, but this might be a step in the correct direction.

**Comment by jcooter** [comment]
There are two potential solutions to this problem as I see it.  The first is to add the drop-down as @bds002 suggested.  However, the more common scenario seems to be that someone is a head in one department, and a staffer/manager in another department.  With that in mind, the other way to solve the problem would be to tie the DH status to a specific department (e.g department head of techops, vs just department head).  This would potentially solve other similar conflicts throughout the codebase.

**Comment by binary1230** [comment]
I too second the concept that DH status is per-department.  The perhaps most correct but also perhaps a little too overkill way to do this would be to remove the DH ribbon as a demarcation of being a dept head, and instead add a new field that is 'Dept head in the following departments' like we do for assigned and trusted depts.

**Comment by jasonspriggs** [comment]
This could be solved by making departments "groups" that you're assigned to at a particular access level?
