### ISSUE TITLE
can multiple email daemon tasks be running at once?

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2064]
We run our email daemon code once every 5 minutes. (300 seconds)

Every time we run the email daemon code we (at minimum) iterate through every attendee in the DB and iterate through every email category on that.

our email daemon code calls sleep(0.01) each time we have run every email category against each model instance order to not eat up too much CPU.

So, minimum runtime for a fully loaded uber database of 20k attendees is (assuming everything else processes instantaneously, which it probably doesn't):

20k attendees \* .01 delay = _200 seconds_.

Which means if our email daemon takes more than 100 seconds to process anything else (which is entirely possible), then we could have another instance of send_emails() kicking off and have two of them running at the same time.  (this could explain some behavior we have seen onsite last year where the uber instance takes up a ton of CPU onsite).

It might make sense to implement some kind of alternative scheduling mode for DaemonTask so that instead of starting a new thread every 300 seconds, we just keep track of how much time has passed since the last run() and make sure that if it's over 300 seconds, we kick another run() off.  That way, there's no chance we could have overlapping run()'s.

I added an `@timed` decorator to a recent PR so at least we should be able to see in the logs if this is happening.

**Comment by binary1230** [comment]
update: should be not possible originally, and now really really not possible with an extra lock added to the automated email sending class

https://github.com/magfest/ubersystem/pull/1896/files#diff-c13fe7f0b04f6c3982c8398c73240256R196

**Comment by EliAndrewC** [comment]
BTW, this is also not possible because of how ``DaemonTask`` is implemented; if you say ``interval=300`` then that means there will be a 300 second interval between one iteration finishing and another starting.
