### ISSUE TITLE
[Sep 16] MIVS round 2 submissions link not present

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#2066]
This is mainly for @EliAndrewC, unless others have knowledge of this process.
The MIVS round 2 is now open and part of that states that: "Round 2, the final round, requires your team to submit your game in a playable form or a demo version of your game for the judges to play. You may submit your demo by continuing your application at"

There is a link in the email that the Indie's that passed round 1 received, but no where on the linked page does it give them directions on how to upload the Game or a way to submit the game.

**Comment by EliAndrewC** [comment]
There's an ``allow_game_submission`` config option that someone will need to set to ``True``:
https://github.com/magfest/mivs/blob/master/mivs/configspec.ini#L5

I can't do this from work, but I can do it this evening if @binary1230 or someone doesn't get to it first.

/cc @bds002 @kitsuta

**Comment by bds002** [comment]
There is probably more to it than what I did, but would:
https://github.com/magfest/mivs/pull/58 work in the short term?

**Comment by EliAndrewC** [comment]
Yes, that would get the job done for now, and we can properly puppetize things later.
