### ISSUE TITLE
Making a group free does not Complete the badges inside the group

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2074]
Steps to reproduce:
1. Create a group intended to be a free group, but don't make it free to start with.
2. Register group members via the group page - these badges are marked as "New" because the group owes money
3. Change the 'group owed' price to $0, making the group free

Expected behavior: now that the group is free, the badges inside the group should be marked as "Completed"

Actual behavior: the badges in the group are not updated unless you explicitly save them.

**Comment by binary1230** [comment]
sounds like a great case to write a unit test to show this bug, then when the test fails, fix the test by fixing the group code

**Comment by EliAndrewC** [comment]
FWIW, even after we fix this change, we'd still have a bunch of legacy badges in this invalid state, so I just fixed that like so:

```python
>>> for g in session.query(Group).filter_by(cost=0, auto_recalc=False):
...   for a in g.attendees:
...     a._status_adjustments()
... 
>>> session.commit()
```

I'll go ahead and add something similar into the code with a unit-test-then-fix and then open a PR later tonight.
