### ISSUE TITLE
As an admin, I want the no_cellphone box to be visible even for Dealers

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2075]
Right now, the "I don't own a cellphone" box is hidden for dealers (usually, people with Shopkeep ribbons). This is fine for the confirmation page, but in some cases an admin will want to override the system's requirement for a cellphone number, such as in cases where staff get "Shopkeep" ribbons without actually being vendors. Therefore we should show the checkbox on the `/registration/form` page no matter what.

**Comment by DataFighter** [comment]
Still working this.

**Comment by DataFighter** [comment]
so we should close this now
