### ISSUE TITLE
As a badge manufacturer, I want a CSV of 2017 data to print on the badges.

### ISSUE THREAD

**Issue by ShevaDas** [magfest/ubersystem#2100]
Our badge types, quantities, and variable data for 2017 are:
- Attendee badge: 21000, barcode, badge #
- Guest badge: 600, barcode, badge #
- Minor badge: 1500, barcode, badge #
- Staff badge: 1000, barcode, badge #, badge name

- Supporter: NOT A BADGE & manufactured separately, just badge name

PLI (our manufacturer) requests that titles are added to the spreadsheet identifying each column. Doing this manually isn't a big deal but if the export script could be tweaked to add this, that would be ideal.

PLI also requests separate tabs in the spreadsheet for each badge design. Since CSVs don't have tabs, I think we're safe to just send them separate labeled files, but documenting here in case an Excel export is ever considered.

**Comment by binary1230** [comment]
working on this
