### ISSUE TITLE
Seperate Staff shirts from Volunteer shirts

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#2101]
On this page: https://super2017.uber.magfest.org/uber/summary/shirt_counts
We list all free/eligible shirts, along with other options.

We need to ability to separate out c.staff shirts from c.attendee_volunteer shirts
and show those as two separate values.

@binary1230 said to ping him here since he had some technical information to add.

**Comment by binary1230** [comment]
Brent's trying to work on staff (not volunteer) shirts to get accurate counts

I think we'll probably need to make a new version of ```Attendee.gets_free_shirt()``` (which is for free swag shirts given to any staff/volunteer with enough hours) and have a new like ```Attendee.gets_staff_shirt()``` which is for staffers getting a 'magfest staff shirt' (which is a new concept that we haven't done)

The new function probably will be for only staff i.e. 2nd year volunteers and not volunteers, @bds002 to verify

**Comment by bds002** [comment]
Correct - It's just those with a Staff badge for this year.

**Comment by binary1230** [comment]
some more info about this change is available in https://github.com/magfest/ubersystem/pull/2173

**Comment by binary1230** [comment]
2017 update:

I _BELIEVE_ this bug should now closed.

There are 2 different shirt reports now:
1) Shirt manufacturing report, which is supposed to show you exactly how many a) swag and b) staff shirts you need to order, taking into account staff get 2 staff shirts sometimes.  The goal with this page is that the user should be able to export it and send directly to the manufacturer without any modification or massaging of data.  as of this writing, I believe this report to be fully functional and ready to go.

2) Shirt sales by week report, which is not used for manufacturing but for gathering statistics about frequency of sold shirts and sizes.  This report is older and shouldn't be used for manufacturer.  This is the data on that report:
 * 'Free Swag Shirts'
 * 'Paid Swag Shirts'
 * 'All Swag Shirts'
 * 'Staff Shirts'

**Comment by binary1230** [comment]
I'm going to close this because I think it's fixed.  It's probably worth testing if anyone has any doubts
