### ISSUE TITLE
As a registration lead, I want to be able to resend bounced emails.

### ISSUE THREAD

**Issue by ShevaDas** [magfest/ubersystem#2104]
(From Sean) Bounced emails continue to be a bane of MAGFest registration with the majority of them occurring when the rush on tickets happens. Currently the process to handle a bounced email is to assign it the Bounced Email Holder in SupportBee, someone then determines the typo, corrects it in Uber, corrects it in the SupportBee ticket, adds the name, changes the subject, copies and pastes the HTML message from Uber to SupportBee, deletes the bounced crap, sends the email, and archives the ticket. 

If we have a link next to the email in the person's history that allows us to resend the email this would be helpful. Then once the correct email is determined we can save it in Uber, click the link which would resend the email to the new saved email in Uber, and just delete the SupportBee ticket.

**Comment by binary1230** [comment]
I think we're close to getting this done in https://github.com/magfest/ubersystem/pull/1990, which I was going to work on after I finish #1896 

We'll need to double check that we're actually solving this particular use-case, and not just re-sending old emails with the wrong email and text in them.

**Comment by binary1230** [comment]
I closed out #1990 in the interest of uncluttering our list of PRs, but if someone wanted to work on this I would recommend resurrecting #1990 from the dead and starting there.

**Comment by kitsuta** [comment]
Update: We had to spend today fixing unit tests, I did other PRs in the meantime. I'll get these unit tests written up tomorrow!
