### ISSUE TITLE
As someone working in Registration, I need group prices to work sensibly again

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2108]
I implemented a 'quick fix' for groups to freeze their prices in place after we realized that bucket-based pricing was trying to charge people extra money every time we reached a new pricing tier. This fix caused a lot of problems with group behavior, though: The group recalculation checkbox no longer works as expected, adding group badges to a group always increases the group's price, and in general it's a huge, confusing mess. This cause a lot of problems at MAGLabs and will be a never-ending headache at MAGFest 2017 if we don't untangle it.

I'm still thinking of the best exact solution. Suggestions welcome.

**Comment by earl7399** [comment]
My best ideas involve adding info to the DB - specifically, storing
original badge price, exact purchase date/time (I think this is already
stored), bucket size @ time of purchase - any/all of these would combine to
help determine exactly what a badge should cost. Other things that might
help (if we don't already have them at hand) are: whether or not a badge
was created in a group (versus added to it), original group membership
(these two *might* combine).
Another thought - do we actually track the discounts available, and which
(if any) are applied? We might want to consider doing so - even if our
policy is to limit to *one* discount per badge, we have these (that I know
about) to sort through: group discount, at least two age-related discounts,
comps for a *multitude of reasons* (that we don't actually make any effort
to track, AFAIK), and the up-coming discount-code. It really seems like
from an accounting POV, it might be good to have a table of discounts that
we can add to (never deleting from), and point into that table to get a
discount (position NULL or ZERO would be no-discount).

I'm afraid I don't have any easy-to-implement ideas. EVER.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086
