### ISSUE TITLE
As an admin, I want to see if an attendee has an admin account

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2119]
As an admin, if I have Account Management permissions, I want to be able to look at an attendee's details page to see 1) if an attendee has an admin account and 2) what permissions they have.

As we get more people with restricted admin accounts, it is going to be harder for Registration staff to tell or know if the attendee they are dealing with has admin access. It would be very helpful if they could see an attendee's admin account if they're looking at their details page, rather than having to go into the Accounts management page.

**Comment by migetman9** [comment]
Implemented
