### ISSUE TITLE
Grid Lines in changelog feed

### ISSUE THREAD

**Issue by ShinRaActual** [magfest/ubersystem#2139]
Older uber iterations had gridlines for data cells in the "list of changes" feed, which appears to have gone missing at some point.  The lack of any spacing or gridlines makes it difficult to determine where data from one cell ends and another begins, particularly for larger changes (new badge creation, for example)

**Comment by binary1230** [comment]
hm I noticed that the other day too, I wonder what happened to them

**Comment by binary1230** [comment]
will check in a while if everything else is calmed down

**Comment by kitsuta** [comment]
The bootstrap refactor happened. It improved the UI for a lot of things,
but some pages weren't actually converted due to the scope of the work, so
they got kinda ugly.

**Comment by kitsuta** [comment]
Whoops! This hasn't made it to MAGFest's master yet. Reopening,
