### ISSUE TITLE
BIG: attendee.amount_unpaid is incorrect with extra donation

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2140]
To repro this:

1) Register an attendee with normal badge ($70) and extra donation amount of $77. 
2) Pay with Stripe $147
3) Click 'confirmation link' on the screen after you purchase the badge

EXPECTED:  Don't owe any money

ACTUAL:

![image](https://cloud.githubusercontent.com/assets/5413064/20548910/72fce530-b0f5-11e6-992d-2f436d0f5096.png)

---

relevant code:

```You've registered for {{ c.EVENT_NAME }} at a {% if attendee.overridden_price %}discounted{% endif %} price of ${{ attendee.overridden_price|default:attendee.badge_cost|floatformat:2 }}{% if attendee.amount_extra %} and you've also kicked in ${{ attendee.amount_extra|floatformat:2 }}{% endif %}; your total outstanding balance is ${{ attendee.amount_unpaid|floatformat:2 }}.```

going to look into it

**Comment by binary1230** [comment]
was able to repro this locally. will check into it

**Comment by kitsuta** [comment]
Yeah I messed up :\

This is actually an issue with code in https://github.com/magfest/magprime, specifically: https://github.com/magfest/magprime/blob/master/magprime/models.py#L34

Good news is, it's a super easy fix. I literally just forgot to account for the "extra donation" when setting the overridden_price.

**Comment by kitsuta** [comment]
Fixed by https://github.com/magfest/magprime/pull/167.
