### ISSUE TITLE
As an attendee with a legal name I don't use, I don't want it printed even if my badge name is blank

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2146]
Right now when printing Staff badges and personalized swag, we use an attendee's full name if their badge_printed_name is blank:
https://github.com/magfest/ubersystem/blob/master/uber/reports.py#L43

This makes a lot of sense, and we generally don't want to just issue people blank badge names, but we also _explicitly_ say that we won't do this on https://super2017.uber.magfest.org/uber/static_views/legal_name.html. "Your legal name is for internal use only and will not be printed on public materials (e.g. badges, swag, etc)."

I'm not totally sure how exactly we want to handle it, but we should at least warn people that their legal name will be printed if they don't provide a badge printed name. And of course, when https://github.com/magfest/ubersystem/issues/1894 is implemented, we'll want to use that before we use the full name.

It's fairly unlikely that people who don't want their legal name on their badge will also not fill in the badge printed name, but safe > sorry.

**Comment by migetman9** [comment]
We should send out an email to everyone in the user base that says something along the lines of, "We have decided in an effort to protect the information of our attendees to replace everyone's name with a default pseudo-name. If you would like to pick your own name to be placed on any public facing documents, please do so within 7 days."

Then add a default to the badge_printed_name for a pseudo-name, and write a one-time use function on a random page that will check and change all blanks to a pseudo-name. We can rip out the function after of course. 

Need to make sure to individually contact if necessary each supporter, as to not write a dumb pseudo-name on anything personalized.

**Comment by kitsuta** [comment]
Hm. Hmm.

I filed this issue mostly as a thing to remember for next year -- keep in mind that we have been doing the export this way for probably as long as we've had personalized badges. I would say that the current functionality is something a lot of people depend on (myself included).

Also I noticed this right (I mean literally 1 minute) before the badge_printed_deadline, which is a hard deadline because that's when we need to get staff badges out to the manufacturer. So we can't change that data. And we have about a week before we planned on closing Supporter registration, too.

**Comment by migetman9** [comment]
I was hoping to not change the data for this year, but to begin the work to affect all future years.

**Comment by kitsuta** [comment]
@BlueHat-GURU fixing this for the event won't help -- we've already ordered the badges. :(

**Comment by BlueHat-GURU** [comment]
Noted.

**Comment by kitsuta** [comment]
This is now fixed by #2350 -- the first and last name are still used if your badge name is blank, but those no longer have to be your legal name.
