### ISSUE TITLE
display a user friendly error if trying to confirm a badge that doesn't exist

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2149]
visit /uber/preregistration/confirm?id=[valid_hex_string_that_no_longer_exists_in_db]

expected: nice error: "we couldn't find any attendee with this ID in the database"
actual: unhelpful and confusing stacktrace

**Comment by binary1230** [comment]
also this is spamming up my error reporting logs :)

**Comment by migetman9** [comment]
This is fixed with PR #2127 please merge it. I want this issue count # to go dooooown.
