### ISSUE TITLE
View Schedule link still targets MAGLabs Guidebook

### ISSUE THREAD

**Issue by ShinRaActual** [magfest/ubersystem#2177]
Clicking "View Schedule" in Uber is still bringing up the MAGLabs Guidebook, rather than the M15 schedule-in-progress, as in past Uber iterations.

**Comment by kitsuta** [comment]
Oops. That's a config option in https://github.com/magfest/panels/blob/master/development-defaults.ini#L6. It needs to be puppetized and update for M2017.
