### ISSUE TITLE
some staff badges appear to be getting switched to attendee after confirming badge

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2179]
uber-app.log.3.gz:2016-11-29 13:44:00,883 [INFO] cherrypy.access.139805246161080: 209.6.184.219 - - [29/Nov/2016:13:44:00] "GET /uber/signups/index?message=Your%20information%20has%20been%20updated. HTTP/1.0" 200 8604 "https://super2017.uber.magfest.org/uber/preregistration/confirm?return_to=../signups/index&id=[REMOVED]" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"

after this access we saw:

Attendee	updated	13:44 on November 29 2016	non-admin	badge_type=''Staff' -> 'Attendee'', requested_depts=''Security,Staff Support,Tea Room' -> ''', badge_num='747 -> None', can_spam='True -> False', staffing='True -> False', assigned_depts=''Regdesk,Staff Support,Logistics,Security' -> '''

we're not sure how the badge type can get switched from staff to attendee on the confirmation page.  this is post-badge#s getting locked in for badge printing.  also, this person came in from the volunteer checklist

**Comment by binary1230** [comment]
I am guessing somewhere, a presave adjustment is getting fired off that sets badge to attendee

**Comment by binary1230** [comment]
ok so Brent and I walked through the logs and code and think maybe this is indeed expected behavior if someone unchecks 'volunteering' on the confirmation page.  it calls unset_volunteering() which is consistent with what we see here.

it just seemed weird to us that 3 long-time staffers would do uncheck that option, but maybe they really did.  just want to verify this isn't a bug.

ALSO UNRELATED RELATED BUG:  these people are not removed from the hotel eligible list, probably the hotel plugin needs to check if someone is no longer staffing and then unset their hotel_eligible flag

**Comment by kitsuta** [comment]
I've reviewed the code and there's really nothing that would be doing this that I can tell. We need to contact these staffers (I believe @earl7399 already did this) and ask them what they did.

**Comment by BlueHat-GURU** [comment]
What did we hear from these staffers, @binary1230 @bds002 @earl7399 ?

**Comment by BlueHat-GURU** [comment]
Per slack comments; the staffers did uncheck the box. Closed.
