### ISSUE TITLE
Update Staffer Summary page to say Assigned Badge # (For Badge Column)

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#2182]
Use Case - Department Head is reviewing Uber Staffing Summary page:
https://super2017.uber.magfest.org/uber/jobs/staffers?location=92001232
To see who has a badge for the event.

The Badge Column list the staffers badge number, but prior to the event the Attendee (Volunteers) are listed as NONE.  This can get confusing to new DH's who see the NONE and think the person doesn't have a badge at all.   (Experienced Uber Users know that if a name appears then they have a badge, but the wording is not as user friendly as it should be).

![capture](https://cloud.githubusercontent.com/assets/8822346/20868429/6f75b512-ba29-11e6-8576-4492f9a2bd6f.PNG)

**Comment by earl7399** [comment]
Do you have any thoughts about what to replace "None" with? How about "TBD"?

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by bds002** [comment]
I'm good with that.
