### ISSUE TITLE
Remove one-day option when creating new badge through Admin interface.

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#2201]
From here: https://super2016.uber.magfest.org/uber/registration/form?id=a1218890-c105-4f06-9854-165bbe3d8a1a&message=This%20attendee%20was%20the%20only%20search%20result

Rams Admins still have the option to create one day badges. The drop down box still shows one day badges. This has been testing in staging (3) - Discovered by David Boyd.

Brent

**Comment by kitsuta** [comment]
This was just a config option, and it's no longer relevant.
