### ISSUE TITLE
As Marketplace head, I want to see when attendees' extra_donation is being added to the group charge

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2208]
Right now, when dealers go to pay for their group, they are charged:
* The group's cost, plus
* The group leader's kick-in level, which is displayed on the group's page and the group admin page, plus
* The group leader's extra_donation, which is not displayed anywhere clearly.

The last of these can cause confusion. For example, if the group leader set `extra_donation` to $10, it looks like the Stripe form is arbitrary charging $10 more than the `group_owed` amount. The only way to see what is really happening is to look at the group leader's Attendee Details page, and to look specifically for what their "extra donation" is. This value should be displayed prominently on the same pages that the kick-in level is displayed, so we can easily see that there are extra charges.

**Comment by binary1230** [comment]
fixed by https://github.com/magfest/ubersystem/pull/2245
