### ISSUE TITLE
we occasionally send stripe bad API data - possible dupe card tokens?

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2209]
```
{
  "card": [
    "tok_9kWC0AP[redacted]",
    "tok_9kWC0AP[redacted]"
  ],
  "currency": "usd",
  "amount": "8000",
  "description": "[redacted - was Firstname Lastname]"
}
```

two 'card' values is probably the issue here, not sure why that's happening. more details not at 10pm

**Comment by binary1230** [comment]
added a bunch of logging and was able to finally reproduce this on actual mobile device, Samsung Galaxy S7, Chrome, Android

I think I registered an attendee and somehow clicked the 'Submit' button twice (that might or might not be important), then was able to get this error.

My guess is the Stripe Javascript is somehow causing the following duplicate values to be sent in via POST, which is messing up the API request:

```
stripeEmail: ['REMOVED@gmail.com', 'REMOVED@gmail.com']
payment_id: 328a84bc91d84b1aREMOVED
stripeToken: ['tok_9mQ7tF9REMOVED', 'tok_9mQ7tF9REMOVED']
stripeTokenType: ['card', 'card']
```
(redacted info is marked as REMOVED there)

**Comment by binary1230** [comment]
![image](https://cloud.githubusercontent.com/assets/5413064/21361817/b86fd568-c6b3-11e6-8db1-15ba51922f63.png)

Repro steps (assuming this works again):
1) fire up your android mobile device, Chrome
2) pre-register an attendee with a birthdate of 1993 (not sure if birthdate is important or not)
3) click the submit button TWICE
4) pay with stripe card
5) observe error when our server tries to call charge_cc() to charge the card

I am betting at this point it's some kind of weird mobile javascript interaction

**Comment by binary1230** [comment]
crappy workaround if we get desperate and don't feel like tracking down the real issue:

for both stripeEmail and stripeToken do the following:

```
# ultrahack
if param is a list, then:
   if all elements in the list are identical then:
      param = param[0]
      log.error("WE JUST HACKED AROUND A PROBLEM")
```

**Comment by kitsuta** [comment]
By the way, we looked into this and we're pretty sure this was a Stripe Checkout problem, which was hopefully temporary (since we no longer are seeing the error). I asked @binary1230 to file the 'hacky' fix anyway just so we can get around it if we find out on Saturday that it's still a problem after all.
