### ISSUE TITLE
multi-issue: prereg kickin options showing past the supporter deadline

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2210]
Nick and I talked about this a bunch and this isn't necessarily a bug, might be desired behavior we're going to keep in place through Magfest 2017, but:

We're current in a situation where today (Dec 16th) we are past both the SUPPORTER_DEADLINE (Nov 30th) and the SHIRT_DEADLINE (Dec 15th).

The website still shows 2 kickin options on prereg form:
- Tshirt which is +$20
- I <3 Magfest which is +$50

Issue 1: c.SHIRT_DEADLINE is not used anywhere in the code except to send an email to attendees reminding them to confirm their tshirt size.  Thus, we will never hide these options on the prereg form.  That has been the intended behavior in the past, so might still be ok. (might want to document this fact in configspec.ini)

Issue 2: "I <3 Magfest" is +$50, which is below the c.SUPPORTER_LEVEL of $80, so it will also be displayed forever.  This has never been a problem we've seen in the past because there was never a kickin level between c.SHIRT_LEVEL and c.SUPPORTER_LEVEL

Solution Part 1: Possible options (ends up having some manufacturing implications):
1) modify c.PREREG_DONATION_DESCRIPTIONS and c.PREREG_DONATION_OPTS so if we're after the SHIRT_DEADLINE we hide anything AT OR ABOVE the c.SHIRT_LEVEL tier
2) have some kind of new deadline (c.KICKIN_TIER_DEADLINE?) that hides the entire Kickin form on the prereg form after a certain date

Solution Part 2: In addition to that, we should hide the entire kickin form if there are no options being displayed (i.e. c.PREREG_DONATION_OPTS is zero-length) [update: as Vicki pointed out we totally already do this]

-------------------

Issue 3: If we do decide to change c.SHIRT_DEADLINE, we'll need to modify the hardcoded date in https://github.com/magfest/magprime/blob/master/magprime/templates/emails/confirm_shirt_size.html to say ```c.SHIRT_DEADLINE - 5 days``` or else people getting that email will have the wrong date in there

------

Nick seems to think we can just leave this as-is, but in case we change our mind later and do want a deadline for all kickins, this is what we'd have to implement

**Comment by BlueHat-GURU** [comment]
Will need to do onsite, #2226

**Comment by kitsuta** [comment]
Yeah, uh, how many extra cowbells do we have? Even if we want to keep selling people tshirts at-fest (this doesn't make a WHOLE lot of sense to me personally) I don't think keeping the $50 level is a good idea.

Sean Pearson pointed out this discrepancy a while back, it's a shame we're just now getting around to worrying about it. Hopefully we don't run out of stuff.

In any case, making the shirt_deadline actually do something is our best bet imo -- it makes it work just like supporter_deadline, which I expect people already think it does.

Solution part 2 already exists: https://github.com/magfest/ubersystem/blob/master/uber/templates/regform.html#L108 I'm pretty sure a 0-length dict is falsey in Python.

Issue 3 should be a separate issue because yeah, the email should totally use the deadline.

**Comment by binary1230** [comment]
Cool.  the update is a week or two ago, Nick and I looked at this one closely, and from a code standpoint I was cool keeping it where it was, and from a manufacturing standpoint Nick was cool selling these items past the official deadline up til when we close reg.  I think it was figured that we had sufficient enough margins on manufacturing for the swag to keep doing the pre-orders, and if sales numbers deviated drastically from last year that we could always do another manufacturing round after this and mail stuff out (which would be office's problem).

**Comment by binary1230** [comment]
btw just to be clear: Nick and I are both open to changing this, just didn't see it as a big on fire thing and decently workable unchanged as-is.  Open to feedback

**Comment by binary1230** [comment]
on-re-reading I totally missed that zero length check in the template for solution part 2, that's nice.
