### ISSUE TITLE
Test kiosk page on desktop and mobile

### ISSUE THREAD

**Issue by BlueHat-GURU** [magfest/ubersystem#2221]
Are any errors thrown? If so, write up an issue and/or fix.

Is the UI distorted? If so, report to #webdev on slack, please attach images.

**Comment by kitsuta** [comment]
Important note: the webdev channel does not deal with anything RAMS-related, so UI issues would still be a devops thing.

**Comment by kitsuta** [comment]
Less important note: we actually want to test `registration/register`, not the prereg page itself (see https://github.com/magfest/ubersystem/issues/2222 -- we don't actually USE the real prereg page during at-con mode).

**Comment by kitsuta** [comment]
This page is tested as working with one minor exception, which is filed in https://github.com/magfest/ubersystem/issues/2232.
