### ISSUE TITLE
Test redirects for attendees in at-con mode

### ISSUE THREAD

**Issue by BlueHat-GURU** [magfest/ubersystem#2222]
Is an attendee redirected to the kiosk page when appropriate? If not, please write an issue to have it repaired, or simply do so.

**Comment by BlueHat-GURU** [comment]
New to this query (i.e. wait to answer until after super): are there other redirects?

**Comment by kitsuta** [comment]
It does redirect. Hooray!

There are no other redirects in the code itself -- there's some nginx proxy stuff that we do with the onsite server vs cloud server, but that's not really testable before we actually set it up.
