### ISSUE TITLE
Review Supporter swag/tshirt box show/hide timing

### ISSUE THREAD

**Issue by BlueHat-GURU** [magfest/ubersystem#2223]
Is the deadline configuration for supporter swag "sane" (at least 6 weeks pre-event? This year was set for 5.)?
Are the tshirt options shown/hidden on correct dates (changeover 4 weeks before event?)?
Please fill out appropriate tickets or do yourself to make this correct.

**Comment by BlueHat-GURU** [comment]
Honestly not quite sure how this relates to the .yaml in production config; mostly my own ignorance.

**Comment by BlueHat-GURU** [comment]
Related to #2210 (which has details) and #2224 (which mentions a specific case)

**Comment by kitsuta** [comment]
T-shirt options have historically been sold right up to the event.

Supporter swag is set and past already.

Both of these options are generally things we review and re-set every year based on when we think we'll need to order stuff. The supporter deadline was pretty late this year compared to when we'd want it set most years -- it's very much a play it by ear sorta thing. In any case, this is really an office yearly maintenance task, isn't it?
