### ISSUE TITLE
Fix Unit tests

### ISSUE THREAD

**Issue by BlueHat-GURU** [magfest/ubersystem#2225]
pasted from slack (thank you for writing yourself)

test_badge_cost needs to be rewritten to accommodate new behavior (we no longer force badge cost of attendees who are paid by group to be 0)

4:50

test_discount is also... erm, hm. Actually I need to look at that bit again; there was a reason I did something weird with age discounts but I forget what I did

4:50

test_free is the same deal -- it uses age_discounts which no longer apply the way they used to, but I want to re-review why/how

4:51

test_over_limit_price needs to stop passing a datetime to get_attendee_price; then it should work. (edited)

4:51

Same with test_refunded_badge_price_bump -- I altered get_attendee_price to stop caring about badges sold if you passed in a datetime, so the tests just need updating

**Comment by kitsuta** [comment]
Addendum: I reviewed test_discount and test_free, they just need to be set to test for what is now happening.
