### ISSUE TITLE
Ensure that kiosk prereg form has all necessary features

### ISSUE THREAD

**Issue by BlueHat-GURU** [magfest/ubersystem#2226]
Features include (but are not necessarily limited to, you know this better than I):
-child/minor badges
-minor ribbon
-rolling 4-day badges (price changes as the weekend goes on)

**Comment by kitsuta** [comment]
I think you've got it covered.

Minor ribbons are already taken care of automatically, although they need to do the opposite of what they currently do (see: https://github.com/magfest/ubersystem/issues/2237).
Separate issues have been filed for the other two functions:
https://github.com/magfest/ubersystem/issues/2235
https://github.com/magfest/ubersystem/issues/2236
