### ISSUE TITLE
Ensure that Admin regform is compatible with new features

### ISSUE THREAD

**Issue by BlueHat-GURU** [magfest/ubersystem#2228]
Features include (but are not necessarily limited to, you know this better than I):
-child/minor badges
-minor ribbon
-rolling 4-day badges (price changes as the weekend goes on)

**Comment by kitsuta** [comment]
The only thing that screws up the admin side is https://github.com/magfest/ubersystem/issues/2233 and the related-and-possibly-the-same-bug https://github.com/magfest/ubersystem/issues/2207. Everything else is pretty standard as far as the admin side goes.
