### ISSUE TITLE
Ensure that new features are supported by RAMS and config file

### ISSUE THREAD

**Issue by BlueHat-GURU** [magfest/ubersystem#2229]
Features include (but are not necessarily limited to, you know this better than I):
-child/minor badges
-minor ribbon
-rolling 4-day badges (price changes as the weekend goes on)

In particular, there is no clear statement of the rolling badges in:
https://github.com/magfest/production-config/blob/master/event-prime.yaml

**Comment by BlueHat-GURU** [comment]
Listed as priority because it looks like other things depend on it.

**Comment by kitsuta** [comment]
This is implicitly covered by the other stuff. See my comments in https://github.com/magfest/ubersystem/issues/2226 for what doesn't work.
