### ISSUE TITLE
Possible issue with no-longer-waitlisted group pricing when it includes staff and <6 minor

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#2251]
I have a specific example (group name will be communicated via Slack) of a group with a Staff badged leader and a single <6 minor. The group leader link shows that they still owe $65 even though neither badge should cost anything.

**Comment by kitsuta** [comment]
This was a one-time DB script that Eli ran that accidentally set dealers' individual badge prices to $65 regardless of their badge type. We'll take care of it elsewhere -- it's not a code issue.
