### ISSUE TITLE
Name Printed on Badge shows up twice on the admin form

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2252]
When we changed around some of the stuff on the attendee detail's page, we accidentally made the "Name Printed on Badge" form show up twice. It should only be displayed once.

**Comment by binary1230** [comment]
This is likely the line:
https://github.com/magfest/ubersystem/pull/2247/files#diff-756d39e16003f4768b0b63c7bd2365aeL108

from
https://github.com/magfest/ubersystem/pull/2247/

We think it's an order of operations bug with the 'or' statement ignoring the c.PAGE_PATH check, dare is going to upload a PR with a proposed fix.  It's a little hard to test locally so we might YOLO this on a staging server

**Comment by kitsuta** [comment]
~*~Oops~*~
