### ISSUE TITLE
As an admin, I'd like to have the "view this group's page" link open a new page.

### ISSUE THREAD

**Issue by migetman9** [magfest/ubersystem#2258]
Currently, when an admin is checking if an attendee is in a group they must click a link that changes the current page. The solution, I assume the admins currently use, is to open it in a new tab, or go back a page.

It would be very simple to make this `<a>` tag open a new window or tab instead of replacing the current page. 

The link looks as follows: 

<img width="461" alt="screen shot 2016-12-30 at 1 51 49 pm" src="https://cloud.githubusercontent.com/assets/6538753/21570796/5f472888-ce97-11e6-90ab-a4dfbd774167.png">

**Comment by BlueHat-GURU** [comment]
Have you communicated with any of the regdesk folks on this?

**Comment by migetman9** [comment]
@BlueHat-GURU talked to @ShevaDas

**Comment by BlueHat-GURU** [comment]
That is useful information.

**Comment by kitsuta** [comment]
This should have been closed on merging the related PR. Huh.
