### ISSUE TITLE
On registration/register the zip code field is made bold as if it is required, but it is not.

### ISSUE THREAD

**Issue by migetman9** [magfest/ubersystem#2259]
This may either be a failure on the part of a validation check, or we really don't require the attendees zipcode. I'm gonna look to @kitsuta for more details on that.

**Comment by kitsuta** [comment]
Ah, yeah, this is legit.

We require a zipcode when pre-registering, but not when registering at-door. However, both templates (preregistration/form and registration/register) use the same set of fields (included via regform.html).

In order for a label to not be bold, it has to have an `optional-field` class on it, but we probably don't have a way to toggle that for the zipcode.

We have a `maybeBold` function on the kiosk page here: https://github.com/magfest/ubersystem/blob/69ff35f191ebbcf13900405539b3f7d068feff80/uber/templates/registration/register.html#L11 It controls the boldness of the email label based on the payment method selected. We need to do something similar, except we just need to unbold the label, period.
