### ISSUE TITLE
Group members' badge prices are being recalculated when claimed

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#2262]
2nd SB ticket in two days asking why GL page wants more money. Specific group available from me - just ask.
Something seems very wrong...

**Comment by earl7399** [comment]
I have a 2nd example group that has added, for no apparent reason, **SIX** separate $25 charges today.

**Comment by kitsuta** [comment]
I endorse the HIGH PRIORITY label.

What is happening is that, when group badges get claimed, they actually get deleted and re-created. Unfortunately, their `overridden_price` is not transferred. This is Bad. Very Bad.
