### ISSUE TITLE
qrcode: QR_CODE_PASSWORD not marked as secret

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2269]
visit URL:
```/uber/angular/magfest.js```

expected: QR_CODE_PASSWORD is hidden
actual: QR_CODE_PASSWORD is visible

This is probably because we're doing this in config.py:
```
c.QR_CODE_PASSWORD = sha512(c.QR_CODE_PASSWORD.encode('UTF-8')).hexdigest()[:24] if c.QR_CODE_PASSWORD else None
```

I guess that by re-assigning the var, we're losing whatever attribute makes this thing be marked as Secret.

**Comment by binary1230** [comment]
when we fix this, we need to reset the password on mcp

**Comment by kitsuta** [comment]
Whoops, yeah, that would probably do it. I'm not super clear on how to fix that, though.

**Comment by binary1230** [comment]
help me @EliAndrewC wankenobi, you're my only hope.

I know Eli will just go paste some one-liner that will blow our minds and the minds of programmers for generations to come

**Comment by binary1230** [comment]
(and if not I can look into it, though a bit out of time for today)

**Comment by EliAndrewC** [comment]
Looks like you fixed this without me, due to me being pulled into a belated Christmas dinner with the in-laws.
