### ISSUE TITLE
Pre-reg form listed incorrect end of pre-reg date

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#2271]
Reg form currently states that pre-reg ends the evening of January 3rd. Since the event starts january 5th, and we have no downtime between pre-reg prices and at-door prices, the reg form should list a pre-reg end date of Jan 4 evening.

**Comment by kitsuta** [comment]
Eli gave good reasoning for having this date be what it is. Here's the messages from Slack:
>For some additional clarification on why we tell people that it's going to close at midnight tonight: since we usually try to migrate to the on-site server on Tuesday night, it's useful to say that prereg will go offline completely.  That way if something went really badly, we could have the system be offline and it's just what was advertised.  Whereas if everything goes well, we can bring the system back up and take away the message about it shutting down and keep taking preregs.
>To further-further clarify the "prereg closing at midnight" thing, there's nothing in the code that actually shuts it down at midnight, so we don't need to emergency-patch anything to keep that from happening.  But it does mean that after midnight we can do whatever we want to take the system down to move things on-site and it'll be consistent with what we advertised.

So I'm comfortable with closing this issue as WNF.
