### ISSUE TITLE
Replace 'QR code' with '2D barcode' in text

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2277]
Since we're using Aztec 2D barcodes, the term "QR code" is technically incorrect. This could confuse some folks. We should instead refer to it as a 'barcode' (which we already do on the confirm page) or '2D barcode.'

**Comment by binary1230** [comment]
hilarious

**Comment by EliAndrewC** [comment]
I've pulled this into our on-site sprint for the coding interns.

**Comment by Utilityman** [comment]
working on it

**Comment by kitsuta** [comment]
Fixed by #2301.
