### ISSUE TITLE
on server restart, clear out session/*.lock

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#230]
I am getting this once in a while when running with the debugger

Killing the server abruptly (which you often do if you're in a breakpoint and realize you want to start over) occasionally leaves lockfiles behind in sessions/ dir which have to be manually cleared out before you can start the server back up.

Eli, do you think it's safe that run_server.py could delete any lockfiles on startup?  I'm guessing probably?

**Comment by EliAndrewC** [comment]
Closing in favor of #1748
