### ISSUE TITLE
As a person giving out merch onsite, I'd like the merch page to list shirt sizes even after shirts have been given away

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2302]
(might be easy)

Comment from  talking to Yettee yesterday:

If an attendee has already picked up merch, they'd like the page that says "attendee already picked up merch" to also still show the shirt size for that attendee.  Apparently they sometimes have situations where they need this info even after the merch has been picked up.

**Comment by EliAndrewC** [comment]
Dragging this into the on-site sprint for our coding interns.

**Comment by EliAndrewC** [comment]
@JoshMackin: After you take a look at https://github.com/magfest/ubersystem/issues/2303 then this would be a good ticket to tackle.  I'll walk you through how the merch page works and where you'd write the code to add this message.

**Comment by EliAndrewC** [comment]
@DataFighter: this would be a good next ticket to tackle.
