### ISSUE TITLE
changing an admin's password logs YOU out?

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2303]
@migetman9 reported that if you change an admin's password, ubersystem logs YOU out.

**Comment by EliAndrewC** [comment]
I suspect that this isn't true and that in fact the password just happened to be changed at around the 20-minutes-since-he-logged-in mark, so his sessions just happened to expire at that time.  I'd be very interested if someone was able to reproduce this.

**Comment by EliAndrewC** [comment]
I'll assign to one of our interns to try to reproduce.

**Comment by EliAndrewC** [comment]
@JoshMackin: Can you try to reproduce this?  I don't think it's really happening, but I want to see if it happens on our development boxes.  If not then I'll close this as Could Not Reproduce.

**Comment by EliAndrewC** [comment]
@DataFighter: since you're around at the moment, can you try to reproduce this?

**Comment by DataFighter** [comment]
Must be a user error. Busted this issue for two accounts
