### ISSUE TITLE
Personal phone number and emergency contact number should not be allowed to be the same

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#2313]
People keep leaving the same number for both fields.

In theory this *could* be valid, e.g. back in the days before cellphones, my home number would have been both my personal number (because it's how you would call me) and my emergency contact number (because it's what you would call to reach my family if something happened to me).

In practice these days it probably causes more problems than it solves to allow them to be different.

**Comment by thaeli** [comment]
Agree with this. Anyone who doesn't have their own mobile phone should be
checking that they don't have one and only providing an emergency contact
number anyway.

**Comment by EliAndrewC** [comment]
@khyperia: This would be a good next one to tackle.  The validations are in ``uber/model_checks.py`` and I *think* it should be evident how to add a new validation.
