### ISSUE TITLE
Emergency contact name

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#2314]
Dorsai requests an emergency contact name to go with the emergency contact number.

**Comment by md1024** [comment]
This [random emergency contact fields article](https://docs.oracle.com/cd/E39904_01/hcm92pbr0/eng/hcm/hhaw/task_TrackingEmergencyContacts-647be9.html) describes a schema for emergency contact fields. While the address sfor the emergency contact seems unnecessary, I think it might be worth asking attendees to defne the relationship to their emergency contact.

ec_phone
ec_full_name
ec_relation

**Comment by kitsuta** [comment]
Ehhhh, I don't know if that'll be wise or if we'll get a bunch of junk data.

**Comment by EliAndrewC** [comment]
FWIW, I'm also leery of anytime we increase the number of required form fields.  We never set up any kind of A/B testing so we don't even have a way to measure how many people get to our form and then don't fill it out, or how many people fill out some of it and then stop and don't come back, etc.

So in general, the usefulness of new form fields needs to be balanced against the potential downside.  In the long run we should set up A/B testing so that we don't have to wonder about "potential" downsides and can make accurate decisions.
