### ISSUE TITLE
Must hit enter twice to submit a form

### ISSUE THREAD

**Issue by dylwhich** [magfest/ubersystem#2339]
Most likely has something to do with barcode scanning detection.

**Comment by kitsuta** [comment]
Oops. I don't know what would be causing it exactly, but yeah, the barcode scanning detection is a likely culprit. Sorry about that.

**Comment by kitsuta** [comment]
This SHOULD be fixed now that we've removed barcode scanning detection. Let me know if it wasn't, please!
