### ISSUE TITLE
As a daily user of Uber, the Red Error message about Bar Code Scanner is a hinderance.

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#2340]
PLEASE REMOVE The Red screen error message, is more pervasive and annoying than the blue screen error message.

I asked about this at event and was told it was going to be handled then.  Instead of making things better, it has made using Uber more infuriating.  Also add to the fact that I don't have a bar code scanner attached, so the error message itself is not accurate for what I am working on.

![capture](https://cloud.githubusercontent.com/assets/8822346/21877030/39f2af80-d856-11e6-9b80-7fa838ad592e.PNG)

**Comment by bds002** [comment]
2nd time to receive error message yet this evening

**Comment by kitsuta** [comment]
Should be fixed by https://github.com/magfest/production-config/pull/187.

**Comment by kitsuta** [comment]
That... didn't work. That's a problem.

**Comment by EliAndrewC** [comment]
To repeat what I said in Slack in case anyone looks at this ticket later: puppet doesn't go in and remove plugins which are no longer shipped, so I had to ssh in and remove this manually, which worked fine.  We did another deploy to confirm that it didn't randomly come back or anything.
