### ISSUE TITLE
As a DH, I would like to put staff/volunteers into groups and restrict Shift signups to certain groups

### ISSUE THREAD

**Issue by rscullin** [magfest/ubersystem#2342]
TechOps is a large department, with many staffers (100+) and many different roles/jobs (~10). We've been using the "trusted" flag in the past to restrict people from signing up for jobs that require skills/training/our sign off, but this hasn't scaled. For example, someone who is trusted to run Panels A/V shouldn't be able to sign up for Network Tech On-Call unless we've verified that they know what they're doing.

An ideal solution for us would be the ability to assign staff/volunteers into (internal, department only) groups and restrict shift signup to only people in certain groups.

Ideally we would also have some form of verbiage on the shift sign up page to contact your DH if you don't see jobs (or groups?) you're expecting.

**Comment by kitsuta** [comment]
This is a great idea for addressing a long-standing problem of 'trusted is not granular enough for most departments.' I think it could actually replace 'trusted' as a Thing.

In Slack, rscullin mentioned that this was a very serious problem for Tech Ops, so I'm tagging this 'before magfest' in the hopes that we remember to do it.

**Comment by EliAndrewC** [comment]
The long term plan is to replace "trusted" with a configurable list of per-department properties so that each department can decide which buckets each attendee falls into.  This is conceptually the same as what this ticket id asking for.  I'm hoping that we can get this in this year once we hire a full-time software engineer.

**Comment by kitsuta** [comment]
I think I could actually handle this, and it's well-defined and straightforward enough that it won't go into the limbo of feature requests that aren't actionable without further specs.

**Comment by BlueHat-GURU** [comment]
I am now aware of and watching this. If I think of specific things to implement to aid this process, I'll do so.

**Comment by EliAndrewC** [comment]
FWIW, I left some thoughts about how we could accomplish this sort of thing in an older comment here:
https://github.com/magfest/ubersystem/issues/1474#issuecomment-148730153

**Comment by kitsuta** [comment]
Thanks, @EliAndrewC. I've written up this schema so far.

```python
class Attendee(MagModel):
    departments = relationship('DeptAssignment', backref='attendees', cascade='save-update,merge,refresh-expire,expunge')


class Department(MagModel):
    name = Column(UnicodeText)
    slug = Column(UnicodeText)
    parent = Column(UUID, ForeignKey('department.id'), nullable=True)
    job_types = Column(MultiChoice(c.JOB_TYPE_OPTS))
    attendees = relationship('DeptAssignment', backref='departments', cascade='save-update,merge,refresh-expire,expunge')


class DeptAssignment(MagModel):
    dept_id = Column(UUID, ForeignKey('department.id'))
    attendee_id = Column(UUID, ForeignKey('attendee.id'))
    role_id = Column(UUID, ForeignKey('job_role.id'))
    roles = relationship('JobRole', backref='dept_assignment', foreign_keys=role_id, cascade='save-update,merge,refresh-expire,expunge')


class RoleAssignment(MagModel):
    job_id  = Column(UUID, ForeignKey('job.id'))
    job_role_id = Column(UUID, ForeignKey('job_role.id'))


class JobRole(MagModel):
    name           = Column(UnicodeText)
    department_id  = Column(UUID, ForeignKey('department.id', ondelete='SET NULL'), nullable=True)
    department     = relationship('Department', backref='job_roles', foreign_keys=department_id,
                                 cascade='save-update,merge,refresh-expire,expunge')
    jobs           = relationship('Job', secondary='role_assignment', backref='roles',
                                 cascade='save-update,merge,refresh-expire,expunge')
    ribbon         = Column(Choice(c.RIBBON_OPTS), default=c.NO_RIBBON)
    gets_checklist = Column(Boolean, default=False)
```

It's pretty complicated and it's late at night, so I'm gonna take some time before I start working on the code itself. But the general idea is to be able to access information in these ways:
attendee.departments
department.attendees
job.roles
role.jobs
attendee.dept_assignment->(filter for a specific dept_id).roles

It's the last bit I'm least sure about. Each attendee could have multiple roles in each department. I'm not sure I modeled it in the most sensible way.

**Comment by rscullin** [comment]
Any chance this could be done by Labs? Ideally it'd be nice to test this before Prime so we can work out any issues.
