### ISSUE TITLE
rename ident column in ApprovedEmail model

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2369]
in models.py, we have this line:

```
ident = Column('subject', UnicodeText)  # TODO: rename column to "ident" in the database; will require a db migration
```

we did this to be cute to avoid a database migration (because man we are lazy), but if we get a chance before any events launch we should just go change it to be:

```
ident = Column('ident', UnicodeText) 
```

only do this if either of the following is true:
1) we don't have any live production DBs and can wipe them, or
2) we have live DBs and we have a DB migration prepared

**Comment by kitsuta** [comment]
I'm like, 33% sure it would have taken you less time to remove that line and submit a PR. :P
