### ISSUE TITLE
Add ident to every automated email

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2383]
In order to prevent a massive number of emails from being resent when an email subject line changes, each automated email should use a static `ident`

This needs to be resolved before #1593 is merged.

Basically, everywhere we have something like this:

```
AutomatedEmail(Attendee, '{EVENT_NAME} payment received', 
         'reg_workflow/attendee_confirmation.html',
         lambda a: a.paid == c.HAS_PAID,
         needs_approval=False, allow_during_con=True)
```

We need to add a line like this:

```
AutomatedEmail(Attendee, '{EVENT_NAME} payment received', 
         'reg_workflow/attendee_confirmation.html',
         lambda a: a.paid == c.HAS_PAID,
         needs_approval=False, allow_during_con=True,
         ident='attendee_payment_received')
```

**Comment by EliAndrewC** [comment]
I will further say that we should consider making ``ident`` a required field once all of the emails have idents.
