### ISSUE TITLE
As a email system user, I would like to be able to preview emails even if none are ready to send

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2384]
Currently uber supports previewing emails from the 'pending email page', but they will only show up IF they have already been generated.

It would be nice to have a way to preview email contents even if no emails are queued up in that category, to make sure that code changes to email templates look good.

We started work on this in https://github.com/magfest/ubersystem/pull/1899, but I have closed that PR out for now because it wasn't 100% ready to go.  With a little work, it could be brought back from the dead. I recommend future people trying to tackle this issue start with that PR.

**Comment by kitsuta** [comment]
Fixed by #2449.
