### ISSUE TITLE
Add `test-defaults.ini` with sqlalchemy_url pointing to SQLite

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2385]
This issue depends on [Sideboard issue #66](https://github.com/magfest/sideboard/issues/66) (we need some way to specify which config file should be used).

Pull request #2360 depends on this issue (checking `Session.engine.dialect.name == 'postgresql'` only really works if the `sqlalchemy_url` is configured a priori).

**Comment by kitsuta** [comment]
We've gone ahead and merged #2360 -- we should make another PR to address this issue when we can.
