### ISSUE TITLE
As an attendee filling out the form, the label of the 'legal name' checkbox appears to 'break' the page

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2400]
Currently, name section of the pre-reg page looks like this:
![image](https://cloud.githubusercontent.com/assets/7198215/24417819/d646b8c6-13b7-11e7-8264-0fe87d63f6c0.png)

This is not attractive, and when scanning the page the checkbox's purpose is harder to parse because the line explaining it is so broken up.

One thing we could do is re-label the checkbox to something like "Legal Name Confirmation" and put the text "The above name is exactly what appears on my ID" right next to the checkbox instead. If we do that, it will look like this instead:
![image](https://cloud.githubusercontent.com/assets/7198215/24417890/26974dc2-13b8-11e7-9f35-051c0336d9b5.png)

Neater and more readable, imho.

**Comment by kitsuta** [comment]
Note: @thaeli has submitted (via Slack) that 'legal name' is not the best term to use in the UI, and we could do with brainstorming alternatives. Maybe something like "Photo ID Name" or "Name On ID"

**Comment by jcooter** [comment]
To be fair, why does the checkbox need to have a value at all if it has a description?

**Comment by kitsuta** [comment]
Technically the label would help assisted-reading devices, which I believe rely on labels. However, I think we can put labels anywhere; I like how your mockup looks. I would probably make first and last name equal widths, though. Lots of long first names too.

**Comment by jcooter** [comment]
The other benefit is it subtly fixes the naming issue.  Your name is your name, and then legal name is something that is not your name.  First name and Last name are treated as parts of your name, and not as descriptors of the type of name they are.

**Comment by BlueHat-GURU** [comment]
How may I help move this along?

**Comment by RobRuana** [comment]
Is this something we want in the current release of MAGStock/Labs/West?

**Comment by kitsuta** [comment]
Not super urgent, was just filing UX/UI issues as I noticed them.

**Comment by kitsuta** [comment]
Whoops! This hasn't made it to MAGFest's master yet. Reopening,
