### ISSUE TITLE
magstock: affiliate display not working

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2403]
![image](https://cloud.githubusercontent.com/assets/5413064/24434838/fb370c24-13ff-11e7-9f30-214652436978.png)

on magstock (which, doesn't really use affiliates so this doesn't matter, but maybe other events do), the affiliate dropdown is not showing anything despite there being javascript code with the correct affiliate values.

not a jinja conversion issue as it's busted in django as well.

low pri

**Comment by binary1230** [comment]
maybe related or dupe of https://github.com/magfest/ubersystem/issues/1632 ?

**Comment by BlueHat-GURU** [comment]
Still going?

**Comment by RobRuana** [comment]
Haven't looked at it yet. Do we want this fixed in the current MAGStock/Labs/West?

**Comment by BlueHat-GURU** [comment]
This _appears_ to no longer be here, so closing this issue.
