### ISSUE TITLE
band plugin: 'mark as band' missing csrf token

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2405]
low pri, jinja2 related

/uber/band_admin/index has a javascript error when you try and mark a group as a band:
![image](https://cloud.githubusercontent.com/assets/5413064/24435293/69e858c4-1402-11e7-888e-d1667ef4b58a.png)

![image](https://cloud.githubusercontent.com/assets/5413064/24435302/7aed6de4-1402-11e7-9a9f-b2aa31b4f70f.png)

**Comment by RobRuana** [comment]
This was fixed by the fix for #2411!
