### ISSUE TITLE
Badge Level buttons do not show prices when registering members of a group

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2433]
When registering members of a group, the prices do not show up on the badge buttons.

At this URL:
```https://staging1.uber.magfest.org/uber/preregistration/register_group_member?group_id=XXX```

the buttons look like this:
![screen shot 2017-04-18 at 11 08 08 pm](https://cloud.githubusercontent.com/assets/2592431/25161762/0d14cd9a-248c-11e7-8ad1-2ff33d4c82dc.png)

While at this URL:
```https://staging1.uber.magfest.org/uber/preregistration/form```

the buttons look like this:
![screen shot 2017-04-18 at 11 10 24 pm](https://cloud.githubusercontent.com/assets/2592431/25161852/4a153b58-248c-11e7-8174-3fbba04790ce.png)

**Comment by kitsuta** [comment]
Hey, actually this doesn't affect Super's pre-reg launch at all -- we hide these badge buttons in favor of the big kick-in buttons. Do we want to take this off the milestone?

**Comment by RobRuana** [comment]
I'm gonna leave this on the milestone, just to verify the big kick-in buttons also look correct in this form.

Also as a reminder to update the prime deployment config to match production, so these buttons are hidden by default on our dev boxes.
