### ISSUE TITLE
As an attendee, I would like to know if I entered an invalid email

### ISSUE THREAD

**Issue by BlueHat-GURU** [magfest/ubersystem#2458]
From Joel: "bounced e-mails. I am not Github-competent, so I am unsure how to tell if anyone put in a usercase regarding the e-mail field accepting anything, even if it's not '[x]@[y].com' because that was a large subset of bounced mails that could be prevented."

I'm pretty sure it should be '.[edu, com, org, net, (etc)]' instead of just '.com'.

**Comment by BlueHat-GURU** [comment]
https://magfest.slack.com/archives/G09PSGLK1/p1493338527148591

**Comment by RobRuana** [comment]
That slack link doesn't work for me ☹️

**Comment by RobRuana** [comment]
Also, I'm like 90% sure that we accept any top level domain, not just ".com". I just registered "test@pirate.ninja" without issue.

We *WERE* having some email issues earlier due to a bug in one of our email templates, but we fixed that. So the failed emails may have been a result of that bug.

**Comment by RobRuana** [comment]
Also, the following emails failed validation: 
* test@pirate
* test@pirate.asdfasdfasdf
* test@pirate.xyza

Whereas the following email passed:
* test@pirate.xyz

The difference being that "pirate.xyza" is not a valid domain, and "pirate.xyz" is.

**Comment by jcooter** [comment]
All of the delivery failures I've seen bounce back to us have been mailboxes that don't exist on major providers, so likely a typo in the front half of the address (which isn't something we can validate without looking like spammers)

**Comment by kitsuta** [comment]
This WAS a problem for MAG2017 (which is what Joel is referring to), but during the fest we had email validations added, so it's already been fixed. :)

**Comment by BlueHat-GURU** [comment]
Ah, thank you!
