### ISSUE TITLE
Extra donation description text looks weird

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2469]
![screen shot 2017-05-04 at 4 01 57 pm](https://cloud.githubusercontent.com/assets/2592431/25726685/52aeebc4-30f3-11e7-82f8-dc7c3503b22a.png)

**Comment by kitsuta** [comment]
Ha, whoops. Yeah, Magprime's repo adds a bunch of stuff via regextra.html. You might want to check the JavaScript console, see if anything broke -- most times when there's a JS error, all our positioning gets thrown out the window.
