### ISSUE TITLE
some django templates referencing variables that don't exist

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#248]
I only notice this when running with Django debugger turned on in Pycharm, but there are  variables being referenced that don't exist.

Django silently ignores these normally, but we should wrap them like this (example from common.js):

```
var csrf_token = "{{ CSRF_TOKEN }}";
```

to

```
var csrf_token = "{% if CSRF_TOKEN %}{{ CSRF_TOKEN }}{% endif %}";
```

Ideally we should always be running with strict debugging on to catch other kinds of errors.  This is a lint thing, low priority, but I'd like to fix it sometime on principal.

**Comment by EliAndrewC** [comment]
We've fixed the "stuff your IDE will never be cool with" and I think the Django template rendering is cool as-is so I'm gonna mark this as closed.
