### ISSUE TITLE
Attach consent form to emails accepting registration of minor

### ISSUE THREAD

**Issue by BlueHat-GURU** [magfest/ubersystem#2493]
sheva: Implement functionality to email minor consent forms to minors who register.
--disposition-- when a minor (probably just between 13-17) registers, attach the consent form to the acceptance email

https://docs.google.com/document/d/1UhcLdu6ShDq3mCRp0LwvKF15y0jw0CGTJQWhnXTwlec/edit?pli=1#heading=h.1we7756nij2t

**Comment by earl7399** [comment]
Attachments are a great way to propagate viruses/malware. I tend to delete e-mails w/PDF and/or DOC attachments.  Strongly recommend this NOT be done.

**Comment by thaeli** [comment]
Agree, do NOT use attachments, instead just add a link to download the consent form.

**Comment by kitsuta** [comment]
Oh, that's right, the folks at MFF found that our confirmation email is actually bugged. It checks for `attendee.consent_form` but needs to check for `attendee.age_group_conf['consent_form']`. So we all THOUGHT attendees were getting a link to the form but they weren't.
