### ISSUE TITLE
Please implement human-readable audit log for groups

### ISSUE THREAD

**Issue by BlueHat-GURU** [magfest/ubersystem#2495]
Have an audit log for groups too; This year we had a tremendous amount of fuckery with groups. I think Eli had to make two widespread changes to the production DB during fest trying to fix it. As a result, group dollar totals and member counts went wacky and required the reg manager's discretion to resolve in many cases. It would have been somewhat easier if those things had been logged. Even assuming the underlying bugs are now fixed, the lack of logging there means an admin could (intentionally or unintentionally) give free badges or take them away from a paid group, with no record of the action. So, in short, the use cases are problem resolution should something go wrong with the system, and error/fraud prevention.

https://docs.google.com/document/d/1UhcLdu6ShDq3mCRp0LwvKF15y0jw0CGTJQWhnXTwlec/edit?pli=1#heading=h.tgvqat3cgzzo

**Comment by earl7399** [comment]
Pretty sure this was done in https://github.com/magfest/ubersystem/pull/2345/

**Comment by kitsuta** [comment]
Yes, this is unfortunately the problem with gathering feedback months after the event. This was done weeks ago.

**Comment by BlueHat-GURU** [comment]
Less gathering, more consolidating.
