### ISSUE TITLE
Non-alpha characters in emails appear to be stripped on save

### ISSUE THREAD

**Issue by jcooter** [magfest/ubersystem#2512]
Steps to reproduce:
- edit an email address of an attendee to have a . (e.g. first.last@gmail.com)
- save attendee

Expected output:
Email address is saved as first.last@gmail.com

Actual output:
Email address is saved as firstlast@gmail.com

**Comment by kitsuta** [comment]
This is https://github.com/magfest/ubersystem/issues/2392. This happens only for periods, and only for gmail addresses, so it's not all non-alphanumeric characters. But yeah it sucks. :\

**Comment by earl7399** [comment]
*This is a bad plan*, IMO. I routinely send to SPAM anything that comes to
raearl@gmail.com - since anyone I've given my address to has r.a.earl, so
99.9% of the time it is just crap. We *really* should keep the address the
user gives us.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086
