### ISSUE TITLE
As an admin, I don't want to accidentally remove a band when checking their information.

### ISSUE THREAD

**Issue by gdreyband** [magfest/ubersystem#2523]
I don't know if this is an issue in the system already but it would be nice if you created a separate column or at least a bit of separation between the "Band Info" and "Remove as a Band" buttons.

![bands page](https://cloud.githubusercontent.com/assets/9372336/26755360/3ed8435c-4840-11e7-8f67-f5f9b1d30eaf.png)

**Comment by gdreyband** [comment]
I've gotten confirmation that it's a pretty minor thing to remove as a band and re-add them, so it's not a critical issue.

**Comment by RobRuana** [comment]
This was actually fixed awhile ago!
