### ISSUE TITLE
Kick-in levels do not look great

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2535]
![screen shot 2017-06-06 at 9 48 25 am](https://cloud.githubusercontent.com/assets/2592431/26832433/7367a144-4a9d-11e7-93a8-5935b1b04b8b.png)

**Comment by earl7399** [comment]
...and yet, I'm not sure they've ever looked better ...

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086
