### ISSUE TITLE
Email Volunteers a direct link to view their shifts, rather than requiring them to login

### ISSUE THREAD

**Issue by rscullin** [magfest/ubersystem#2546]
As a volunteer, I would like to not have to sign in to view my shifts when receiving an email about viewing shifts. The same email also includes a link that goes to my pre-reg info, which includes every bit of information I'd need to log in.

Instead, I would like to get a link that I can click and have it login for me so it is less effort to view my shifts.

**Comment by kitsuta** [comment]
Moving this to mid-epoch because shifts do not get emailed out till later in the year.

**Comment by rscullin** [comment]
Arguably this would be nice to have implemented by Labs -- initially reporting because this happened to me for MAGStock.

**Comment by kitsuta** [comment]
OK, I've looked into this and the only two emails I can find that match the description ("Please complete your {EVENT_NAME} Staff/Volunteer Checklist" and two reminders to sign up for shifts) should only be sent to volunteers with no shifts. You need to log in because you'd be signing up for shifts, not just viewing them. Can you specify the email you received, and what the circumstance was that you wanted to view shifts from the email?

**Comment by rscullin** [comment]
These are the two emails I received:

> Please complete your MAGStock Staff/Volunteer Checklist
>MAGFest Staffing stops@magfest.org via amazonses.com to me
>
>Robert,
>
>Thanks for signing up to volunteer at MAGStock!  You're currently assigned to the Concert Tent department, but let us know if you'd also like to work in any other departments.
>
>You can sign up for shifts at https://magstock7.uber.magfest.org/uber/signups/login and if you have trouble logging in, you can verify/update your personal information at https://magstock7.uber.magfest.org/uber/preregistration/confirm?id=aaaaaaa-bbbb-1337-1010-c0ff33
>
>You can add / drop / change your shifts anytime until 2:00pm EDT on Thursday, Jun 8.

> Last chance to sign up for MAGStock (Jun 2017) shifts
>MAGFest Staffing stops@magfest.org via amazonses.com to me
>
>Robert,
>Thanks again for signing up to volunteer at MAGStock!  You're not currently signed up for any shifts, and it's really helpful when our staffers sign up for shifts as far in advance as possible, since that lets us know which times and departments are shorthanded.
>
>Please sign up for shifts at https://magstock7.uber.magfest.org/uber/signups/login and if you have trouble logging in, you can verify/update your personal information at https://magstock7.uber.magfest.org/uber/preregistration/confirm?id=aaaaaaa-bbbb-1337-1010-c0ff33
>
>You can add / drop / change your shifts anytime until 2:00pm EDT on Thursday, Jun 8.


My initial report wasn't super clear, so let me try this again.

I got an email from MAG letting me know I needed to sign up for shifts/do a checklist (if I've signed up for shifts or not isn't relevant). That email has both a link to a page where I need to log in, and also a link to view all my registration details, which contains everything I'd need to know to log in.

Instead, I'd like the first link (login) to just auto sign me in and then let me view shifts / complete a checklist / etc, without making me enter information (email/zip) to sign in.
