### ISSUE TITLE
As a browser who's picky about HTML, I want new_base.html to stop including a TD inside a FORM tag

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2551]
We noticed this in a recent PR, but new_base.html has invalid HTML in the table. Full details here: https://github.com/magfest/ubersystem/pull/2534#discussion_r120379835

**Comment by RobRuana** [comment]
Minor note, the input `form` attribute is not supported by IE, but I don't think we care about that.

**Comment by kitsuta** [comment]
Yeah, I realized that some browsers don't support `form` cause it's an HTML5-only thing, but at the same time we use `form` in many other places in the codebase (including on that page, when we add fields via the magstock plugin). I think it's safe to say we're an HTML5 repo.
