### ISSUE TITLE
As someone up late at night, I'd like to not be confused by the organization of datetime.

### ISSUE THREAD

**Issue by migetman9** [magfest/ubersystem#2568]
@binary1230 should make a change on [ubersystem-deploy.md](https://gist.github.com/binary1230/2f4a61f24cef4180403b#file-ubersystem-list-md) to place MAGFest 15 into the 2017 year category, and move MAGFest 16 into a 2018 year category. 

My reasoning, the following picture, is simple, and should be self-explanatory.

<img width="494" alt="screen shot 2017-06-13 at 10 23 02 pm" src="https://user-images.githubusercontent.com/6538753/27116658-555d2710-5087-11e7-8b54-254fe51a5a21.png">

I mean, it literally says 2017 twice in the name.

**Comment by RobRuana** [comment]
This has been incidentally fixed by updates to ubersystem-deploy.md.
