### ISSUE TITLE
As a band, I want to be sure my panel is considered

### ISSUE THREAD

**Issue by gdreyband** [magfest/ubersystem#2573]
The user story in the description is contrived but if a band submits a panel idea, a few issues arise.

1) The band tech needs is not properly populated (I'm looking at SSB's panel right now) in the backend.

2) The band goes through a less rigorous process of panel submission than the real one so important information is left out like: number of additional panelists, "Have you held this panel before?", "When are you Unavailable" etc.

3) Because they're doing it as part of a checklist, the current placement makes sense. Also a checkbox is marked off when they indicate what they want (no panel, or yes with details).

4) Currently the panel submission gets attached to the band bio page (I only discovered one as a result of the changes to Uber's display in the Bands page), but it does not get through the official panels submission process (dumped into the panels section of Uber).

Proposed solutions:
A) Have the checklist page include the contents of the panels submission page. The most annoying thing will be packaging the contents of the panels page and then making sure if any links change, the change is reflected.

B) Duplicate the contents of the panels submission page entirely. Would probably be good if it was piped directly into the process so it doesn't get lost in the bands bio page and ends up in the panels.

**Comment by kitsuta** [comment]
Can you elaborate on 'not properly populated?' Do you mean that they select options and it doesn't go through, or that you aren't able to view them, or...?

**Comment by gdreyband** [comment]
If you go to the band details for SSB, it populated the panel description but not the panel tech needs which are checkboxes.

**Comment by RobRuana** [comment]
The band plugin has a separate `BandPanel` model class, which is totally unrelated to anything in the panels plugin. Part of the done condition for this issue should include a database migration which removes the `band_panel` table, and converts existing `BandPanel` objects to regular `Panel` objects.

Then we can use the same exact panel forms in the band plugin, and band panels will automatically be incorporated into the panels submission workflow.

**Comment by kitsuta** [comment]
Thanks to @Travis-Snoozy we got this working before a data migration was necessary for this year -- bands now get the same link that guests do, which is a specialized version of the panel application. See also https://jira.magfest.net/browse/MAGDEV-450.
