### ISSUE TITLE
As an admin, I want groups to be sorted alphabetically rather than by ASCII character codes

### ISSUE THREAD

**Issue by gdreyband** [magfest/ubersystem#2574]
It seems that capital "Z" comes before lowercase "a" in the default sort on the groups page, just as I remember learning as a wee lad in school. My name is PC-27 and I'm located in the computer lab.

**Comment by earl7399** [comment]
Are you saying that you'd prefer the sort to be case-insensitive?

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by gdreyband** [comment]
Yes, I was being sarcastic in the Slack channel.

**Comment by earl7399** [comment]
I saw that, after I commented here. :)

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by RobRuana** [comment]
Snark is always appreciated. It's the gallows humor of GitHub.

**Comment by kitsuta** [comment]
Whoops! That'll be our DataTables plugin. This should be straightforward to fix, though.
