### ISSUE TITLE
As a marketplace head, I want to limit the number of apps I receive

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2577]
Marketplace gets overwhelmed every year with hundreds of dealer apps. In addition to a date-based opening and closing of dealer apps, as a marketplace head, I want to also stop accepting dealer apps after a certain number of people have applied.

**Comment by ShevaDas** [comment]
Not to stick my nose in, but I saw this go by and had some thoughts, as someone who runs Marketplace for another fairly large event and has dealt with this before:

1) One dealer may submit many near-duplicate applications (either to try and limit competition or because they're "not sure if if went through the first time")
2) Depending on the limit of applications and how fast that limit is hit, this may skew the system in favor of people who are at their computer a lot and/or have no handicaps that would prevent them from quickly filling out and submitting an application
3) Dealers generally feel less satisfied with the process when there's a limit on application submissions

**Comment by kitsuta** [comment]
Those are all good points. I'm gonna tag @nickthenewbie1 in on this since I mostly wrote this as a way to get stuff written down from the meeting (this got brought up as a pre-prereg task). It's a request from our marketplace dept, but we should definitely consider those -- especially the dupe apps thing, since our system currently does not even care if you submit exactly the same app twice.

**Comment by thaeli** [comment]
I think an application fee would be fairly easy to implement. We could even implement it as a deposit that rolls over to their dealer fee if accepted, and refund if not.. though I'd prefer to say it's a non-refundable application fee or a "convertible to attendee badge" fee.

From what I've seen at other events that have used a fee, it discourages a lot of the people who you were going to reject anyway from applying, and some dealers whine about it, but it's not really a big deal. Look, if you can't afford the price of one badge to apply as a dealer, with a "if you aren't accepted it converts to an attendee badge" you have no business dealing at a major event anyway.

**Comment by nickthenewbie1** [comment]
Good conversation! Here's my thoughts on sheva's stuff:

1. To date, we've never had a significant problem with dupe applications, although we've never limited the number of apps either. I think that if we're worried about dupes then we should build a bit of overhead into the cap, and if we're worried about competition limiters, we should automatically reject any obvious attempts to do so.
2. We sort of already have that issue. Apps are evaluated both by timestamp and adjudication. They're evaluated in the order received, and many are passed over, but once all the "good enough" ones are accepted for a category of vendor, that category is filled up. There can be exceptions made for extraordinary applications submitted later in the process, but that kind of leap in quality rarely appears, so most of the "good enough" ones are a little tough to rank/differentiate in quality
3. Hmmmmm, any notable instances of this happening?

Thaeli:
I wouldn't be down with a non-refundable fee, but that roll-over deposit sounds like a fascinating concept.... We'd have to see if the marketplace team would bite, though...

**Comment by kitsuta** [comment]
By the way, one thing that hasn't really been discussed or made clear is what actually happens when the limit is reached. We have the built-in ability to auto-waitlist any new apps after a certain date -- would new apps be allowed but auto-waitlisted after a certain number?

**Comment by earl7399** [comment]
/me thinks that's the way to go

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by nickthenewbie1** [comment]
I agree. Should check with danielle though....

**Comment by RobRuana** [comment]
FYI, I think marketplace is considering putting the cap at 500 applications.

**Comment by kitsuta** [comment]
Was.. anything else discussed with marketplace? 😅

**Comment by nickthenewbie1** [comment]
Just caught up with her last evening! Beyond what's already in github, there were a few inconveniences/tedium that could be smoothed over. Prod me today on slack to get meeting notes

**Comment by dlenik** [comment]
Here are the notes from our meeting. Let me know if you can't access them! https://docs.google.com/document/d/1ojbbxmCIyLmT2Zf2yGZHVLamrOa32O1KDsmslCIIVZ4/edit

**Comment by kitsuta** [comment]
I can, @dlenik! Thank you!

**Comment by kitsuta** [comment]
OK, for our business processes, it's just gonna be a solid cap with an additional time limit (so 500 apps or 48 hours, whichever comes first). We're not currently worried about duplicate applications, especially with such a high cap. Anyone past the cap gets automatically waitlisted, so it's not as harsh as just not accepting applications past a certain number.
