### ISSUE TITLE
As a marketplace head, I want a multiselect list of categories for dealers to select on their apps

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2578]
This way a dealer applying for the marketplace can select themselves as, e.g., an "artist."

~TBD: What these categories should be.~

From the marketplace department:

### Artist/Vendor Categories 
* Video Games 
* T-shirts 
* Figures 
* General Merchandise 
* Prints 
* Plushes 
* Lanyards/Keychains 
* Pearler Beads 
* Jewelry 
* Bath Products 
* General Hand Made 
* Other Please Specify (Should be free-form text field)

**Comment by nickthenewbie1** [comment]
Is it possible/reasonable for this to be checkboxes? I imagine some dealers will have an existential crisis trying to classify themselves as a single thing.

**Comment by kitsuta** [comment]
Yup! Since it's just data for the admin to review, and we aren't doing anything fancy with it, they can be pretty much anything. We'll just have to run it by our marketplace head(s) first.

**Comment by kitsuta** [comment]
Oh, do we want this feature for all events or just for SuperMAG?

**Comment by RobRuana** [comment]
I would guess all events.
