### ISSUE TITLE
As an event runner, I'd like hotel room booking requests to be integrated into the preregistration process, so that the speed at which hotel rooms sell out can be managed

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2579]
This is a totally new feature in MAGFest's preregistration workflow, so we want to make it as visible as possible for attendees.

The current idea is to have a second page in the prereg workflow where an attendee can request a hotel room. Then, 18-24 hours after preregistration opens we'll send out an email to everyone that requested a hotel room. The email will contain a link where the registered attendee can book a room. 

The exact details of the link haven't been hammered out yet. It may be a link direct to the Gaylord's booking system, or it may be a link to a hotel info page on the magfest.org website (which in turn will probably point to the Gaylord's site?). The nature of the link itself isn't really important at this point, because it will be configurable and stored with our other secrets (see #2576).

Once the hotel booking emails are sent, the preregistration page will revert to it's current state (without the additional hotel step in the workflow). We'll make an announcement on the magfest.org website how any unregistered attendees can book a hotel room (if there are any still available).

It's critical that attendees don't accidentally miss the hotel room request option, which is why we are considering adding a full step to the workflow:

![mockup](https://user-images.githubusercontent.com/2592431/27411988-93974fea-56bf-11e7-8afa-b126c9032b36.png)

This issue is probably harder than it sounds. The preregistration code is dicey at best. There's automated emails to create, and we need to be able to toggle the hotel workflow on and off.

# NOTE

In order to keep the pull request for this issue small, I am breaking it up into two parts:
1. Implement the "Request Hotel Info" checkbox during preregistration (this issue)
2. Implement the automated emails that are sent to attendees that requested it (issue #2632)

**Comment by Hachi05** [comment]
Who is proposing this? Seems like a pretty radical departure from how we've previously manage hotel bookings.

I don't remember hearing about this before -- I like it, but think there should be some information gathering!

**Comment by RobRuana** [comment]
Also, this should be "opt-out", meaning the request a hotel room option will be checked yes by default.

**Comment by nickthenewbie1** [comment]
@Hachi05 we've been hashing it out with the hotel, promo, and reg team. A widespread announcement will be made in the next week or so to give everyone a heads up.

**Comment by RobRuana** [comment]
@nickthenewbie1 & @ShevaDas I have some followup questions on requirements:

1. Is this a simple [yes/no] request, or are we accepting requests for a number of rooms?
_(I would stick with simple [yes/no])_
2. Are we accepting requests for specific nights, or is this a general interest request?
_(I am guessing this is just a general interest request?)_
3. For group registrations, are we accepting a single hotel request for the group – perhaps for multiple rooms – or should each group member need to make an individual request for hotel space?
_(I would think each group member needs to make an individual request, and the leader is requesting space just for themselves during prereg)_
4. I need some input on the copy for this page (text for title, description, and checkbox):
![screen shot 2017-07-03 at 10 17 03 am](https://user-images.githubusercontent.com/2592431/27797060-39dce5c2-5fda-11e7-8a7b-b741e7367822.png)

**Comment by kitsuta** [comment]
We're only sending out booking links for the event's hotel, so I would definitely specify that this is for hotel space in the Gaylord. I think we might have the hotel name configurable somewhere.

**Comment by nickthenewbie1** [comment]
1. Yes/No. basically you're just telling them that you'll be sending them the link on information on how to book a hotel, which will not be publicly announced.
2. Not specific, it's general interest. See above
3. I think the best way to go about this is that when a group member claims their badge, they go through the same process as the group leader when the leader initially bought their badge (along with the rest of the groups badges which, at time of purchase, are yet to be claimed).
4.
"Would you like to be informed when hotel booking is available?"
"In an effort to help hotel availability, we will initially only release hotel booking information to people registered for MAGFest. Checking this box will put you on the list of people to receive this information  before it's posted publicly."
"Yes, tell me when hotels begin accepting reservations"

**Comment by nickthenewbie1** [comment]
I think it will be best to do this for ALL rooms. The link that we reveal will be the magfest.org hotel booking page, which will have a nonobvious url initially

**Comment by RobRuana** [comment]
# NOTE

In order to keep the pull request for this issue small, I am breaking it up into two parts:
1. Implement the "Request Hotel Info" checkbox during preregistration (this issue)
2. Implement the automated emails that are send to attendees that requested it (issue #2632)
