### ISSUE TITLE
As a developer, I don't want to have to fudge with the prereg opening date to work on issues

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2580]
I've encountered this about four or five times, so it's time to finally fix it. The function that redirects to the various "Prereg isn't open" pages shouldn't do so if we're on a dev_box.

**Comment by RobRuana** [comment]
My only concern with this is, how do we test that prereg dates & redirection are working on a dev box?

**Comment by kitsuta** [comment]
I was thinking about this too, but ultimately I'd rather turn off 'dev_box' temporarily to test that kind of thing (which rarely needs to be tested) than have to constantly fudge dates to test all other fixes (which need to be tested a lot).

One thing we could do is set a message on the prereg form to inform the developer that the form WOULD be turned off because of XYZ.

**Comment by RobRuana** [comment]
I'm not 100% comfortable with this. I'd recommend not doing it. 

However, on a scale of 1-5 of how much I care about this, I'm at like a 1 or 2. So, if you're more passionate about this than a 2, I say go for it!
