### ISSUE TITLE
Volunteer-specific fields are showing when they should be hidden

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2585]
The prereg form and confirmation page (and likely others) are showing volunteer-specific fields like "Where do you want to help?" and "I don't own a cellphone" when they should be hidden by default. Checking and unchecking the "Want to Volunteer?" box doesn't do anything. The oddest thing about this is that there's no JS errors, which are the most common cause of this sort of display error.
![image](https://user-images.githubusercontent.com/7198215/27458554-99012ede-5777-11e7-87da-1a9fb74dcc63.png)

**Comment by RobRuana** [comment]
Ah hah! It happened here: 90946b714e9a4a922f0645d03b8b9cae64098a2b. We just commented too much out :)
