### ISSUE TITLE
As an attendee, I would like to know how limited the current badge price is

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#2591]
Some form of text on the pre-registration page that says:

Availability of tickets at this price: [High|Medium|Low|Critical]

**Comment by nickthenewbie1** [comment]
What do we think about setting a milestone to this one?

**Comment by RobRuana** [comment]
How high is the priority on this?

**Comment by nickthenewbie1** [comment]
It would be especially helpful as badges are flying off the shelf during opening week, but I don't know how much effort is required for the rest off the issues in the milestone.
