### ISSUE TITLE
Unassigned Group Badge Collisions

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2609]
Reported by @iollan on slack: 

> We ran into an issue with the  Amazon group where if two people went into the group and chose the same unassigned badge without realizing it uber would record the information for both in the history but the last one to save would get the badge. It's probably better to explain in person but essentially we need to have uber lock an unassigned badge while someone is entering in the data. Aka mark the specific ID as read-only for anyone else.
>
> Happened in Prime 2016, may have been fixed, but I don't see in github.

**Comment by Iollan** [comment]
You've tagged the wrong person.

**Comment by RobRuana** [comment]
Ah, we have a user on slack with the handle @iollan. The flood of notifications  must have been incredibly frustrating for you.

Please accept my sincere apologies.

**Comment by kitsuta** [comment]
This is a very old bug. We now assign group badges when someone clicks 'save,' not when they click a certain link. This should no longer be an issue.
