### ISSUE TITLE
Emails: Add more send-from addresses for non-reg emails

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2611]
Reported by iollan on slack:

> A number of pending emails are associated with Registration that have nothing to do with Registration. Please adjust this to the appropriate department as Registration should not be dealing with bounced emails or questions for these emails. They are
> 
> Your tournament application has been received - Whoever is running the tournament or default magfest address
> Your tournament application has been approved - Whoever is running the tournament  or default magfest address.
> Your tournament application has been declined - Whoever is running the tournament  or default magfest address.
> MAGFest XYZ FAQ - Reg can answer some questions, but as we're not involved with making the schedule or layouts this should go to someone else like social media, etc.
> Last Chance for MAGFest bonus swag! - Merch
> MAGFest t-shirt size confirmation - Merch"

**Comment by kitsuta** [comment]
We'll need to gather the relevant email addresses before we can do this.
