### ISSUE TITLE
HTML -> Reg and Staffing

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2612]
Reported by iollan on slack:

> While those with at-con access only can access a person's history, they need Registration and Staffing access for HTML emails. This should be changed to at-con access so they can look at those emails as well.
> 
> This is from before Labs 2016. I don't know if it's been fixed and I can't find it in github.

**Comment by kitsuta** [comment]
While it wouldn't hurt to test it, this line should have fixed this bug: https://github.com/magfest/ubersystem/blob/master/uber/site_sections/emails.py#L20

**Comment by kitsuta** [comment]
Just tested this in staging2 (it's the only one in at-con mode right now) and this bug has indeed been fixed.
