### ISSUE TITLE
+1 Deadlines

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2613]
Reported by iollan on slack:

> If someone has an ability to have add a plus one to their registration (Guests, whatever) the confirmation email they receive should provide them with a link to a placeholder badge for their plus one. All placeholder badges created this way should have specific deadline, even the day before the fest is fine. This will prevent registration from having to add badges during the event.

**Comment by kitsuta** [comment]
I'll need to know more about the process of creating guests and their +1s to know how to approach this.

**Comment by kitsuta** [comment]
This is actually in the system now:
![image](https://user-images.githubusercontent.com/7198215/32986238-d1c863e2-cc9b-11e7-9388-8c69786947cc.png)
