### ISSUE TITLE
Purging Inactive Staffers

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2615]
Reported by iollan on slack:

> Regdesk has 217 individuals and only 123 have any hours in the department for Prime 2017.  Is there a way to compare our staffer list with those from previous uber instanances and remove inactive staffers. This is partially due to the next item, but also so that we can get a better idea of our staffing needs.

**Comment by kitsuta** [comment]
The import process is partially manual every year, so we just need to add a step in the importing process to remove departments if someone hasn't volunteered in that department for at least two years. I expect we'll be moving staff over with the CSV export/import, so this won't be a code change.

**Comment by RobRuana** [comment]
Handled by the import script
