### ISSUE TITLE
Emails: Changes to Confirmation Emails

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2618]
Reported by iollan on slack:

> Send FAQ to Attendees: All badge/group confirmation emails should have a line added that directs people to the FAQs. This will reduce commonly asked SupportBee questions.
>
> Parental Consent Form: With the new Child badges, we need to have seperate confirmation email specifically for this badge type that provides them a link to the parental consent form. Sending out a reminder email when it's not mentioned before it's helpful.
>
> MAGFest parental consent form reminder: Please change all references of waiver to form. We don't call it a waiver anywhere else.

**Comment by kitsuta** [comment]
The first and third items were taken care of in #2726. Waiting on more specs for the second item (i.e., what exact wording reg wants).
