### ISSUE TITLE
As a person running the Escape Room, I'd like a way for attendees to sign up for a time and a room during the event

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2627]
There's a few parts to this issue. 

On the admin side, some way to create a number of rooms with:
* titles
* descriptions
* locations
* time slots (start time/duration)

On the attendee side (probably as a kiosk page that is enabled during `AT_THE_CON`):
* some way to browse rooms & time slots
* some way to sign up for a room & time using attendee name/email address/badge number

**Comment by earl7399** [comment]
If we use Badge # for the sign-ups, we could auto-populate
name/e-mail/phone # ... and maybe ask if they want a text reminder some set
amount of time before their start time.

--
Bob Earl <r.a.earl@gmail.com>
FAX: +1 440 919 5086

**Comment by RobRuana** [comment]
I would also say we could easily make this support more generic sign-ups for other activities besides Escape Room. When the admin is setting up rooms and time slots, they would also enter a general category or activity name, like "Escape Room" for example.

**Comment by earl7399** [comment]
Do we already have something support tournament sign-ups? Because this
suddenly feels like it could fit that too...

--
Bob Earl <r.a.earl@gmail.com>
FAX: +1 440 919 5086

**Comment by RobRuana** [comment]
There is also [this issue](https://github.com/magfest/ubersystem/issues/2491) which would be very similar, but with online access before the event, instead of kiosk mode during the event. But very similar indeed.

We're definitely circling around an overarching generic system that would support both of these issues and other similar activities.

**Comment by RobRuana** [comment]
Dumping this here, need to review, clean up, and update...

# Escape Room Requirements

- Multiple Rooms with titles & descriptions
- Rooms need start times & durations (15 minute stagger start times)
- Will need volunteer staffing to oversee signup kiosks, rooms during games, and room reset after games
- Kiosk sign ups, using badge number (only at the con, not online)
- 5 per room (can support 6, but is discouraged)
- Waitlist, should it be per room, or one big waitlist? 
- Automated notifications like 15 and 30 minutes before start time
- Maybe notify waitlist people if any no-shows at the 5 minute pregame mark? Not sure
- Record groups start time, finish time, success/failure
- Limit sign ups to one slot per attendee, but can change slots if available
- No attendee should be able to play two games
- Able to sign up friends? Limit to one room (five signups)?

**Comment by thaeli** [comment]
+1 for a generic system. Artemis immediately comes to mind as yet another
user..

**Comment by RobRuana** [comment]
Notably, a generic sign up system would also work to mitigate huge autograph lines.

**Comment by RobRuana** [comment]
Calling this one done.
