### ISSUE TITLE
As someone creating teardown shifts, I want to schedule shifts after 6 hours on the last day

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2640]
Our teardown shifts are set up in a really strange way in config.py (https://github.com/magfest/ubersystem/blob/master/uber/config.py#L527):

```
c.TEARDOWN_TIME_OPTS = [(dt, dt.strftime('%I %p %a')) for dt in (c.ESCHATON + timedelta(hours=i) for i in range(6))] \
+ [(dt, dt.strftime('%I %p %a'))
for dt in ((c.ESCHATON + timedelta(days=1)).replace(hour=10) + timedelta(hours=i) for i in range(12))]
```

This code makes teardown shifts every hour for six hours after the eschaton (end of event), then for some reason skips the rest of that day and starts over again at 10am the next day.

It's unclear why we ever did that. It's been that way for a long time, but we probably want to change it to just making shifts from epoch till 10pm (or even midnight?) the next day.

**Comment by RobRuana** [comment]
It looks like setup shifts are defined in the same way. Basically makes it impossible to create a setup shift outside of the predefined window.

Done condition for this should probably include fixing setup shifts as well.

**Comment by RobRuana** [comment]
From gamma on slack
> Use case: I’d like to add setup for LAN at MAGWest from 8am - 12am on Friday
