### ISSUE TITLE
As someone typing a URL with capslock on, I want Uber URLs to be case-insensitive

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2644]
For example, https://labs2.uber.magfest.org/UBER results in a 404 but https://labs2.uber.magfest.org/uber works.

This isn't a huge deal, I just ran into this when manually editing a URL with capslock on by accident. I figured it would work anyway, but it didn't!

**Comment by binary1230** [comment]
this could be doable, but actually (from my limited experience) would be pretty non-standard for us to support it vs other websites

**Comment by kitsuta** [comment]
Huh, really? Well, we can close it if it's not standard. I guess most people don't type URLs (and mess up). :P

**Comment by RobRuana** [comment]
There is _some_ precedent for this. See
* https://www.reddit.com/r/asoiaf/
* https://www.reddit.com/r/ASOIAF/

Interestingly, https://www.reddit.com/R/asoiaf/ does NOT work.
