### ISSUE TITLE
Dealer application needs better address collection

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2649]
The address is required for tax purposes, and is submitted to the Maryland Comptroller. Dealers often leave crucial detail out of their address, like "123 Main St." and that's it. No city, zip, or state.

The address should be split into individual fields that are required. We should also add some verbiage indicating it should be the address they use for tax purposes.

We also need to support vendors from other countries, which may not have states, zip codes, etc...

**Comment by kitsuta** [comment]
We have some really solid address collection stuff already in the system. The tricky bit is gonna be just hooking it up to groups (right now it's attendee-based).
