### ISSUE TITLE
admin attendee edit: cell phone field not marked as required

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#265]
http://staging.uber.magfest.org/magstock/registration/form

add a new attendee, check 'is volunteering', don't type in a cellphone number

result: error message that says 'you must enter a cellphone number'

expected result: the cellphone field should be bolded once you check the box for 'is volunteering'

**Comment by kitsuta** [comment]
Fixed in... one of the many, many front-end refactors we've done in the past year.

**Comment by binary1230** [comment]
I seem to vaguely recall this still being an active issue, gonna re open just to be super sure.  If you're super sure, feel free to close

**Comment by kitsuta** [comment]
@binary1230 It's literally working as expected in MAGClassic staging right now.

To make it clear, my recent clean-up of issues is fairly definitive. If I wasn't sure if an issue was fixed, I either didn't touch it (that applies to most of the STOPS-related issues) or I left a comment.

**Comment by binary1230** [comment]
cool good stuff
