### ISSUE TITLE
Dealer application should indicate that the Website URL field is crucial info

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2650]
The current help text for the Website URL states:
> The one you want us to link on our website, or n/a

The marketplace department spends a lot of time trying to track down websites and images of the dealers' wares. This year they'd like stronger wording on for the help text, indicating that if the dealer does NOT provide a website with images of their wares, they'll be automatically waitlisted.

**Comment by kitsuta** [comment]
... harsh

More seriously though, I'd anticipate that this is gonna be a SuperMAG-only thing. @RobRuana shall I implement it in the magprime plugin?

**Comment by RobRuana** [comment]
I agree with your assessment - this probably belongs in magprime.
