### ISSUE TITLE
Add dealer group leader's info to dealer export

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2652]
The dealer's personal info needs to be included with the dealer export that is submitted to the Maryland Comptroller.

The dealer list must be submitted to the Maryland Comptroller no later than December 1, so this feature must be completed at least a week before that.

**Comment by dlenik** [comment]
@kitsuta this came up during sprint planning yesterday--I thought this had been completed over the summer, but looks like it's still here? we have to send in the information to the comptroller by Dec 1.

**Comment by kitsuta** [comment]
I... have no idea what this issue entails. Not really sure why I self-assigned this. Which export is this? Does just the group leader need to be included? What format should the info be in? How MUCH info should be included?

**Comment by dlenik** [comment]
So I thiiiiink this is the other half of https://github.com/magfest/ubersystem/issues/2649

Basically, we asked to have the fields added to the dealer registration form for comptroller/tax purposes, and we just want to make sure the information that was collected makes it into the export when we download it before Dec 1. Does that ring a bell?

**Comment by kitsuta** [comment]
Nnnope! :'D

Which export?

**Comment by dlenik** [comment]
I assume this issue refers to this export or one like it: https://super2018.uber.magfest.org/uber/summary/dealer_table_info 
(This is a .csv download called "Dealer Table Info" which looks like it's mostly used for marketplace admin purposes.)

It would be great to have an export that contains the following fields for dealers for comptroller purposes:
1. Vendor/Business Name
2. Point of Contact Full Name
3. Point of Contact Email Address
4. Point of Contact Phone Number (with area code)
5. Point of Contact Physical Address (full address incl. city, state, zip)

If it ends up being a new export, it could be called "Marketplace Comptroller Info" or something like that. Let me know if you have further questions!
