### ISSUE TITLE
MAGWest Uber: Change Name in Pending Guests Email

### ISSUE THREAD

**Issue by StephPrader** [magfest/ubersystem#2686]
Hi yet again,

In the Pending Emails (Email Categories) section in West's Uber, there's an email titled "MAGWest Guest Badge Confirmation." The text in this email is 98% perfect but the name needs to change. Please replace "Steph Prader" with "Ashley Watts" as the sender and change MAGFest to MAGWest Guest Coordinator. Here it is:
"Grant,

Thanks for coming out to MAGWest as a Guest!  We've added you to our registration database for your complimentary badge, but we don't have all of your personal information.  To ensure that you can pick up your badge with no hassles at our registration desk, please fill out the rest of your info at https://west2017.uber.magfest.org/uber/preregistration/confirm?id=45e85769-4dfb-4fec-b4ec-c37f20f90e10 and then simply bring a photo ID to MAGWest.

Please let us know if you have any questions.

 - Steph Prader,
MAGFest Guest Coordinator"

Thank you very much! ^_^;;
Steph

**Comment by kitsuta** [comment]
Config change! I'll do this right now.
