### ISSUE TITLE
Enable submit buttons on page load

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2696]
We disable submit buttons after they are clicked, which is a good thing as it prevents people from double-submitting forms. However, after submitting a form if you click the browser's back button the submit buttons are still disabled (at least in safari). Super annoying.

We just need a little javascript snippet that runs on page load that removes the disabled attribute from submit buttons.

**Comment by kitsuta** [comment]
Can't reproduce in Chrome, so this might be a Safari-only bug.

**Comment by RobRuana** [comment]
Interesting note about this – this is indeed a Safari only bug, however if only happens when you use Safari's "swipe to go back" touch gesture. If you click the back button, then the submit button will be enabled properly.

I'm inclined to close this as a bug in Safari. Trying to work around it will be more effort than it's worth; and will almost certainly be very brittle, with every new Safari update potentially breaking things again.
