### ISSUE TITLE
Preregistration wizard dots show the last step as completed with URL variants

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2697]
If you visit /uber/preregistration/ the dot for the last step is highlighted.

**Comment by kitsuta** [comment]
Possibly a Safari bug? It WFM on staging1 in Chrome.

**Comment by RobRuana** [comment]
Ah, steps to reproduce:
1. Visit https://staging1.uber.magfest.org/uber/preregistration/form
2. Fill out form and click submit
3. Now visit https://staging1.uber.magfest.org/uber/preregistration/

This bug is coming from the wizard macro I made, and I think sure I know exactly how to fix it.

**Comment by kitsuta** [comment]
Oh yea! Successfully reproduced. Thanks!
![image](https://user-images.githubusercontent.com/7198215/28388301-47eb30e2-6ca0-11e7-9e04-2e10ad388d44.png)
