### ISSUE TITLE
As registration staff for SuperMAG, I would like the system to correctly price child badges in groups

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2714]
Last year, groups calculated their prices simply by multiplying the number of attendees inside them by the current group price. This prevented attendees from having complex groups, like a group with a Child (half-off) badge in it. Instead, attendees had to email registration staff to get a child badge moved into a group.

It'd save registration a ton of hassle this year if instead the pre-reg page had some way of
1. Knowing what the DOB was of the people inside it
2. Charging the correct price for same

**Comment by earl7399** [comment]
Verbiage on the page would need to be exceedingly clear that they don't get
both discounts.

--
Bob Earl <r.a.earl@gmail.com>
FAX: +1 440 919 5086

**Comment by kitsuta** [comment]
AFAICT, a policy decision was made that getting a child discount means you don't count as a 'head' in a group.

It'd be nice if we could in the future have family groups that are just for ease-of-management for parents (i.e., no extra discounts), but that's another feature for another time.
