### ISSUE TITLE
Remove commas between words on shift admin page

### ISSUE THREAD

**Issue by ShevaDas** [magfest/ubersystem#2716]
![image](https://user-images.githubusercontent.com/3937986/28487840-8e90ccec-6e57-11e7-959f-642eec2ec1e2.png)

**Comment by RobRuana** [comment]
![captain-kirk-you-can-never-have-too-many-commas](https://user-images.githubusercontent.com/2592431/28487866-fb9d2266-6e68-11e7-8085-af8ef7ae2ef1.jpg)
