### ISSUE TITLE
As Registration staff, I want the hotel booking info email to have a different reply-to address

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2725]
Most people simply hit 'reply' to an automated email they get if they have a question about it. SuperMAG reg staff has asked us to change the reply-to address for the hotel booking info email so they don't get flooded with emails they aren't equipped to answer.

**Comment by RobRuana** [comment]
So... who should the reply go to?

**Comment by kitsuta** [comment]
No idea! :( Maybe use a generic contact email? I don't know what it is off the top of my head.
