### ISSUE TITLE
Hotel export functions need to use legal names, not preferred names.

### ISSUE THREAD

**Issue by outlaw-josiah** [magfest/ubersystem#2727]
The Mark Center/Gaylord format export functions in all uber instances need to be updated to use the legal name attached to a badge, not the preferred name. I imagine this is an easy fix, and is probably tied to the room assignment page. However, Labs needs it ready to go by August 1st, so the pressure is in time.

**Comment by kitsuta** [comment]
Yikes! I'll go ahead and do this right now.
