### ISSUE TITLE
Update text for badge type buttons

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2729]
Text for badge type buttons:

> _Group Leader: $40 per badge_
> _Register a group of 8 people or more. (Please purchase badges for children 12 and under separate from your group.)_
>
> _12 and Under: $25:_
> _Attendees 12 and under must be accompanied by an adult with a valid Attendee badge._

**Comment by earl7399** [comment]
For the group button - how will they know to e-mail us to get the child
badges manually added to their group?

--
Bob Earl <r.a.earl@gmail.com>
FAX: +1 440 919 5086
