### ISSUE TITLE
Test Bitcoin payments on dev server

### ISSUE THREAD

**Issue by ShevaDas** [magfest/ubersystem#2731]
After much discussion, we'd like to test using Bitcoin payments on an Uber dev server. If all goes well with the testing, I would like to accept Bitcoin when Super MAG reg opens.

The extent of the code changes, to my knowledge, would be adding the following line:

```data-bitcoin="true"```

to this file anywhere between lines 6-13: https://github.com/magfest/ubersystem/blob/391977f544ab179d6b313f250e6ff298bc41f9df/uber/templates/preregistration/stripeForm.html

@binary1230 suggests something like

```
{% if c.DEV_BOX %}
data-bitcoin="true"
{% end if %}
```

**Comment by RobRuana** [comment]
I love this idea! However, there's a good chance this won't get done before preregistration opens. If we don't get to it, we can do it right after the launch. Just managing expectations here.

**Comment by ShevaDas** [comment]
Works for me!

**Comment by RobRuana** [comment]
#2853 looks good for testing. I must caution everyone, that there is still a good deal of investigation & work before this moves to production.
