### ISSUE TITLE
As someone filling out the preregistration form, I would like clarification of the phone number field

### ISSUE THREAD

**Issue by cmchick** [magfest/ubersystem#2739]
On the `uber/preregistration/confirm` page, the **Your Phone Number** field is followed by a checkbox field "I don't own a cellphone." It is not clear if the latter is related to the former.

Assuming the latter is supposed to indicate whether or not the former is a mobile phone number, here are some possible solutions:
* have checkbox indicate "This is a landline phone number",
* have checkbox indicate "This is a mobile phone number" and adjust logic appropriately, or
* replace checkbox with radio buttons or a list with "Mobile" and "Landline" options.

Another way of looking at this problem:
A field labeled **Your vehicle license plate number** followed by checkbox "I don't own a motorcycle"

**Comment by kitsuta** [comment]
Dev note: This checkbox is for volunteers to opt out of an otherwise-required field. The field used to say "Your Cellphone Number" but was later updated.
