### ISSUE TITLE
As the person handling printed badges, I don't want barcodes to start with an equal sign.

### ISSUE THREAD

**Issue by ShevaDas** [magfest/ubersystem#2762]
If a generated barcode in the badge export CSV starts with an equal sign, when the file is opened in any spreadsheet editor it will think it's an invalid formula (in Excel, this displays as `#NAME?`).

Unless this is noticed and manually corrected, if any changes are made to the file, after saving the CSV will replace the barcode with the text `#NAME?` or some similar garbage.

Especially since multiple exports usually need to be generated, correcting this by hand is error-prone and time-consuming.

**Comment by binary1230** [comment]
alt thing: we should see if we can export directly in XLS format (without ever touching a CSV) to sidestep this issue.  I think i have an open ticket for that somewhere.  

I remember someone just tried this and reported it was a pain

**Comment by ShevaDas** [comment]
It kinda hurts my soul to export in a proprietary format, but that is potentially also an option. xlsx-writer might do the trick fairly easily.

**Comment by ShevaDas** [comment]
Since all barcodes now start with a ~, closing this.
