### ISSUE TITLE
As an admin for West Jam Space, I'd like to add content to the internal schedule

### ISSUE THREAD

**Issue by gdreyband** [magfest/ubersystem#2768]
Under the normal schedules dropdown page, admins can normally add time blocks for scheduled performances, panels and events. Jam Space doesn't currently exist but we have scheduled content for West this year so it helps to get a high level view of all simultaneous events.

**Comment by jcooter** [comment]
What room is the Jam Space in?  It appears that there's a convention for names on the west schedule that includes their location in parenthesis

**Comment by gdreyband** [comment]
Cypress

**Comment by RobRuana** [comment]
@jcooter with the clutch fix!
