### ISSUE TITLE
Attendees are somehow ending up with multiple copies of the same ribbon

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2775]
# Shopkeep, Shopkeep, Shopkeep!

<img width="776" alt="screen shot 2017-08-04 at 10 16 31 am" src="https://user-images.githubusercontent.com/2592431/28972668-89904c7a-78fe-11e7-8037-a6730121f0a2.png">

**Comment by kitsuta** [comment]
This happens when there are two inputs with the same name in a form. Do you have any more context?

**Comment by RobRuana** [comment]
If you check out the attendee list in super2018, you'll see tons of people with duplicate ribbons. I cropped the screenshot to remove personally identifiable info.

**Comment by kitsuta** [comment]
OK, this happens specifically when you save a dealer group in `groups/form`.
