### ISSUE TITLE
'add another prereg' button once disabled by stripe never becomes re-enabled

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#279]
1. Fill out preregistration form
2. Click 'Pay With Card'
3. Close Stripe window without paying
4. Observe 'Add another prereg' button does not get re-enabled

![image](https://cloud.githubusercontent.com/assets/5413064/3142225/15180d44-e9b2-11e3-9b8f-5bf14d62584d.png)

I'm guessing either this is just a quick bug or we did it on purpose in order to send some finalized data down to Stripe that requires DB changes thereby disabling the button.

**Comment by kitsuta** [comment]
Fixed by https://github.com/magfest/ubersystem/pull/1202
