### ISSUE TITLE
Add "Music" as a separate department in Uber

### ISSUE THREAD

**Issue by dlenik** [magfest/ubersystem#2797]
For Super, please list "Music" as a separate department in Uber.

From Phil (concert security head) and Brandon (music department head): "currently there is no actual Music Department listed in Uber and all of those staff are currently listed within Chipspace and Main Theater Operations." Brandon would like to be able to look at all of his staff together.

**Comment by kitsuta** [comment]
Should I assume that Brandon and Phil _don't_ want it listed on the registration form as a job interest (i.e., no random volunteers)?
