### ISSUE TITLE
Add Rock Island .pdf and deadline to Super band plugin

### ISSUE THREAD

**Issue by dlenik** [magfest/ubersystem#2804]
Rock Island heads would like performers to be able to view the RI information packet and deadline as part of completing their checklist. All performers must decide whether or not to use Rock Island by September 30.

[Rock Island Write Up 2018_ver.Aug1.pdf](https://github.com/magfest/ubersystem/files/1206271/Rock.Island.Write.Up.2018_ver.Aug1.pdf)

**Comment by dlenik** [comment]
For context, I will also be adding issues on behalf of RI heads (post-launch or semi-epoch--not super urgent) to actually collect info from performers who opt into Rock Island, e.g. item descriptions, images, prices, .mp3s, etc.

**Comment by RobRuana** [comment]
Fixed by https://github.com/magfest/bands/pull/88
