### ISSUE TITLE
potential launch blocker: group badge price calculations incorrect

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2805]
(sorry for hasty detail)

![image](https://user-images.githubusercontent.com/5413064/29086811-cdcaa836-7c41-11e7-9997-253fa31a2a3a.png)

$5959

Registration Complete

Congratulations! Your registration was successful.

Your credit card was successfully charged for $5959, and you will receive a confirmation email sent to you shortly. If you paid for other registrations, those attendees will get their own confirmation email.

https://staging4.uber.magfest.org/uber/preregistration/group_members?id=1b6b8f13-3fa8-4c80-9efb-5232a792d088

![image](https://user-images.githubusercontent.com/5413064/29086869-f8718618-7c41-11e7-9703-5068aa3dcf87.png)

**Comment by kitsuta** [comment]
For posterity, this was indeed a launch blocker. The prereg_payment function was (correctly) removing the amount_extra from the group.amount_paid and applying it to the relevant attendees instead, but the group's cost was set to `default_cost` ... which INCORRECTLY included everyone's extra money. So we weren't losing people's money, exactly, but we were double-charging them by accident. Whoooooops.
