### ISSUE TITLE
I would like people in certain departments to not receive automated volunteer emails.

### ISSUE THREAD

**Issue by outlaw-josiah** [magfest/ubersystem#2809]
Specifically Arcade-Crew. Would it be possible to put in a flag to drop people in that department when the automated emails are populated from the database of volunteers? Please include @tronster, @carrence, or @outlaw in the discussion on how that's possible.

We're also partial to a discussion on adding a new contractor badge type that functions as a staff badge without needing to activate the "I would like to volunteer" toggle.

**Comment by RobRuana** [comment]
Added "Arcade Crew" to `shiftless_depts` which was literally designed for this exact purpose.
