### ISSUE TITLE
As a volunteer at an event, I would like to only be able to sign up for shifts in departments that I'm assigned to

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2841]
This is either related to at-the-con mode or was broken recently, since otherwise this would have come to our attention before now. Probably the former, since `onsite_jobs` is clearly a different URL than what we'd using during prereg.

The long and short of it is, the shift signups page does not respect a volunteer's assigned or trusted departments -- it simply allows them to sign up for literally any open shift, even 'trusted' shifts. Oops.

**Comment by kitsuta** [comment]
This looks like the offending line: https://github.com/magfest/ubersystem/blob/master/uber/models.py#L1985

The confusing part is that all the relevant code seems to have been like this for at least two years. Was this always a bug? :/

**Comment by RobRuana** [comment]
Oof, I am not a fan of this construct: 
```python
self.session.query(Job).filter(*[] if c.AT_THE_CON else [Job.location.in_(self.assigned_depts_ints)])
```

I mean, it's totally fine, totally valid – just hard for my brain to process 😢 The asterisk before the ternary operator always throws me off. Maybe I should just get used to it?

I prefer something like this:
```python
job_filters = [] if c.AT_THE_CON else [Job.location.in_(self.assigned_depts_ints)]
self.session.query(Job).filter(*job_filters)
```

**Comment by kitsuta** [comment]
Yeah, I'm on the same page there. That line is too magical to exist.

I'm not sure how to proceed on this bug, though, because I don't know why it was like this in the first place. :(
