### ISSUE TITLE
Create a generic sign-up system

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2866]
This could be used to sign up for slots/times for:
* Autographs (We don't have an issue for this, but it's a valid use-case)
* Escape Room (https://github.com/magfest/ubersystem/issues/2627)
* Tournaments (https://github.com/magfest/ubersystem/issues/2491)

**Comment by EliAndrewC** [comment]
FWIW, I agree that this kind of generic system could be used for a range of things, like Escape Room, Tournaments, RPG Tabletop sessions, etc.  However, I'm extremely skeptical that such a system would work for Autographs, which has drastically different constraints and requirements.

**Comment by RobRuana** [comment]
Strong disagree.

**Comment by EliAndrewC** [comment]
Haha, I'm now very excited to see what you come up with!

**Comment by RobRuana** [comment]
I look at this as a opportunity to amaze and delight!

**Comment by RobRuana** [comment]
Calling this one done.

**Comment by EliAndrewC** [comment]
I am amazed and delighted!
