### ISSUE TITLE
Barcodes... to encrypt or not?

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2901]

**Comment by kitsuta** [comment]
I'm not entirely sure this is the best way to start an internal MAGFest policy discussion. :)

But my vote is a hard 'no'.

**Comment by RobRuana** [comment]
I also lean towards 'no' (though perhaps with less conviction 😄).

The reason I bring this up is because LAN straight-up will not use our badge barcodes for Super if they aren't encrypted. They'll revert to printing their own barcodes. Which is a workable solution, but I feel like it would be a lot of duplicated effort.

**Comment by kitsuta** [comment]
But they also were still printing out their own barcode when they DID use the badge barcode. Would they print out two barcodes if we stopped encrypting ours, or still just the one?

**Comment by RobRuana** [comment]
I think they'd print two, and stick one on the back of the attendee's badge. At least that's my understanding.

**Comment by RobRuana** [comment]
Also, MAGCon seems like a good time to really hash this decision out.

**Comment by kitsuta** [comment]
Strong agree!

**Comment by kitsuta** [comment]
@nickthenewbie1 pointed out that if we're going to eventually transition to RFID, we'll want a way to process a non-badge-number that's tied to the badge number anyway, so we aren't necessarily saving ourselves any work in the long run by avoiding this.

**Comment by RobRuana** [comment]
Marking this as done. We've decided we _are_ encrypting barcodes. We've also worked out the export format [here](https://github.com/rams/barcode/pull/16). We still need to make sure the registration scanning is rock solid, and fix up the API, but those are separate issues.
