### ISSUE TITLE
Tech Ops volunteer email text change

### ISSUE THREAD

**Issue by outlaw-josiah** [magfest/ubersystem#2902]
https://super2018.uber.magfest.org/uber/emails/pending_examples?ident=magprime_techops_volunteer

At this email, it references an email address that no longer exists. Please change "techops-heads@magfest.org" to "techops@magfest.org"

Thanks!

**Comment by kitsuta** [comment]
Looks like this got fixed by https://github.com/magfest/magprime/commit/c5b1786a94c10f611e8deb6d58272c919dc437e8?

**Comment by RobRuana** [comment]
Good catch! I assumed the reference I made in the commit would auto-close the issue. I guess that doesn't work across repositories?

**Comment by kitsuta** [comment]
It does work across repos, but I don't think it works in commit titles. Which is weird.

**Comment by kitsuta** [comment]
Oh wait, the commit actually has to be merged into a 'master' branch before it'll count! Here, I'll reopen this, and it should close when you actually merge the related PR.
