### ISSUE TITLE
Update available rooms on internal schedule page

### ISSUE THREAD

**Issue by dlenik** [magfest/ubersystem#2903]
We have two new locations where performances will be occurring for Super 2018: POSE Lounge and the Lobby Bar. I want to make sure the spaces appear on the internal schedule so they can later end up in Guidebook for attendees.

If possible, could we also get a checkbox like the one Panels has for "show only music rooms"? This is Main Concerts (Potomac Ballroom), Chipspace (Potomac Hallway), Jamspace (tent. Eastern Shore 1-3), Jam Clinic (tent. Chesapeake ABC), POSE, and the lobby bar.

https://super2018.uber.magfest.org/uber/schedule/internal

**Comment by dlenik** [comment]
Jamspace and Jam Clinic do not appear on the list either, so it's possible this is part of a larger task to include updating all spaces for Super 2018.

**Comment by RobRuana** [comment]
Fixed by 
* https://github.com/magfest/panels/pull/128
* https://github.com/magfest/production-config/pull/324
* https://github.com/magfest/production-config/pull/327
