### ISSUE TITLE
emails need event name attached to them

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#291]
A lot of them don't mention the event name and it's not easy to tell where they came from.

should use {{ EVENT_NAME_AND_YEAR }}

**Comment by EliAndrewC** [comment]
This has already been done; pretty much every email has ``c.EVENT_NAME`` in its subject at this point and has for some time.

There's a separate ticket for changing that to ``EVENT_NAME_AND_YEAR`` which we might want to do.
