### ISSUE TITLE
watchlist search is broken for firstname/lastname/email searches

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2942]
Don't quite have time to dig into the technical details here, but,

Repro: create a watchlist entry with the following info:
![image](https://user-images.githubusercontent.com/5413064/32742240-d6c10184-c876-11e7-9762-a75ac3ab125e.png)

Searches matching stuff in the first/lass/email fields doesn't work

Searches matching stuff in the reason/action column DO work.

**Comment by kitsuta** [comment]
Why a high priority? The typical workflow is to just search for the attendee -- if you have watchlist access, there's a tab on their details page that takes you to their watchlist details.

**Comment by binary1230** [comment]
I would say it's high priority because while doing some work updating the watchlist, I almost added duplicate entries and missed others being on the list already because the search box doesn't pick those fields, and it seems like it should.

It would be fine too if we hacked around it by having some text that said 'this field only searches the following fields: first/last/etc
