### ISSUE TITLE
Switch Panel Room Names on Schedule

### ISSUE THREAD

**Issue by StephPrader** [magfest/ubersystem#2946]
Heya! Could you please switch Panels 1 with Panels 3? Not the whole column, but just switch the titles? It'll read:
Panels 1
(Cherry Blossom Ballroom)
and
Panels 3
(Woodrow Wilson Ballroom)

That's all! Thank youuuuuu! ^_^;;
Steph

**Comment by StephPrader** [comment]
OH! also, sorry, please rename Panels 4? Reads as:
Panels 4
(Annapolis 1-4)

Phew, that's it for now! Thanks!
Steph

**Comment by RobRuana** [comment]
Done and done! Will take a few minutes to deploy...
