### ISSUE TITLE
*Urgent* Guest Plugin, Panels Preferred Times

### ISSUE THREAD

**Issue by StephPrader** [magfest/ubersystem#2952]
An actual major issue!
When looking at a Panel I can't see their preferred panel times. See? https://super2018.uber.magfest.org/uber/panel_app_management/app?id=e60de2d8-714a-467f-86d7-f9218111d852 - as an example. I don't know when they want to do it.
I just checked the .csv too and it's not on there. ;_; 
Please help! Thanks!
Steph

**Comment by RobRuana** [comment]
👍
