### ISSUE TITLE
Badge shifting assigned number outside of valid range

### ISSUE THREAD

**Issue by ShevaDas** [magfest/ubersystem#2954]
I ran the badge consistency check and noticed that one staffer had a badge with the number 53053. Looking at the history, this appeared to be an automatic badge shift from their original badge number of 305 (which nobody else had been assigned to after shifting to the new number).

DM me for staffer name (or just look for badge 305 in Uber).

**Comment by kitsuta** [comment]
When you changed the badge manually, that also got logged as an "automatic badge-shift," so this wasn't necessarily done by the system. The attendee (who has an admin account) could have changed it manually.

**Comment by ShevaDas** [comment]
That’s exactly what happened. Closing.

**Comment by kitsuta** [comment]
Well, the system should not be allowing just any logged-in admin to change the badge numbers now that the deadline is past... I thought? :(

**Comment by ShevaDas** [comment]
Allowing any admin to change the numbers is bad, allowing the admin in charge of manufacturing to change them is good. We already have an "expert mode" hidden in the export system, maybe we should just have an "expert" role that allows doing dangerous stuff like this and that only 1-2 people get.
