### ISSUE TITLE
As a coder, I wonder why there is not a  Coding department

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#2975]
It seems that at most events, there is an un-official Coding Department. Can we make it official? It might make it easier for folks who want to participate do so if, in addition to the spur-of-the-moment sessions there were a couple of scheduled time blocks (per day?) where at least one fairly knowledgeable coder was available to help, do a demo, help with a setup, etc.

**Comment by EliAndrewC** [comment]
+1 on this suggestion.  We have had coding shifts for the past couple of years, which I thing just got slotted into the Fest Ops department, but there's no real reason why we shouldn't have a separate department for it as you suggest!

**Comment by RobRuana** [comment]
There is already a Dev Ops department in production!

**Comment by earl7399** [comment]
So there is!
