### ISSUE TITLE
THIS WEEK PLEASE: Dealer Info for Comptroller

### ISSUE THREAD

**Issue by StephPrader** [magfest/ubersystem#3001]
Hiya! Can y'all please make a .csv pull that will include:
Dealer Name (probably Name of Group, actually)
Group Leader Name
Group Leader email address
Phone number
Street
City
State/Region
ZIP/Postal Code
Country

All only APPROVED dealer tables, please. There's a "Dealer Table Info" in the Sitemap, but it only gives me a fraction of this info, tho I believe they're all approved at least. Maybe update that if it already exists? If that's even a thing, I have no idea.

Thanks tons!
Steph

**Comment by RobRuana** [comment]
Related to #2652
