### ISSUE TITLE
Different lookups via API do not return the same data in the same way.

### ISSUE THREAD

**Issue by Tahvohck** [magfest/ubersystem#3015]
`attendee.lookup` and `barcode.lookup_attendee_from_barcode` do not return the same JSON string despite being effectively the same lookup. The only thing this really effects is my unit testing, but I'd rather not have to store duplicate data or otherwise post-process those. See the following error snippet:

```
======================================================================
FAIL: test_viaScannedBadge (tests.requestchecks) [Badge ~nE1GAw]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edward/projects/magbadge-2.0/backend/tests/tests.py", line 83, in test_viaScannedBadge
    self.assertEqual(apidata, sampledata)
AssertionError: '{"result": {"is_dept_head": true, "email": [777 chars].0"}' != '{"id": null, "jsonrpc": "2.0", "result": {"[777 chars]ue}}'
- {"result": {"is_dept_head": true, "email": "zachary.greenhause@example.com", "badge_status_label": "New", "badge_type_label": "Staff", "badge_printed_name": "", "last_name": "Greenhause", "ec_name": "", "cellphone": "(123) 456-7890", "staffing": true, "assigned_depts_labels": ["Arcade"], "ec_phone": "098-765-4321", "legal_name": "", "checked_in": null, "ribbon_labels": ["Department Head"], "shifts": [], "_model": "Attendee", "zip_code": "20853", "worked_hours": 0, "first_name": "Zachary", "id": "1010d5c7-988e-4c33-927e-b1a8fbc947b8", "weighted_hours": 0, "full_name": "Zachary Greenhause", "badge_num": 39, "food_restrictions": {"standard_labels": [], "freeform": "", "_model": "FoodRestrictions", "id": "59677aa6-51da-4d37-a041-7a90d259e0db", "sandwich_pref_labels": ["Peanut Butter"]}}, "id": null, "jsonrpc": "2.0"}
+ {"id": null, "jsonrpc": "2.0", "result": {"shifts": [], "last_name": "Greenhause", "email": "zachary.greenhause@example.com", "badge_printed_name": "", "ec_name": "", "legal_name": "", "id": "1010d5c7-988e-4c33-927e-b1a8fbc947b8", "ribbon_labels": ["Department Head"], "full_name": "Zachary Greenhause", "ec_phone": "098-765-4321", "worked_hours": 0, "zip_code": "20853", "assigned_depts_labels": ["Arcade"], "first_name": "Zachary", "checked_in": null, "badge_type_label": "Staff", "is_dept_head": true, "_model": "Attendee", "badge_status_label": "New", "food_restrictions": {"id": "59677aa6-51da-4d37-a041-7a90d259e0db", "sandwich_pref_labels": ["Peanut Butter"], "standard_labels": [], "_model": "FoodRestrictions", "freeform": ""}, "cellphone": "(123) 456-7890", "weighted_hours": 0, "badge_num": 39, "staffing": true}}
```
Line 1 in the diff is the result via `barcode.lookup_attendee_from_barcode`. Line 2 in the diff is via `attendee.lookup` (stored locally on my machine)

**Comment by RobRuana** [comment]
So, the data is actually the same, you just want it returned in sorted order?

Might I suggest the following
```python
self.assertEqual(json.loads(apidata), json.loads(sampledata))
```

**Comment by Tahvohck** [comment]
Yeah, doing that fits equality tests. That'll solve things for my unit testing, but I'd say that this is indicative of code duplication that could be removed/refactored.

**Comment by Tahvohck** [comment]
Never mind. Closing this, the data is being returned the same but order changed since I downloaded the sample data.

**Comment by RobRuana** [comment]
That's certainly a good thought!

The root cause of this issue is that the order of items/keys in a python dictionary is not guaranteed (prior to python 3.6). Both the `barcode` service and `attendee` service use the same code to serialize their result sets, but the data may be sorted differently due to python's underlying dictionary implementation.

We could sort all of the data on the server before we serialize it, but that incurs an unnecessary processing cost. I say unnecessary, because the assumption is that any client consuming the data will parse it and treat it as structured data, rather than a plain string.

**Comment by RobRuana** [comment]
Now that I think about it, I would imagine the order of the results from a repeated calls to a single API method will also vary over time.

**Comment by Tahvohck** [comment]
Makes sense. I was testing a new unit test, so I was skipping the old one. Was definitely a bad assumption.
