### ISSUE TITLE
As a DH I would like to make my shifts available to any volunteer

### ISSUE THREAD

**Issue by dlenik** [magfest/ubersystem#3016]
From Paul A/DDAL:
"I have some front desk shifts (mainly greeting, marshaling and data entry) and I would like their availability to be seen by any volunteer (not just people who check tabletop-DDAL), but I’m not sure if they can already see it or not?  How would I accomplish this?"

Rob suggested adding a flag that makes shifts accessible to the entire volunteer population (either on a per-department basis or on a per-shift basis).

**Comment by thaeli** [comment]
Do we really want this for everyone including staff in other departments? I'm a little concerned because Mag doesn't have a clear volunteer vs staffer distinction.

**Comment by RobRuana** [comment]
I think it could be configurable? Like, some jobs literally anyone could do. And some you maybe only want to open up to the general pool of staffers.
