### ISSUE TITLE
As an API Consumer, I would like HTTP Status Codes to match the status returned by the API

### ISSUE THREAD

**Issue by rscullin** [magfest/ubersystem#3026]
`attendee.lookup(badge_num, full)` will return a `200` status code, even if the returned JSON indicates an error because the badge was not found.

Ideally, lookups that fail due to the badge not being found should return the HTTP status `404` (?). I would like to make use of my language's `response.IsSuccessStatusCode` rather than try-parsing the returned JSON to determine if an error was returned.

**Comment by RobRuana** [comment]
This will likely not be changed.
