### ISSUE TITLE
Refresh View Recent At-the-Door Registrations After Mark as Paid

### ISSUE THREAD

**Issue by iollanmag** [magfest/ubersystem#3038]
Opened per conversation with Rob & Vicki:

At Labs 2017, when on the View Recent At-the-Door Registrations, whenever we clicked "Mark as Paid" we still had to refresh the page to enter in the badge number. Please add in a page refresh when "Mark as Paid" is checked.

**Comment by kitsuta** [comment]
We should try to get to this before Super, if possible.

**Comment by iollanmag** [comment]
Pretty please. I didn't know how to mark priority or I would have done that.
