### ISSUE TITLE
Need an "MIVS" or "Indie" Ribbon added to Registration data

### ISSUE THREAD

**Issue by LowPolyCount** [magfest/ubersystem#3046]
Hi, 

MIVS needs to add it's ribbon to the ribbons checkboxes in registration data.  The ribbon itself is brown and says "Indie" on them, so the checkbox can be called "Indie" or "MIVS", whatever would make things easier for onsite registration.

**Comment by iollanmag** [comment]
Please be specific and use MIVS. As Indie is a broad term that can be applied to other groups, and has been with MITS, that may want their own ribbons in the future, a specific ribbon name would be desired.

**Comment by RobRuana** [comment]
Do we have physical ribbons for this? I think the ribbon order is going out soonish.

@ShevaDas MIVS ribbons?

**Comment by LowPolyCount** [comment]
I did put a request for Ribbons in our department checklist

**Comment by RobRuana** [comment]
Nice!
