### ISSUE TITLE
Uber Schedule Column Title Changes

### ISSUE THREAD

**Issue by StephPrader** [magfest/ubersystem#3048]
Not really urgent but some ppl are still freaking about the toppers having incorrect info. So do whenever you like. Gonna go from left to right:

Forum - Chesapeake 10,11,12
Forge - Baltimore 3,4
Autographs Red - Expo E
Autographs Blue - Expo E
Games on Film - Chesapeake J,K,L
Starship Horizons - Maryland C
Artemis - Maryland C
LARP - Expo E
Zombie Tag - Magnolia 1
Jamspace + Community Curated Stage - Eastern Shore 1,2,3

And that should be it forever 2018.
Thank you!
Steph

**Comment by RobRuana** [comment]
Quick question, is "Jamspace + Community Curated Stage" two different toppers, or are you asking me to change the name "Jamspace" to "Jamspace + Community Curated Stage"?

**Comment by RobRuana** [comment]
Ok, I think these are all the requested changes: https://github.com/magfest/production-config/pull/342/files

**Comment by RobRuana** [comment]
Okay, we're going with "Jamspace + Community Curated Stage" as a single place. If that's not right, I can change it!

**Comment by StephPrader** [comment]
It's the same place. All in Eastern Shore.
