### ISSUE TITLE
As a logistics DH I would like to email attendee volunteers who have been assigned to my department

### ISSUE THREAD

**Issue by dlenik** [magfest/ubersystem#3054]
Logistics has a lot of unfilled shifts and recently added a bunch of "I'll work anywhere" attendee volunteers to their department. They'd like to contact those people (or the subset of those people who have not signed up for any shifts).

So they either want one of these custom emails for which they'll adapt copy for logistics (https://super2018.uber.magfest.org/uber/emails/pending_examples?ident=magprime_staff_suite_volunteer_food_interest) 

OR they would like to be able to pull a list of emails for their department vols.

Please contact Matt Beale (@MattBeale on Slack) for more info. He's also preparing copy for the email, whether he sends it through Uber or via an exported list of email addresses.

**Comment by iollanmag** [comment]
This is similar to https://github.com/magfest/ubersystem/issues/2616 where Reg would like to be able to pull a subset of emails for our staff, not the whole department.

**Comment by earl7399** [comment]
On the Staffer Summary page, there is a link to create an e-mail that goes to @EliAndrewC (probably need to change that!), and BCCs the e-mail address of all staffers in that department.

Will that work for what you need?

**Comment by earl7399** [comment]
On the Staffer Summary page, there is a link to create an e-mail that goes to @EliAndrewC (probably need to change that!), and BCCs the e-mail address of all staffers in that department.

Will that work for what you need? (sent to Matt in Slack as well)

**Comment by earl7399** [comment]
From Slack:
MattBeale It should. My main issues is general onboarding and getting up to speed with the current systems in place. I got a crash course from Deb and Ashley on the finer points of Uber this morning, so I think I good to go between this and what I learned earlier. Thank you kindly for the assistance!
