### ISSUE TITLE
watchlist 'activate entry' button broken and kinda confusing

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#3066]
1) add attendee
2) add an active watchlist entry that matches this attendee via first/last/email or some combo of those
3) edit the attendee, and click the 'watchlist entries' at the top menu bar on the attendee edit page

EXPECTED: the green 'activate watchlist entry' button is able to be turned on and off when you click update

ACTUAL: button is never turned on or off

This one's a little insidious because, as @kitsuta noted in issue #2950, it's only the UI on this page that's broken.  it does appear to actually updating the right fields behind the scenes in the DB - you can verify this by going to the main watchlist page and note the entry has been turned on or off.

it means you can accidentally turn OFF a watchlist entry without realizing it, which is potentially catastrophic from a security policy standpoint.

**Comment by binary1230** [comment]
did a little homework, gotta run, quick notes are:

this should probably be what is in watchlist.html at https://github.com/magfest/ubersystem/blob/a4619f51678eae1af3715c9b8078be5ad6442db8/uber/templates/registration/watchlist.html#L44

```
        <div class="form-group">
            <label class="btn btn-success">
                <input type="checkbox" name="active" {% if entry.active %}checked{% endif %} />
                Watchlist entry active
            </label>
            (If checked, this entry is active for ALL attendees. If unchecked, it's disabled for all attendees)
        </div>
```

backend needs to be reworked a little for this to work.

related to #2950 , I think we may also want to make it clearer what operations are operating on the global watchlist entry (the .active property) and which operations are operating on the _association of the attendee to a particular watchlist entry_

I have some ideas, will run by you guys later

**Comment by binary1230** [comment]
also some grid action to make this a bit more readable

**Comment by kitsuta** [comment]
Haha, so. The page still refers to `attendee.banned.active` -- the `banned` property for attendees used to pull down an actual watchlist item, so this was to access that item's `active` column. Now the `banned` property simply returns a list representation of the watchlist entries, so there's no active property of that. No wonder this checkbox broke.

Even better: at some point we also changed the `banned` property to only return _active entries_ -- this was for good reason (IIRC we use the `banned` property to determine whether or not to send an email, and we were getting false positives for deactivated entries), but this means that now deactivated entries won't even appear on this page! The dual-state nature of the checkbox doesn't even make sense anymore. Whoops!!
