### ISSUE TITLE
Update Registration Pending Emails

### ISSUE THREAD

**Issue by iollanmag** [magfest/ubersystem#3073]
I stripped out the most of the HTML to make edits but you can leave it in if needed. I'd like to approve these Monday 01/01 if possible.

**[MAGFest (Jan 2018) parental consent form reminder](https://super2018.uber.magfest.org/uber/emails/pending_examples?ident=under_18_parental_consent_reminder)**

Thanks for pre-registering for MAGFest.  Our records indicate that you are under the age of 18, and as such, you will need a signed parental consent form. If a parent/ legal guardian will be present at MAGFest, then they can sign the consent form when you pick up your badge at Registration in Expo Hall E. If a parent/legal guardian will not be at the event, the form may be brought pre-signed, however it MUST be notarized. We will not accept pre-signed forms that are not notarized. You may find the form at http://super.magfest.org/parentalconsentform.

If you are actually over 18, please update your age in our database at _**insert personalized link**_ prior to picking up your badge.

We look forward to seeing you at MAGFest 2018!

**[Check in faster at MAGFest: ](https://super2018.uber.magfest.org/uber/emails/pending_examples?ident=qrcode_for_checkin)**

MAGFest is coming up on January 4!

To help speed up check-in, please bring the 2D barcode below with you when you pick up your badge. You can print it out or display it on your phone.

Please note, however, that this code is not a replacement for your photo ID. You must still present your government issued photo ID when picking up your badge.

You may not pick up badges on behalf of other attendees, even if you have a copy of their barcode and ID.

_**insert bar code url**_

Registered attendees agree to the MAGFest code of conduct by picking up their badge. You can review the code of conduct anytime by <a href="http://super.magfest.org/codeofconduct">clicking here</a>.

Got a question? Most common questions are answered in our FAQ. Be sure to check the FAQ by <a href="http://super.magfest.org/faq/">clicking here</a>!

MAGFest has a no-refund policy for all registrations.  If for any reason you can't make it, we allow and encourage you to resell your registration up to the exact price you paid for it.  To transfer your registration to another person, send them  _**insert personalized link**_.

**Comment by RobRuana** [comment]
👍 will do!
