### ISSUE TITLE
Public jobs hidden in list of signed-up shifts

### ISSUE THREAD

**Issue by andygoth** [magfest/ubersystem#3247]
In order to see all my signed-up shifts, I keep having to reenable display of public jobs, then reenter the signed-up shift list. The public job display option keeps getting cleared, also I feel it should have no influence over the signed-up shift list.

**Comment by RobRuana** [comment]
Thanks for the report! Will look into it ASAP

**Comment by RobRuana** [comment]
Okay, this should be fixed and working as you'd expect!
* When viewing the shift list, you can toggle between hiding or showing public events
* If you've signed up for a public shift, then it will always show up in the event list with the \[Drop\] button, no matter what the state of the toggle is
* The "public shift" toggle no longer has any influence over the signed-up shifts list

**Comment by andygoth** [comment]
On 07/14/18 13:38, Rob Ruana wrote:
> Okay, this should be fixed and working as you'd expect!
> 
>   * When viewing the shift list, you can toggle between hiding or
>     showing public events
>   * If you've signed up for a public shift, then it will always show up
>     in the event list with the [Drop] button, no matter what the state
>     of the toggle is
>   * The "public shift" toggle no longer has any influence over the
>     signed-up shifts list

Checks good on all counts, thanks for the quick correction.

-- 
Andy Goth | <andrew.m.goth/at/gmail/dot/com>
