### ISSUE TITLE
Having 

### ISSUE THREAD

**Issue by Strrgzrrshawano** [magfest/ubersystem#3249]
As a Group Leader, I would like any user-interface pop-ups for making changes to appear in front of anything else so that they are able to be seen and interacted with. Example attached below where the 'gotta go west' logo interferes with this.

![inkederr0r_li](https://user-images.githubusercontent.com/10124852/42975515-7f2b802a-8b8a-11e8-8c45-d6fde46eb5ac.jpg)

**Comment by RobRuana** [comment]
The fix for this is live! You may have to clear your browser cache to get it to work though.
