### ISSUE TITLE
schedule page filter buttons not working (west2018)

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#3252]
on the west2018 schedule page, the filter buttons don't appear to work.

![image](https://user-images.githubusercontent.com/5413064/43591414-4b95d3fc-9641-11e8-92ee-19dddeaf7792.png)

expected: click 'music' or 'panels' and see just those columns
actual: click any button that's not 'all' and it hides all columns

**Comment by kitsuta** [comment]
The Other button still shows all the columns, which indicates that the system just doesn't recognize the music and panel locations.
