### ISSUE TITLE
Blue question marks on shift signup page don't expand

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#34]
The blue questions marks next to shifts are supposed to do 2 things:

1) when you hover your mouse over them, they'll show you the shift description as a tooltip

2) when you click on them, it expands the shift row to show the description

So #1 works, but I kind of forgot to implement #2 before we launched, and I haven't had time to fix it yet.

---
- Bitbucket: https://bitbucket.org/EliAndrewC/magfest/issue/34
- Originally Reported By: [ ](http://bitbucket.org/EliAndrewC)
- Originally Created At: 2013-11-23T21:55:39.130

**Comment by willmurnane** [comment]
See https://github.com/magfest/ubersystem/commit/d88a8091e8207dc05355698ed3925026f05f1f7a#commitcomment-9343494
