### ISSUE TITLE
implement banned staff list in puppet

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#343]
lots of config code changed in sideboard, ensure that we are both loading event.conf and production.conf to play nice with our puppet config.

**Comment by binary1230** [comment]
hey actually the new puppet refactor makes it easy for us to inherit one banned list across all magfest events, and keep it private.

we still need to stick the names in puppet and write them to the INI file though, but that part's easy.

**Comment by binary1230** [comment]
so this is 2 things:
1) a technical non-event specific issue where we implement the banned list in puppet (this issue)
2) a magfest-specific config issue where we insert magfest's banned list into our specific instance, which is here: https://jira.magfest.net/browse/MAG-110

**Comment by EliAndrewC** [comment]
Obsoleted by the new watchlist implementation.
