### ISSUE TITLE
If a staffer updates their badge via the confirmation page, they are changed to an attendee

### ISSUE THREAD

**Issue by BlueChillLabs** [magfest/ubersystem#3472]
When my registration was imported as Staff, I confirmed my info.  Later, I decided to buy a Supporter pack, and upon payment, my badge type changed from Staff to an Attendee with Volunteer ribbon.

This has happened in both Magstock 2019 and Magwest 2019.

**Comment by kitsuta** [comment]
Changed the title to reflect new findings -- this is not actually related to supporter packages directly but to the page that you buy supporter packages! 😰
