### ISSUE TITLE
Reg Marketplace Group Payment issue

### ISSUE THREAD

**Issue by Strrgzrrshawano** [magfest/ubersystem#3698]
Marketplace sellers are not able to see a means to pay (no 'click here to pay') option from either individual badge or group management page. Currently a reg-head can go to e-mails and find the link in history tab, use it to type in card info ourselves. Not sure why we can see it there but seller cannot. Sean says Vic may know that there is something she hid that wasn't considered regarding this.

**Comment by kitsuta** [comment]
When I tested this, I could see the payment button at the top of the dealer's page as expected. If this is still a problem, please DM me or email developers@magfest.org with an example group -- then I'll be able to look into it more thoroughly. Thank you!
