### ISSUE TITLE
Need to update references to virtual2021 to super2022

### ISSUE THREAD

**Issue by outlaw-josiah** [magfest/ubersystem#3785]
Hi! We noted recently that a few emails linking back to reggie (specifically the "you have a new account" email) direct to virtual2021.reggie.magfest.org as opposed to super2022.reggie.magfest.org. To prevent confusion, could we update some of these references so we don't have to blast out additional updates telling people to use the correct URL?

Thanks!

**Comment by kitsuta** [comment]
We ended up migrating to a new droplet so we could be sure it was actually set up correctly -- this also fixed the SSL error we were getting. Should be fixed!
