### ISSUE TITLE
Analyze last year's growth problem

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#382]
Last year (M12) there was a blizzard up north which we believe hurt our at-the-door prereg numbers.  We have enough data that we should be able to confirm this by checking the following things:
- how much higher this year was the percentage of people who paid and didn't show up?
- how much lower this year was our percentage of Saturday at-the-door badges?
- how were the zip codes of people who paid and didn't show up distributed?  were they especially clustered in the north where there was snow?
- how does the geographic distribution of no-shows compared to past years?  Is it MORE distributed to the north than usual, thus supporting the hypothesis that the snow hurt us?
- assuming that our at-the-door Saturday badges were lower as a percentage (I'm pretty sure they were but haven't checked), what was the geographic distribution of zip codes of Saturday badges for the past few years?  If they're clustered in the north then that would fit, otherwise the snow was probably not the reason for the drop

This would be a lot of work, but this is actually a pretty important question because last year was our lowest percentage growth since MAGFest 5-6.  (I'm not counting our attendance cap year.)  So if the snow DID hurt our growth then we can expect (absent more weather problems) larger growth this year.  If it didn't hurt our growth, we'd expect a lower percentage growth this year.

This will involve crunching data from the past several years, but we have the databases so it should be doable, just time consuming.

**Comment by thaeli** [comment]
Closing as part of post-M13 cleanup.

**Comment by binary1230** [comment]
https://jira.magfest.net/browse/INC-173
