### ISSUE TITLE
Issue with Editing Payment Form

### ISSUE THREAD

**Issue by JoshMackin** [magfest/ubersystem#391]
title: Issue with Editing Payment Form

steps:
1) https://staging2.uber.magfest.org/m13/preregistration/index - Pay With Card
2) Input information (ex: 1234 4242 4242 4242, 06/20, 656)
3) Position the cursor somewhere along the date or card number lines in attempt to edit(maybe the number 1234 was supposed to be 1233 or the date was supposed to be 07 instead of 06) 
4) Press backspace to delete character

observed result:
Deletes character where the cursor was positioned but then the cursor moves to the end of the string instead of keeping it at the deleted character

expected result:
For the cursor to stay in place instead of moving to the end of the line so that edits could be made at the desired position

recommended fix: 
To make it less confusing for the user when they need to edit the information, the cursor should stay in place after you delete a character. 

ALSO:

When you try to insert a character at the cursor, it inserts the character but then moves the cursor to the end of the line.

Editing the CVC works fine.

**Comment by thaeli** [comment]
Closing, Stripe fixed this a long time ago.
