### ISSUE TITLE
reset_uber_db is needed but doesn't work on non-dev boxes

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#395]
the issues is:
when installing uber for the first time, it creates the tables automatically, but does not create an admin user so there's no way to login

on dev boxes, you can run 
env/bin/sep reset_uber_db

but on non-dev boxes there is an ```assert DEV_BOX``` that doesn't let you run this.

options:
- make the script work even on non-dev boxes
- make the script not do anything if it detects that the Attendee/Admin table exists and there is already one admin user created

I ran into this issue when installing through puppet.

Whatever the fix is, I want to make sure that there is some really explicit action (like what we have now) that doesn't let you accidentally drop tables on a production database without some kind of crazy-ass warning.

**Comment by kitsuta** [comment]
Oh hey, this is actually addressed by the insert_test_admin URL that Dom put in on https://github.com/magfest/ubersystem/pull/1177 - I'll go ahead and close this.
