### ISSUE TITLE
Deleted exposed API Key

### ISSUE THREAD

**Issue by daredoes** [magfest/ubersystem#4226]
https://github.com/magfest/ubersystem/blob/d39b52e7edca20696f389351f293e50779c0e15d/uber/templates/map/index.html#L146

Apparently this key of mine from my junior days has been exposed. So that key is now deleted. You'll want to fix this to restore functionality to this part of the site if it's still used.

**Comment by kitsuta** [comment]
Whoa, I totally missed that there was a key embedded in the code like that. I'll convert it to a config value now, thanks a bunch for the heads up!

**Comment by daredoes** [comment]
@kitsuta the key is dead too, so a new one will need to be generated from a google cloud console on an account owned by the magfest google org
