### ISSUE TITLE
When typing in a new affiliate append "(add new)" to the selectable item in the dropdown box

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#431]
As you're typing in a new affiliate when kicking in (e.g. "Community I'm With"), the dropdown should be more clear that you are going to add that option if you select it: e.g. Community I'm With (add new)

**Comment by kitsuta** [comment]
Per #1228, this functionality is now straight-up broken.

**Comment by floraline** [comment]
For anyone looking at this in the future, #2857 does not attempt to fix anything that is broken. Broken functionality described in #1228 has already been resolved by 9bd109a.
