### ISSUE TITLE
restructure vagrant setup

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#453]
Sideboard + Uber + Vagrant setup is hacked up and kind of a mess.

With Vagrant, the folder structure on the host computer doesn't match that on the linux box, so debugging is problematic.

We should bite the bullet and restructure sideboard + uber correctly so that it works easier for debugging.

I'm not quite sure exactly how to do this yet, might look into it soon-ish.

I think in the end, what we might want to do is have a sideboard Vagrant config that then runs all the configs for any sideboard plugins inside the 'sideboard' dir.

Or, perhaps see if we can just use the existing puppet scripts to handle all this jazz.

**Comment by kitsuta** [comment]
This is pretty much covered with the planned docker deployment setup, so I'm closing this issue since it's redundant.
