### ISSUE TITLE
analytics currently broken

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#454]
For m13, we want the data from previous magfests.

For any other ubers, we just need to show the current year's data.

I had some SQL stored procs that we used to use, though really we should probably be doing all that heavy lifting inside ubersystem vs in the DB.  Here are the old procs:
https://gist.github.com/binary1230/e30abced34e462dcd07e

-Dom

**Comment by kitsuta** [comment]
@binary1230 this is now covered by the analytics plugin, yes?

**Comment by binary1230** [comment]
Yea though that module is I think currently broken, however, that's an issue in that plugin so yea, close this.
