### ISSUE TITLE
EVENT_NAME_AND_YEAR doesn't have year in Magfest 13

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#464]
https://github.com/magfest/ubersystem/blob/f331502bf7d136f31be10c98ade0ce6c80ffccc8/uber/templates/emails/daily_checks/duplicates.html

{{ EVENT_NAME_AND_YEAR }} returns "Magfest", I guess we never setup "Year" in development-defaults.ini

low priority thing, just makes the duplicate registration emails easier to read.

**Comment by kitsuta** [comment]
A config issue that is no longer relevant.
