### ISSUE TITLE
trying to create admins when they are set to register themselves and no email was provided fails in a confusing way

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#492]
In ubersystem, when you want to add someone as an admin account, you have to first add them into the system as a regular attendee.  Once they are a regular attendee, you can promote them to a full administrator.

The bug here is that if you add an attendee without an email address, they (confusingly) don't show up as an option to add them as an administrator.

This is because the system won't let you add an admin without an email address, because it needs to send an email to that person to get them a link they can use to login.

How we should fix it:
1) Make people without emails show up in the list by modifying the database query
2) When we try and add anyone as an admin, check to make sure they have a valid email, and if they don't, display an error message saying 'this attendee needs a valid email, please fix'

Reproduce steps:

Go to People -> Attendees:
![image](https://cloud.githubusercontent.com/assets/5413064/8056486/ab701b26-0e76-11e5-8cc7-5f761adab5bb.png)

Click top-level 'Add Attendee', fill in the following:
1) First name: Cool
2) Last name: Guy
3) check the checkbox for 'register themselves'
4) leave email field blank

![image](https://cloud.githubusercontent.com/assets/5413064/8056480/95d124c2-0e76-11e5-9712-bb9e123347b5.png)

Click top-level 'Accounts' link:
Click the dropdown that shows attendee's names:
![image](https://cloud.githubusercontent.com/assets/5413064/8056510/fdfc83ca-0e76-11e5-8f3b-df692960daac.png)

EXPECTED BEHAVIOR: Cool Guy is shown in the list.  If you select 'Create Account' it should fail with an error message that says 'Cool Guy' doesn't have a valid email address, please add one first.
ACTUAL BEHAVIOR: Cool Guy does not show up in the list.

Tech notes
===

This line here is the DB query:
```python
Attendee.objects.exclude(email='')
```

To return an error message to the user, you need to pass 'message' to the template engine something like this:

```python
return {'message': "can't create an admin account for user because attendee doesn't have a valid email address set, please set one first" }
```

-------
(low priority cause this is kind of an edge case, but documenting nonetheless)

**Comment by binary1230** [comment]
Going to have Brian work on this one.

**Comment by Lusarien** [comment]
Hey Dom <- Brian

**Comment by kitsuta** [comment]
That PR was merged but this didn't get closed out for some reason - @binary1230 is this fully handled by #1134?

**Comment by binary1230** [comment]
confirmed this is fixed, I actually ran into it myself the other day :)

this solves my PICNIC issue.
(PICNIC - Problem In Chair, Not In Computer)
