### ISSUE TITLE
Replace email regex with more robust email address validation

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#527]
an email address of this form was accepted as valid from an attendee filling out the form:

email@whatever..com

note the incorrect ".." there.  our regex didn't catch this.

**Comment by kitsuta** [comment]
As mentioned in the related PR, the preferred solution to this bug is to implement a real email checker, like https://github.com/mailgun/flanker

**Comment by Utilityman** [comment]
type="email" in the html should do it

source: http://youmightnotneedjs.com/

**Comment by kitsuta** [comment]
Having tested that email validation, it seems to be incredibly basic. It's a good first step but I wouldn't consider this issue fixed just by that.

The thing I'd prefer to do is use Mailgun's email validation API, which offloads validation to someone that specializes in it. They offer a jQuery plugin.
https://www.mailgun.com/email-validation

If we don't want to sign up for a mailgun account, we can use this regex:
http://emailregex.com/
plus this domain verification plugin:
https://github.com/mailcheck/mailcheck

This will catch a lot of the easy stuff.

Ultimately though, the Real Solution to this is to use two email address inputs, verify them against each other, and then use a confirmation email. That's out of the scope of this issue though.

**Comment by EliAndrewC** [comment]
Agreed on ``input type="email"`` not being robust enough for our needs.  The python libraries I've seen linked in this thread all look decent, but ``flanker`` doesn't fill me with confidence w.r.t. Python 3 support (it's docs just say "built for Python 2.7").

The one I'd recommend is https://github.com/JoshData/python-email-validator which looks the best out of all the ones I've used.

@khyperia: can you tackle this one next?  You've already done some validation stuff, so the only extra part will be adding a new software dependency in ``requirements.txt``... plus we should also probably add some code to the ``normalize_email`` function in ``uber/utils.py`` which saves the canonical form using this library.

**Comment by thaeli** [comment]
Yeah, I agree with python-email-validator.

**Comment by thaeli** [comment]
Also, this is JS but looks easy to port.. it is a much more comprehensive email normalization library.
https://github.com/iDoRecall/email-normalize

You should definitely use the normalization in python-email-validator too, it does a bunch of important Unicode normalization while email-normalize fixes up common webmail provider email "dots and pluses" stuff.

**Comment by thaeli** [comment]
Another thing to think about: Should we drop the + part of emails before storing, or should we store it (so emails sent will still respect tagging that users might have via their email address) and just normalize every time? I think we can probably just drop it but is that a jerk move?

**Comment by EliAndrewC** [comment]
We should *definitely* keep the stuff after the ``+`` since dropping that is something that spammers do, and we know for a fact we have attendees who say ``+magfest`` in their GMail addresses they provide for us.

**Comment by kitsuta** [comment]
These both look good. I expect we want to drop the + stuff not for email-sending but perhaps for duplicate checks, searching, and some other usability things. I dunno if we wanna use both though.

**Comment by thaeli** [comment]
OK, definitely keep and then process for drops only when checking for dupes.

We need both because they fix *different things GS* about incoming emails.
One is going to make my novelty emoji domains not blow up the system and
the other will help with Gmail duplicates.
