### ISSUE TITLE
Dealer emails show total calc'd cost instead of what's actually owed.

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#529]
The dealer_approved.html uses ```group.total_cost``` to tell the dealers what they owe.

This however, is the total COST which is calculated from the incorrect numbers.

    @property
    def table_cost(self):
        prices = {0: 0, 0.5: 0, 1: 125, 2: 175, 3: 225}   # WRONG PRICES FOR 8.5!!!
        total = 0
        for table in range(int(self.tables) + 1):
            total += prices.get(table, 300)
        return total

    @property
    def total_cost(self):
        return self.table_cost + self.badge_cost

This is not what they actually OWE that takes into accounts payments already made including in cash, and any kind of custom deals Danielle made if group.auto_recalc isn't set.

------

I think the right fix is to just change dealer_approved.html to display group.amount_unpaid instead which is the following:

    @property
    def amount_unpaid(self):
        return (self.amount_owed - self.amount_paid) if self.id else self.badge_cost

-Dom

**Comment by EliAndrewC** [comment]
We just confirmed that we are NOT using ``group.total_cost`` in any of the group emails any longer, so we're closing this as resolved.
