### ISSUE TITLE
Stripe privacy settings

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#548]
When we point uber at registration/register (registration.py register()), having multiple attendees use Stripe sometimes saves numbers and emails and stuff.  We need to see if there are any Stripe settings to disable that, and also contact Stripe support to see if they can add in some options for us.

On-site so I am being brief and vague, but issue needs investigation, along with our entire at-door workflow.  Things could be easier and more obvious for reg staff to figure out how to operate uber vs remembering a bunch of different URLs

-Dom

**Comment by kitsuta** [comment]
I think this is actually being solved by TechOps, who will be disabling the public registration computers' autocomplete.

**Comment by thaeli** [comment]
Migrated to RAMS Refactor issue tracker as T13.
