### ISSUE TITLE
Order system for food

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#55]
Snippet from an email from Jenn Truss (Ian assures us that the chef suite WILL have intranet access this year):

A special request. We are trying to fine tune our food delivery set up. The wish is to incorporate into Uber a food delivery order ability. Each department will have until a certain time to place food orders and we will make deliveries during a specified time before service. If and when we have people free up during service, we will open to make additional deliveries. I was wondering if it would also be possible to incorporate into this the ability to know who, by badge number, qualifies to be fed. Even if this could work with the scheduling system some how, that would be great. Especially so if we are able to somehow get access to Uber from the Staff Suite to use with a check in system to help track numbers and make sure no one is double dipping before we run out of food.

Feel free to let me know if you have any questions. I have actually been working on a check in system to be written in either ColdFusion or a Flash application to run locally. We would just like to coordinate better with STOPS to help make food delivery and service go smoother and keep everyone happy. (well, as best we can)

---------------------------------------
- Bitbucket: https://bitbucket.org/EliAndrewC/magfest/issue/56
- Originally Reported By: [ ](http://bitbucket.org/EliAndrewC)
- Originally Created At: 2013-12-01T05:36:59.359

**Comment by bds002** [comment]
I think with Staff Suite's on going work, this issue has become obsolete?
@Jenny True?

**Comment by JennyTruss** [comment]
Yes it is. Especially since on shift food is changing this year
