### ISSUE TITLE
De normalize badge sales from attendee table

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#552]
A useful step towards making a multi event compatible  db might be to decouple badge sale data, shirt info, and other info from the attendee table. Attendee table would then just be an attendees personal info and that's it

This is probably a very large change that would need a ton of testing.

Might also be useful to help with accounting and refunds to treat badge tshirt vendor etc sales as items in a shopping cart and they get totalled up to form the final amount owed. Could make customization for other cons easier too

More later

**Comment by thaeli** [comment]
Closing as part of post-M13 cleanup - major refactors of badges has been moved into the RAMS Refactor issue tracker.
