### ISSUE TITLE
Feature Request: Add staffer shift information to Notes for Later Review

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#560]
From Carla:

>I found the link for the "notes for later review" >https://half.uber.magfest.org/magfest_85/registration/review
>
>but I can't find the link for the report of staffers and their shift ratings and comments (for A+ and shifty eyes). 
>
>Can we get a report that is a clickable link of staffer name, shift rating comments, and notes for later review all on one page? That way we can check against the 13 database.

**Comment by EliAndrewC** [comment]
This has been implemented: https://prime.uber.magfest.org/uber/summary/ratings
