### ISSUE TITLE
"Attendees checked in" on summary page gives the wrong number

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#607]
On https://prime.uber.magfest.org/m13/summary/index

"Attendees checked in: 5180"

Um, no they aren't. P: It's pre-con!

**Comment by kitsuta** [comment]
I actually fixed this in ac-staging - the culprit is here:
https://github.com/magfest/ubersystem/blob/master/uber/site_sections/summary.py#L15

You'll note that it's looking for `checked_in=None` which is literally the opposite of what it ought to be doing.

**Comment by EliAndrewC** [comment]
This was fixed in the recent performance refactor.
