### ISSUE TITLE
Summary page doesn't include all payment types

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#608]
In https://prime.uber.magfest.org/m13/summary/index

The data looks like:
```
Badge Type	Paid Badges	Unpaid Badges	All Badges
Attendee	  (some number)     (another #)  (more than the first two #s)
```

Columns that don't actually add up is confusing - it makes it look like there's a discrepancy. In reality, the table just isn't enumerating all the different types of payment. It totally should!

**Comment by EliAndrewC** [comment]
This was fixed in a recent performance refactor.
