### ISSUE TITLE
from room assignment page, reveal data/allow edit of volunteers who are assigned to a room in another department

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#61]
deferring this to next year

---------------------------------------
- Bitbucket: https://bitbucket.org/EliAndrewC/magfest/issue/62
- Originally Reported By: [ ](http://bitbucket.org/hachi05)
- Originally Created At: 2013-12-02T06:47:15.433

**Comment by bds002** [comment]
I think for M13 - somewhere along the way we trashed keeping staffers hotel room linked to the departments they where assigned.  That should resolved this particular issue - @EliAndrewC

**Comment by EliAndrewC** [comment]
That's true, so this can be closed as OBE.
