### ISSUE TITLE
ensure that under-5 badges can be reg'd for free on the site

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#655]
at magfest, kids with badges under 5years old reg for free.

Can they prereg? 

If not, just thought of this interesting scenario:  Parent brings non-prereg'd kid to Magfest and if we're capped out, they won't be able to register them at the door.

We should test that you can register and not pay for a kid under 5 years old in prereg in the event that we have a cap to deal with.

We probably don't have to deal with this this year, but we probably will for next year.

**Comment by EliAndrewC** [comment]
This was implemented this year.
