### ISSUE TITLE
Retrieving past Staff History if staffer was dropped from Auto Import

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#664]
Based on a Conversation with Eli - Here is the scenario:
There is a History link for staffers so we can go back and look at what Emails they've received, their hours worked for past magfest etc etc
I have  staffer -- barnaby.yeh@gmail.com
That staffed M11 (30+hours)
So in the M12 database there is the long list of Emails and hours he worked etc etc....
He has no recorded shifts for M!2.. so he was dropped from the M13 datatbase...
When he added himself as a paid attendee for M13 the history was blank...
It would be nice to have things linked to EMail addresses maybe so it pulls from 1 or 2 years back..... I can see the issue with people changing EMail addresses as well....
--- Eli:  Hmm, yeah I see what you're saying.  Ideally we'd have an easy way to link histories from past years to this year.
--- me:  But that is probably the exception... not the rule since most staffers repeat year to year... it would only be handfull I would think that it might affect
-- Eli:  So here's what we could ideally do:
- staffers imported from past years have their histories like they do now
- in addition, we keep a record of ALL "histories" from the past year around but not linked to anything
- on the history page for an attendee, we check the name and email address of all of the unlinked histories
- if there's a history which matches, there's a button that's like "Hey do you want to link this history to this guy?"
I mean, this is the exception, but at the same time, with like 500 staffers even if this is only happening like 5-10% of the time, that's dozens of people.
--- me:  yeah... so how do I write that all up as a Github case?
--- Eli:  Simplest thing would probably be to open a Github issue and just literally copy/paste this conversation.  Since it already has all the info someone would need to understand the issue and see what we're proposing to fix it
-- me:  Ok will do.

**Comment by EliAndrewC** [comment]
This was fixed in the M13->Mag2016 import, and for next year we'll have a broader solution so I'm closing this.
