### ISSUE TITLE
Email when someone requests to volunteer in Food Prep

### ISSUE THREAD

**Issue by JennyTruss** [magfest/ubersystem#669]
Please have this email automatically send out to anyone that requests to volunteer in Food Prep. This has already been sent to anyone that has requested as of 11/3/2014 at 11 am.

------------------------------------------------

Hello!

Thanks for not only signing up to volunteer at MAGFest, but to volunteer with the Staff Suite. If you are confused, then allow me to explain. When you signed up to volunteer, you either checked any or specifically checked “Food Prep” as a requested department to work in.

If you are not familiar with the Staff Suite, it’s part of the perks of volunteering. We are the ones who cook and provide the 3 meals a day, as well as snacks and drinks. Your job could range from checking badges to make sure people are allowed in there, to serving food, to keeping the suite clean, and maybe even possibly prep and cook food. 

If you are new to the Staff Suite, please keep in mind that you will not be handed a knife and a spatula and told to cut and cook. We do have a system in place that requires volunteers to work their way up into the staffer ranks and become trusted staff within the Staff Suite. This does require impressing at least 2 senior staffers with your work ethic, teamwork, and customer service.

If you are still interested in working us, then GREAT! Just send us a small blurb on why you should work with us why you think you are qualified. If you have worked with us in the past, then let us know and the most memorable time of yourself with us.

If you are no longer interested in working with us, please let us know as soon as possible, and we will get that corrected within the system. This will mean that you will not be able to see Food Prep shifts to sign up for.

Please email jennifer.truss@gmail.com with your reply. Any questions, just let us know!

Thanks!

MAGFest Staff Suite

**Comment by kitsuta** [comment]
I've fixed this in the magprime_emails repo.
