### ISSUE TITLE
remove hard coded reference to CHALLENGES from base.html

### ISSUE THREAD

**Issue by ksonney** [magfest/ubersystem#677]
The hard-coded "HAS_CHALLENGES_ACCESS" call in templates/base.html requires that a matching job_location exist in the ini files. This should be made configurable so that non-mag events, or events without challenges are not required to have this job location.

**Comment by kitsuta** [comment]
We've had several refactors since anyone looked at this issue, and there's no longer any reference to `CHALLENGES` in base.html.
