### ISSUE TITLE
Merge State and global constants into "c" object

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#678]
Tagging this with "next year" because it's just an internal refactor.

Currently there are two types of global setting objects:

1) For static values we just have global variables everywhere like ``ATTENDEE_BADGE`` and ``PANELS_3`` and ``SHIFT_WORKED`` etc.

2) Sometimes we want convenient variables we can refer to in our program logic and also in our template code like ``BEFORE_PLACEHOLDER_DEADLINE`` or ``BADGES_SOLD_OUT`` and such, but those aren't static constants because they depend on the current time and the state of the database.  So we make them properties on a global ``state`` object, whose fields we extract as template variables.

Our global constant variables are dynamically jammed into the ``constants`` module namespace, which is okay in and of itself, except that
* it makes IDEs freak out with wavy red underlines because they see references all over the place to variables which don't exist
* It forces us to say ``from <whatever> import *`` all over the place, which is not recommended if you don't have an ``__all__`` defined, which we most certainly do not.  (Theoretically we could dynamically define one for ``constants.py`` but most modules don't directly import from there, so that's just passing the buck.)

Regardless, it would be more Pythonic to define a single global constants objects, which for brevity we could call ``c`` so that instead of saying ``ATTENDEE_BADGE`` we would say ``c.ATTENDEE_BADGE``, etc.  This would make people's IDEs not freak out as much, and make it easier to give each module a defined set of symbols it exports.

**Comment by thaeli** [comment]
Migrated to the RAMS Refactor project as T9.
