### ISSUE TITLE
"Free badges for life"

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#698]
At this point we have several people who ran MAGFest departments for many years who are no longer able to run things but who still make it out to MAGFest.  Examples include Big Mat, Ryon Sumner, and most of all Brendan Becker.

These people are all in the category "free badge for life" because of the countless hours they've put in.  We should probably have an official list somewhere so that they get imported at the same time as returning staffers.

**Comment by bds002** [comment]
I created a JIRA issue for this, we could close it out of Github.
https://jira.magfest.net/browse/INC-558.

I don't have the ability to close out this issue
