### ISSUE TITLE
Stops admins should be able to edit hotel requests after the deadline

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#73]
This is a feature for next year.

Every year we get a flood of requests from department heads and such after the deadline.  I have to handle them myself since it's a manual process.  We should expose a nice way to edit this info through the UI.

It should probably only be made available to Stops people though.

---------------------------------------
- Bitbucket: https://bitbucket.org/EliAndrewC/magfest/issue/74
- Originally Reported By: [ ](http://bitbucket.org/EliAndrewC)
- Originally Created At: 2013-12-10T01:56:17.920

**Comment by bds002** [comment]
I think we have the ability now with the Admin Function (Stops-Only staff Rooms) Ability, is that right? @EliAndrewC

**Comment by EliAndrewC** [comment]
Correct.  Closing.
