### ISSUE TITLE
Hotel Room Request Page

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#743]
I know we have:
https://prime.uber.magfest.org/m13/hotel/requests 
to track staffers room request. 

I also know there are some broader plans to change how these are handled in the future.

But for M13 I would like to see a check box or a data entry line so that as STOPS address the request, we can mark them as such.  That way we don't have to spend time re-evaluating the list each time we go back into it. 

As an example I just updated the sheet for Vicki and Eli (and others) but other Stops staff wouldn't know that until I compare the rooming spreadsheet with the request page.

Thanks, Brent

**Comment by binary1230** [comment]
@bds002 is this still a valid issue?
