### ISSUE TITLE
Hotel room approvals should be non-boolean

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#78]
For easy tracking purposes, we should change "approved" to be a status field with at least three values: unset / approved / declined.

Something for next year.

---------------------------------------
- Bitbucket: https://bitbucket.org/EliAndrewC/magfest/issue/79
- Originally Reported By: [ ](http://bitbucket.org/EliAndrewC)
- Originally Created At: 2013-12-14T13:09:37.432

**Comment by bds002** [comment]
I think this issue has been resolved?  We have Approved/Declined already... ?

**Comment by EliAndrewC** [comment]
This is still a valid issue, but I'll close it out here and open a new ticket at https://github.com/magfest/hotel/issues/16
