### ISSUE TITLE
Tool Tip on Volunteers for Hotel Assignments

### ISSUE THREAD

**Issue by MAGFestJack** [magfest/ubersystem#816]
Please add a tool tip that shows the staffers' roommate requests.

**Comment by bds002** [comment]
Jack,

I remember talking about this... but what page were we going to add this to?
The Staffers main registration page?

**Comment by MAGFestJack** [comment]
I'm not sure what you are talking about.

**Comment by bds002** [comment]
Where did you want the Tool tip added to?
"Please add a tool tip that shows the staffers' roommate requests."

**Comment by MAGFestJack** [comment]
I do not remember honestly, we should have reviewed it back in March,
April, May or June, like I asked office/BOD to do each of those months. It
probably had something to do with the staffer's page displaying this info
for easier access to this.

When are sign ups going out for hotel rooms and shifts. I thought I saw an
email, but the only thing I got that had a link did not work.

To answer your email from earlier, I plan to do tea room and tabletops as a
DH or normal staffer, but I might help a bit in Rescuers or Reg as well.

**Comment by binary1230** [comment]
@bds002 going through old tickets, is this still an open request given the recent UI overhauls of the hotel plugin in uber? I suspect the new workflow solves a lot of the old issues, so I'm going to go ahead and close this out.  If that's not the case, feel free to re-open.  I know there are a bunch of more recent hotel UI issues open, and suspect they detail related requests.
