### ISSUE TITLE
Food info email for volunteers and guests

### ISSUE THREAD

**Issue by JennyTruss** [magfest/ubersystem#822]
Here are the modified emails that should be sent out to volunteers and guests:

**Volunteers:**

{{ attendee.first_name }},

Thanks again for volunteering at {{ EVENT_NAME }} this year. We feed our volunteers three meals per day during {{ EVENT_NAME }}, so you can drop by the Hospitality Suite in Room 6176 for food at anytime during {{ EVENT_NAME }} for a snack or drink. Meals will be served at the following times:

Breakfast: 7:00 am to 11:00 am
Lunch: 12:00 pm to 4:00 pm
Dinner: 5:00 pm to 9:00 pm
Overnight: 9:00 pm to 4:00 am (or until the hot food has run out, whichever occurs first)

{% if attendee.badge_type == ATTENDEE_BADGE %}You will become eligible for food after working your first shift if you have signed up for at least 12 hours. Please come to Staffing Ops (in the Fest Ops room) after you first get your badge to get your shift schedule, and then come back to get your ribbon marked after working your first shift and getting your department head to sign your sheet. You will not be able to get snacks, drinks, or meals, or have food delivered without your volunteer ribbon being properly marked.

{% endif %}The first meal served will be breakfast on Friday morning, and the suite will remain open through Monday afternoon. Monday will have a breakfast option, but once breakfast is over, leftovers will be served. You will be able to help yourself. Please feel free to bring tupperware or storage bags to carry items home. You will be responsible for their proper storage.

You will also have the option to have food delivered to you while on shift. This option is primarily for those staffers and volunteers who are unable to visit the suite during meal service.

Meal schedule, menu, food delivery ordering, and suite rules can all be found at http://magsuite.jennytru.com/.

In addition to the Hospitality Suite, you'll be eligible to buy food at the Galaxy Cafe, which is the Gaylord's cafeteria for its own staff which they've generously allowed us to use. To get to the Galaxy Cafe, go to the far back of the Maryland Ballroom foyer, then go through the doors and turn left. Just before you get to the Security desk in the hallway, look to your left and there will be a wide set of stairs going down. Go down those stairs and then the Galaxy Cafe will be on your right. You can use the Galaxy Cafe during any of the following times:

Breakfast ($13.00): 6:30am - 8:00am
Lunch ($15.00): 1:00pm - 2:30pm
Dinner ($15.00): 7:00pm - 9:00pm

Returning volunteers may notice that those prices are significantly higher than they've been in the past. Apparently this is what the Gaylord was supposed to be charging us all along, but due to an oversight on their part we've been getting the "Gaylord Staff" price instead of the "Contractor" price. They noticed and informed us of the oversight this year - alas!

Please let us know if you have any questions.

{{ STOPS_EMAIL_SIGNATURE }}

**Guests**

{{ attendee.first_name }},
Thanks again for coming out to {{ EVENT_NAME }} as a Guest! As we've previously mentioned, we feed our guests three meals per day during {{ EVENT_NAME }}, so you can drop by the Hospitality Suite in Room 6176 for food during any of the following times:

Breakfast: 7:00 am to 11:00 am
Lunch: 12:00 pm to 4:00 pm
Dinner: 5:00 pm to 9:00 pm
Overnight: 9:00 pm to 4:00 am (or until the hot food has run out, whichever occurs first)

The first meal served will be breakfast on Friday morning, and the suite will remain open through Monday afternoon. Monday will have a breakfast option, but once breakfast is over, leftovers will be served. You will be able to help yourself. Please feel free to bring tupperware or storage bags to carry items home. You will be responsible for their proper storage.

Meal schedule, menu, and suite rules can all be found at http://magsuite.jennytru.com/.

Please let us know if you have any questions.
{{ PEGLEGS_EMAIL_SIGNATURE }}

**Comment by kitsuta** [comment]
I updated this text in the magprime_emails repo. Sorry for the wait, @JennyTruss!
