### ISSUE TITLE
Add Lost and Found Handling

### ISSUE THREAD

**Issue by ksonney** [magfest/ubersystem#830]
At the moment, all Lost and Found items get sent to Security, then registered in a spreadsheet and tagged with a ticket. It would be useful to have this table of items in Uber instead, with the following fields :

- UUID
- Tag ID (Int)
- Item Description (Text)
- Where Found (Text)
- When Found/turned in (datetime)
- Returned (Bool)

This would allow fast lookups of "has this been turned in" and "yes we have it" wersus having to search through both a box and a spreadsheet on every request. 

(We do something similar at AC, but with a Google Spreadsheet, so this would be used both places)

**Comment by thaeli** [comment]
Migrated to T11 in the RAMS Refactor issue tracker.
