### ISSUE TITLE
Department Head Checklist Changes

### ISSUE THREAD

**Issue by MAGFestJack** [magfest/ubersystem#833]
setup the Tech Requirements, Printed Signs, Office Supplies, and Custom Ribbons pages under Department Head Checklist to show what all department heads entered that are in the same department.  This will help prevent duplicate requests when items are unnecessary and will help prevent us from providing duplicate things when it is not necessary.  This may help department heads remember what they need as well.

**Comment by binary1230** [comment]
going through old tickets, I think all the options here are now added, and the duplicates checking is detailed in issue https://github.com/magfest/ubersystem/issues/874, so we'll close this issue and leave the other one open
