### ISSUE TITLE
Send attendees check-in barcodes

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#841]
A large portion of our problems during check-in is volunteers making mistakes while looking people up or checking them in.

In order to help alleviate that, we can send attendees a barcode before the event. The barcode would be encoded with their UUID, so when a volunteer scans it, it takes them to the Attendee's details page. After ensuring that the name on the registration matches the name on the attendee's photo ID, the volunteer can check that attendee in.

Specifically, this would prevent the following (fairly common) situations:
1. Volunteer can't find attendee in the system because of minor data issues (name is misspelled, they used a name that's not on their photo ID, etc)
2. Volunteer checks in the wrong attendee because the attendee was in a large list of names and the volunteer selected the wrong row without noticing.

The other portion of this feature would be adding a badge number field to the Attendee details page, since currently you have to navigate to change_badge and that's too unwieldy.

This would be really nice to have for MAGFest 13. However, we may not be able to use it if we can't afford to buy 40 barcode scanners.

If we want, we can implemented it for a limited number of badges this year (e.g. just staff), so we can limit the number of scanners we buy and make sure there's no unforeseen problems.

**Comment by bds002** [comment]
With the most recent discussion in Uber about Barcodes and badges, where does this issue stand?
I think this would be a good compromise instead of mailing out badges... - Print your Email, bring it in....
If you forget your Email, find it on your phone or show us your photo ID and here is your badge.

**Comment by kitsuta** [comment]
I'm definitely hoping to test this out at MAGClassic this year. :)
