### ISSUE TITLE
Crowd Manager Training Cert. Query on databases

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#846]
Part of the security/public safety aspects of MAGFest is the Maryland required Crowd Manager Safety Training.  There is now a charge for this training.  In order to better budget our resources for this requirement we want to know the issues dates for the past years staffers.

I would like a query run on the past Magfest databases to return the following information:
Name, Email address of staffer, Cert number (in the database as "fire_safety_cert") and the year it was issued or inputted into Uber.  

Since this cert. is good for 3 years, this will allow us to determine how many staffers we need to have certified each year, and who those particular staffers are.

Thanks,
Brent

**Comment by EliAndrewC** [comment]
This was done and I forgot to close it before now.
