### ISSUE TITLE
Button to re-send automated emails

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#895]
We occasionally have the following situation occur:
- someone registers or is registered for a badge
- their email address is send some number of automated emails
- it turns out that their email address was entered incorrectly
- if/when we want to re-send those automated emails, we have to copy/paste them manually

We already display what emails someone has received on their History page, so we could easily put a button next to each email to re-send the email.

**Comment by migetman9** [comment]
This is in progress and might be a duplicate issue as a newer one was logged.

**Comment by RobRuana** [comment]
Done!
