### ISSUE TITLE
Better workflow for Arcade Collectors

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#896]
Here's an excerpt from an email chain about how to better handle Arcade Collectors in Uber:

Right now the process goes like:
- Mr. Collector volunteers to bring some stuff to MAGFest and is assigned a staff badge
- Since he's bringing Arcade machines, Mr. Collector is assigned to the Arcade department, where there are setup/teardown shifts they can sign up for
- Mr. Collector doesn't fill out the volunteer checklist or sign up for shifts, so Stops bugs him and also pesters Ethan to get "his" person to sign up for shifts
- Mr. Collector isn't really "Ethan's guy", he's just some guy who volunteered to bring more arcade machines to help Ethan out, Ethan may have never even met this guy, so that guy isn't really any more likely to respond to Ethan than he is to respond to Stops

Assuming this is correct, we could do some things to make it clearer in Uber who Stops should pester when people aren't filling out the proper forms.  Like we could make an "Arcade Collectors" department, and anyone bringing machines gets put into a group, where the group leader is the person that Stops will pester when their people aren't filling out their forms.  Since they're assigned to the "Arcade Collectors" department, we know that it's not someone who Ethan (or any of the other Arcade folks) even necessarily know, so we can go directly to the source and we can take some of the load off of Ethan for this kind of tracking.  (And then we'll still pester Ethan when folks who really ARE "Ethan's people" aren't doing their stuff.)

Later on in the email chain, Mark G also said this:

Another thing is the "non-shift hours" part of Uber.  That has to be put in manually, and is sort of a work-around for shifts that don't yet exist -- like for arcade guys who start loading trucks on Monday.  We don't have all of those non-shift hours in yet, but in the future, it would be great to automate filling-in some of those hours for certain folks.

I'm not really sure what he means, but we should follow up next year to improve thier workflow.

**Comment by bds002** [comment]
Currently how we are handling this is to create a group for each Arcade Supplie/Crew we have coming and assigning the crew staffers that way.  Subsequently there are setup and tear-down shift created for each crew ... I think (4) 6 hour shifts total (2 before and 2 after event) that are time and a half .. 

I'm not sure if we want to revisit this, or maybe talk about it with Arcades at MAGCon, but I think this issue can be closed.@markG

**Comment by binary1230** [comment]
seems like we have a decent workflow, so closing this for now
