### ISSUE TITLE
Guest badges shouldn't show the "Transfer my badge" option

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#946]
There are likely other badge types that should not show it either.

**Comment by EliAndrewC** [comment]
Hmm, I thought we already prevented this, but I guess not.  We do prevent certain types of badges from being transferred, e.g. Staff badges.  I thought Guest badges were on this list, but since they're not it should be simple to add.

**Comment by earl7399** [comment]
To be clear, the attempt to transfer fails with a 500 error.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by EliAndrewC** [comment]
Even more interesting; the "Transfer" button on the confirm page shouldn't even show.  I guess the best thing in this case is to redirect people if they ever make their way to the transfer page with a non-transferable badge.
