### ISSUE TITLE
Ensure unassigned badges are given a number only when claimed

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#967]
Right now, unassigned badges that are pre-assigned badge types are given a number when they're _created_. However, this is bad for any event that has a lot of pre-assigned badge types (like... all of them, for example), as there will be a ton of blank badges taking up numbers.

When an unassigned badge is claimed, it's not assigned a number currently, so theoretically it would get assigned number 0. This is bad for any pre-assigned badge type, which obviously should have a number.

So we need to ensure that badges _don't_ have a number when they're created, but _get assigned_ a number when someone claims them.

I think it actually works this way in ac-staging currently, but it's worth double-checking after we merge.

**Comment by bds002** [comment]
Is this related to the issue of Pre-assigned but unclaimed badges loosing their assignment when claimed?  I like the thought of pre-assigning a group of badges - IE I set the Dorsai to have badges in 300-330 range approximately.

**Comment by kitsuta** [comment]
Yes, this issue covers the problem where assigned badges' numbers are wiped when they're claimed.

At some point we should have this set up so that assigning numbers is more dynamic and can be better controlled... but until then, unassigned numbers is a better default, I think.

**Comment by kitsuta** [comment]
This currently works as expected in master.
