### ISSUE TITLE
Error dropping an attendee with shifts

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#970]
I swear I fixed this already, but apparently not.  When you drop an attendee with shifts, we get an error because the delete doesn't cascade properly.

The SQLAlchemy docs are really deficient here.  Next year I'm going to reverse how we declare our foreign keys to match their examples just because that probably makes it less likely for this kind of mistake to keep happening.

**Comment by bds002** [comment]
We'll want to look at what the notification process is here. 
If a staffer or Attendee/Volunteer goes in and delete's themselves and they had shifts assigned then the Corresponding DH or Stops should be notified that those shifts are now open and not staffed.
Brent

**Comment by EliAndrewC** [comment]
Hmm, normally there's no way for that to happen on-site, but since we might just leave Uber online for the most part, we might need to check for this.

Previously we assumed that all of the ways for someone to drop a shift weren't available during MAGFest itself, since Uber was offline.  This may no longer be the case.

**Comment by EliAndrewC** [comment]
This is indeed a thing.  If someone unchecks the box that indicates they're not volunteering, it automatically drops all of their shifts.

We should probably add a check that you can't do that in at-the-con mode or something.

**Comment by kitsuta** [comment]
I can't reproduce the original bug, so it was probably fixed at some point.
