### ISSUE TITLE
Waitlisted vendors don't indicate that on attendee page, and could easily be checked in.

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#985]
There is nothing on the attendee page to show that they should be allowed to check in and get a badge/ribbon.  Please fix ASAP!

**Comment by EliAndrewC** [comment]
I could have sworn I went in and deleted all of the waitlisted vendors like a month ago, which is what we always do.

I'll go ahead and do that tonight.

**Comment by EliAndrewC** [comment]
I'll also mark the members of all dealer groups as having shopkeep ribbons.

**Comment by EliAndrewC** [comment]
This is done.
