### ISSUE TITLE
magfest: support printing badges in waves

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#990]
Magfest: Our real-life customized badge manufacturing process is breaking down because we are sending all our custom badges to the printer all at once.

Next year we should think about making it so, once a month, we can lock a chunk of badges in uber and send those to print.  That way the printer has several months to work on several waves, instead of a couple weeks of one giant all-encompassing batch.

To do this we'd need functionality to lock down a subset of badges and badge#'s.

AC might already be doing this in their branch, investigate.

**Comment by kitsuta** [comment]
#606.

**Comment by binary1230** [comment]
woops. duplicate. nice. closing.
